from .functions.abilityfuncs import *

py_dict = {'Adaptability': {'flags': {},
                  'name': 'Adaptability',
                  'num': 91,
                  'onModifySTAB': 'Adaptability.onModifySTAB',
                  'rating': 4},
 'Aerilate': {'flags': {},
              'name': 'Aerilate',
              'num': 184,
              'onBasePower': 'Aerilate.onBasePower',
              'onBasePowerPriority': 23,
              'onModifyType': 'Aerilate.onModifyType',
              'onModifyTypePriority': -1,
              'rating': 4},
 'Aftermath': {'flags': {},
               'name': 'Aftermath',
               'num': 106,
               'onDamagingHit': 'Aftermath.onDamagingHit',
               'onDamagingHitOrder': 1,
               'rating': 2},
 'Airlock': {'flags': {},
             'name': 'Air Lock',
             'num': 76,
             'onEnd': 'Airlock.onEnd',
             'onStart': 'Airlock.onStart',
             'onSwitchIn': 'Airlock.onSwitchIn',
             'rating': 1.5,
             'suppressWeather': True},
 'Analytic': {'flags': {},
              'name': 'Analytic',
              'num': 148,
              'onBasePower': 'Analytic.onBasePower',
              'onBasePowerPriority': 21,
              'rating': 2.5},
 'Angerpoint': {'flags': {}, 'name': 'Anger Point', 'num': 83, 'onHit': 'Angerpoint.onHit', 'rating': 1},
 'Angershell': {'flags': {},
                'name': 'Anger Shell',
                'num': 271,
                'onAfterMoveSecondary': 'Angershell.onAfterMoveSecondary',
                'onDamage': 'Angershell.onDamage',
                'onTryEatItem': 'Angershell.onTryEatItem',
                'rating': 3},
 'Anticipation': {'flags': {}, 'name': 'Anticipation', 'num': 107, 'onStart': 'Anticipation.onStart', 'rating': 0.5},
 'Arenatrap': {'flags': {},
               'name': 'Arena Trap',
               'num': 71,
               'onFoeMaybeTrapPokemon': 'Arenatrap.onFoeMaybeTrapPokemon',
               'onFoeTrapPokemon': 'Arenatrap.onFoeTrapPokemon',
               'rating': 5},
 'Armortail': {'flags': {'breakable': 1},
               'name': 'Armor Tail',
               'num': 296,
               'onFoeTryMove': 'Armortail.onFoeTryMove',
               'rating': 2.5},
 'Aromaveil': {'flags': {'breakable': 1},
               'name': 'Aroma Veil',
               'num': 165,
               'onAllyTryAddVolatile': 'Aromaveil.onAllyTryAddVolatile',
               'rating': 2},
 'Asoneglastrier': {'flags': {'cantsuppress': 1,
                              'failroleplay': 1,
                              'failskillswap': 1,
                              'noentrain': 1,
                              'noreceiver': 1,
                              'notrace': 1},
                    'name': 'As One (Glastrier)',
                    'num': 266,
                    'onEnd': 'Asoneglastrier.onEnd',
                    'onFoeTryEatItem': 'Asoneglastrier.onFoeTryEatItem',
                    'onPreStart': 'Asoneglastrier.onPreStart',
                    'onSourceAfterFaint': 'Asoneglastrier.onSourceAfterFaint',
                    'onStart': 'Asoneglastrier.onStart',
                    'rating': 3.5},
 'Asonespectrier': {'flags': {'cantsuppress': 1,
                              'failroleplay': 1,
                              'failskillswap': 1,
                              'noentrain': 1,
                              'noreceiver': 1,
                              'notrace': 1},
                    'name': 'As One (Spectrier)',
                    'num': 267,
                    'onEnd': 'Asonespectrier.onEnd',
                    'onFoeTryEatItem': 'Asonespectrier.onFoeTryEatItem',
                    'onPreStart': 'Asonespectrier.onPreStart',
                    'onSourceAfterFaint': 'Asonespectrier.onSourceAfterFaint',
                    'onStart': 'Asonespectrier.onStart',
                    'rating': 3.5},
 'Aurabreak': {'flags': {'breakable': 1},
               'name': 'Aura Break',
               'num': 188,
               'onAnyTryPrimaryHit': 'Aurabreak.onAnyTryPrimaryHit',
               'onStart': 'Aurabreak.onStart',
               'rating': 1},
 'Baddreams': {'flags': {},
               'name': 'Bad Dreams',
               'num': 123,
               'onResidual': 'Baddreams.onResidual',
               'onResidualOrder': 28,
               'onResidualSubOrder': 2,
               'rating': 1.5},
 'Ballfetch': {'flags': {}, 'name': 'Ball Fetch', 'num': 237, 'rating': 0},
 'Battery': {'flags': {},
             'name': 'Battery',
             'num': 217,
             'onAllyBasePower': 'Battery.onAllyBasePower',
             'onAllyBasePowerPriority': 22,
             'rating': 0},
 'Battlearmor': {'flags': {'breakable': 1}, 'name': 'Battle Armor', 'num': 4, 'onCriticalHit': False, 'rating': 1},
 'Battlebond': {'flags': {'cantsuppress': 1,
                          'failroleplay': 1,
                          'failskillswap': 1,
                          'noentrain': 1,
                          'noreceiver': 1,
                          'notrace': 1},
                'name': 'Battle Bond',
                'num': 210,
                'onSourceAfterFaint': 'Battlebond.onSourceAfterFaint',
                'rating': 3.5},
 'Beadsofruin': {'flags': {},
                 'name': 'Beads of Ruin',
                 'num': 284,
                 'onAnyModifySpD': 'Beadsofruin.onAnyModifySpD',
                 'onStart': 'Beadsofruin.onStart',
                 'rating': 4.5},
 'Beastboost': {'flags': {},
                'name': 'Beast Boost',
                'num': 224,
                'onSourceAfterFaint': 'Beastboost.onSourceAfterFaint',
                'rating': 3.5},
 'Berserk': {'flags': {},
             'name': 'Berserk',
             'num': 201,
             'onAfterMoveSecondary': 'Berserk.onAfterMoveSecondary',
             'onDamage': 'Berserk.onDamage',
             'onTryEatItem': 'Berserk.onTryEatItem',
             'rating': 2},
 'Bigpecks': {'flags': {'breakable': 1},
              'name': 'Big Pecks',
              'num': 145,
              'onTryBoost': 'Bigpecks.onTryBoost',
              'rating': 0.5},
 'Blaze': {'flags': {},
           'name': 'Blaze',
           'num': 66,
           'onModifyAtk': 'Blaze.onModifyAtk',
           'onModifyAtkPriority': 5,
           'onModifySpA': 'Blaze.onModifySpA',
           'onModifySpAPriority': 5,
           'rating': 2},
 'Bulletproof': {'flags': {'breakable': 1},
                 'name': 'Bulletproof',
                 'num': 171,
                 'onTryHit': 'Bulletproof.onTryHit',
                 'rating': 3},
 'Cheekpouch': {'flags': {}, 'name': 'Cheek Pouch', 'num': 167, 'onEatItem': 'Cheekpouch.onEatItem', 'rating': 2},
 'Chillingneigh': {'flags': {},
                   'name': 'Chilling Neigh',
                   'num': 264,
                   'onSourceAfterFaint': 'Chillingneigh.onSourceAfterFaint',
                   'rating': 3},
 'Chlorophyll': {'flags': {}, 'name': 'Chlorophyll', 'num': 34, 'onModifySpe': 'Chlorophyll.onModifySpe', 'rating': 3},
 'Clearbody': {'flags': {'breakable': 1},
               'name': 'Clear Body',
               'num': 29,
               'onTryBoost': 'Clearbody.onTryBoost',
               'rating': 2},
 'Cloudnine': {'flags': {},
               'name': 'Cloud Nine',
               'num': 13,
               'onEnd': 'Cloudnine.onEnd',
               'onStart': 'Cloudnine.onStart',
               'onSwitchIn': 'Cloudnine.onSwitchIn',
               'rating': 1.5,
               'suppressWeather': True},
 'Colorchange': {'flags': {},
                 'name': 'Color Change',
                 'num': 16,
                 'onAfterMoveSecondary': 'Colorchange.onAfterMoveSecondary',
                 'rating': 0},
 'Comatose': {'flags': {'cantsuppress': 1,
                        'failroleplay': 1,
                        'failskillswap': 1,
                        'noentrain': 1,
                        'noreceiver': 1,
                        'notrace': 1},
              'name': 'Comatose',
              'num': 213,
              'onSetStatus': 'Comatose.onSetStatus',
              'onStart': 'Comatose.onStart',
              'rating': 4},
 'Commander': {'flags': {'failroleplay': 1, 'failskillswap': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
               'name': 'Commander',
               'num': 279,
               'onUpdate': 'Commander.onUpdate',
               'rating': 0},
 'Competitive': {'flags': {},
                 'name': 'Competitive',
                 'num': 172,
                 'onAfterEachBoost': 'Competitive.onAfterEachBoost',
                 'rating': 2.5},
 'Compoundeyes': {'flags': {},
                  'name': 'Compound Eyes',
                  'num': 14,
                  'onSourceModifyAccuracy': 'Compoundeyes.onSourceModifyAccuracy',
                  'onSourceModifyAccuracyPriority': -1,
                  'rating': 3},
 'Contrary': {'flags': {'breakable': 1},
              'name': 'Contrary',
              'num': 126,
              'onChangeBoost': 'Contrary.onChangeBoost',
              'rating': 4.5},
 'Corrosion': {'flags': {}, 'name': 'Corrosion', 'num': 212, 'rating': 2.5},
 'Costar': {'flags': {}, 'name': 'Costar', 'num': 294, 'onStart': 'Costar.onStart', 'rating': 0},
 'Cottondown': {'flags': {},
                'name': 'Cotton Down',
                'num': 238,
                'onDamagingHit': 'Cottondown.onDamagingHit',
                'rating': 2},
 'Cudchew': {'condition': {'duration': 2, 'noCopy': True, 'onResidualOrder': 28, 'onResidualSubOrder': 2},
             'flags': {},
             'name': 'Cud Chew',
             'num': 291,
             'onEatItem': 'Cudchew.onEatItem',
             'onEnd': 'Cudchew.onEnd',
             'rating': 2},
 'Curiousmedicine': {'flags': {},
                     'name': 'Curious Medicine',
                     'num': 261,
                     'onStart': 'Curiousmedicine.onStart',
                     'rating': 0},
 'Cursedbody': {'flags': {},
                'name': 'Cursed Body',
                'num': 130,
                'onDamagingHit': 'Cursedbody.onDamagingHit',
                'rating': 2},
 'Cutecharm': {'flags': {}, 'name': 'Cute Charm', 'num': 56, 'onDamagingHit': 'Cutecharm.onDamagingHit', 'rating': 0.5},
 'Damp': {'flags': {'breakable': 1},
          'name': 'Damp',
          'num': 6,
          'onAnyDamage': 'Damp.onAnyDamage',
          'onAnyTryMove': 'Damp.onAnyTryMove',
          'rating': 0.5},
 'Dancer': {'flags': {}, 'name': 'Dancer', 'num': 216, 'rating': 1.5},
 'Darkaura': {'flags': {},
              'name': 'Dark Aura',
              'num': 186,
              'onAnyBasePower': 'Darkaura.onAnyBasePower',
              'onAnyBasePowerPriority': 20,
              'onStart': 'Darkaura.onStart',
              'rating': 3},
 'Dauntlessshield': {'flags': {},
                     'name': 'Dauntless Shield',
                     'num': 235,
                     'onStart': 'Dauntlessshield.onStart',
                     'rating': 3.5},
 'Dazzling': {'flags': {'breakable': 1},
              'name': 'Dazzling',
              'num': 219,
              'onFoeTryMove': 'Dazzling.onFoeTryMove',
              'rating': 2.5},
 'Defeatist': {'flags': {},
               'name': 'Defeatist',
               'num': 129,
               'onModifyAtk': 'Defeatist.onModifyAtk',
               'onModifyAtkPriority': 5,
               'onModifySpA': 'Defeatist.onModifySpA',
               'onModifySpAPriority': 5,
               'rating': -1},
 'Defiant': {'flags': {}, 'name': 'Defiant', 'num': 128, 'onAfterEachBoost': 'Defiant.onAfterEachBoost', 'rating': 3},
 'Deltastream': {'flags': {},
                 'name': 'Delta Stream',
                 'num': 191,
                 'onAnySetWeather': 'Deltastream.onAnySetWeather',
                 'onEnd': 'Deltastream.onEnd',
                 'onStart': 'Deltastream.onStart',
                 'rating': 4},
 'Desolateland': {'flags': {},
                  'name': 'Desolate Land',
                  'num': 190,
                  'onAnySetWeather': 'Desolateland.onAnySetWeather',
                  'onEnd': 'Desolateland.onEnd',
                  'onStart': 'Desolateland.onStart',
                  'rating': 4.5},
 'Disguise': {'flags': {'breakable': 1,
                        'cantsuppress': 1,
                        'failroleplay': 1,
                        'failskillswap': 1,
                        'noentrain': 1,
                        'noreceiver': 1,
                        'notrace': 1,
                        'notransform': 1},
              'name': 'Disguise',
              'num': 209,
              'onCriticalHit': 'Disguise.onCriticalHit',
              'onDamage': 'Disguise.onDamage',
              'onDamagePriority': 1,
              'onEffectiveness': 'Disguise.onEffectiveness',
              'onUpdate': 'Disguise.onUpdate',
              'rating': 3.5},
 'Download': {'flags': {}, 'name': 'Download', 'num': 88, 'onStart': 'Download.onStart', 'rating': 3.5},
 'Dragonsmaw': {'flags': {},
                'name': "Dragon's Maw",
                'num': 263,
                'onModifyAtk': 'Dragonsmaw.onModifyAtk',
                'onModifyAtkPriority': 5,
                'onModifySpA': 'Dragonsmaw.onModifySpA',
                'onModifySpAPriority': 5,
                'rating': 3.5},
 'Drizzle': {'flags': {}, 'name': 'Drizzle', 'num': 2, 'onStart': 'Drizzle.onStart', 'rating': 4},
 'Drought': {'flags': {}, 'name': 'Drought', 'num': 70, 'onStart': 'Drought.onStart', 'rating': 4},
 'Dryskin': {'flags': {'breakable': 1},
             'name': 'Dry Skin',
             'num': 87,
             'onSourceBasePower': 'Dryskin.onSourceBasePower',
             'onSourceBasePowerPriority': 17,
             'onTryHit': 'Dryskin.onTryHit',
             'onWeather': 'Dryskin.onWeather',
             'rating': 3},
 'Earlybird': {'flags': {}, 'name': 'Early Bird', 'num': 48, 'rating': 1.5},
 'Eartheater': {'flags': {'breakable': 1},
                'name': 'Earth Eater',
                'num': 297,
                'onTryHit': 'Eartheater.onTryHit',
                'rating': 3.5},
 'Effectspore': {'flags': {},
                 'name': 'Effect Spore',
                 'num': 27,
                 'onDamagingHit': 'Effectspore.onDamagingHit',
                 'rating': 2},
 'Electricsurge': {'flags': {}, 'name': 'Electric Surge', 'num': 226, 'onStart': 'Electricsurge.onStart', 'rating': 4},
 'Electromorphosis': {'flags': {},
                      'name': 'Electromorphosis',
                      'num': 280,
                      'onDamagingHit': 'Electromorphosis.onDamagingHit',
                      'onDamagingHitOrder': 1,
                      'rating': 3},
 'Embodyaspectcornerstone': {'flags': {'failroleplay': 1,
                                       'failskillswap': 1,
                                       'noentrain': 1,
                                       'noreceiver': 1,
                                       'notrace': 1,
                                       'notransform': 1},
                             'name': 'Embody Aspect (Cornerstone)',
                             'num': 304,
                             'onStart': 'Embodyaspectcornerstone.onStart',
                             'onSwitchIn': 'Embodyaspectcornerstone.onSwitchIn',
                             'rating': 3.5},
 'Embodyaspecthearthflame': {'flags': {'failroleplay': 1,
                                       'failskillswap': 1,
                                       'noentrain': 1,
                                       'noreceiver': 1,
                                       'notrace': 1,
                                       'notransform': 1},
                             'name': 'Embody Aspect (Hearthflame)',
                             'num': 303,
                             'onStart': 'Embodyaspecthearthflame.onStart',
                             'onSwitchIn': 'Embodyaspecthearthflame.onSwitchIn',
                             'rating': 3.5},
 'Embodyaspectteal': {'flags': {'failroleplay': 1,
                                'failskillswap': 1,
                                'noentrain': 1,
                                'noreceiver': 1,
                                'notrace': 1,
                                'notransform': 1},
                      'name': 'Embody Aspect (Teal)',
                      'num': 301,
                      'onStart': 'Embodyaspectteal.onStart',
                      'onSwitchIn': 'Embodyaspectteal.onSwitchIn',
                      'rating': 3.5},
 'Embodyaspectwellspring': {'flags': {'failroleplay': 1,
                                      'failskillswap': 1,
                                      'noentrain': 1,
                                      'noreceiver': 1,
                                      'notrace': 1,
                                      'notransform': 1},
                            'name': 'Embody Aspect (Wellspring)',
                            'num': 302,
                            'onStart': 'Embodyaspectwellspring.onStart',
                            'onSwitchIn': 'Embodyaspectwellspring.onSwitchIn',
                            'rating': 3.5},
 'Emergencyexit': {'flags': {},
                   'name': 'Emergency Exit',
                   'num': 194,
                   'onEmergencyExit': 'Emergencyexit.onEmergencyExit',
                   'rating': 1},
 'Fairyaura': {'flags': {},
               'name': 'Fairy Aura',
               'num': 187,
               'onAnyBasePower': 'Fairyaura.onAnyBasePower',
               'onAnyBasePowerPriority': 20,
               'onStart': 'Fairyaura.onStart',
               'rating': 3},
 'Filter': {'flags': {'breakable': 1},
            'name': 'Filter',
            'num': 111,
            'onSourceModifyDamage': 'Filter.onSourceModifyDamage',
            'rating': 3},
 'Flamebody': {'flags': {}, 'name': 'Flame Body', 'num': 49, 'onDamagingHit': 'Flamebody.onDamagingHit', 'rating': 2},
 'Flareboost': {'flags': {},
                'name': 'Flare Boost',
                'num': 138,
                'onBasePower': 'Flareboost.onBasePower',
                'onBasePowerPriority': 19,
                'rating': 2},
 'Flashfire': {'condition': {'noCopy': True, 'onModifyAtkPriority': 5, 'onModifySpAPriority': 5},
               'flags': {'breakable': 1},
               'name': 'Flash Fire',
               'num': 18,
               'onEnd': 'Flashfire.onEnd',
               'onTryHit': 'Flashfire.onTryHit',
               'rating': 3.5},
 'Flowergift': {'flags': {'breakable': 1, 'failroleplay': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
                'name': 'Flower Gift',
                'num': 122,
                'onAllyModifyAtk': 'Flowergift.onAllyModifyAtk',
                'onAllyModifyAtkPriority': 3,
                'onAllyModifySpD': 'Flowergift.onAllyModifySpD',
                'onAllyModifySpDPriority': 4,
                'onStart': 'Flowergift.onStart',
                'onWeatherChange': 'Flowergift.onWeatherChange',
                'rating': 1},
 'Flowerveil': {'flags': {'breakable': 1},
                'name': 'Flower Veil',
                'num': 166,
                'onAllySetStatus': 'Flowerveil.onAllySetStatus',
                'onAllyTryAddVolatile': 'Flowerveil.onAllyTryAddVolatile',
                'onAllyTryBoost': 'Flowerveil.onAllyTryBoost',
                'rating': 0},
 'Fluffy': {'flags': {'breakable': 1},
            'name': 'Fluffy',
            'num': 218,
            'onSourceModifyDamage': 'Fluffy.onSourceModifyDamage',
            'rating': 3.5},
 'Forecast': {'flags': {'failroleplay': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
              'name': 'Forecast',
              'num': 59,
              'onStart': 'Forecast.onStart',
              'onWeatherChange': 'Forecast.onWeatherChange',
              'rating': 2},
 'Forewarn': {'flags': {}, 'name': 'Forewarn', 'num': 108, 'onStart': 'Forewarn.onStart', 'rating': 0.5},
 'Friendguard': {'flags': {'breakable': 1},
                 'name': 'Friend Guard',
                 'num': 132,
                 'onAnyModifyDamage': 'Friendguard.onAnyModifyDamage',
                 'rating': 0},
 'Frisk': {'flags': {}, 'name': 'Frisk', 'num': 119, 'onStart': 'Frisk.onStart', 'rating': 1.5},
 'Fullmetalbody': {'flags': {},
                   'name': 'Full Metal Body',
                   'num': 230,
                   'onTryBoost': 'Fullmetalbody.onTryBoost',
                   'rating': 2},
 'Furcoat': {'flags': {'breakable': 1},
             'name': 'Fur Coat',
             'num': 169,
             'onModifyDef': 'Furcoat.onModifyDef',
             'onModifyDefPriority': 6,
             'rating': 4},
 'Galewings': {'flags': {},
               'name': 'Gale Wings',
               'num': 177,
               'onModifyPriority': 'Galewings.onModifyPriority',
               'rating': 1.5},
 'Galvanize': {'flags': {},
               'name': 'Galvanize',
               'num': 206,
               'onBasePower': 'Galvanize.onBasePower',
               'onBasePowerPriority': 23,
               'onModifyType': 'Galvanize.onModifyType',
               'onModifyTypePriority': -1,
               'rating': 4},
 'Gluttony': {'flags': {},
              'name': 'Gluttony',
              'num': 82,
              'onDamage': 'Gluttony.onDamage',
              'onStart': 'Gluttony.onStart',
              'rating': 1.5},
 'Goodasgold': {'flags': {'breakable': 1},
                'name': 'Good as Gold',
                'num': 283,
                'onTryHit': 'Goodasgold.onTryHit',
                'rating': 5},
 'Gooey': {'flags': {}, 'name': 'Gooey', 'num': 183, 'onDamagingHit': 'Gooey.onDamagingHit', 'rating': 2},
 'Gorillatactics': {'flags': {},
                    'name': 'Gorilla Tactics',
                    'num': 255,
                    'onBeforeMove': 'Gorillatactics.onBeforeMove',
                    'onDisableMove': 'Gorillatactics.onDisableMove',
                    'onEnd': 'Gorillatactics.onEnd',
                    'onModifyAtk': 'Gorillatactics.onModifyAtk',
                    'onModifyAtkPriority': 1,
                    'onModifyMove': 'Gorillatactics.onModifyMove',
                    'onStart': 'Gorillatactics.onStart',
                    'rating': 4.5},
 'Grasspelt': {'flags': {'breakable': 1},
               'name': 'Grass Pelt',
               'num': 179,
               'onModifyDef': 'Grasspelt.onModifyDef',
               'onModifyDefPriority': 6,
               'rating': 0.5},
 'Grassysurge': {'flags': {}, 'name': 'Grassy Surge', 'num': 229, 'onStart': 'Grassysurge.onStart', 'rating': 4},
 'Grimneigh': {'flags': {},
               'name': 'Grim Neigh',
               'num': 265,
               'onSourceAfterFaint': 'Grimneigh.onSourceAfterFaint',
               'rating': 3},
 'Guarddog': {'flags': {'breakable': 1},
              'name': 'Guard Dog',
              'num': 275,
              'onDragOut': 'Guarddog.onDragOut',
              'onDragOutPriority': 1,
              'onTryBoost': 'Guarddog.onTryBoost',
              'rating': 2},
 'Gulpmissile': {'flags': {'cantsuppress': 1, 'notransform': 1},
                 'name': 'Gulp Missile',
                 'num': 241,
                 'onDamagingHit': 'Gulpmissile.onDamagingHit',
                 'onSourceTryPrimaryHit': 'Gulpmissile.onSourceTryPrimaryHit',
                 'rating': 2.5},
 'Guts': {'flags': {},
          'name': 'Guts',
          'num': 62,
          'onModifyAtk': 'Guts.onModifyAtk',
          'onModifyAtkPriority': 5,
          'rating': 3.5},
 'Hadronengine': {'flags': {},
                  'name': 'Hadron Engine',
                  'num': 289,
                  'onModifySpA': 'Hadronengine.onModifySpA',
                  'onModifySpAPriority': 5,
                  'onStart': 'Hadronengine.onStart',
                  'rating': 4.5},
 'Harvest': {'flags': {},
             'name': 'Harvest',
             'num': 139,
             'onResidual': 'Harvest.onResidual',
             'onResidualOrder': 28,
             'onResidualSubOrder': 2,
             'rating': 2.5},
 'Healer': {'flags': {},
            'name': 'Healer',
            'num': 131,
            'onResidual': 'Healer.onResidual',
            'onResidualOrder': 5,
            'onResidualSubOrder': 3,
            'rating': 0},
 'Heatproof': {'flags': {'breakable': 1},
               'name': 'Heatproof',
               'num': 85,
               'onDamage': 'Heatproof.onDamage',
               'onSourceModifyAtk': 'Heatproof.onSourceModifyAtk',
               'onSourceModifyAtkPriority': 6,
               'onSourceModifySpA': 'Heatproof.onSourceModifySpA',
               'onSourceModifySpAPriority': 5,
               'rating': 2},
 'Heavymetal': {'flags': {'breakable': 1},
                'name': 'Heavy Metal',
                'num': 134,
                'onModifyWeight': 'Heavymetal.onModifyWeight',
                'onModifyWeightPriority': 1,
                'rating': 0},
 'Honeygather': {'flags': {}, 'name': 'Honey Gather', 'num': 118, 'rating': 0},
 'Hospitality': {'flags': {}, 'name': 'Hospitality', 'num': 299, 'onStart': 'Hospitality.onStart', 'rating': 0},
 'Hugepower': {'flags': {},
               'name': 'Huge Power',
               'num': 37,
               'onModifyAtk': 'Hugepower.onModifyAtk',
               'onModifyAtkPriority': 5,
               'rating': 5},
 'Hungerswitch': {'flags': {'failroleplay': 1,
                            'failskillswap': 1,
                            'noentrain': 1,
                            'noreceiver': 1,
                            'notrace': 1,
                            'notransform': 1},
                  'name': 'Hunger Switch',
                  'num': 258,
                  'onResidual': 'Hungerswitch.onResidual',
                  'onResidualOrder': 29,
                  'rating': 1},
 'Hustle': {'flags': {},
            'name': 'Hustle',
            'num': 55,
            'onModifyAtk': 'Hustle.onModifyAtk',
            'onModifyAtkPriority': 5,
            'onSourceModifyAccuracy': 'Hustle.onSourceModifyAccuracy',
            'onSourceModifyAccuracyPriority': -1,
            'rating': 3.5},
 'Hydration': {'flags': {},
               'name': 'Hydration',
               'num': 93,
               'onResidual': 'Hydration.onResidual',
               'onResidualOrder': 5,
               'onResidualSubOrder': 3,
               'rating': 1.5},
 'Hypercutter': {'flags': {'breakable': 1},
                 'name': 'Hyper Cutter',
                 'num': 52,
                 'onTryBoost': 'Hypercutter.onTryBoost',
                 'rating': 1.5},
 'Icebody': {'flags': {},
             'name': 'Ice Body',
             'num': 115,
             'onImmunity': 'Icebody.onImmunity',
             'onWeather': 'Icebody.onWeather',
             'rating': 1},
 'Iceface': {'flags': {'breakable': 1,
                       'cantsuppress': 1,
                       'failroleplay': 1,
                       'failskillswap': 1,
                       'noentrain': 1,
                       'noreceiver': 1,
                       'notrace': 1,
                       'notransform': 1},
             'name': 'Ice Face',
             'num': 248,
             'onCriticalHit': 'Iceface.onCriticalHit',
             'onDamage': 'Iceface.onDamage',
             'onDamagePriority': 1,
             'onEffectiveness': 'Iceface.onEffectiveness',
             'onStart': 'Iceface.onStart',
             'onUpdate': 'Iceface.onUpdate',
             'onWeatherChange': 'Iceface.onWeatherChange',
             'rating': 3},
 'Icescales': {'flags': {'breakable': 1},
               'name': 'Ice Scales',
               'num': 246,
               'onSourceModifyDamage': 'Icescales.onSourceModifyDamage',
               'rating': 4},
 'Illuminate': {'flags': {'breakable': 1},
                'name': 'Illuminate',
                'num': 35,
                'onModifyMove': 'Illuminate.onModifyMove',
                'onTryBoost': 'Illuminate.onTryBoost',
                'rating': 0.5},
 'Illusion': {'flags': {'failroleplay': 1, 'failskillswap': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
              'name': 'Illusion',
              'num': 149,
              'onBeforeSwitchIn': 'Illusion.onBeforeSwitchIn',
              'onDamagingHit': 'Illusion.onDamagingHit',
              'onEnd': 'Illusion.onEnd',
              'onFaint': 'Illusion.onFaint',
              'rating': 4.5},
 'Immunity': {'flags': {'breakable': 1},
              'name': 'Immunity',
              'num': 17,
              'onSetStatus': 'Immunity.onSetStatus',
              'onUpdate': 'Immunity.onUpdate',
              'rating': 2},
 'Imposter': {'flags': {'failroleplay': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
              'name': 'Imposter',
              'num': 150,
              'onStart': 'Imposter.onStart',
              'onSwitchIn': 'Imposter.onSwitchIn',
              'rating': 5},
 'Infiltrator': {'flags': {},
                 'name': 'Infiltrator',
                 'num': 151,
                 'onModifyMove': 'Infiltrator.onModifyMove',
                 'rating': 2.5},
 'Innardsout': {'flags': {},
                'name': 'Innards Out',
                'num': 215,
                'onDamagingHit': 'Innardsout.onDamagingHit',
                'onDamagingHitOrder': 1,
                'rating': 4},
 'Innerfocus': {'flags': {'breakable': 1},
                'name': 'Inner Focus',
                'num': 39,
                'onTryAddVolatile': 'Innerfocus.onTryAddVolatile',
                'onTryBoost': 'Innerfocus.onTryBoost',
                'rating': 1},
 'Insomnia': {'flags': {'breakable': 1},
              'name': 'Insomnia',
              'num': 15,
              'onSetStatus': 'Insomnia.onSetStatus',
              'onTryAddVolatile': 'Insomnia.onTryAddVolatile',
              'onUpdate': 'Insomnia.onUpdate',
              'rating': 1.5},
 'Intimidate': {'flags': {}, 'name': 'Intimidate', 'num': 22, 'onStart': 'Intimidate.onStart', 'rating': 3.5},
 'Intrepidsword': {'flags': {}, 'name': 'Intrepid Sword', 'num': 234, 'onStart': 'Intrepidsword.onStart', 'rating': 4},
 'Ironbarbs': {'flags': {},
               'name': 'Iron Barbs',
               'num': 160,
               'onDamagingHit': 'Ironbarbs.onDamagingHit',
               'onDamagingHitOrder': 1,
               'rating': 2.5},
 'Ironfist': {'flags': {},
              'name': 'Iron Fist',
              'num': 89,
              'onBasePower': 'Ironfist.onBasePower',
              'onBasePowerPriority': 23,
              'rating': 3},
 'Justified': {'flags': {}, 'name': 'Justified', 'num': 154, 'onDamagingHit': 'Justified.onDamagingHit', 'rating': 2.5},
 'Keeneye': {'flags': {'breakable': 1},
             'name': 'Keen Eye',
             'num': 51,
             'onModifyMove': 'Keeneye.onModifyMove',
             'onTryBoost': 'Keeneye.onTryBoost',
             'rating': 0.5},
 'Klutz': {'flags': {}, 'name': 'Klutz', 'num': 103, 'onStart': 'Klutz.onStart', 'rating': -1},
 'Leafguard': {'flags': {'breakable': 1},
               'name': 'Leaf Guard',
               'num': 102,
               'onSetStatus': 'Leafguard.onSetStatus',
               'onTryAddVolatile': 'Leafguard.onTryAddVolatile',
               'rating': 0.5},
 'Levitate': {'flags': {'breakable': 1}, 'name': 'Levitate', 'num': 26, 'rating': 3.5},
 'Libero': {'flags': {},
            'name': 'Libero',
            'num': 236,
            'onPrepareHit': 'Libero.onPrepareHit',
            'onSwitchIn': 'Libero.onSwitchIn',
            'rating': 4},
 'Lightmetal': {'flags': {'breakable': 1},
                'name': 'Light Metal',
                'num': 135,
                'onModifyWeight': 'Lightmetal.onModifyWeight',
                'rating': 1},
 'Lightningrod': {'flags': {'breakable': 1},
                  'name': 'Lightning Rod',
                  'num': 31,
                  'onAnyRedirectTarget': 'Lightningrod.onAnyRedirectTarget',
                  'onTryHit': 'Lightningrod.onTryHit',
                  'rating': 3},
 'Limber': {'flags': {'breakable': 1},
            'name': 'Limber',
            'num': 7,
            'onSetStatus': 'Limber.onSetStatus',
            'onUpdate': 'Limber.onUpdate',
            'rating': 2},
 'Lingeringaroma': {'flags': {},
                    'name': 'Lingering Aroma',
                    'num': 268,
                    'onDamagingHit': 'Lingeringaroma.onDamagingHit',
                    'rating': 2},
 'Liquidooze': {'flags': {},
                'name': 'Liquid Ooze',
                'num': 64,
                'onSourceTryHeal': 'Liquidooze.onSourceTryHeal',
                'rating': 2.5},
 'Liquidvoice': {'flags': {},
                 'name': 'Liquid Voice',
                 'num': 204,
                 'onModifyType': 'Liquidvoice.onModifyType',
                 'onModifyTypePriority': -1,
                 'rating': 1.5},
 'Longreach': {'flags': {}, 'name': 'Long Reach', 'num': 203, 'onModifyMove': 'Longreach.onModifyMove', 'rating': 1},
 'Magicbounce': {'condition': {'duration': 1},
                 'flags': {'breakable': 1},
                 'name': 'Magic Bounce',
                 'num': 156,
                 'onAllyTryHitSide': 'Magicbounce.onAllyTryHitSide',
                 'onTryHit': 'Magicbounce.onTryHit',
                 'onTryHitPriority': 1,
                 'rating': 4},
 'Magicguard': {'flags': {}, 'name': 'Magic Guard', 'num': 98, 'onDamage': 'Magicguard.onDamage', 'rating': 4},
 'Magician': {'flags': {},
              'name': 'Magician',
              'num': 170,
              'onAfterMoveSecondarySelf': 'Magician.onAfterMoveSecondarySelf',
              'rating': 1},
 'Magmaarmor': {'flags': {'breakable': 1},
                'name': 'Magma Armor',
                'num': 40,
                'onImmunity': 'Magmaarmor.onImmunity',
                'onUpdate': 'Magmaarmor.onUpdate',
                'rating': 0.5},
 'Magnetpull': {'flags': {},
                'name': 'Magnet Pull',
                'num': 42,
                'onFoeMaybeTrapPokemon': 'Magnetpull.onFoeMaybeTrapPokemon',
                'onFoeTrapPokemon': 'Magnetpull.onFoeTrapPokemon',
                'rating': 4},
 'Marvelscale': {'flags': {'breakable': 1},
                 'name': 'Marvel Scale',
                 'num': 63,
                 'onModifyDef': 'Marvelscale.onModifyDef',
                 'onModifyDefPriority': 6,
                 'rating': 2.5},
 'Megalauncher': {'flags': {},
                  'name': 'Mega Launcher',
                  'num': 178,
                  'onBasePower': 'Megalauncher.onBasePower',
                  'onBasePowerPriority': 19,
                  'rating': 3},
 'Merciless': {'flags': {},
               'name': 'Merciless',
               'num': 196,
               'onModifyCritRatio': 'Merciless.onModifyCritRatio',
               'rating': 1.5},
 'Mimicry': {'flags': {},
             'name': 'Mimicry',
             'num': 250,
             'onStart': 'Mimicry.onStart',
             'onTerrainChange': 'Mimicry.onTerrainChange',
             'rating': 0},
 'Mindseye': {'flags': {'breakable': 1},
              'name': "Mind's Eye",
              'num': 300,
              'onModifyMove': 'Mindseye.onModifyMove',
              'onModifyMovePriority': -5,
              'onTryBoost': 'Mindseye.onTryBoost',
              'rating': 0},
 'Minus': {'flags': {},
           'name': 'Minus',
           'num': 58,
           'onModifySpA': 'Minus.onModifySpA',
           'onModifySpAPriority': 5,
           'rating': 0},
 'Mirrorarmor': {'flags': {'breakable': 1},
                 'name': 'Mirror Armor',
                 'num': 240,
                 'onTryBoost': 'Mirrorarmor.onTryBoost',
                 'rating': 2},
 'Mistysurge': {'flags': {}, 'name': 'Misty Surge', 'num': 228, 'onStart': 'Mistysurge.onStart', 'rating': 3.5},
 'Moldbreaker': {'flags': {},
                 'name': 'Mold Breaker',
                 'num': 104,
                 'onModifyMove': 'Moldbreaker.onModifyMove',
                 'onStart': 'Moldbreaker.onStart',
                 'rating': 3},
 'Moody': {'flags': {},
           'name': 'Moody',
           'num': 141,
           'onResidual': 'Moody.onResidual',
           'onResidualOrder': 28,
           'onResidualSubOrder': 2,
           'rating': 5},
 'Motordrive': {'flags': {'breakable': 1},
                'name': 'Motor Drive',
                'num': 78,
                'onTryHit': 'Motordrive.onTryHit',
                'rating': 3},
 'Mountaineer': {'flags': {'breakable': 1},
                 'isNonstandard': 'CAP',
                 'name': 'Mountaineer',
                 'num': -2,
                 'onDamage': 'Mountaineer.onDamage',
                 'onTryHit': 'Mountaineer.onTryHit',
                 'rating': 3},
 'Moxie': {'flags': {}, 'name': 'Moxie', 'num': 153, 'onSourceAfterFaint': 'Moxie.onSourceAfterFaint', 'rating': 3},
 'Multiscale': {'flags': {'breakable': 1},
                'name': 'Multiscale',
                'num': 136,
                'onSourceModifyDamage': 'Multiscale.onSourceModifyDamage',
                'rating': 3.5},
 'Multitype': {'flags': {'cantsuppress': 1,
                         'failroleplay': 1,
                         'failskillswap': 1,
                         'noentrain': 1,
                         'noreceiver': 1,
                         'notrace': 1},
               'name': 'Multitype',
               'num': 121,
               'rating': 4},
 'Mummy': {'flags': {}, 'name': 'Mummy', 'num': 152, 'onDamagingHit': 'Mummy.onDamagingHit', 'rating': 2},
 'Myceliummight': {'flags': {},
                   'name': 'Mycelium Might',
                   'num': 298,
                   'onFractionalPriority': 'Myceliummight.onFractionalPriority',
                   'onFractionalPriorityPriority': -1,
                   'onModifyMove': 'Myceliummight.onModifyMove',
                   'rating': 2},
 'Naturalcure': {'flags': {},
                 'name': 'Natural Cure',
                 'num': 30,
                 'onCheckShow': 'Naturalcure.onCheckShow',
                 'onSwitchOut': 'Naturalcure.onSwitchOut',
                 'rating': 2.5},
 'Neuroforce': {'flags': {},
                'name': 'Neuroforce',
                'num': 233,
                'onModifyDamage': 'Neuroforce.onModifyDamage',
                'rating': 2.5},
 'Neutralizinggas': {'flags': {'failroleplay': 1,
                               'failskillswap': 1,
                               'noentrain': 1,
                               'noreceiver': 1,
                               'notrace': 1,
                               'notransform': 1},
                     'name': 'Neutralizing Gas',
                     'num': 256,
                     'onEnd': 'Neutralizinggas.onEnd',
                     'onPreStart': 'Neutralizinggas.onPreStart',
                     'rating': 3.5},
 'Noability': {'flags': {}, 'isNonstandard': 'Past', 'name': 'No Ability', 'num': 0, 'rating': 0.1},
 'Noguard': {'flags': {},
             'name': 'No Guard',
             'num': 99,
             'onAnyAccuracy': 'Noguard.onAnyAccuracy',
             'onAnyInvulnerability': 'Noguard.onAnyInvulnerability',
             'onAnyInvulnerabilityPriority': 1,
             'rating': 4},
 'Normalize': {'flags': {},
               'name': 'Normalize',
               'num': 96,
               'onBasePower': 'Normalize.onBasePower',
               'onBasePowerPriority': 23,
               'onModifyType': 'Normalize.onModifyType',
               'onModifyTypePriority': 1,
               'rating': 0},
 'Oblivious': {'flags': {'breakable': 1},
               'name': 'Oblivious',
               'num': 12,
               'onImmunity': 'Oblivious.onImmunity',
               'onTryBoost': 'Oblivious.onTryBoost',
               'onTryHit': 'Oblivious.onTryHit',
               'onUpdate': 'Oblivious.onUpdate',
               'rating': 1.5},
 'Opportunist': {'flags': {},
                 'name': 'Opportunist',
                 'num': 290,
                 'onFoeAfterBoost': 'Opportunist.onFoeAfterBoost',
                 'rating': 3},
 'Orichalcumpulse': {'flags': {},
                     'name': 'Orichalcum Pulse',
                     'num': 288,
                     'onModifyAtk': 'Orichalcumpulse.onModifyAtk',
                     'onModifyAtkPriority': 5,
                     'onStart': 'Orichalcumpulse.onStart',
                     'rating': 4.5},
 'Overcoat': {'flags': {'breakable': 1},
              'name': 'Overcoat',
              'num': 142,
              'onImmunity': 'Overcoat.onImmunity',
              'onTryHit': 'Overcoat.onTryHit',
              'onTryHitPriority': 1,
              'rating': 2},
 'Overgrow': {'flags': {},
              'name': 'Overgrow',
              'num': 65,
              'onModifyAtk': 'Overgrow.onModifyAtk',
              'onModifyAtkPriority': 5,
              'onModifySpA': 'Overgrow.onModifySpA',
              'onModifySpAPriority': 5,
              'rating': 2},
 'Owntempo': {'flags': {'breakable': 1},
              'name': 'Own Tempo',
              'num': 20,
              'onHit': 'Owntempo.onHit',
              'onTryAddVolatile': 'Owntempo.onTryAddVolatile',
              'onTryBoost': 'Owntempo.onTryBoost',
              'onUpdate': 'Owntempo.onUpdate',
              'rating': 1.5},
 'Parentalbond': {'flags': {},
                  'name': 'Parental Bond',
                  'num': 185,
                  'onPrepareHit': 'Parentalbond.onPrepareHit',
                  'onSourceModifySecondaries': 'Parentalbond.onSourceModifySecondaries',
                  'rating': 4.5},
 'Pastelveil': {'flags': {'breakable': 1},
                'name': 'Pastel Veil',
                'num': 257,
                'onAllySetStatus': 'Pastelveil.onAllySetStatus',
                'onAllySwitchIn': 'Pastelveil.onAllySwitchIn',
                'onSetStatus': 'Pastelveil.onSetStatus',
                'onStart': 'Pastelveil.onStart',
                'onUpdate': 'Pastelveil.onUpdate',
                'rating': 2},
 'Perishbody': {'flags': {},
                'name': 'Perish Body',
                'num': 253,
                'onDamagingHit': 'Perishbody.onDamagingHit',
                'rating': 1},
 'Persistent': {'flags': {}, 'isNonstandard': 'CAP', 'name': 'Persistent', 'num': -4, 'rating': 3},
 'Pickpocket': {'flags': {},
                'name': 'Pickpocket',
                'num': 124,
                'onAfterMoveSecondary': 'Pickpocket.onAfterMoveSecondary',
                'rating': 1},
 'Pickup': {'flags': {},
            'name': 'Pickup',
            'num': 53,
            'onResidual': 'Pickup.onResidual',
            'onResidualOrder': 28,
            'onResidualSubOrder': 2,
            'rating': 0.5},
 'Pixilate': {'flags': {},
              'name': 'Pixilate',
              'num': 182,
              'onBasePower': 'Pixilate.onBasePower',
              'onBasePowerPriority': 23,
              'onModifyType': 'Pixilate.onModifyType',
              'onModifyTypePriority': -1,
              'rating': 4},
 'Plus': {'flags': {},
          'name': 'Plus',
          'num': 57,
          'onModifySpA': 'Plus.onModifySpA',
          'onModifySpAPriority': 5,
          'rating': 0},
 'Poisonheal': {'flags': {},
                'name': 'Poison Heal',
                'num': 90,
                'onDamage': 'Poisonheal.onDamage',
                'onDamagePriority': 1,
                'rating': 4},
 'Poisonpoint': {'flags': {},
                 'name': 'Poison Point',
                 'num': 38,
                 'onDamagingHit': 'Poisonpoint.onDamagingHit',
                 'rating': 1.5},
 'Poisonpuppeteer': {'flags': {'failroleplay': 1, 'failskillswap': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
                     'name': 'Poison Puppeteer',
                     'num': 310,
                     'onAnyAfterSetStatus': 'Poisonpuppeteer.onAnyAfterSetStatus',
                     'rating': 3},
 'Poisontouch': {'flags': {},
                 'name': 'Poison Touch',
                 'num': 143,
                 'onSourceDamagingHit': 'Poisontouch.onSourceDamagingHit',
                 'rating': 2},
 'Powerconstruct': {'flags': {'cantsuppress': 1,
                              'failroleplay': 1,
                              'failskillswap': 1,
                              'noentrain': 1,
                              'noreceiver': 1,
                              'notrace': 1},
                    'name': 'Power Construct',
                    'num': 211,
                    'onResidual': 'Powerconstruct.onResidual',
                    'onResidualOrder': 29,
                    'rating': 5},
 'Powerofalchemy': {'flags': {'failroleplay': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
                    'name': 'Power of Alchemy',
                    'num': 223,
                    'onAllyFaint': 'Powerofalchemy.onAllyFaint',
                    'rating': 0},
 'Powerspot': {'flags': {},
               'name': 'Power Spot',
               'num': 249,
               'onAllyBasePower': 'Powerspot.onAllyBasePower',
               'onAllyBasePowerPriority': 22,
               'rating': 0},
 'Prankster': {'flags': {},
               'name': 'Prankster',
               'num': 158,
               'onModifyPriority': 'Prankster.onModifyPriority',
               'rating': 4},
 'Pressure': {'flags': {},
              'name': 'Pressure',
              'num': 46,
              'onDeductPP': 'Pressure.onDeductPP',
              'onStart': 'Pressure.onStart',
              'rating': 2.5},
 'Primordialsea': {'flags': {},
                   'name': 'Primordial Sea',
                   'num': 189,
                   'onAnySetWeather': 'Primordialsea.onAnySetWeather',
                   'onEnd': 'Primordialsea.onEnd',
                   'onStart': 'Primordialsea.onStart',
                   'rating': 4.5},
 'Prismarmor': {'flags': {},
                'name': 'Prism Armor',
                'num': 232,
                'onSourceModifyDamage': 'Prismarmor.onSourceModifyDamage',
                'rating': 3},
 'Propellertail': {'flags': {},
                   'name': 'Propeller Tail',
                   'num': 239,
                   'onModifyMove': 'Propellertail.onModifyMove',
                   'onModifyMovePriority': 1,
                   'rating': 0},
 'Protean': {'flags': {},
             'name': 'Protean',
             'num': 168,
             'onPrepareHit': 'Protean.onPrepareHit',
             'onSwitchIn': 'Protean.onSwitchIn',
             'rating': 4},
 'Protosynthesis': {'condition': {'noCopy': True,
                                  'onModifyAtkPriority': 5,
                                  'onModifyDefPriority': 6,
                                  'onModifySpAPriority': 5,
                                  'onModifySpDPriority': 6},
                    'flags': {'failroleplay': 1,
                              'failskillswap': 1,
                              'noentrain': 1,
                              'noreceiver': 1,
                              'notrace': 1,
                              'notransform': 1},
                    'name': 'Protosynthesis',
                    'num': 281,
                    'onEnd': 'Protosynthesis.onEnd',
                    'onStart': 'Protosynthesis.onStart',
                    'onWeatherChange': 'Protosynthesis.onWeatherChange',
                    'rating': 3},
 'Psychicsurge': {'flags': {}, 'name': 'Psychic Surge', 'num': 227, 'onStart': 'Psychicsurge.onStart', 'rating': 4},
 'Punkrock': {'flags': {'breakable': 1},
              'name': 'Punk Rock',
              'num': 244,
              'onBasePower': 'Punkrock.onBasePower',
              'onBasePowerPriority': 7,
              'onSourceModifyDamage': 'Punkrock.onSourceModifyDamage',
              'rating': 3.5},
 'Purepower': {'flags': {},
               'name': 'Pure Power',
               'num': 74,
               'onModifyAtk': 'Purepower.onModifyAtk',
               'onModifyAtkPriority': 5,
               'rating': 5},
 'Purifyingsalt': {'flags': {'breakable': 1},
                   'name': 'Purifying Salt',
                   'num': 272,
                   'onSetStatus': 'Purifyingsalt.onSetStatus',
                   'onSourceModifyAtk': 'Purifyingsalt.onSourceModifyAtk',
                   'onSourceModifyAtkPriority': 6,
                   'onSourceModifySpA': 'Purifyingsalt.onSourceModifySpA',
                   'onSourceModifySpAPriority': 5,
                   'onTryAddVolatile': 'Purifyingsalt.onTryAddVolatile',
                   'rating': 4},
 'Quarkdrive': {'condition': {'noCopy': True,
                              'onModifyAtkPriority': 5,
                              'onModifyDefPriority': 6,
                              'onModifySpAPriority': 5,
                              'onModifySpDPriority': 6},
                'flags': {'failroleplay': 1,
                          'failskillswap': 1,
                          'noentrain': 1,
                          'noreceiver': 1,
                          'notrace': 1,
                          'notransform': 1},
                'name': 'Quark Drive',
                'num': 282,
                'onEnd': 'Quarkdrive.onEnd',
                'onStart': 'Quarkdrive.onStart',
                'onTerrainChange': 'Quarkdrive.onTerrainChange',
                'rating': 3},
 'Queenlymajesty': {'flags': {'breakable': 1},
                    'name': 'Queenly Majesty',
                    'num': 214,
                    'onFoeTryMove': 'Queenlymajesty.onFoeTryMove',
                    'rating': 2.5},
 'Quickdraw': {'flags': {},
               'name': 'Quick Draw',
               'num': 259,
               'onFractionalPriority': 'Quickdraw.onFractionalPriority',
               'onFractionalPriorityPriority': -1,
               'rating': 2.5},
 'Quickfeet': {'flags': {}, 'name': 'Quick Feet', 'num': 95, 'onModifySpe': 'Quickfeet.onModifySpe', 'rating': 2.5},
 'Raindish': {'flags': {}, 'name': 'Rain Dish', 'num': 44, 'onWeather': 'Raindish.onWeather', 'rating': 1.5},
 'Rattled': {'flags': {},
             'name': 'Rattled',
             'num': 155,
             'onAfterBoost': 'Rattled.onAfterBoost',
             'onDamagingHit': 'Rattled.onDamagingHit',
             'rating': 1},
 'Rebound': {'condition': {'duration': 1},
             'flags': {'breakable': 1},
             'isNonstandard': 'CAP',
             'name': 'Rebound',
             'num': -3,
             'onAllyTryHitSide': 'Rebound.onAllyTryHitSide',
             'onTryHit': 'Rebound.onTryHit',
             'onTryHitPriority': 1,
             'rating': 3},
 'Receiver': {'flags': {'failroleplay': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
              'name': 'Receiver',
              'num': 222,
              'onAllyFaint': 'Receiver.onAllyFaint',
              'rating': 0},
 'Reckless': {'flags': {},
              'name': 'Reckless',
              'num': 120,
              'onBasePower': 'Reckless.onBasePower',
              'onBasePowerPriority': 23,
              'rating': 3},
 'Refrigerate': {'flags': {},
                 'name': 'Refrigerate',
                 'num': 174,
                 'onBasePower': 'Refrigerate.onBasePower',
                 'onBasePowerPriority': 23,
                 'onModifyType': 'Refrigerate.onModifyType',
                 'onModifyTypePriority': -1,
                 'rating': 4},
 'Regenerator': {'flags': {},
                 'name': 'Regenerator',
                 'num': 144,
                 'onSwitchOut': 'Regenerator.onSwitchOut',
                 'rating': 4.5},
 'Ripen': {'flags': {},
           'name': 'Ripen',
           'num': 247,
           'onChangeBoost': 'Ripen.onChangeBoost',
           'onEatItem': 'Ripen.onEatItem',
           'onSourceModifyDamage': 'Ripen.onSourceModifyDamage',
           'onSourceModifyDamagePriority': -1,
           'onTryEatItem': 'Ripen.onTryEatItem',
           'onTryEatItemPriority': -1,
           'onTryHeal': 'Ripen.onTryHeal',
           'rating': 2},
 'Rivalry': {'flags': {},
             'name': 'Rivalry',
             'num': 79,
             'onBasePower': 'Rivalry.onBasePower',
             'onBasePowerPriority': 24,
             'rating': 0},
 'Rkssystem': {'flags': {'cantsuppress': 1,
                         'failroleplay': 1,
                         'failskillswap': 1,
                         'noentrain': 1,
                         'noreceiver': 1,
                         'notrace': 1},
               'name': 'RKS System',
               'num': 225,
               'rating': 4},
 'Rockhead': {'flags': {}, 'name': 'Rock Head', 'num': 69, 'onDamage': 'Rockhead.onDamage', 'rating': 3},
 'Rockypayload': {'flags': {},
                  'name': 'Rocky Payload',
                  'num': 276,
                  'onModifyAtk': 'Rockypayload.onModifyAtk',
                  'onModifyAtkPriority': 5,
                  'onModifySpA': 'Rockypayload.onModifySpA',
                  'onModifySpAPriority': 5,
                  'rating': 3.5},
 'Roughskin': {'flags': {},
               'name': 'Rough Skin',
               'num': 24,
               'onDamagingHit': 'Roughskin.onDamagingHit',
               'onDamagingHitOrder': 1,
               'rating': 2.5},
 'Runaway': {'flags': {}, 'name': 'Run Away', 'num': 50, 'rating': 0},
 'Sandforce': {'flags': {},
               'name': 'Sand Force',
               'num': 159,
               'onBasePower': 'Sandforce.onBasePower',
               'onBasePowerPriority': 21,
               'onImmunity': 'Sandforce.onImmunity',
               'rating': 2},
 'Sandrush': {'flags': {},
              'name': 'Sand Rush',
              'num': 146,
              'onImmunity': 'Sandrush.onImmunity',
              'onModifySpe': 'Sandrush.onModifySpe',
              'rating': 3},
 'Sandspit': {'flags': {}, 'name': 'Sand Spit', 'num': 245, 'onDamagingHit': 'Sandspit.onDamagingHit', 'rating': 1},
 'Sandstream': {'flags': {}, 'name': 'Sand Stream', 'num': 45, 'onStart': 'Sandstream.onStart', 'rating': 4},
 'Sandveil': {'flags': {'breakable': 1},
              'name': 'Sand Veil',
              'num': 8,
              'onImmunity': 'Sandveil.onImmunity',
              'onModifyAccuracy': 'Sandveil.onModifyAccuracy',
              'onModifyAccuracyPriority': -1,
              'rating': 1.5},
 'Sapsipper': {'flags': {'breakable': 1},
               'name': 'Sap Sipper',
               'num': 157,
               'onAllyTryHitSide': 'Sapsipper.onAllyTryHitSide',
               'onTryHit': 'Sapsipper.onTryHit',
               'onTryHitPriority': 1,
               'rating': 3},
 'Schooling': {'flags': {'cantsuppress': 1,
                         'failroleplay': 1,
                         'failskillswap': 1,
                         'noentrain': 1,
                         'noreceiver': 1,
                         'notrace': 1},
               'name': 'Schooling',
               'num': 208,
               'onResidual': 'Schooling.onResidual',
               'onResidualOrder': 29,
               'onStart': 'Schooling.onStart',
               'rating': 3},
 'Scrappy': {'flags': {},
             'name': 'Scrappy',
             'num': 113,
             'onModifyMove': 'Scrappy.onModifyMove',
             'onModifyMovePriority': -5,
             'onTryBoost': 'Scrappy.onTryBoost',
             'rating': 3},
 'Screencleaner': {'flags': {}, 'name': 'Screen Cleaner', 'num': 251, 'onStart': 'Screencleaner.onStart', 'rating': 2},
 'Seedsower': {'flags': {},
               'name': 'Seed Sower',
               'num': 269,
               'onDamagingHit': 'Seedsower.onDamagingHit',
               'rating': 2.5},
 'Serenegrace': {'flags': {},
                 'name': 'Serene Grace',
                 'num': 32,
                 'onModifyMove': 'Serenegrace.onModifyMove',
                 'onModifyMovePriority': -2,
                 'rating': 3.5},
 'Shadowshield': {'flags': {},
                  'name': 'Shadow Shield',
                  'num': 231,
                  'onSourceModifyDamage': 'Shadowshield.onSourceModifyDamage',
                  'rating': 3.5},
 'Shadowtag': {'flags': {},
               'name': 'Shadow Tag',
               'num': 23,
               'onFoeMaybeTrapPokemon': 'Shadowtag.onFoeMaybeTrapPokemon',
               'onFoeTrapPokemon': 'Shadowtag.onFoeTrapPokemon',
               'rating': 5},
 'Sharpness': {'flags': {},
               'name': 'Sharpness',
               'num': 292,
               'onBasePower': 'Sharpness.onBasePower',
               'onBasePowerPriority': 19,
               'rating': 3.5},
 'Shedskin': {'flags': {},
              'name': 'Shed Skin',
              'num': 61,
              'onResidual': 'Shedskin.onResidual',
              'onResidualOrder': 5,
              'onResidualSubOrder': 3,
              'rating': 3},
 'Sheerforce': {'flags': {},
                'name': 'Sheer Force',
                'num': 125,
                'onBasePower': 'Sheerforce.onBasePower',
                'onBasePowerPriority': 21,
                'onModifyMove': 'Sheerforce.onModifyMove',
                'rating': 3.5},
 'Shellarmor': {'flags': {'breakable': 1}, 'name': 'Shell Armor', 'num': 75, 'onCriticalHit': False, 'rating': 1},
 'Shielddust': {'flags': {'breakable': 1},
                'name': 'Shield Dust',
                'num': 19,
                'onModifySecondaries': 'Shielddust.onModifySecondaries',
                'rating': 2},
 'Shieldsdown': {'flags': {'cantsuppress': 1,
                           'failroleplay': 1,
                           'failskillswap': 1,
                           'noentrain': 1,
                           'noreceiver': 1,
                           'notrace': 1},
                 'name': 'Shields Down',
                 'num': 197,
                 'onResidual': 'Shieldsdown.onResidual',
                 'onResidualOrder': 29,
                 'onSetStatus': 'Shieldsdown.onSetStatus',
                 'onStart': 'Shieldsdown.onStart',
                 'onTryAddVolatile': 'Shieldsdown.onTryAddVolatile',
                 'rating': 3},
 'Simple': {'flags': {'breakable': 1},
            'name': 'Simple',
            'num': 86,
            'onChangeBoost': 'Simple.onChangeBoost',
            'rating': 4},
 'Skilllink': {'flags': {}, 'name': 'Skill Link', 'num': 92, 'onModifyMove': 'Skilllink.onModifyMove', 'rating': 3},
 'Slowstart': {'condition': {'duration': 5, 'onModifyAtkPriority': 5, 'onResidualOrder': 28, 'onResidualSubOrder': 2},
               'flags': {},
               'name': 'Slow Start',
               'num': 112,
               'onEnd': 'Slowstart.onEnd',
               'onStart': 'Slowstart.onStart',
               'rating': -1},
 'Slushrush': {'flags': {}, 'name': 'Slush Rush', 'num': 202, 'onModifySpe': 'Slushrush.onModifySpe', 'rating': 3},
 'Sniper': {'flags': {}, 'name': 'Sniper', 'num': 97, 'onModifyDamage': 'Sniper.onModifyDamage', 'rating': 2},
 'Snowcloak': {'flags': {'breakable': 1},
               'name': 'Snow Cloak',
               'num': 81,
               'onImmunity': 'Snowcloak.onImmunity',
               'onModifyAccuracy': 'Snowcloak.onModifyAccuracy',
               'onModifyAccuracyPriority': -1,
               'rating': 1.5},
 'Snowwarning': {'flags': {}, 'name': 'Snow Warning', 'num': 117, 'onStart': 'Snowwarning.onStart', 'rating': 4},
 'Solarpower': {'flags': {},
                'name': 'Solar Power',
                'num': 94,
                'onModifySpA': 'Solarpower.onModifySpA',
                'onModifySpAPriority': 5,
                'onWeather': 'Solarpower.onWeather',
                'rating': 2},
 'Solidrock': {'flags': {'breakable': 1},
               'name': 'Solid Rock',
               'num': 116,
               'onSourceModifyDamage': 'Solidrock.onSourceModifyDamage',
               'rating': 3},
 'Soulheart': {'flags': {},
               'name': 'Soul-Heart',
               'num': 220,
               'onAnyFaint': 'Soulheart.onAnyFaint',
               'onAnyFaintPriority': 1,
               'rating': 3.5},
 'Soundproof': {'flags': {'breakable': 1},
                'name': 'Soundproof',
                'num': 43,
                'onAllyTryHitSide': 'Soundproof.onAllyTryHitSide',
                'onTryHit': 'Soundproof.onTryHit',
                'rating': 2},
 'Speedboost': {'flags': {},
                'name': 'Speed Boost',
                'num': 3,
                'onResidual': 'Speedboost.onResidual',
                'onResidualOrder': 28,
                'onResidualSubOrder': 2,
                'rating': 4.5},
 'Stakeout': {'flags': {},
              'name': 'Stakeout',
              'num': 198,
              'onModifyAtk': 'Stakeout.onModifyAtk',
              'onModifyAtkPriority': 5,
              'onModifySpA': 'Stakeout.onModifySpA',
              'onModifySpAPriority': 5,
              'rating': 4.5},
 'Stall': {'flags': {}, 'name': 'Stall', 'num': 100, 'onFractionalPriority': -0.1, 'rating': -1},
 'Stalwart': {'flags': {},
              'name': 'Stalwart',
              'num': 242,
              'onModifyMove': 'Stalwart.onModifyMove',
              'onModifyMovePriority': 1,
              'rating': 0},
 'Stamina': {'flags': {}, 'name': 'Stamina', 'num': 192, 'onDamagingHit': 'Stamina.onDamagingHit', 'rating': 4},
 'Stancechange': {'flags': {'cantsuppress': 1,
                            'failroleplay': 1,
                            'failskillswap': 1,
                            'noentrain': 1,
                            'noreceiver': 1,
                            'notrace': 1},
                  'name': 'Stance Change',
                  'num': 176,
                  'onModifyMove': 'Stancechange.onModifyMove',
                  'onModifyMovePriority': 1,
                  'rating': 4},
 'Static': {'flags': {}, 'name': 'Static', 'num': 9, 'onDamagingHit': 'Static.onDamagingHit', 'rating': 2},
 'Steadfast': {'flags': {}, 'name': 'Steadfast', 'num': 80, 'onFlinch': 'Steadfast.onFlinch', 'rating': 1},
 'Steamengine': {'flags': {},
                 'name': 'Steam Engine',
                 'num': 243,
                 'onDamagingHit': 'Steamengine.onDamagingHit',
                 'rating': 2},
 'Steelworker': {'flags': {},
                 'name': 'Steelworker',
                 'num': 200,
                 'onModifyAtk': 'Steelworker.onModifyAtk',
                 'onModifyAtkPriority': 5,
                 'onModifySpA': 'Steelworker.onModifySpA',
                 'onModifySpAPriority': 5,
                 'rating': 3.5},
 'Steelyspirit': {'flags': {},
                  'name': 'Steely Spirit',
                  'num': 252,
                  'onAllyBasePower': 'Steelyspirit.onAllyBasePower',
                  'onAllyBasePowerPriority': 22,
                  'rating': 3.5},
 'Stench': {'flags': {},
            'name': 'Stench',
            'num': 1,
            'onModifyMove': 'Stench.onModifyMove',
            'onModifyMovePriority': -1,
            'rating': 0.5},
 'Stickyhold': {'flags': {'breakable': 1},
                'name': 'Sticky Hold',
                'num': 60,
                'onTakeItem': 'Stickyhold.onTakeItem',
                'rating': 1.5},
 'Stormdrain': {'flags': {'breakable': 1},
                'name': 'Storm Drain',
                'num': 114,
                'onAnyRedirectTarget': 'Stormdrain.onAnyRedirectTarget',
                'onTryHit': 'Stormdrain.onTryHit',
                'rating': 3},
 'Strongjaw': {'flags': {},
               'name': 'Strong Jaw',
               'num': 173,
               'onBasePower': 'Strongjaw.onBasePower',
               'onBasePowerPriority': 19,
               'rating': 3.5},
 'Sturdy': {'flags': {'breakable': 1},
            'name': 'Sturdy',
            'num': 5,
            'onDamage': 'Sturdy.onDamage',
            'onDamagePriority': -30,
            'onTryHit': 'Sturdy.onTryHit',
            'rating': 3},
 'Suctioncups': {'flags': {'breakable': 1},
                 'name': 'Suction Cups',
                 'num': 21,
                 'onDragOut': 'Suctioncups.onDragOut',
                 'onDragOutPriority': 1,
                 'rating': 1},
 'Superluck': {'flags': {},
               'name': 'Super Luck',
               'num': 105,
               'onModifyCritRatio': 'Superluck.onModifyCritRatio',
               'rating': 1.5},
 'Supersweetsyrup': {'flags': {},
                     'name': 'Supersweet Syrup',
                     'num': 306,
                     'onStart': 'Supersweetsyrup.onStart',
                     'rating': 1.5},
 'Supremeoverlord': {'flags': {},
                     'name': 'Supreme Overlord',
                     'num': 293,
                     'onBasePower': 'Supremeoverlord.onBasePower',
                     'onBasePowerPriority': 21,
                     'onEnd': 'Supremeoverlord.onEnd',
                     'onStart': 'Supremeoverlord.onStart',
                     'rating': 4},
 'Surgesurfer': {'flags': {},
                 'name': 'Surge Surfer',
                 'num': 207,
                 'onModifySpe': 'Surgesurfer.onModifySpe',
                 'rating': 3},
 'Swarm': {'flags': {},
           'name': 'Swarm',
           'num': 68,
           'onModifyAtk': 'Swarm.onModifyAtk',
           'onModifyAtkPriority': 5,
           'onModifySpA': 'Swarm.onModifySpA',
           'onModifySpAPriority': 5,
           'rating': 2},
 'Sweetveil': {'flags': {'breakable': 1},
               'name': 'Sweet Veil',
               'num': 175,
               'onAllySetStatus': 'Sweetveil.onAllySetStatus',
               'onAllyTryAddVolatile': 'Sweetveil.onAllyTryAddVolatile',
               'rating': 2},
 'Swiftswim': {'flags': {}, 'name': 'Swift Swim', 'num': 33, 'onModifySpe': 'Swiftswim.onModifySpe', 'rating': 3},
 'Swordofruin': {'flags': {},
                 'name': 'Sword of Ruin',
                 'num': 285,
                 'onAnyModifyDef': 'Swordofruin.onAnyModifyDef',
                 'onStart': 'Swordofruin.onStart',
                 'rating': 4.5},
 'Symbiosis': {'flags': {},
               'name': 'Symbiosis',
               'num': 180,
               'onAllyAfterUseItem': 'Symbiosis.onAllyAfterUseItem',
               'rating': 0},
 'Synchronize': {'flags': {},
                 'name': 'Synchronize',
                 'num': 28,
                 'onAfterSetStatus': 'Synchronize.onAfterSetStatus',
                 'rating': 2},
 'Tabletsofruin': {'flags': {},
                   'name': 'Tablets of Ruin',
                   'num': 284,
                   'onAnyModifyAtk': 'Tabletsofruin.onAnyModifyAtk',
                   'onStart': 'Tabletsofruin.onStart',
                   'rating': 4.5},
 'Tangledfeet': {'flags': {'breakable': 1},
                 'name': 'Tangled Feet',
                 'num': 77,
                 'onModifyAccuracy': 'Tangledfeet.onModifyAccuracy',
                 'onModifyAccuracyPriority': -1,
                 'rating': 1},
 'Tanglinghair': {'flags': {},
                  'name': 'Tangling Hair',
                  'num': 221,
                  'onDamagingHit': 'Tanglinghair.onDamagingHit',
                  'rating': 2},
 'Technician': {'flags': {},
                'name': 'Technician',
                'num': 101,
                'onBasePower': 'Technician.onBasePower',
                'onBasePowerPriority': 30,
                'rating': 3.5},
 'Telepathy': {'flags': {'breakable': 1},
               'name': 'Telepathy',
               'num': 140,
               'onTryHit': 'Telepathy.onTryHit',
               'rating': 0},
 'Teraformzero': {'flags': {'failroleplay': 1, 'failskillswap': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
                  'name': 'Teraform Zero',
                  'num': 309,
                  'onAfterTerastallization': 'Teraformzero.onAfterTerastallization',
                  'rating': 3},
 'Terashell': {'flags': {'breakable': 1,
                         'failroleplay': 1,
                         'failskillswap': 1,
                         'noentrain': 1,
                         'noreceiver': 1,
                         'notrace': 1},
               'name': 'Tera Shell',
               'num': 308,
               'onAnyAfterMove': 'Terashell.onAnyAfterMove',
               'onEffectiveness': 'Terashell.onEffectiveness',
               'rating': 3.5},
 'Terashift': {'flags': {'cantsuppress': 1,
                         'failroleplay': 1,
                         'failskillswap': 1,
                         'noentrain': 1,
                         'noreceiver': 1,
                         'notrace': 1,
                         'notransform': 1},
               'name': 'Tera Shift',
               'num': 307,
               'onPreStart': 'Terashift.onPreStart',
               'rating': 3},
 'Teravolt': {'flags': {},
              'name': 'Teravolt',
              'num': 164,
              'onModifyMove': 'Teravolt.onModifyMove',
              'onStart': 'Teravolt.onStart',
              'rating': 3},
 'Thermalexchange': {'flags': {'breakable': 1},
                     'name': 'Thermal Exchange',
                     'num': 270,
                     'onDamagingHit': 'Thermalexchange.onDamagingHit',
                     'onSetStatus': 'Thermalexchange.onSetStatus',
                     'onUpdate': 'Thermalexchange.onUpdate',
                     'rating': 2.5},
 'Thickfat': {'flags': {'breakable': 1},
              'name': 'Thick Fat',
              'num': 47,
              'onSourceModifyAtk': 'Thickfat.onSourceModifyAtk',
              'onSourceModifyAtkPriority': 6,
              'onSourceModifySpA': 'Thickfat.onSourceModifySpA',
              'onSourceModifySpAPriority': 5,
              'rating': 3.5},
 'Tintedlens': {'flags': {},
                'name': 'Tinted Lens',
                'num': 110,
                'onModifyDamage': 'Tintedlens.onModifyDamage',
                'rating': 4},
 'Torrent': {'flags': {},
             'name': 'Torrent',
             'num': 67,
             'onModifyAtk': 'Torrent.onModifyAtk',
             'onModifyAtkPriority': 5,
             'onModifySpA': 'Torrent.onModifySpA',
             'onModifySpAPriority': 5,
             'rating': 2},
 'Toughclaws': {'flags': {},
                'name': 'Tough Claws',
                'num': 181,
                'onBasePower': 'Toughclaws.onBasePower',
                'onBasePowerPriority': 21,
                'rating': 3.5},
 'Toxicboost': {'flags': {},
                'name': 'Toxic Boost',
                'num': 137,
                'onBasePower': 'Toxicboost.onBasePower',
                'onBasePowerPriority': 19,
                'rating': 3},
 'Toxicchain': {'flags': {},
                'name': 'Toxic Chain',
                'num': 305,
                'onSourceDamagingHit': 'Toxicchain.onSourceDamagingHit',
                'rating': 4.5},
 'Toxicdebris': {'flags': {},
                 'name': 'Toxic Debris',
                 'num': 295,
                 'onDamagingHit': 'Toxicdebris.onDamagingHit',
                 'rating': 3.5},
 'Trace': {'flags': {'failroleplay': 1, 'noentrain': 1, 'noreceiver': 1, 'notrace': 1},
           'name': 'Trace',
           'num': 36,
           'onStart': 'Trace.onStart',
           'onUpdate': 'Trace.onUpdate',
           'rating': 2.5},
 'Transistor': {'flags': {},
                'name': 'Transistor',
                'num': 262,
                'onModifyAtk': 'Transistor.onModifyAtk',
                'onModifyAtkPriority': 5,
                'onModifySpA': 'Transistor.onModifySpA',
                'onModifySpAPriority': 5,
                'rating': 3.5},
 'Triage': {'flags': {}, 'name': 'Triage', 'num': 205, 'onModifyPriority': 'Triage.onModifyPriority', 'rating': 3.5},
 'Truant': {'condition': {},
            'flags': {},
            'name': 'Truant',
            'num': 54,
            'onBeforeMove': 'Truant.onBeforeMove',
            'onBeforeMovePriority': 9,
            'onStart': 'Truant.onStart',
            'rating': -1},
 'Turboblaze': {'flags': {},
                'name': 'Turboblaze',
                'num': 163,
                'onModifyMove': 'Turboblaze.onModifyMove',
                'onStart': 'Turboblaze.onStart',
                'rating': 3},
 'Unaware': {'flags': {'breakable': 1},
             'name': 'Unaware',
             'num': 109,
             'onAnyModifyBoost': 'Unaware.onAnyModifyBoost',
             'rating': 4},
 'Unburden': {'condition': {},
              'flags': {},
              'name': 'Unburden',
              'num': 84,
              'onAfterUseItem': 'Unburden.onAfterUseItem',
              'onEnd': 'Unburden.onEnd',
              'onTakeItem': 'Unburden.onTakeItem',
              'rating': 3.5},
 'Unnerve': {'flags': {},
             'name': 'Unnerve',
             'num': 127,
             'onEnd': 'Unnerve.onEnd',
             'onFoeTryEatItem': 'Unnerve.onFoeTryEatItem',
             'onPreStart': 'Unnerve.onPreStart',
             'onStart': 'Unnerve.onStart',
             'rating': 1},
 'Unseenfist': {'flags': {}, 'name': 'Unseen Fist', 'num': 260, 'onModifyMove': 'Unseenfist.onModifyMove', 'rating': 2},
 'Vesselofruin': {'flags': {},
                  'name': 'Vessel of Ruin',
                  'num': 284,
                  'onAnyModifySpA': 'Vesselofruin.onAnyModifySpA',
                  'onStart': 'Vesselofruin.onStart',
                  'rating': 4.5},
 'Victorystar': {'flags': {},
                 'name': 'Victory Star',
                 'num': 162,
                 'onAnyModifyAccuracy': 'Victorystar.onAnyModifyAccuracy',
                 'onAnyModifyAccuracyPriority': -1,
                 'rating': 2},
 'Vitalspirit': {'flags': {'breakable': 1},
                 'name': 'Vital Spirit',
                 'num': 72,
                 'onSetStatus': 'Vitalspirit.onSetStatus',
                 'onTryAddVolatile': 'Vitalspirit.onTryAddVolatile',
                 'onUpdate': 'Vitalspirit.onUpdate',
                 'rating': 1.5},
 'Voltabsorb': {'flags': {'breakable': 1},
                'name': 'Volt Absorb',
                'num': 10,
                'onTryHit': 'Voltabsorb.onTryHit',
                'rating': 3.5},
 'Wanderingspirit': {'flags': {},
                     'name': 'Wandering Spirit',
                     'num': 254,
                     'onDamagingHit': 'Wanderingspirit.onDamagingHit',
                     'rating': 2.5},
 'Waterabsorb': {'flags': {'breakable': 1},
                 'name': 'Water Absorb',
                 'num': 11,
                 'onTryHit': 'Waterabsorb.onTryHit',
                 'rating': 3.5},
 'Waterbubble': {'flags': {'breakable': 1},
                 'name': 'Water Bubble',
                 'num': 199,
                 'onModifyAtk': 'Waterbubble.onModifyAtk',
                 'onModifySpA': 'Waterbubble.onModifySpA',
                 'onSetStatus': 'Waterbubble.onSetStatus',
                 'onSourceModifyAtk': 'Waterbubble.onSourceModifyAtk',
                 'onSourceModifyAtkPriority': 5,
                 'onSourceModifySpA': 'Waterbubble.onSourceModifySpA',
                 'onSourceModifySpAPriority': 5,
                 'onUpdate': 'Waterbubble.onUpdate',
                 'rating': 4.5},
 'Watercompaction': {'flags': {},
                     'name': 'Water Compaction',
                     'num': 195,
                     'onDamagingHit': 'Watercompaction.onDamagingHit',
                     'rating': 1.5},
 'Waterveil': {'flags': {'breakable': 1},
               'name': 'Water Veil',
               'num': 41,
               'onSetStatus': 'Waterveil.onSetStatus',
               'onUpdate': 'Waterveil.onUpdate',
               'rating': 2},
 'Weakarmor': {'flags': {}, 'name': 'Weak Armor', 'num': 133, 'onDamagingHit': 'Weakarmor.onDamagingHit', 'rating': 1},
 'Wellbakedbody': {'flags': {'breakable': 1},
                   'name': 'Well-Baked Body',
                   'num': 273,
                   'onTryHit': 'Wellbakedbody.onTryHit',
                   'rating': 3.5},
 'Whitesmoke': {'flags': {'breakable': 1},
                'name': 'White Smoke',
                'num': 73,
                'onTryBoost': 'Whitesmoke.onTryBoost',
                'rating': 2},
 'Wimpout': {'flags': {}, 'name': 'Wimp Out', 'num': 193, 'onEmergencyExit': 'Wimpout.onEmergencyExit', 'rating': 1},
 'Windpower': {'flags': {},
               'name': 'Wind Power',
               'num': 277,
               'onAllySideConditionStart': 'Windpower.onAllySideConditionStart',
               'onDamagingHit': 'Windpower.onDamagingHit',
               'onDamagingHitOrder': 1,
               'rating': 1},
 'Windrider': {'flags': {'breakable': 1},
               'name': 'Wind Rider',
               'num': 274,
               'onAllySideConditionStart': 'Windrider.onAllySideConditionStart',
               'onStart': 'Windrider.onStart',
               'onTryHit': 'Windrider.onTryHit',
               'rating': 3.5},
 'Wonderguard': {'flags': {'breakable': 1, 'failroleplay': 1, 'failskillswap': 1, 'noentrain': 1, 'noreceiver': 1},
                 'name': 'Wonder Guard',
                 'num': 25,
                 'onTryHit': 'Wonderguard.onTryHit',
                 'rating': 5},
 'Wonderskin': {'flags': {'breakable': 1},
                'name': 'Wonder Skin',
                'num': 147,
                'onModifyAccuracy': 'Wonderskin.onModifyAccuracy',
                'onModifyAccuracyPriority': 10,
                'rating': 2},
 'Zenmode': {'condition': {},
             'flags': {'cantsuppress': 1,
                       'failroleplay': 1,
                       'failskillswap': 1,
                       'noentrain': 1,
                       'noreceiver': 1,
                       'notrace': 1},
             'name': 'Zen Mode',
             'num': 161,
             'onEnd': 'Zenmode.onEnd',
             'onResidual': 'Zenmode.onResidual',
             'onResidualOrder': 29,
             'rating': 0},
 'Zerotohero': {'flags': {'cantsuppress': 1,
                          'failroleplay': 1,
                          'failskillswap': 1,
                          'noentrain': 1,
                          'noreceiver': 1,
                          'notrace': 1,
                          'notransform': 1},
                'name': 'Zero to Hero',
                'num': 278,
                'onStart': 'Zerotohero.onStart',
                'onSwitchIn': 'Zerotohero.onSwitchIn',
                'onSwitchOut': 'Zerotohero.onSwitchOut',
                'rating': 5}}
