"""Pokédex entries for Alola region."""
from ..functions.pokedex_funcs import *

pokedex = {
    'Rowlet': {   'num': 722,
                  'name': 'Rowlet',
                  'types': ['Grass', 'Flying'],
                  'genderRatio': {'M': 0.875, 'F': 0.125},
                  'baseStats': {'hp': 68, 'atk': 55, 'def': 55, 'spa': 50, 'spd': 50, 'spe': 42},
                  'abilities': {'0': 'Overgrow', 'H': 'Long Reach'},
                  'heightm': 0.3,
                  'weightkg': 1.5,
                  'color': 'Brown',
                  'evos': ['Dartrix'],
                  'eggGroups': ['Flying']},
    'Dartrix': {   'num': 723,
                   'name': 'Dartrix',
                   'types': ['Grass', 'Flying'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 78, 'atk': 75, 'def': 75, 'spa': 70, 'spd': 70, 'spe': 52},
                   'abilities': {'0': 'Overgrow', 'H': 'Long Reach'},
                   'heightm': 0.7,
                   'weightkg': 16,
                   'color': 'Brown',
                   'prevo': 'Rowlet',
                   'evoLevel': 17,
                   'evos': ['Decidueye', 'Decidueye-Hisui'],
                   'eggGroups': ['Flying']},
    'Decidueye': {   'num': 724,
                     'name': 'Decidueye',
                     'types': ['Grass', 'Ghost'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 78, 'atk': 107, 'def': 75, 'spa': 100, 'spd': 100, 'spe': 70},
                     'abilities': {'0': 'Overgrow', 'H': 'Long Reach'},
                     'heightm': 1.6,
                     'weightkg': 36.6,
                     'color': 'Brown',
                     'prevo': 'Dartrix',
                     'evoLevel': 34,
                     'eggGroups': ['Flying'],
                     'otherFormes': ['Decidueye-Hisui'],
                     'formeOrder': ['Decidueye', 'Decidueye-Hisui']},
    'Decidueyehisui': {   'num': 724,
                          'name': 'Decidueye-Hisui',
                          'baseSpecies': 'Decidueye',
                          'forme': 'Hisui',
                          'types': ['Grass', 'Fighting'],
                          'genderRatio': {'M': 0.875, 'F': 0.125},
                          'baseStats': {'hp': 88, 'atk': 112, 'def': 80, 'spa': 95, 'spd': 95, 'spe': 60},
                          'abilities': {'0': 'Overgrow', 'H': 'Scrappy'},
                          'heightm': 1.6,
                          'weightkg': 37,
                          'color': 'Brown',
                          'prevo': 'Dartrix',
                          'evoLevel': 36,
                          'eggGroups': ['Flying']},
    'Litten': {   'num': 725,
                  'name': 'Litten',
                  'types': ['Fire'],
                  'genderRatio': {'M': 0.875, 'F': 0.125},
                  'baseStats': {'hp': 45, 'atk': 65, 'def': 40, 'spa': 60, 'spd': 40, 'spe': 70},
                  'abilities': {'0': 'Blaze', 'H': 'Intimidate'},
                  'heightm': 0.4,
                  'weightkg': 4.3,
                  'color': 'Red',
                  'evos': ['Torracat'],
                  'eggGroups': ['Field']},
    'Torracat': {   'num': 726,
                    'name': 'Torracat',
                    'types': ['Fire'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 65, 'atk': 85, 'def': 50, 'spa': 80, 'spd': 50, 'spe': 90},
                    'abilities': {'0': 'Blaze', 'H': 'Intimidate'},
                    'heightm': 0.7,
                    'weightkg': 25,
                    'color': 'Red',
                    'prevo': 'Litten',
                    'evoLevel': 17,
                    'evos': ['Incineroar'],
                    'eggGroups': ['Field']},
    'Incineroar': {   'num': 727,
                      'name': 'Incineroar',
                      'types': ['Fire', 'Dark'],
                      'genderRatio': {'M': 0.875, 'F': 0.125},
                      'baseStats': {'hp': 95, 'atk': 115, 'def': 90, 'spa': 80, 'spd': 90, 'spe': 60},
                      'abilities': {'0': 'Blaze', 'H': 'Intimidate'},
                      'heightm': 1.8,
                      'weightkg': 83,
                      'color': 'Red',
                      'prevo': 'Torracat',
                      'evoLevel': 34,
                      'eggGroups': ['Field']},
    'Popplio': {   'num': 728,
                   'name': 'Popplio',
                   'types': ['Water'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 50, 'atk': 54, 'def': 54, 'spa': 66, 'spd': 56, 'spe': 40},
                   'abilities': {'0': 'Torrent', 'H': 'Liquid Voice'},
                   'heightm': 0.4,
                   'weightkg': 7.5,
                   'color': 'Blue',
                   'evos': ['Brionne'],
                   'eggGroups': ['Water 1', 'Field']},
    'Brionne': {   'num': 729,
                   'name': 'Brionne',
                   'types': ['Water'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 60, 'atk': 69, 'def': 69, 'spa': 91, 'spd': 81, 'spe': 50},
                   'abilities': {'0': 'Torrent', 'H': 'Liquid Voice'},
                   'heightm': 0.6,
                   'weightkg': 17.5,
                   'color': 'Blue',
                   'prevo': 'Popplio',
                   'evoLevel': 17,
                   'evos': ['Primarina'],
                   'eggGroups': ['Water 1', 'Field']},
    'Primarina': {   'num': 730,
                     'name': 'Primarina',
                     'types': ['Water', 'Fairy'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 80, 'atk': 74, 'def': 74, 'spa': 126, 'spd': 116, 'spe': 60},
                     'abilities': {'0': 'Torrent', 'H': 'Liquid Voice'},
                     'heightm': 1.8,
                     'weightkg': 44,
                     'color': 'Blue',
                     'prevo': 'Brionne',
                     'evoLevel': 34,
                     'eggGroups': ['Water 1', 'Field']},
    'Pikipek': {   'num': 731,
                   'name': 'Pikipek',
                   'types': ['Normal', 'Flying'],
                   'baseStats': {'hp': 35, 'atk': 75, 'def': 30, 'spa': 30, 'spd': 30, 'spe': 65},
                   'abilities': {'0': 'Keen Eye', '1': 'Skill Link', 'H': 'Pickup'},
                   'heightm': 0.3,
                   'weightkg': 1.2,
                   'color': 'Black',
                   'evos': ['Trumbeak'],
                   'eggGroups': ['Flying']},
    'Trumbeak': {   'num': 732,
                    'name': 'Trumbeak',
                    'types': ['Normal', 'Flying'],
                    'baseStats': {'hp': 55, 'atk': 85, 'def': 50, 'spa': 40, 'spd': 50, 'spe': 75},
                    'abilities': {'0': 'Keen Eye', '1': 'Skill Link', 'H': 'Pickup'},
                    'heightm': 0.6,
                    'weightkg': 14.8,
                    'color': 'Black',
                    'prevo': 'Pikipek',
                    'evoLevel': 14,
                    'evos': ['Toucannon'],
                    'eggGroups': ['Flying']},
    'Toucannon': {   'num': 733,
                     'name': 'Toucannon',
                     'types': ['Normal', 'Flying'],
                     'baseStats': {'hp': 80, 'atk': 120, 'def': 75, 'spa': 75, 'spd': 75, 'spe': 60},
                     'abilities': {'0': 'Keen Eye', '1': 'Skill Link', 'H': 'Sheer Force'},
                     'heightm': 1.1,
                     'weightkg': 26,
                     'color': 'Black',
                     'prevo': 'Trumbeak',
                     'evoLevel': 28,
                     'eggGroups': ['Flying']},
    'Yungoos': {   'num': 734,
                   'name': 'Yungoos',
                   'types': ['Normal'],
                   'baseStats': {'hp': 48, 'atk': 70, 'def': 30, 'spa': 30, 'spd': 30, 'spe': 45},
                   'abilities': {'0': 'Stakeout', '1': 'Strong Jaw', 'H': 'Adaptability'},
                   'heightm': 0.4,
                   'weightkg': 6,
                   'color': 'Brown',
                   'evos': ['Gumshoos'],
                   'eggGroups': ['Field']},
    'Gumshoos': {   'num': 735,
                    'name': 'Gumshoos',
                    'types': ['Normal'],
                    'baseStats': {'hp': 88, 'atk': 110, 'def': 60, 'spa': 55, 'spd': 60, 'spe': 45},
                    'abilities': {'0': 'Stakeout', '1': 'Strong Jaw', 'H': 'Adaptability'},
                    'heightm': 0.7,
                    'weightkg': 14.2,
                    'color': 'Brown',
                    'prevo': 'Yungoos',
                    'evoLevel': 20,
                    'evoCondition': 'during the day',
                    'eggGroups': ['Field'],
                    'otherFormes': ['Gumshoos-Totem'],
                    'formeOrder': ['Gumshoos', 'Gumshoos-Totem']},
    'Gumshoostotem': {   'num': 735,
                         'name': 'Gumshoos-Totem',
                         'baseSpecies': 'Gumshoos',
                         'forme': 'Totem',
                         'types': ['Normal'],
                         'baseStats': {'hp': 88, 'atk': 110, 'def': 60, 'spa': 55, 'spd': 60, 'spe': 45},
                         'abilities': {'0': 'Adaptability'},
                         'heightm': 1.4,
                         'weightkg': 60,
                         'color': 'Brown',
                         'eggGroups': ['Field']},
    'Grubbin': {   'num': 736,
                   'name': 'Grubbin',
                   'types': ['Bug'],
                   'baseStats': {'hp': 47, 'atk': 62, 'def': 45, 'spa': 55, 'spd': 45, 'spe': 46},
                   'abilities': {'0': 'Swarm'},
                   'heightm': 0.4,
                   'weightkg': 4.4,
                   'color': 'Gray',
                   'evos': ['Charjabug'],
                   'eggGroups': ['Bug']},
    'Charjabug': {   'num': 737,
                     'name': 'Charjabug',
                     'types': ['Bug', 'Electric'],
                     'baseStats': {'hp': 57, 'atk': 82, 'def': 95, 'spa': 55, 'spd': 75, 'spe': 36},
                     'abilities': {'0': 'Battery'},
                     'heightm': 0.5,
                     'weightkg': 10.5,
                     'color': 'Green',
                     'prevo': 'Grubbin',
                     'evoLevel': 20,
                     'evos': ['Vikavolt'],
                     'eggGroups': ['Bug']},
    'Vikavolt': {   'num': 738,
                    'name': 'Vikavolt',
                    'types': ['Bug', 'Electric'],
                    'baseStats': {'hp': 77, 'atk': 70, 'def': 90, 'spa': 145, 'spd': 75, 'spe': 43},
                    'abilities': {'0': 'Levitate'},
                    'heightm': 1.5,
                    'weightkg': 45,
                    'color': 'Blue',
                    'prevo': 'Charjabug',
                    'evoType': 'useItem',
                    'evoItem': 'Thunder Stone',
                    'eggGroups': ['Bug'],
                    'otherFormes': ['Vikavolt-Totem'],
                    'formeOrder': ['Vikavolt', 'Vikavolt-Totem']},
    'Vikavolttotem': {   'num': 738,
                         'name': 'Vikavolt-Totem',
                         'baseSpecies': 'Vikavolt',
                         'forme': 'Totem',
                         'types': ['Bug', 'Electric'],
                         'baseStats': {'hp': 77, 'atk': 70, 'def': 90, 'spa': 145, 'spd': 75, 'spe': 43},
                         'abilities': {'0': 'Levitate'},
                         'heightm': 2.6,
                         'weightkg': 147.5,
                         'color': 'Blue',
                         'eggGroups': ['Bug']},
    'Crabrawler': {   'num': 739,
                      'name': 'Crabrawler',
                      'types': ['Fighting'],
                      'baseStats': {'hp': 47, 'atk': 82, 'def': 57, 'spa': 42, 'spd': 47, 'spe': 63},
                      'abilities': {'0': 'Hyper Cutter', '1': 'Iron Fist', 'H': 'Anger Point'},
                      'heightm': 0.6,
                      'weightkg': 7,
                      'color': 'Purple',
                      'evos': ['Crabominable'],
                      'eggGroups': ['Water 3']},
    'Crabominable': {   'num': 740,
                        'name': 'Crabominable',
                        'types': ['Fighting', 'Ice'],
                        'baseStats': {'hp': 97, 'atk': 132, 'def': 77, 'spa': 62, 'spd': 67, 'spe': 43},
                        'abilities': {'0': 'Hyper Cutter', '1': 'Iron Fist', 'H': 'Anger Point'},
                        'heightm': 1.7,
                        'weightkg': 180,
                        'color': 'White',
                        'prevo': 'Crabrawler',
                        'evoType': 'useItem',
                        'evoItem': 'Ice Stone',
                        'eggGroups': ['Water 3']},
    'Oricorio': {   'num': 741,
                    'name': 'Oricorio',
                    'baseForme': 'Baile',
                    'types': ['Fire', 'Flying'],
                    'genderRatio': {'M': 0.25, 'F': 0.75},
                    'baseStats': {'hp': 75, 'atk': 70, 'def': 70, 'spa': 98, 'spd': 70, 'spe': 93},
                    'abilities': {'0': 'Dancer'},
                    'heightm': 0.6,
                    'weightkg': 3.4,
                    'color': 'Red',
                    'eggGroups': ['Flying'],
                    'otherFormes': ['Oricorio-Pom-Pom', "Oricorio-Pa'u", 'Oricorio-Sensu'],
                    'formeOrder': ['Oricorio', 'Oricorio-Pom-Pom', "Oricorio-Pa'u", 'Oricorio-Sensu']},
    'Oricoriopompom': {   'num': 741,
                          'name': 'Oricorio-Pom-Pom',
                          'baseSpecies': 'Oricorio',
                          'forme': 'Pom-Pom',
                          'types': ['Electric', 'Flying'],
                          'genderRatio': {'M': 0.25, 'F': 0.75},
                          'baseStats': {'hp': 75, 'atk': 70, 'def': 70, 'spa': 98, 'spd': 70, 'spe': 93},
                          'abilities': {'0': 'Dancer'},
                          'heightm': 0.6,
                          'weightkg': 3.4,
                          'color': 'Yellow',
                          'eggGroups': ['Flying'],
                          'changesFrom': 'Oricorio'},
    'Oricoriopau': {   'num': 741,
                       'name': "Oricorio-Pa'u",
                       'baseSpecies': 'Oricorio',
                       'forme': "Pa'u",
                       'types': ['Psychic', 'Flying'],
                       'genderRatio': {'M': 0.25, 'F': 0.75},
                       'baseStats': {'hp': 75, 'atk': 70, 'def': 70, 'spa': 98, 'spd': 70, 'spe': 93},
                       'abilities': {'0': 'Dancer'},
                       'heightm': 0.6,
                       'weightkg': 3.4,
                       'color': 'Pink',
                       'eggGroups': ['Flying'],
                       'changesFrom': 'Oricorio'},
    'Oricoriosensu': {   'num': 741,
                         'name': 'Oricorio-Sensu',
                         'baseSpecies': 'Oricorio',
                         'forme': 'Sensu',
                         'types': ['Ghost', 'Flying'],
                         'genderRatio': {'M': 0.25, 'F': 0.75},
                         'baseStats': {'hp': 75, 'atk': 70, 'def': 70, 'spa': 98, 'spd': 70, 'spe': 93},
                         'abilities': {'0': 'Dancer'},
                         'heightm': 0.6,
                         'weightkg': 3.4,
                         'color': 'Purple',
                         'eggGroups': ['Flying'],
                         'changesFrom': 'Oricorio'},
    'Cutiefly': {   'num': 742,
                    'name': 'Cutiefly',
                    'types': ['Bug', 'Fairy'],
                    'baseStats': {'hp': 40, 'atk': 45, 'def': 40, 'spa': 55, 'spd': 40, 'spe': 84},
                    'abilities': {'0': 'Honey Gather', '1': 'Shield Dust', 'H': 'Sweet Veil'},
                    'heightm': 0.1,
                    'weightkg': 0.2,
                    'color': 'Yellow',
                    'evos': ['Ribombee'],
                    'eggGroups': ['Bug', 'Fairy']},
    'Ribombee': {   'num': 743,
                    'name': 'Ribombee',
                    'types': ['Bug', 'Fairy'],
                    'baseStats': {'hp': 60, 'atk': 55, 'def': 60, 'spa': 95, 'spd': 70, 'spe': 124},
                    'abilities': {'0': 'Honey Gather', '1': 'Shield Dust', 'H': 'Sweet Veil'},
                    'heightm': 0.2,
                    'weightkg': 0.5,
                    'color': 'Yellow',
                    'prevo': 'Cutiefly',
                    'evoLevel': 25,
                    'eggGroups': ['Bug', 'Fairy'],
                    'otherFormes': ['Ribombee-Totem'],
                    'formeOrder': ['Ribombee', 'Ribombee-Totem']},
    'Ribombeetotem': {   'num': 743,
                         'name': 'Ribombee-Totem',
                         'baseSpecies': 'Ribombee',
                         'forme': 'Totem',
                         'types': ['Bug', 'Fairy'],
                         'baseStats': {'hp': 60, 'atk': 55, 'def': 60, 'spa': 95, 'spd': 70, 'spe': 124},
                         'abilities': {'0': 'Sweet Veil'},
                         'heightm': 0.4,
                         'weightkg': 2,
                         'color': 'Yellow',
                         'eggGroups': ['Bug', 'Fairy']},
    'Rockruff': {   'num': 744,
                    'name': 'Rockruff',
                    'baseForme': 'Midday',
                    'types': ['Rock'],
                    'baseStats': {'hp': 45, 'atk': 65, 'def': 40, 'spa': 30, 'spd': 40, 'spe': 60},
                    'abilities': {'0': 'Keen Eye', '1': 'Vital Spirit', 'H': 'Steadfast', 'S': 'Own Tempo'},
                    'heightm': 0.5,
                    'weightkg': 9.2,
                    'color': 'Brown',
                    'evos': ['Lycanroc', 'Lycanroc-Midnight', 'Lycanroc-Dusk'],
                    'eggGroups': ['Field'],
                    'formeOrder': ['Rockruff', 'Rockruff']},
    'Lycanroc': {   'num': 745,
                    'name': 'Lycanroc',
                    'baseForme': 'Midday',
                    'types': ['Rock'],
                    'baseStats': {'hp': 75, 'atk': 115, 'def': 65, 'spa': 55, 'spd': 65, 'spe': 112},
                    'abilities': {'0': 'Keen Eye', '1': 'Sand Rush', 'H': 'Steadfast'},
                    'heightm': 0.8,
                    'weightkg': 25,
                    'color': 'Brown',
                    'prevo': 'Rockruff',
                    'evoLevel': 25,
                    'evoCondition': 'during the day',
                    'eggGroups': ['Field'],
                    'otherFormes': ['Lycanroc-Midnight', 'Lycanroc-Dusk'],
                    'formeOrder': ['Lycanroc', 'Lycanroc-Midnight', 'Lycanroc-Dusk']},
    'Lycanrocmidnight': {   'num': 745,
                            'name': 'Lycanroc-Midnight',
                            'baseSpecies': 'Lycanroc',
                            'forme': 'Midnight',
                            'types': ['Rock'],
                            'baseStats': {'hp': 85, 'atk': 115, 'def': 75, 'spa': 55, 'spd': 75, 'spe': 82},
                            'abilities': {'0': 'Keen Eye', '1': 'Vital Spirit', 'H': 'No Guard'},
                            'heightm': 1.1,
                            'weightkg': 25,
                            'color': 'Red',
                            'prevo': 'Rockruff',
                            'evoLevel': 25,
                            'evoCondition': 'at night',
                            'eggGroups': ['Field']},
    'Lycanrocdusk': {   'num': 745,
                        'name': 'Lycanroc-Dusk',
                        'baseSpecies': 'Lycanroc',
                        'forme': 'Dusk',
                        'types': ['Rock'],
                        'baseStats': {'hp': 75, 'atk': 117, 'def': 65, 'spa': 55, 'spd': 65, 'spe': 110},
                        'abilities': {'0': 'Tough Claws'},
                        'heightm': 0.8,
                        'weightkg': 25,
                        'color': 'Brown',
                        'prevo': 'Rockruff',
                        'evoLevel': 25,
                        'evoCondition': 'from a special Rockruff',
                        'eggGroups': ['Field']},
    'Wishiwashi': {   'num': 746,
                      'name': 'Wishiwashi',
                      'baseForme': 'Solo',
                      'types': ['Water'],
                      'baseStats': {'hp': 45, 'atk': 20, 'def': 20, 'spa': 25, 'spd': 25, 'spe': 40},
                      'abilities': {'0': 'Schooling'},
                      'heightm': 0.2,
                      'weightkg': 0.3,
                      'color': 'Blue',
                      'eggGroups': ['Water 2'],
                      'otherFormes': ['Wishiwashi-School'],
                      'formeOrder': ['Wishiwashi', 'Wishiwashi-School']},
    'Wishiwashischool': {   'num': 746,
                            'name': 'Wishiwashi-School',
                            'baseSpecies': 'Wishiwashi',
                            'forme': 'School',
                            'types': ['Water'],
                            'baseStats': {'hp': 45, 'atk': 140, 'def': 130, 'spa': 140, 'spd': 135, 'spe': 30},
                            'abilities': {'0': 'Schooling'},
                            'heightm': 8.2,
                            'weightkg': 78.6,
                            'color': 'Blue',
                            'eggGroups': ['Water 2'],
                            'requiredAbility': 'Schooling',
                            'battleOnly': 'Wishiwashi'},
    'Mareanie': {   'num': 747,
                    'name': 'Mareanie',
                    'types': ['Poison', 'Water'],
                    'baseStats': {'hp': 50, 'atk': 53, 'def': 62, 'spa': 43, 'spd': 52, 'spe': 45},
                    'abilities': {'0': 'Merciless', '1': 'Limber', 'H': 'Regenerator'},
                    'heightm': 0.4,
                    'weightkg': 8,
                    'color': 'Blue',
                    'evos': ['Toxapex'],
                    'eggGroups': ['Water 1']},
    'Toxapex': {   'num': 748,
                   'name': 'Toxapex',
                   'types': ['Poison', 'Water'],
                   'baseStats': {'hp': 50, 'atk': 63, 'def': 152, 'spa': 53, 'spd': 142, 'spe': 35},
                   'abilities': {'0': 'Merciless', '1': 'Limber', 'H': 'Regenerator'},
                   'heightm': 0.7,
                   'weightkg': 14.5,
                   'color': 'Blue',
                   'prevo': 'Mareanie',
                   'evoLevel': 38,
                   'eggGroups': ['Water 1']},
    'Mudbray': {   'num': 749,
                   'name': 'Mudbray',
                   'types': ['Ground'],
                   'baseStats': {'hp': 70, 'atk': 100, 'def': 70, 'spa': 45, 'spd': 55, 'spe': 45},
                   'abilities': {'0': 'Own Tempo', '1': 'Stamina', 'H': 'Inner Focus'},
                   'heightm': 1,
                   'weightkg': 110,
                   'color': 'Brown',
                   'evos': ['Mudsdale'],
                   'eggGroups': ['Field']},
    'Mudsdale': {   'num': 750,
                    'name': 'Mudsdale',
                    'types': ['Ground'],
                    'baseStats': {'hp': 100, 'atk': 125, 'def': 100, 'spa': 55, 'spd': 85, 'spe': 35},
                    'abilities': {'0': 'Own Tempo', '1': 'Stamina', 'H': 'Inner Focus'},
                    'heightm': 2.5,
                    'weightkg': 920,
                    'color': 'Brown',
                    'prevo': 'Mudbray',
                    'evoLevel': 30,
                    'eggGroups': ['Field']},
    'Dewpider': {   'num': 751,
                    'name': 'Dewpider',
                    'types': ['Water', 'Bug'],
                    'baseStats': {'hp': 38, 'atk': 40, 'def': 52, 'spa': 40, 'spd': 72, 'spe': 27},
                    'abilities': {'0': 'Water Bubble', 'H': 'Water Absorb'},
                    'heightm': 0.3,
                    'weightkg': 4,
                    'color': 'Green',
                    'evos': ['Araquanid'],
                    'eggGroups': ['Water 1', 'Bug']},
    'Araquanid': {   'num': 752,
                     'name': 'Araquanid',
                     'types': ['Water', 'Bug'],
                     'baseStats': {'hp': 68, 'atk': 70, 'def': 92, 'spa': 50, 'spd': 132, 'spe': 42},
                     'abilities': {'0': 'Water Bubble', 'H': 'Water Absorb'},
                     'heightm': 1.8,
                     'weightkg': 82,
                     'color': 'Green',
                     'prevo': 'Dewpider',
                     'evoLevel': 22,
                     'eggGroups': ['Water 1', 'Bug'],
                     'otherFormes': ['Araquanid-Totem'],
                     'formeOrder': ['Araquanid', 'Araquanid-Totem']},
    'Araquanidtotem': {   'num': 752,
                          'name': 'Araquanid-Totem',
                          'baseSpecies': 'Araquanid',
                          'forme': 'Totem',
                          'types': ['Water', 'Bug'],
                          'baseStats': {'hp': 68, 'atk': 70, 'def': 92, 'spa': 50, 'spd': 132, 'spe': 42},
                          'abilities': {'0': 'Water Bubble'},
                          'heightm': 3.1,
                          'weightkg': 217.5,
                          'color': 'Green',
                          'eggGroups': ['Water 1', 'Bug']},
    'Fomantis': {   'num': 753,
                    'name': 'Fomantis',
                    'types': ['Grass'],
                    'baseStats': {'hp': 40, 'atk': 55, 'def': 35, 'spa': 50, 'spd': 35, 'spe': 35},
                    'abilities': {'0': 'Leaf Guard', 'H': 'Contrary'},
                    'heightm': 0.3,
                    'weightkg': 1.5,
                    'color': 'Pink',
                    'evos': ['Lurantis'],
                    'eggGroups': ['Grass']},
    'Lurantis': {   'num': 754,
                    'name': 'Lurantis',
                    'types': ['Grass'],
                    'baseStats': {'hp': 70, 'atk': 105, 'def': 90, 'spa': 80, 'spd': 90, 'spe': 45},
                    'abilities': {'0': 'Leaf Guard', 'H': 'Contrary'},
                    'heightm': 0.9,
                    'weightkg': 18.5,
                    'color': 'Pink',
                    'prevo': 'Fomantis',
                    'evoLevel': 34,
                    'evoCondition': 'during the day',
                    'eggGroups': ['Grass'],
                    'otherFormes': ['Lurantis-Totem'],
                    'formeOrder': ['Lurantis', 'Lurantis-Totem']},
    'Lurantistotem': {   'num': 754,
                         'name': 'Lurantis-Totem',
                         'baseSpecies': 'Lurantis',
                         'forme': 'Totem',
                         'types': ['Grass'],
                         'baseStats': {'hp': 70, 'atk': 105, 'def': 90, 'spa': 80, 'spd': 90, 'spe': 45},
                         'abilities': {'0': 'Leaf Guard'},
                         'heightm': 1.5,
                         'weightkg': 58,
                         'color': 'Pink',
                         'eggGroups': ['Grass']},
    'Morelull': {   'num': 755,
                    'name': 'Morelull',
                    'types': ['Grass', 'Fairy'],
                    'baseStats': {'hp': 40, 'atk': 35, 'def': 55, 'spa': 65, 'spd': 75, 'spe': 15},
                    'abilities': {'0': 'Illuminate', '1': 'Effect Spore', 'H': 'Rain Dish'},
                    'heightm': 0.2,
                    'weightkg': 1.5,
                    'color': 'Purple',
                    'evos': ['Shiinotic'],
                    'eggGroups': ['Grass']},
    'Shiinotic': {   'num': 756,
                     'name': 'Shiinotic',
                     'types': ['Grass', 'Fairy'],
                     'baseStats': {'hp': 60, 'atk': 45, 'def': 80, 'spa': 90, 'spd': 100, 'spe': 30},
                     'abilities': {'0': 'Illuminate', '1': 'Effect Spore', 'H': 'Rain Dish'},
                     'heightm': 1,
                     'weightkg': 11.5,
                     'color': 'Purple',
                     'prevo': 'Morelull',
                     'evoLevel': 24,
                     'eggGroups': ['Grass']},
    'Salandit': {   'num': 757,
                    'name': 'Salandit',
                    'types': ['Poison', 'Fire'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 48, 'atk': 44, 'def': 40, 'spa': 71, 'spd': 40, 'spe': 77},
                    'abilities': {'0': 'Corrosion', 'H': 'Oblivious'},
                    'heightm': 0.6,
                    'weightkg': 4.8,
                    'color': 'Black',
                    'evos': ['Salazzle'],
                    'eggGroups': ['Monster', 'Dragon']},
    'Salazzle': {   'num': 758,
                    'name': 'Salazzle',
                    'types': ['Poison', 'Fire'],
                    'gender': 'F',
                    'baseStats': {'hp': 68, 'atk': 64, 'def': 60, 'spa': 111, 'spd': 60, 'spe': 117},
                    'abilities': {'0': 'Corrosion', 'H': 'Oblivious'},
                    'heightm': 1.2,
                    'weightkg': 22.2,
                    'color': 'Black',
                    'prevo': 'Salandit',
                    'evoLevel': 33,
                    'eggGroups': ['Monster', 'Dragon'],
                    'otherFormes': ['Salazzle-Totem'],
                    'formeOrder': ['Salazzle', 'Salazzle-Totem']},
    'Salazzletotem': {   'num': 758,
                         'name': 'Salazzle-Totem',
                         'baseSpecies': 'Salazzle',
                         'forme': 'Totem',
                         'types': ['Poison', 'Fire'],
                         'gender': 'F',
                         'baseStats': {'hp': 68, 'atk': 64, 'def': 60, 'spa': 111, 'spd': 60, 'spe': 117},
                         'abilities': {'0': 'Corrosion'},
                         'heightm': 2.1,
                         'weightkg': 81,
                         'color': 'Black',
                         'eggGroups': ['Monster', 'Dragon']},
    'Stufful': {   'num': 759,
                   'name': 'Stufful',
                   'types': ['Normal', 'Fighting'],
                   'baseStats': {'hp': 70, 'atk': 75, 'def': 50, 'spa': 45, 'spd': 50, 'spe': 50},
                   'abilities': {'0': 'Fluffy', '1': 'Klutz', 'H': 'Cute Charm'},
                   'heightm': 0.5,
                   'weightkg': 6.8,
                   'color': 'Pink',
                   'evos': ['Bewear'],
                   'eggGroups': ['Field']},
    'Bewear': {   'num': 760,
                  'name': 'Bewear',
                  'types': ['Normal', 'Fighting'],
                  'baseStats': {'hp': 120, 'atk': 125, 'def': 80, 'spa': 55, 'spd': 60, 'spe': 60},
                  'abilities': {'0': 'Fluffy', '1': 'Klutz', 'H': 'Unnerve'},
                  'heightm': 2.1,
                  'weightkg': 135,
                  'color': 'Pink',
                  'prevo': 'Stufful',
                  'evoLevel': 27,
                  'eggGroups': ['Field']},
    'Bounsweet': {   'num': 761,
                     'name': 'Bounsweet',
                     'types': ['Grass'],
                     'gender': 'F',
                     'baseStats': {'hp': 42, 'atk': 30, 'def': 38, 'spa': 30, 'spd': 38, 'spe': 32},
                     'abilities': {'0': 'Leaf Guard', '1': 'Oblivious', 'H': 'Sweet Veil'},
                     'heightm': 0.3,
                     'weightkg': 3.2,
                     'color': 'Purple',
                     'evos': ['Steenee'],
                     'eggGroups': ['Grass']},
    'Steenee': {   'num': 762,
                   'name': 'Steenee',
                   'types': ['Grass'],
                   'gender': 'F',
                   'baseStats': {'hp': 52, 'atk': 40, 'def': 48, 'spa': 40, 'spd': 48, 'spe': 62},
                   'abilities': {'0': 'Leaf Guard', '1': 'Oblivious', 'H': 'Sweet Veil'},
                   'heightm': 0.7,
                   'weightkg': 8.2,
                   'color': 'Purple',
                   'prevo': 'Bounsweet',
                   'evoLevel': 18,
                   'evos': ['Tsareena'],
                   'eggGroups': ['Grass']},
    'Tsareena': {   'num': 763,
                    'name': 'Tsareena',
                    'types': ['Grass'],
                    'gender': 'F',
                    'baseStats': {'hp': 72, 'atk': 120, 'def': 98, 'spa': 50, 'spd': 98, 'spe': 72},
                    'abilities': {'0': 'Leaf Guard', '1': 'Queenly Majesty', 'H': 'Sweet Veil'},
                    'heightm': 1.2,
                    'weightkg': 21.4,
                    'color': 'Purple',
                    'prevo': 'Steenee',
                    'evoType': 'levelMove',
                    'evoMove': 'Stomp',
                    'eggGroups': ['Grass']},
    'Comfey': {   'num': 764,
                  'name': 'Comfey',
                  'types': ['Fairy'],
                  'genderRatio': {'M': 0.25, 'F': 0.75},
                  'baseStats': {'hp': 51, 'atk': 52, 'def': 90, 'spa': 82, 'spd': 110, 'spe': 100},
                  'abilities': {'0': 'Flower Veil', '1': 'Triage', 'H': 'Natural Cure'},
                  'heightm': 0.1,
                  'weightkg': 0.3,
                  'color': 'Green',
                  'eggGroups': ['Grass']},
    'Oranguru': {   'num': 765,
                    'name': 'Oranguru',
                    'types': ['Normal', 'Psychic'],
                    'baseStats': {'hp': 90, 'atk': 60, 'def': 80, 'spa': 90, 'spd': 110, 'spe': 60},
                    'abilities': {'0': 'Inner Focus', '1': 'Telepathy', 'H': 'Symbiosis'},
                    'heightm': 1.5,
                    'weightkg': 76,
                    'color': 'White',
                    'eggGroups': ['Field']},
    'Passimian': {   'num': 766,
                     'name': 'Passimian',
                     'types': ['Fighting'],
                     'baseStats': {'hp': 100, 'atk': 120, 'def': 90, 'spa': 40, 'spd': 60, 'spe': 80},
                     'abilities': {'0': 'Receiver', 'H': 'Defiant'},
                     'heightm': 2,
                     'weightkg': 82.8,
                     'color': 'White',
                     'eggGroups': ['Field']},
    'Wimpod': {   'num': 767,
                  'name': 'Wimpod',
                  'types': ['Bug', 'Water'],
                  'baseStats': {'hp': 25, 'atk': 35, 'def': 40, 'spa': 20, 'spd': 30, 'spe': 80},
                  'abilities': {'0': 'Wimp Out'},
                  'heightm': 0.5,
                  'weightkg': 12,
                  'color': 'Gray',
                  'evos': ['Golisopod'],
                  'eggGroups': ['Bug', 'Water 3']},
    'Golisopod': {   'num': 768,
                     'name': 'Golisopod',
                     'types': ['Bug', 'Water'],
                     'baseStats': {'hp': 75, 'atk': 125, 'def': 140, 'spa': 60, 'spd': 90, 'spe': 40},
                     'abilities': {'0': 'Emergency Exit'},
                     'heightm': 2,
                     'weightkg': 108,
                     'color': 'Gray',
                     'prevo': 'Wimpod',
                     'evoLevel': 30,
                     'eggGroups': ['Bug', 'Water 3']},
    'Sandygast': {   'num': 769,
                     'name': 'Sandygast',
                     'types': ['Ghost', 'Ground'],
                     'baseStats': {'hp': 55, 'atk': 55, 'def': 80, 'spa': 70, 'spd': 45, 'spe': 15},
                     'abilities': {'0': 'Water Compaction', 'H': 'Sand Veil'},
                     'heightm': 0.5,
                     'weightkg': 70,
                     'color': 'Brown',
                     'evos': ['Palossand'],
                     'eggGroups': ['Amorphous']},
    'Palossand': {   'num': 770,
                     'name': 'Palossand',
                     'types': ['Ghost', 'Ground'],
                     'baseStats': {'hp': 85, 'atk': 75, 'def': 110, 'spa': 100, 'spd': 75, 'spe': 35},
                     'abilities': {'0': 'Water Compaction', 'H': 'Sand Veil'},
                     'heightm': 1.3,
                     'weightkg': 250,
                     'color': 'Brown',
                     'prevo': 'Sandygast',
                     'evoLevel': 42,
                     'eggGroups': ['Amorphous']},
    'Pyukumuku': {   'num': 771,
                     'name': 'Pyukumuku',
                     'types': ['Water'],
                     'baseStats': {'hp': 55, 'atk': 60, 'def': 130, 'spa': 30, 'spd': 130, 'spe': 5},
                     'abilities': {'0': 'Innards Out', 'H': 'Unaware'},
                     'heightm': 0.3,
                     'weightkg': 1.2,
                     'color': 'Black',
                     'eggGroups': ['Water 1']},
    'Typenull': {   'num': 772,
                    'name': 'Type: Null',
                    'types': ['Normal'],
                    'gender': 'N',
                    'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 59},
                    'abilities': {'0': 'Battle Armor'},
                    'heightm': 1.9,
                    'weightkg': 120.5,
                    'color': 'Gray',
                    'tags': ['Sub-Legendary'],
                    'evos': ['Silvally'],
                    'eggGroups': ['Undiscovered']},
    'Silvally': {   'num': 773,
                    'name': 'Silvally',
                    'types': ['Normal'],
                    'gender': 'N',
                    'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                    'abilities': {'0': 'RKS System'},
                    'heightm': 2.3,
                    'weightkg': 100.5,
                    'color': 'Gray',
                    'tags': ['Sub-Legendary'],
                    'prevo': 'Type: Null',
                    'evoType': 'levelFriendship',
                    'eggGroups': ['Undiscovered'],
                    'otherFormes': [   'Silvally-Bug',
                                       'Silvally-Dark',
                                       'Silvally-Dragon',
                                       'Silvally-Electric',
                                       'Silvally-Fairy',
                                       'Silvally-Fighting',
                                       'Silvally-Fire',
                                       'Silvally-Flying',
                                       'Silvally-Ghost',
                                       'Silvally-Grass',
                                       'Silvally-Ground',
                                       'Silvally-Ice',
                                       'Silvally-Poison',
                                       'Silvally-Psychic',
                                       'Silvally-Rock',
                                       'Silvally-Steel',
                                       'Silvally-Water'],
                    'formeOrder': [   'Silvally',
                                      'Silvally-Fighting',
                                      'Silvally-Flying',
                                      'Silvally-Poison',
                                      'Silvally-Ground',
                                      'Silvally-Rock',
                                      'Silvally-Bug',
                                      'Silvally-Ghost',
                                      'Silvally-Steel',
                                      'Silvally-Fire',
                                      'Silvally-Water',
                                      'Silvally-Grass',
                                      'Silvally-Electric',
                                      'Silvally-Psychic',
                                      'Silvally-Ice',
                                      'Silvally-Dragon',
                                      'Silvally-Dark',
                                      'Silvally-Fairy']},
    'Silvallybug': {   'num': 773,
                       'name': 'Silvally-Bug',
                       'baseSpecies': 'Silvally',
                       'forme': 'Bug',
                       'types': ['Bug'],
                       'gender': 'N',
                       'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                       'abilities': {'0': 'RKS System'},
                       'heightm': 2.3,
                       'weightkg': 100.5,
                       'color': 'Gray',
                       'eggGroups': ['Undiscovered'],
                       'requiredItem': 'Bug Memory',
                       'changesFrom': 'Silvally'},
    'Silvallydark': {   'num': 773,
                        'name': 'Silvally-Dark',
                        'baseSpecies': 'Silvally',
                        'forme': 'Dark',
                        'types': ['Dark'],
                        'gender': 'N',
                        'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                        'abilities': {'0': 'RKS System'},
                        'heightm': 2.3,
                        'weightkg': 100.5,
                        'color': 'Gray',
                        'eggGroups': ['Undiscovered'],
                        'requiredItem': 'Dark Memory',
                        'changesFrom': 'Silvally'},
    'Silvallydragon': {   'num': 773,
                          'name': 'Silvally-Dragon',
                          'baseSpecies': 'Silvally',
                          'forme': 'Dragon',
                          'types': ['Dragon'],
                          'gender': 'N',
                          'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                          'abilities': {'0': 'RKS System'},
                          'heightm': 2.3,
                          'weightkg': 100.5,
                          'color': 'Gray',
                          'eggGroups': ['Undiscovered'],
                          'requiredItem': 'Dragon Memory',
                          'changesFrom': 'Silvally'},
    'Silvallyelectric': {   'num': 773,
                            'name': 'Silvally-Electric',
                            'baseSpecies': 'Silvally',
                            'forme': 'Electric',
                            'types': ['Electric'],
                            'gender': 'N',
                            'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                            'abilities': {'0': 'RKS System'},
                            'heightm': 2.3,
                            'weightkg': 100.5,
                            'color': 'Gray',
                            'eggGroups': ['Undiscovered'],
                            'requiredItem': 'Electric Memory',
                            'changesFrom': 'Silvally'},
    'Silvallyfairy': {   'num': 773,
                         'name': 'Silvally-Fairy',
                         'baseSpecies': 'Silvally',
                         'forme': 'Fairy',
                         'types': ['Fairy'],
                         'gender': 'N',
                         'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                         'abilities': {'0': 'RKS System'},
                         'heightm': 2.3,
                         'weightkg': 100.5,
                         'color': 'Gray',
                         'eggGroups': ['Undiscovered'],
                         'requiredItem': 'Fairy Memory',
                         'changesFrom': 'Silvally'},
    'Silvallyfighting': {   'num': 773,
                            'name': 'Silvally-Fighting',
                            'baseSpecies': 'Silvally',
                            'forme': 'Fighting',
                            'types': ['Fighting'],
                            'gender': 'N',
                            'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                            'abilities': {'0': 'RKS System'},
                            'heightm': 2.3,
                            'weightkg': 100.5,
                            'color': 'Gray',
                            'eggGroups': ['Undiscovered'],
                            'requiredItem': 'Fighting Memory',
                            'changesFrom': 'Silvally'},
    'Silvallyfire': {   'num': 773,
                        'name': 'Silvally-Fire',
                        'baseSpecies': 'Silvally',
                        'forme': 'Fire',
                        'types': ['Fire'],
                        'gender': 'N',
                        'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                        'abilities': {'0': 'RKS System'},
                        'heightm': 2.3,
                        'weightkg': 100.5,
                        'color': 'Gray',
                        'eggGroups': ['Undiscovered'],
                        'requiredItem': 'Fire Memory',
                        'changesFrom': 'Silvally'},
    'Silvallyflying': {   'num': 773,
                          'name': 'Silvally-Flying',
                          'baseSpecies': 'Silvally',
                          'forme': 'Flying',
                          'types': ['Flying'],
                          'gender': 'N',
                          'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                          'abilities': {'0': 'RKS System'},
                          'heightm': 2.3,
                          'weightkg': 100.5,
                          'color': 'Gray',
                          'eggGroups': ['Undiscovered'],
                          'requiredItem': 'Flying Memory',
                          'changesFrom': 'Silvally'},
    'Silvallyghost': {   'num': 773,
                         'name': 'Silvally-Ghost',
                         'baseSpecies': 'Silvally',
                         'forme': 'Ghost',
                         'types': ['Ghost'],
                         'gender': 'N',
                         'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                         'abilities': {'0': 'RKS System'},
                         'heightm': 2.3,
                         'weightkg': 100.5,
                         'color': 'Gray',
                         'eggGroups': ['Undiscovered'],
                         'requiredItem': 'Ghost Memory',
                         'changesFrom': 'Silvally'},
    'Silvallygrass': {   'num': 773,
                         'name': 'Silvally-Grass',
                         'baseSpecies': 'Silvally',
                         'forme': 'Grass',
                         'types': ['Grass'],
                         'gender': 'N',
                         'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                         'abilities': {'0': 'RKS System'},
                         'heightm': 2.3,
                         'weightkg': 100.5,
                         'color': 'Gray',
                         'eggGroups': ['Undiscovered'],
                         'requiredItem': 'Grass Memory',
                         'changesFrom': 'Silvally'},
    'Silvallyground': {   'num': 773,
                          'name': 'Silvally-Ground',
                          'baseSpecies': 'Silvally',
                          'forme': 'Ground',
                          'types': ['Ground'],
                          'gender': 'N',
                          'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                          'abilities': {'0': 'RKS System'},
                          'heightm': 2.3,
                          'weightkg': 100.5,
                          'color': 'Gray',
                          'eggGroups': ['Undiscovered'],
                          'requiredItem': 'Ground Memory',
                          'changesFrom': 'Silvally'},
    'Silvallyice': {   'num': 773,
                       'name': 'Silvally-Ice',
                       'baseSpecies': 'Silvally',
                       'forme': 'Ice',
                       'types': ['Ice'],
                       'gender': 'N',
                       'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                       'abilities': {'0': 'RKS System'},
                       'heightm': 2.3,
                       'weightkg': 100.5,
                       'color': 'Gray',
                       'eggGroups': ['Undiscovered'],
                       'requiredItem': 'Ice Memory',
                       'changesFrom': 'Silvally'},
    'Silvallypoison': {   'num': 773,
                          'name': 'Silvally-Poison',
                          'baseSpecies': 'Silvally',
                          'forme': 'Poison',
                          'types': ['Poison'],
                          'gender': 'N',
                          'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                          'abilities': {'0': 'RKS System'},
                          'heightm': 2.3,
                          'weightkg': 100.5,
                          'color': 'Gray',
                          'eggGroups': ['Undiscovered'],
                          'requiredItem': 'Poison Memory',
                          'changesFrom': 'Silvally'},
    'Silvallypsychic': {   'num': 773,
                           'name': 'Silvally-Psychic',
                           'baseSpecies': 'Silvally',
                           'forme': 'Psychic',
                           'types': ['Psychic'],
                           'gender': 'N',
                           'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                           'abilities': {'0': 'RKS System'},
                           'heightm': 2.3,
                           'weightkg': 100.5,
                           'color': 'Gray',
                           'eggGroups': ['Undiscovered'],
                           'requiredItem': 'Psychic Memory',
                           'changesFrom': 'Silvally'},
    'Silvallyrock': {   'num': 773,
                        'name': 'Silvally-Rock',
                        'baseSpecies': 'Silvally',
                        'forme': 'Rock',
                        'types': ['Rock'],
                        'gender': 'N',
                        'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                        'abilities': {'0': 'RKS System'},
                        'heightm': 2.3,
                        'weightkg': 100.5,
                        'color': 'Gray',
                        'eggGroups': ['Undiscovered'],
                        'requiredItem': 'Rock Memory',
                        'changesFrom': 'Silvally'},
    'Silvallysteel': {   'num': 773,
                         'name': 'Silvally-Steel',
                         'baseSpecies': 'Silvally',
                         'forme': 'Steel',
                         'types': ['Steel'],
                         'gender': 'N',
                         'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                         'abilities': {'0': 'RKS System'},
                         'heightm': 2.3,
                         'weightkg': 100.5,
                         'color': 'Gray',
                         'eggGroups': ['Undiscovered'],
                         'requiredItem': 'Steel Memory',
                         'changesFrom': 'Silvally'},
    'Silvallywater': {   'num': 773,
                         'name': 'Silvally-Water',
                         'baseSpecies': 'Silvally',
                         'forme': 'Water',
                         'types': ['Water'],
                         'gender': 'N',
                         'baseStats': {'hp': 95, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 95},
                         'abilities': {'0': 'RKS System'},
                         'heightm': 2.3,
                         'weightkg': 100.5,
                         'color': 'Gray',
                         'eggGroups': ['Undiscovered'],
                         'requiredItem': 'Water Memory',
                         'changesFrom': 'Silvally'},
    'Minior': {   'num': 774,
                  'name': 'Minior',
                  'baseForme': 'Red',
                  'types': ['Rock', 'Flying'],
                  'gender': 'N',
                  'baseStats': {'hp': 60, 'atk': 100, 'def': 60, 'spa': 100, 'spd': 60, 'spe': 120},
                  'abilities': {'0': 'Shields Down'},
                  'heightm': 0.3,
                  'weightkg': 0.3,
                  'color': 'Red',
                  'eggGroups': ['Mineral'],
                  'otherFormes': ['Minior-Meteor'],
                  'cosmeticFormes': [   'Minior-Orange',
                                        'Minior-Yellow',
                                        'Minior-Green',
                                        'Minior-Blue',
                                        'Minior-Indigo',
                                        'Minior-Violet'],
                  'formeOrder': [   'Minior-Meteor',
                                    'Minior-Meteor',
                                    'Minior-Meteor',
                                    'Minior-Meteor',
                                    'Minior-Meteor',
                                    'Minior-Meteor',
                                    'Minior-Meteor',
                                    'Minior',
                                    'Minior-Orange',
                                    'Minior-Yellow',
                                    'Minior-Green',
                                    'Minior-Blue',
                                    'Minior-Indigo',
                                    'Minior-Violet']},
    'Miniormeteor': {   'num': 774,
                        'name': 'Minior-Meteor',
                        'baseSpecies': 'Minior',
                        'forme': 'Meteor',
                        'types': ['Rock', 'Flying'],
                        'gender': 'N',
                        'baseStats': {'hp': 60, 'atk': 60, 'def': 100, 'spa': 60, 'spd': 100, 'spe': 60},
                        'abilities': {'0': 'Shields Down'},
                        'heightm': 0.3,
                        'weightkg': 40,
                        'color': 'Brown',
                        'eggGroups': ['Mineral'],
                        'requiredAbility': 'Shields Down',
                        'battleOnly': 'Minior'},
    'Komala': {   'num': 775,
                  'name': 'Komala',
                  'types': ['Normal'],
                  'baseStats': {'hp': 65, 'atk': 115, 'def': 65, 'spa': 75, 'spd': 95, 'spe': 65},
                  'abilities': {'0': 'Comatose'},
                  'heightm': 0.4,
                  'weightkg': 19.9,
                  'color': 'Blue',
                  'eggGroups': ['Field']},
    'Turtonator': {   'num': 776,
                      'name': 'Turtonator',
                      'types': ['Fire', 'Dragon'],
                      'baseStats': {'hp': 60, 'atk': 78, 'def': 135, 'spa': 91, 'spd': 85, 'spe': 36},
                      'abilities': {'0': 'Shell Armor'},
                      'heightm': 2,
                      'weightkg': 212,
                      'color': 'Red',
                      'eggGroups': ['Monster', 'Dragon']},
    'Togedemaru': {   'num': 777,
                      'name': 'Togedemaru',
                      'types': ['Electric', 'Steel'],
                      'baseStats': {'hp': 65, 'atk': 98, 'def': 63, 'spa': 40, 'spd': 73, 'spe': 96},
                      'abilities': {'0': 'Iron Barbs', '1': 'Lightning Rod', 'H': 'Sturdy'},
                      'heightm': 0.3,
                      'weightkg': 3.3,
                      'color': 'Gray',
                      'eggGroups': ['Field', 'Fairy'],
                      'otherFormes': ['Togedemaru-Totem'],
                      'formeOrder': ['Togedemaru', 'Togedemaru-Totem']},
    'Togedemarutotem': {   'num': 777,
                           'name': 'Togedemaru-Totem',
                           'baseSpecies': 'Togedemaru',
                           'forme': 'Totem',
                           'types': ['Electric', 'Steel'],
                           'baseStats': {'hp': 65, 'atk': 98, 'def': 63, 'spa': 40, 'spd': 73, 'spe': 96},
                           'abilities': {'0': 'Sturdy'},
                           'heightm': 0.6,
                           'weightkg': 13,
                           'color': 'Gray',
                           'eggGroups': ['Field', 'Fairy']},
    'Mimikyu': {   'num': 778,
                   'name': 'Mimikyu',
                   'baseForme': 'Disguised',
                   'types': ['Ghost', 'Fairy'],
                   'baseStats': {'hp': 55, 'atk': 90, 'def': 80, 'spa': 50, 'spd': 105, 'spe': 96},
                   'abilities': {'0': 'Disguise'},
                   'heightm': 0.2,
                   'weightkg': 0.7,
                   'color': 'Yellow',
                   'eggGroups': ['Amorphous'],
                   'otherFormes': ['Mimikyu-Busted', 'Mimikyu-Totem', 'Mimikyu-Busted-Totem'],
                   'formeOrder': ['Mimikyu', 'Mimikyu-Busted', 'Mimikyu-Totem', 'Mimikyu-Busted-Totem']},
    'Mimikyubusted': {   'num': 778,
                         'name': 'Mimikyu-Busted',
                         'baseSpecies': 'Mimikyu',
                         'forme': 'Busted',
                         'types': ['Ghost', 'Fairy'],
                         'baseStats': {'hp': 55, 'atk': 90, 'def': 80, 'spa': 50, 'spd': 105, 'spe': 96},
                         'abilities': {'0': 'Disguise'},
                         'heightm': 0.2,
                         'weightkg': 0.7,
                         'color': 'Yellow',
                         'eggGroups': ['Amorphous'],
                         'requiredAbility': 'Disguise',
                         'battleOnly': 'Mimikyu'},
    'Mimikyutotem': {   'num': 778,
                        'name': 'Mimikyu-Totem',
                        'baseSpecies': 'Mimikyu',
                        'forme': 'Totem',
                        'types': ['Ghost', 'Fairy'],
                        'baseStats': {'hp': 55, 'atk': 90, 'def': 80, 'spa': 50, 'spd': 105, 'spe': 96},
                        'abilities': {'0': 'Disguise'},
                        'heightm': 0.4,
                        'weightkg': 2.8,
                        'color': 'Yellow',
                        'eggGroups': ['Amorphous']},
    'Mimikyubustedtotem': {   'num': 778,
                              'name': 'Mimikyu-Busted-Totem',
                              'baseSpecies': 'Mimikyu',
                              'forme': 'Busted-Totem',
                              'types': ['Ghost', 'Fairy'],
                              'baseStats': {'hp': 55, 'atk': 90, 'def': 80, 'spa': 50, 'spd': 105, 'spe': 96},
                              'abilities': {'0': 'Disguise'},
                              'heightm': 0.4,
                              'weightkg': 2.8,
                              'color': 'Yellow',
                              'eggGroups': ['Amorphous'],
                              'requiredAbility': 'Disguise',
                              'battleOnly': 'Mimikyu-Totem'},
    'Bruxish': {   'num': 779,
                   'name': 'Bruxish',
                   'types': ['Water', 'Psychic'],
                   'baseStats': {'hp': 68, 'atk': 105, 'def': 70, 'spa': 70, 'spd': 70, 'spe': 92},
                   'abilities': {'0': 'Dazzling', '1': 'Strong Jaw', 'H': 'Wonder Skin'},
                   'heightm': 0.9,
                   'weightkg': 19,
                   'color': 'Pink',
                   'eggGroups': ['Water 2']},
    'Drampa': {   'num': 780,
                  'name': 'Drampa',
                  'types': ['Normal', 'Dragon'],
                  'baseStats': {'hp': 78, 'atk': 60, 'def': 85, 'spa': 135, 'spd': 91, 'spe': 36},
                  'abilities': {'0': 'Berserk', '1': 'Sap Sipper', 'H': 'Cloud Nine'},
                  'heightm': 3,
                  'weightkg': 185,
                  'color': 'White',
                  'eggGroups': ['Monster', 'Dragon']},
    'Dhelmise': {   'num': 781,
                    'name': 'Dhelmise',
                    'types': ['Ghost', 'Grass'],
                    'gender': 'N',
                    'baseStats': {'hp': 70, 'atk': 131, 'def': 100, 'spa': 86, 'spd': 90, 'spe': 40},
                    'abilities': {'0': 'Steelworker'},
                    'heightm': 3.9,
                    'weightkg': 210,
                    'color': 'Green',
                    'eggGroups': ['Mineral']},
    'Jangmoo': {   'num': 782,
                   'name': 'Jangmo-o',
                   'types': ['Dragon'],
                   'baseStats': {'hp': 45, 'atk': 55, 'def': 65, 'spa': 45, 'spd': 45, 'spe': 45},
                   'abilities': {'0': 'Bulletproof', '1': 'Soundproof', 'H': 'Overcoat'},
                   'heightm': 0.6,
                   'weightkg': 29.7,
                   'color': 'Gray',
                   'evos': ['Hakamo-o'],
                   'eggGroups': ['Dragon']},
    'Hakamoo': {   'num': 783,
                   'name': 'Hakamo-o',
                   'types': ['Dragon', 'Fighting'],
                   'baseStats': {'hp': 55, 'atk': 75, 'def': 90, 'spa': 65, 'spd': 70, 'spe': 65},
                   'abilities': {'0': 'Bulletproof', '1': 'Soundproof', 'H': 'Overcoat'},
                   'heightm': 1.2,
                   'weightkg': 47,
                   'color': 'Gray',
                   'prevo': 'Jangmo-o',
                   'evoLevel': 35,
                   'evos': ['Kommo-o'],
                   'eggGroups': ['Dragon']},
    'Kommoo': {   'num': 784,
                  'name': 'Kommo-o',
                  'types': ['Dragon', 'Fighting'],
                  'baseStats': {'hp': 75, 'atk': 110, 'def': 125, 'spa': 100, 'spd': 105, 'spe': 85},
                  'abilities': {'0': 'Bulletproof', '1': 'Soundproof', 'H': 'Overcoat'},
                  'heightm': 1.6,
                  'weightkg': 78.2,
                  'color': 'Gray',
                  'prevo': 'Hakamo-o',
                  'evoLevel': 45,
                  'eggGroups': ['Dragon'],
                  'otherFormes': ['Kommo-o-Totem'],
                  'formeOrder': ['Kommo-o', 'Kommo-o-Totem']},
    'Kommoototem': {   'num': 784,
                       'name': 'Kommo-o-Totem',
                       'baseSpecies': 'Kommo-o',
                       'forme': 'Totem',
                       'types': ['Dragon', 'Fighting'],
                       'baseStats': {'hp': 75, 'atk': 110, 'def': 125, 'spa': 100, 'spd': 105, 'spe': 85},
                       'abilities': {'0': 'Overcoat'},
                       'heightm': 2.4,
                       'weightkg': 207.5,
                       'color': 'Gray',
                       'eggGroups': ['Dragon']},
    'Tapukoko': {   'num': 785,
                    'name': 'Tapu Koko',
                    'types': ['Electric', 'Fairy'],
                    'gender': 'N',
                    'baseStats': {'hp': 70, 'atk': 115, 'def': 85, 'spa': 95, 'spd': 75, 'spe': 130},
                    'abilities': {'0': 'Electric Surge', 'H': 'Telepathy'},
                    'heightm': 1.8,
                    'weightkg': 20.5,
                    'color': 'Yellow',
                    'tags': ['Sub-Legendary'],
                    'eggGroups': ['Undiscovered']},
    'Tapulele': {   'num': 786,
                    'name': 'Tapu Lele',
                    'types': ['Psychic', 'Fairy'],
                    'gender': 'N',
                    'baseStats': {'hp': 70, 'atk': 85, 'def': 75, 'spa': 130, 'spd': 115, 'spe': 95},
                    'abilities': {'0': 'Psychic Surge', 'H': 'Telepathy'},
                    'heightm': 1.2,
                    'weightkg': 18.6,
                    'color': 'Pink',
                    'tags': ['Sub-Legendary'],
                    'eggGroups': ['Undiscovered']},
    'Tapubulu': {   'num': 787,
                    'name': 'Tapu Bulu',
                    'types': ['Grass', 'Fairy'],
                    'gender': 'N',
                    'baseStats': {'hp': 70, 'atk': 130, 'def': 115, 'spa': 85, 'spd': 95, 'spe': 75},
                    'abilities': {'0': 'Grassy Surge', 'H': 'Telepathy'},
                    'heightm': 1.9,
                    'weightkg': 45.5,
                    'color': 'Red',
                    'tags': ['Sub-Legendary'],
                    'eggGroups': ['Undiscovered']},
    'Tapufini': {   'num': 788,
                    'name': 'Tapu Fini',
                    'types': ['Water', 'Fairy'],
                    'gender': 'N',
                    'baseStats': {'hp': 70, 'atk': 75, 'def': 115, 'spa': 95, 'spd': 130, 'spe': 85},
                    'abilities': {'0': 'Misty Surge', 'H': 'Telepathy'},
                    'heightm': 1.3,
                    'weightkg': 21.2,
                    'color': 'Purple',
                    'tags': ['Sub-Legendary'],
                    'eggGroups': ['Undiscovered']},
    'Cosmog': {   'num': 789,
                  'name': 'Cosmog',
                  'types': ['Psychic'],
                  'gender': 'N',
                  'baseStats': {'hp': 43, 'atk': 29, 'def': 31, 'spa': 29, 'spd': 31, 'spe': 37},
                  'abilities': {'0': 'Unaware'},
                  'heightm': 0.2,
                  'weightkg': 0.1,
                  'color': 'Blue',
                  'evos': ['Cosmoem'],
                  'tags': ['Restricted Legendary'],
                  'eggGroups': ['Undiscovered']},
    'Cosmoem': {   'num': 790,
                   'name': 'Cosmoem',
                   'types': ['Psychic'],
                   'gender': 'N',
                   'baseStats': {'hp': 43, 'atk': 29, 'def': 131, 'spa': 29, 'spd': 131, 'spe': 37},
                   'abilities': {'0': 'Sturdy'},
                   'heightm': 0.1,
                   'weightkg': 999.9,
                   'color': 'Blue',
                   'tags': ['Restricted Legendary'],
                   'prevo': 'Cosmog',
                   'evoLevel': 43,
                   'evos': ['Solgaleo', 'Lunala'],
                   'eggGroups': ['Undiscovered']},
    'Solgaleo': {   'num': 791,
                    'name': 'Solgaleo',
                    'types': ['Psychic', 'Steel'],
                    'gender': 'N',
                    'baseStats': {'hp': 137, 'atk': 137, 'def': 107, 'spa': 113, 'spd': 89, 'spe': 97},
                    'abilities': {'0': 'Full Metal Body'},
                    'heightm': 3.4,
                    'weightkg': 230,
                    'color': 'White',
                    'tags': ['Restricted Legendary'],
                    'prevo': 'Cosmoem',
                    'evoLevel': 53,
                    'eggGroups': ['Undiscovered']},
    'Lunala': {   'num': 792,
                  'name': 'Lunala',
                  'types': ['Psychic', 'Ghost'],
                  'gender': 'N',
                  'baseStats': {'hp': 137, 'atk': 113, 'def': 89, 'spa': 137, 'spd': 107, 'spe': 97},
                  'abilities': {'0': 'Shadow Shield'},
                  'heightm': 4,
                  'weightkg': 120,
                  'color': 'Purple',
                  'tags': ['Restricted Legendary'],
                  'prevo': 'Cosmoem',
                  'evoLevel': 53,
                  'eggGroups': ['Undiscovered']},
    'Nihilego': {   'num': 793,
                    'name': 'Nihilego',
                    'types': ['Rock', 'Poison'],
                    'gender': 'N',
                    'baseStats': {'hp': 109, 'atk': 53, 'def': 47, 'spa': 127, 'spd': 131, 'spe': 103},
                    'abilities': {'0': 'Beast Boost'},
                    'heightm': 1.2,
                    'weightkg': 55.5,
                    'color': 'White',
                    'tags': ['Ultra Beast'],
                    'eggGroups': ['Undiscovered']},
    'Buzzwole': {   'num': 794,
                    'name': 'Buzzwole',
                    'types': ['Bug', 'Fighting'],
                    'gender': 'N',
                    'baseStats': {'hp': 107, 'atk': 139, 'def': 139, 'spa': 53, 'spd': 53, 'spe': 79},
                    'abilities': {'0': 'Beast Boost'},
                    'heightm': 2.4,
                    'weightkg': 333.6,
                    'color': 'Red',
                    'tags': ['Ultra Beast'],
                    'eggGroups': ['Undiscovered']},
    'Pheromosa': {   'num': 795,
                     'name': 'Pheromosa',
                     'types': ['Bug', 'Fighting'],
                     'gender': 'N',
                     'baseStats': {'hp': 71, 'atk': 137, 'def': 37, 'spa': 137, 'spd': 37, 'spe': 151},
                     'abilities': {'0': 'Beast Boost'},
                     'heightm': 1.8,
                     'weightkg': 25,
                     'color': 'White',
                     'tags': ['Ultra Beast'],
                     'eggGroups': ['Undiscovered']},
    'Xurkitree': {   'num': 796,
                     'name': 'Xurkitree',
                     'types': ['Electric'],
                     'gender': 'N',
                     'baseStats': {'hp': 83, 'atk': 89, 'def': 71, 'spa': 173, 'spd': 71, 'spe': 83},
                     'abilities': {'0': 'Beast Boost'},
                     'heightm': 3.8,
                     'weightkg': 100,
                     'color': 'Black',
                     'tags': ['Ultra Beast'],
                     'eggGroups': ['Undiscovered']},
    'Celesteela': {   'num': 797,
                      'name': 'Celesteela',
                      'types': ['Steel', 'Flying'],
                      'gender': 'N',
                      'baseStats': {'hp': 97, 'atk': 101, 'def': 103, 'spa': 107, 'spd': 101, 'spe': 61},
                      'abilities': {'0': 'Beast Boost'},
                      'heightm': 9.2,
                      'weightkg': 999.9,
                      'color': 'Green',
                      'tags': ['Ultra Beast'],
                      'eggGroups': ['Undiscovered']},
    'Kartana': {   'num': 798,
                   'name': 'Kartana',
                   'types': ['Grass', 'Steel'],
                   'gender': 'N',
                   'baseStats': {'hp': 59, 'atk': 181, 'def': 131, 'spa': 59, 'spd': 31, 'spe': 109},
                   'abilities': {'0': 'Beast Boost'},
                   'heightm': 0.3,
                   'weightkg': 0.1,
                   'color': 'White',
                   'tags': ['Ultra Beast'],
                   'eggGroups': ['Undiscovered']},
    'Guzzlord': {   'num': 799,
                    'name': 'Guzzlord',
                    'types': ['Dark', 'Dragon'],
                    'gender': 'N',
                    'baseStats': {'hp': 223, 'atk': 101, 'def': 53, 'spa': 97, 'spd': 53, 'spe': 43},
                    'abilities': {'0': 'Beast Boost'},
                    'heightm': 5.5,
                    'weightkg': 888,
                    'color': 'Black',
                    'tags': ['Ultra Beast'],
                    'eggGroups': ['Undiscovered']},
    'Necrozma': {   'num': 800,
                    'name': 'Necrozma',
                    'types': ['Psychic'],
                    'gender': 'N',
                    'baseStats': {'hp': 97, 'atk': 107, 'def': 101, 'spa': 127, 'spd': 89, 'spe': 79},
                    'abilities': {'0': 'Prism Armor'},
                    'heightm': 2.4,
                    'weightkg': 230,
                    'color': 'Black',
                    'tags': ['Restricted Legendary'],
                    'eggGroups': ['Undiscovered'],
                    'otherFormes': ['Necrozma-Dusk-Mane', 'Necrozma-Dawn-Wings', 'Necrozma-Ultra'],
                    'formeOrder': ['Necrozma', 'Necrozma-Dusk-Mane', 'Necrozma-Dawn-Wings', 'Necrozma-Ultra']},
    'Necrozmaduskmane': {   'num': 800,
                            'name': 'Necrozma-Dusk-Mane',
                            'baseSpecies': 'Necrozma',
                            'forme': 'Dusk-Mane',
                            'types': ['Psychic', 'Steel'],
                            'gender': 'N',
                            'baseStats': {'hp': 97, 'atk': 157, 'def': 127, 'spa': 113, 'spd': 109, 'spe': 77},
                            'abilities': {'0': 'Prism Armor'},
                            'heightm': 3.8,
                            'weightkg': 460,
                            'color': 'Yellow',
                            'eggGroups': ['Undiscovered'],
                            'changesFrom': 'Necrozma'},
    'Necrozmadawnwings': {   'num': 800,
                             'name': 'Necrozma-Dawn-Wings',
                             'baseSpecies': 'Necrozma',
                             'forme': 'Dawn-Wings',
                             'types': ['Psychic', 'Ghost'],
                             'gender': 'N',
                             'baseStats': {'hp': 97, 'atk': 113, 'def': 109, 'spa': 157, 'spd': 127, 'spe': 77},
                             'abilities': {'0': 'Prism Armor'},
                             'heightm': 4.2,
                             'weightkg': 350,
                             'color': 'Blue',
                             'eggGroups': ['Undiscovered'],
                             'changesFrom': 'Necrozma'},
    'Necrozmaultra': {   'num': 800,
                         'name': 'Necrozma-Ultra',
                         'baseSpecies': 'Necrozma',
                         'forme': 'Ultra',
                         'types': ['Psychic', 'Dragon'],
                         'gender': 'N',
                         'baseStats': {'hp': 97, 'atk': 167, 'def': 97, 'spa': 167, 'spd': 97, 'spe': 129},
                         'abilities': {'0': 'Neuroforce'},
                         'heightm': 7.5,
                         'weightkg': 230,
                         'color': 'Yellow',
                         'eggGroups': ['Undiscovered'],
                         'requiredItem': 'Ultranecrozium Z',
                         'battleOnly': ['Necrozma-Dawn-Wings', 'Necrozma-Dusk-Mane']},
    'Magearna': {   'num': 801,
                    'name': 'Magearna',
                    'types': ['Steel', 'Fairy'],
                    'gender': 'N',
                    'baseStats': {'hp': 80, 'atk': 95, 'def': 115, 'spa': 130, 'spd': 115, 'spe': 65},
                    'abilities': {'0': 'Soul-Heart'},
                    'heightm': 1,
                    'weightkg': 80.5,
                    'color': 'Gray',
                    'eggGroups': ['Undiscovered'],
                    'tags': ['Mythical'],
                    'otherFormes': ['Magearna-Original'],
                    'formeOrder': ['Magearna', 'Magearna-Original']},
    'Magearnaoriginal': {   'num': 801,
                            'name': 'Magearna-Original',
                            'baseSpecies': 'Magearna',
                            'forme': 'Original',
                            'types': ['Steel', 'Fairy'],
                            'gender': 'N',
                            'baseStats': {'hp': 80, 'atk': 95, 'def': 115, 'spa': 130, 'spd': 115, 'spe': 65},
                            'abilities': {'0': 'Soul-Heart'},
                            'heightm': 1,
                            'weightkg': 80.5,
                            'color': 'Red',
                            'eggGroups': ['Undiscovered']},
    'Marshadow': {   'num': 802,
                     'name': 'Marshadow',
                     'types': ['Fighting', 'Ghost'],
                     'gender': 'N',
                     'baseStats': {'hp': 90, 'atk': 125, 'def': 80, 'spa': 90, 'spd': 90, 'spe': 125},
                     'abilities': {'0': 'Technician'},
                     'heightm': 0.7,
                     'weightkg': 22.2,
                     'color': 'Gray',
                     'tags': ['Mythical'],
                     'eggGroups': ['Undiscovered']},
    'Poipole': {   'num': 803,
                   'name': 'Poipole',
                   'types': ['Poison'],
                   'gender': 'N',
                   'baseStats': {'hp': 67, 'atk': 73, 'def': 67, 'spa': 73, 'spd': 67, 'spe': 73},
                   'abilities': {'0': 'Beast Boost'},
                   'heightm': 0.6,
                   'weightkg': 1.8,
                   'color': 'Purple',
                   'tags': ['Ultra Beast'],
                   'evos': ['Naganadel'],
                   'eggGroups': ['Undiscovered']},
    'Naganadel': {   'num': 804,
                     'name': 'Naganadel',
                     'types': ['Poison', 'Dragon'],
                     'gender': 'N',
                     'baseStats': {'hp': 73, 'atk': 73, 'def': 73, 'spa': 127, 'spd': 73, 'spe': 121},
                     'abilities': {'0': 'Beast Boost'},
                     'heightm': 3.6,
                     'weightkg': 150,
                     'color': 'Purple',
                     'tags': ['Ultra Beast'],
                     'prevo': 'Poipole',
                     'evoType': 'levelMove',
                     'evoMove': 'Dragon Pulse',
                     'eggGroups': ['Undiscovered']},
    'Stakataka': {   'num': 805,
                     'name': 'Stakataka',
                     'types': ['Rock', 'Steel'],
                     'gender': 'N',
                     'baseStats': {'hp': 61, 'atk': 131, 'def': 211, 'spa': 53, 'spd': 101, 'spe': 13},
                     'abilities': {'0': 'Beast Boost'},
                     'heightm': 5.5,
                     'weightkg': 820,
                     'color': 'Gray',
                     'tags': ['Ultra Beast'],
                     'eggGroups': ['Undiscovered']},
    'Blacephalon': {   'num': 806,
                       'name': 'Blacephalon',
                       'types': ['Fire', 'Ghost'],
                       'gender': 'N',
                       'baseStats': {'hp': 53, 'atk': 127, 'def': 53, 'spa': 151, 'spd': 79, 'spe': 107},
                       'abilities': {'0': 'Beast Boost'},
                       'heightm': 1.8,
                       'weightkg': 13,
                       'color': 'White',
                       'tags': ['Ultra Beast'],
                       'eggGroups': ['Undiscovered']},
    'Zeraora': {   'num': 807,
                   'name': 'Zeraora',
                   'types': ['Electric'],
                   'gender': 'N',
                   'baseStats': {'hp': 88, 'atk': 112, 'def': 75, 'spa': 102, 'spd': 80, 'spe': 143},
                   'abilities': {'0': 'Volt Absorb'},
                   'heightm': 1.5,
                   'weightkg': 44.5,
                   'color': 'Yellow',
                   'tags': ['Mythical'],
                   'eggGroups': ['Undiscovered']},
    'Meltan': {   'num': 808,
                  'name': 'Meltan',
                  'types': ['Steel'],
                  'gender': 'N',
                  'baseStats': {'hp': 46, 'atk': 65, 'def': 65, 'spa': 55, 'spd': 35, 'spe': 34},
                  'abilities': {'0': 'Magnet Pull'},
                  'heightm': 0.2,
                  'weightkg': 8,
                  'color': 'Gray',
                  'tags': ['Mythical'],
                  'eggGroups': ['Undiscovered']},
    'Melmetal': {   'num': 809,
                    'name': 'Melmetal',
                    'types': ['Steel'],
                    'gender': 'N',
                    'baseStats': {'hp': 135, 'atk': 143, 'def': 143, 'spa': 80, 'spd': 65, 'spe': 34},
                    'abilities': {'0': 'Iron Fist'},
                    'heightm': 2.5,
                    'weightkg': 800,
                    'color': 'Gray',
                    'tags': ['Mythical'],
                    'eggGroups': ['Undiscovered'],
                    'canGigantamax': 'G-Max Meltdown'},
    'Melmetalgmax': {   'num': 809,
                        'name': 'Melmetal-Gmax',
                        'baseSpecies': 'Melmetal',
                        'forme': 'Gmax',
                        'types': ['Steel'],
                        'gender': 'N',
                        'baseStats': {'hp': 135, 'atk': 143, 'def': 143, 'spa': 80, 'spd': 65, 'spe': 34},
                        'abilities': {'0': 'Iron Fist'},
                        'heightm': 25,
                        'weightkg': 0,
                        'color': 'Gray',
                        'eggGroups': ['Undiscovered'],
                        'changesFrom': 'Melmetal'}}
