"""Pokédex entries for Extras region."""
from ..functions.pokedex_funcs import *

pokedex = {
    'Missingno': {   'num': 0,
                     'name': 'MissingNo.',
                     'types': ['Bird', 'Normal'],
                     'baseStats': {'hp': 33, 'atk': 136, 'def': 0, 'spa': 6, 'spd': 6, 'spe': 29},
                     'abilities': {'0': ''},
                     'heightm': 3,
                     'weightkg': 1590.8,
                     'color': 'Gray',
                     'eggGroups': ['Undiscovered']},
    'Syclar': {   'num': -1,
                  'name': 'Syclar',
                  'types': ['Ice', 'Bug'],
                  'baseStats': {'hp': 40, 'atk': 76, 'def': 45, 'spa': 74, 'spd': 39, 'spe': 91},
                  'abilities': {'0': 'Compound Eyes', '1': 'Snow Cloak', 'H': 'Ice Body'},
                  'heightm': 0.2,
                  'weightkg': 4,
                  'color': 'Blue',
                  'evos': ['Syclant'],
                  'eggGroups': ['Bug'],
                  'gen': 4},
    'Syclant': {   'num': -2,
                   'name': 'Syclant',
                   'types': ['Ice', 'Bug'],
                   'baseStats': {'hp': 70, 'atk': 116, 'def': 70, 'spa': 114, 'spd': 64, 'spe': 121},
                   'abilities': {'0': 'Compound Eyes', '1': 'Mountaineer', 'H': 'Ice Body'},
                   'heightm': 1.7,
                   'weightkg': 52,
                   'color': 'Blue',
                   'prevo': 'Syclar',
                   'evoLevel': 30,
                   'eggGroups': ['Bug'],
                   'gen': 4},
    'Revenankh': {   'num': -3,
                     'name': 'Revenankh',
                     'types': ['Ghost', 'Fighting'],
                     'baseStats': {'hp': 90, 'atk': 105, 'def': 90, 'spa': 65, 'spd': 110, 'spe': 65},
                     'abilities': {'0': 'Air Lock', '1': 'Triage', 'H': 'Shed Skin'},
                     'heightm': 1.8,
                     'weightkg': 44,
                     'color': 'White',
                     'eggGroups': ['Amorphous', 'Human-Like'],
                     'gen': 4},
    'Embirch': {   'num': -4,
                   'name': 'Embirch',
                   'types': ['Fire', 'Grass'],
                   'baseStats': {'hp': 60, 'atk': 40, 'def': 55, 'spa': 65, 'spd': 40, 'spe': 60},
                   'abilities': {'0': 'Reckless', '1': 'Leaf Guard', 'H': 'Chlorophyll'},
                   'heightm': 0.6,
                   'weightkg': 15,
                   'color': 'Brown',
                   'evos': ['Flarelm'],
                   'eggGroups': ['Monster', 'Dragon'],
                   'gen': 4},
    'Flarelm': {   'num': -5,
                   'name': 'Flarelm',
                   'types': ['Fire', 'Grass'],
                   'baseStats': {'hp': 90, 'atk': 50, 'def': 95, 'spa': 75, 'spd': 70, 'spe': 40},
                   'abilities': {'0': 'Rock Head', '1': 'Battle Armor', 'H': 'White Smoke'},
                   'heightm': 1.4,
                   'weightkg': 73,
                   'color': 'Brown',
                   'prevo': 'Embirch',
                   'evoLevel': 24,
                   'evos': ['Pyroak'],
                   'eggGroups': ['Monster', 'Dragon'],
                   'gen': 4},
    'Pyroak': {   'num': -6,
                  'name': 'Pyroak',
                  'types': ['Fire', 'Grass'],
                  'baseStats': {'hp': 120, 'atk': 70, 'def': 105, 'spa': 70, 'spd': 65, 'spe': 60},
                  'abilities': {'0': 'Rock Head', '1': 'Battle Armor', 'H': 'Contrary'},
                  'heightm': 2.1,
                  'weightkg': 168,
                  'color': 'Brown',
                  'prevo': 'Flarelm',
                  'evoLevel': 38,
                  'eggGroups': ['Monster', 'Dragon'],
                  'gen': 4},
    'Breezi': {   'num': -7,
                  'name': 'Breezi',
                  'types': ['Poison', 'Flying'],
                  'baseStats': {'hp': 50, 'atk': 46, 'def': 69, 'spa': 60, 'spd': 50, 'spe': 75},
                  'abilities': {'0': 'Unburden', '1': 'Own Tempo', 'H': 'Frisk'},
                  'heightm': 0.4,
                  'weightkg': 0.6,
                  'color': 'Purple',
                  'evos': ['Fidgit'],
                  'eggGroups': ['Field'],
                  'gen': 4},
    'Fidgit': {   'num': -8,
                  'name': 'Fidgit',
                  'types': ['Poison', 'Ground'],
                  'baseStats': {'hp': 95, 'atk': 76, 'def': 109, 'spa': 90, 'spd': 80, 'spe': 105},
                  'abilities': {'0': 'Persistent', '1': 'Vital Spirit', 'H': 'Frisk'},
                  'heightm': 0.9,
                  'weightkg': 53,
                  'color': 'Purple',
                  'prevo': 'Breezi',
                  'evoLevel': 33,
                  'eggGroups': ['Field'],
                  'gen': 4},
    'Rebble': {   'num': -9,
                  'name': 'Rebble',
                  'types': ['Rock'],
                  'gender': 'N',
                  'baseStats': {'hp': 45, 'atk': 25, 'def': 65, 'spa': 75, 'spd': 55, 'spe': 80},
                  'abilities': {'0': 'Levitate', '1': 'Solid Rock', 'H': 'Sniper'},
                  'heightm': 0.3,
                  'weightkg': 7,
                  'color': 'Gray',
                  'evos': ['Tactite'],
                  'eggGroups': ['Mineral'],
                  'gen': 4},
    'Tactite': {   'num': -10,
                   'name': 'Tactite',
                   'types': ['Rock'],
                   'gender': 'N',
                   'baseStats': {'hp': 70, 'atk': 40, 'def': 65, 'spa': 100, 'spd': 65, 'spe': 95},
                   'abilities': {'0': 'Levitate', '1': 'Technician', 'H': 'Sniper'},
                   'heightm': 0.6,
                   'weightkg': 16,
                   'color': 'Gray',
                   'prevo': 'Rebble',
                   'evoLevel': 28,
                   'evos': ['Stratagem'],
                   'eggGroups': ['Mineral'],
                   'gen': 4},
    'Stratagem': {   'num': -11,
                     'name': 'Stratagem',
                     'types': ['Rock'],
                     'gender': 'N',
                     'baseStats': {'hp': 90, 'atk': 60, 'def': 65, 'spa': 120, 'spd': 70, 'spe': 130},
                     'abilities': {'0': 'Levitate', '1': 'Technician', 'H': 'Sniper'},
                     'heightm': 0.9,
                     'weightkg': 45,
                     'color': 'Gray',
                     'prevo': 'Tactite',
                     'evoType': 'trade',
                     'eggGroups': ['Mineral'],
                     'gen': 4},
    'Privatyke': {   'num': -12,
                     'name': 'Privatyke',
                     'types': ['Water', 'Fighting'],
                     'baseStats': {'hp': 65, 'atk': 75, 'def': 65, 'spa': 40, 'spd': 60, 'spe': 45},
                     'abilities': {'0': 'Unaware', 'H': 'Technician'},
                     'heightm': 1,
                     'weightkg': 35,
                     'color': 'Green',
                     'evos': ['Arghonaut'],
                     'eggGroups': ['Water 1', 'Water 3'],
                     'gen': 4},
    'Arghonaut': {   'num': -13,
                     'name': 'Arghonaut',
                     'types': ['Water', 'Fighting'],
                     'baseStats': {'hp': 105, 'atk': 110, 'def': 95, 'spa': 70, 'spd': 100, 'spe': 75},
                     'abilities': {'0': 'Unaware', 'H': 'Technician'},
                     'heightm': 1.7,
                     'weightkg': 151,
                     'color': 'Green',
                     'prevo': 'Privatyke',
                     'evoLevel': 37,
                     'eggGroups': ['Water 1', 'Water 3'],
                     'gen': 4},
    'Kitsunoh': {   'num': -14,
                    'name': 'Kitsunoh',
                    'types': ['Ghost', 'Steel'],
                    'baseStats': {'hp': 80, 'atk': 103, 'def': 85, 'spa': 55, 'spd': 80, 'spe': 110},
                    'abilities': {'0': 'Frisk', '1': 'Limber', 'H': 'Iron Fist'},
                    'heightm': 1.1,
                    'weightkg': 51,
                    'color': 'Gray',
                    'prevo': 'Nohface',
                    'evoType': 'trade',
                    'evoItem': 'Metal Coat',
                    'eggGroups': ['Field'],
                    'gen': 4},
    'Cyclohm': {   'num': -15,
                   'name': 'Cyclohm',
                   'types': ['Electric', 'Dragon'],
                   'baseStats': {'hp': 108, 'atk': 60, 'def': 118, 'spa': 112, 'spd': 70, 'spe': 80},
                   'abilities': {'0': 'Shield Dust', '1': 'Static', 'H': 'Damp'},
                   'heightm': 1.6,
                   'weightkg': 59,
                   'color': 'Yellow',
                   'prevo': 'Duohm',
                   'evoLevel': 43,
                   'eggGroups': ['Dragon', 'Monster'],
                   'gen': 4},
    'Colossoil': {   'num': -16,
                     'name': 'Colossoil',
                     'types': ['Ground', 'Dark'],
                     'baseStats': {'hp': 133, 'atk': 122, 'def': 72, 'spa': 71, 'spd': 72, 'spe': 95},
                     'abilities': {'0': 'Rebound', '1': 'Guts', 'H': 'Unnerve'},
                     'heightm': 2.6,
                     'weightkg': 683.6,
                     'color': 'Brown',
                     'prevo': 'Dorsoil',
                     'evoLevel': 39,
                     'eggGroups': ['Water 2', 'Field'],
                     'gen': 4},
    'Krilowatt': {   'num': -17,
                     'name': 'Krilowatt',
                     'types': ['Electric', 'Water'],
                     'baseStats': {'hp': 151, 'atk': 84, 'def': 73, 'spa': 83, 'spd': 74, 'spe': 105},
                     'abilities': {'0': 'Trace', '1': 'Magic Guard', 'H': 'Minus'},
                     'heightm': 0.7,
                     'weightkg': 10.6,
                     'color': 'Red',
                     'prevo': 'Protowatt',
                     'evoLevel': 15,
                     'eggGroups': ['Water 1', 'Fairy'],
                     'gen': 4},
    'Voodoll': {   'num': -18,
                   'name': 'Voodoll',
                   'types': ['Normal', 'Dark'],
                   'baseStats': {'hp': 55, 'atk': 40, 'def': 55, 'spa': 75, 'spd': 50, 'spe': 70},
                   'abilities': {'0': 'Volt Absorb', '1': 'Lightning Rod', 'H': 'Cursed Body'},
                   'heightm': 1,
                   'weightkg': 25,
                   'color': 'Brown',
                   'evos': ['Voodoom'],
                   'eggGroups': ['Human-Like', 'Field'],
                   'gen': 4},
    'Voodoom': {   'num': -19,
                   'name': 'Voodoom',
                   'types': ['Fighting', 'Dark'],
                   'baseStats': {'hp': 90, 'atk': 85, 'def': 80, 'spa': 130, 'spd': 80, 'spe': 110},
                   'abilities': {'0': 'Volt Absorb', '1': 'Lightning Rod', 'H': 'Cursed Body'},
                   'heightm': 2,
                   'weightkg': 75.5,
                   'color': 'Brown',
                   'prevo': 'Voodoll',
                   'evoLevel': 32,
                   'eggGroups': ['Human-Like', 'Field'],
                   'gen': 4},
    'Scratchet': {   'num': -20,
                     'name': 'Scratchet',
                     'types': ['Normal', 'Fighting'],
                     'baseStats': {'hp': 55, 'atk': 85, 'def': 80, 'spa': 20, 'spd': 70, 'spe': 40},
                     'abilities': {'0': 'Scrappy', '1': 'Prankster', 'H': 'Vital Spirit'},
                     'heightm': 0.5,
                     'weightkg': 20,
                     'color': 'Brown',
                     'evos': ['Tomohawk'],
                     'eggGroups': ['Field', 'Flying'],
                     'gen': 5},
    'Tomohawk': {   'num': -21,
                    'name': 'Tomohawk',
                    'types': ['Flying', 'Fighting'],
                    'baseStats': {'hp': 105, 'atk': 60, 'def': 90, 'spa': 115, 'spd': 80, 'spe': 85},
                    'abilities': {'0': 'Intimidate', '1': 'Prankster', 'H': 'Justified'},
                    'heightm': 1.27,
                    'weightkg': 37.2,
                    'color': 'Red',
                    'prevo': 'Scratchet',
                    'evoLevel': 23,
                    'eggGroups': ['Field', 'Flying'],
                    'gen': 5},
    'Necturine': {   'num': -22,
                     'name': 'Necturine',
                     'types': ['Grass', 'Ghost'],
                     'gender': 'F',
                     'baseStats': {'hp': 49, 'atk': 55, 'def': 60, 'spa': 50, 'spd': 75, 'spe': 51},
                     'abilities': {'0': 'Anticipation', 'H': 'Telepathy'},
                     'heightm': 0.3,
                     'weightkg': 1.8,
                     'color': 'White',
                     'evos': ['Necturna'],
                     'eggGroups': ['Grass', 'Field'],
                     'gen': 5},
    'Necturna': {   'num': -23,
                    'name': 'Necturna',
                    'types': ['Grass', 'Ghost'],
                    'gender': 'F',
                    'baseStats': {'hp': 64, 'atk': 120, 'def': 100, 'spa': 85, 'spd': 120, 'spe': 58},
                    'abilities': {'0': 'Forewarn', 'H': 'Telepathy'},
                    'heightm': 1.65,
                    'weightkg': 49.6,
                    'color': 'Black',
                    'prevo': 'Necturine',
                    'evoLevel': 31,
                    'eggGroups': ['Grass', 'Field'],
                    'gen': 5},
    'Mollux': {   'num': -24,
                  'name': 'Mollux',
                  'types': ['Fire', 'Poison'],
                  'baseStats': {'hp': 95, 'atk': 45, 'def': 83, 'spa': 131, 'spd': 105, 'spe': 76},
                  'abilities': {'0': 'Dry Skin', 'H': 'Illuminate'},
                  'heightm': 1.2,
                  'weightkg': 41,
                  'color': 'Pink',
                  'eggGroups': ['Fairy', 'Field'],
                  'gen': 5},
    'Cupra': {   'num': -25,
                 'name': 'Cupra',
                 'types': ['Bug', 'Psychic'],
                 'baseStats': {'hp': 50, 'atk': 60, 'def': 49, 'spa': 67, 'spd': 30, 'spe': 44},
                 'abilities': {'0': 'Shield Dust', '1': 'Keen Eye', 'H': 'Magic Guard'},
                 'heightm': 0.5,
                 'weightkg': 4.8,
                 'color': 'Brown',
                 'evos': ['Argalis'],
                 'eggGroups': ['Bug'],
                 'gen': 5},
    'Argalis': {   'num': -26,
                   'name': 'Argalis',
                   'types': ['Bug', 'Psychic'],
                   'baseStats': {'hp': 60, 'atk': 90, 'def': 89, 'spa': 87, 'spd': 40, 'spe': 54},
                   'abilities': {'0': 'Shed Skin', '1': 'Compound Eyes', 'H': 'Overcoat'},
                   'heightm': 1.3,
                   'weightkg': 341.4,
                   'color': 'Gray',
                   'prevo': 'Cupra',
                   'evoLevel': 30,
                   'evos': ['Aurumoth'],
                   'eggGroups': ['Bug'],
                   'gen': 5},
    'Aurumoth': {   'num': -27,
                    'name': 'Aurumoth',
                    'types': ['Bug', 'Psychic'],
                    'baseStats': {'hp': 110, 'atk': 120, 'def': 99, 'spa': 117, 'spd': 60, 'spe': 94},
                    'abilities': {'0': 'Weak Armor', '1': 'No Guard', 'H': 'Light Metal'},
                    'heightm': 2.1,
                    'weightkg': 193,
                    'color': 'Purple',
                    'prevo': 'Argalis',
                    'evoLevel': 50,
                    'eggGroups': ['Bug'],
                    'gen': 5},
    'Brattler': {   'num': -28,
                    'name': 'Brattler',
                    'types': ['Dark', 'Grass'],
                    'baseStats': {'hp': 80, 'atk': 70, 'def': 40, 'spa': 20, 'spd': 90, 'spe': 30},
                    'abilities': {'0': 'Harvest', '1': 'Infiltrator', 'H': 'Rattled'},
                    'heightm': 1.8,
                    'weightkg': 11.5,
                    'color': 'Brown',
                    'evos': ['Malaconda'],
                    'eggGroups': ['Grass', 'Dragon'],
                    'gen': 5},
    'Malaconda': {   'num': -29,
                     'name': 'Malaconda',
                     'types': ['Dark', 'Grass'],
                     'baseStats': {'hp': 115, 'atk': 100, 'def': 60, 'spa': 40, 'spd': 130, 'spe': 55},
                     'abilities': {'0': 'Harvest', '1': 'Infiltrator', 'H': 'Drought'},
                     'heightm': 5.5,
                     'weightkg': 108.8,
                     'color': 'Brown',
                     'prevo': 'Brattler',
                     'evoLevel': 33,
                     'eggGroups': ['Grass', 'Dragon'],
                     'gen': 5},
    'Cawdet': {   'num': -30,
                  'name': 'Cawdet',
                  'types': ['Steel', 'Flying'],
                  'baseStats': {'hp': 35, 'atk': 72, 'def': 85, 'spa': 40, 'spd': 55, 'spe': 88},
                  'abilities': {'0': 'Keen Eye', '1': 'Volt Absorb', 'H': 'Big Pecks'},
                  'heightm': 0.76,
                  'weightkg': 25,
                  'color': 'Gray',
                  'evos': ['Cawmodore'],
                  'eggGroups': ['Flying'],
                  'gen': 5},
    'Cawmodore': {   'num': -31,
                     'name': 'Cawmodore',
                     'types': ['Steel', 'Flying'],
                     'baseStats': {'hp': 50, 'atk': 92, 'def': 130, 'spa': 65, 'spd': 75, 'spe': 118},
                     'abilities': {'0': 'Intimidate', '1': 'Volt Absorb', 'H': 'Big Pecks'},
                     'heightm': 1.7,
                     'weightkg': 37,
                     'color': 'Black',
                     'prevo': 'Cawdet',
                     'evoLevel': 33,
                     'eggGroups': ['Flying'],
                     'gen': 5},
    'Volkritter': {   'num': -32,
                      'name': 'Volkritter',
                      'types': ['Water', 'Fire'],
                      'baseStats': {'hp': 60, 'atk': 30, 'def': 50, 'spa': 80, 'spd': 60, 'spe': 70},
                      'abilities': {'0': 'Anticipation', '1': 'Infiltrator', 'H': 'Unnerve'},
                      'heightm': 0.3,
                      'weightkg': 15,
                      'color': 'Red',
                      'evos': ['Volkraken'],
                      'eggGroups': ['Water 1', 'Water 2'],
                      'gen': 6},
    'Volkraken': {   'num': -33,
                     'name': 'Volkraken',
                     'types': ['Water', 'Fire'],
                     'baseStats': {'hp': 100, 'atk': 45, 'def': 80, 'spa': 135, 'spd': 100, 'spe': 95},
                     'abilities': {'0': 'Analytic', '1': 'Infiltrator', 'H': 'Pressure'},
                     'heightm': 1.3,
                     'weightkg': 44.5,
                     'color': 'Red',
                     'prevo': 'Volkritter',
                     'evoLevel': 34,
                     'eggGroups': ['Water 1', 'Water 2'],
                     'gen': 6},
    'Snugglow': {   'num': -34,
                    'name': 'Snugglow',
                    'types': ['Electric', 'Poison'],
                    'baseStats': {'hp': 40, 'atk': 37, 'def': 79, 'spa': 91, 'spd': 68, 'spe': 70},
                    'abilities': {'0': 'Storm Drain', '1': 'Vital Spirit', 'H': 'Telepathy'},
                    'heightm': 1.2,
                    'weightkg': 6,
                    'color': 'Purple',
                    'evos': ['Plasmanta'],
                    'eggGroups': ['Water 1', 'Water 2'],
                    'gen': 6},
    'Plasmanta': {   'num': -35,
                     'name': 'Plasmanta',
                     'types': ['Electric', 'Poison'],
                     'baseStats': {'hp': 60, 'atk': 57, 'def': 119, 'spa': 131, 'spd': 98, 'spe': 100},
                     'abilities': {'0': 'Storm Drain', '1': 'Vital Spirit', 'H': 'Telepathy'},
                     'heightm': 7,
                     'weightkg': 460,
                     'color': 'Purple',
                     'prevo': 'Snugglow',
                     'evoLevel': 29,
                     'eggGroups': ['Water 1', 'Water 2'],
                     'gen': 6},
    'Floatoy': {   'num': -36,
                   'name': 'Floatoy',
                   'types': ['Water'],
                   'baseStats': {'hp': 48, 'atk': 70, 'def': 40, 'spa': 70, 'spd': 30, 'spe': 77},
                   'abilities': {'0': 'Water Veil', '1': 'Heatproof', 'H': 'Swift Swim'},
                   'heightm': 0.8,
                   'weightkg': 1.9,
                   'color': 'White',
                   'evos': ['Caimanoe'],
                   'eggGroups': ['Water 1', 'Field'],
                   'gen': 6},
    'Caimanoe': {   'num': -37,
                    'name': 'Caimanoe',
                    'types': ['Water', 'Steel'],
                    'baseStats': {'hp': 73, 'atk': 85, 'def': 65, 'spa': 80, 'spd': 40, 'spe': 87},
                    'abilities': {'0': 'Water Veil', '1': 'Heatproof', 'H': 'Light Metal'},
                    'heightm': 1.4,
                    'weightkg': 72.5,
                    'color': 'Gray',
                    'prevo': 'Floatoy',
                    'evoLevel': 21,
                    'evos': ['Naviathan'],
                    'eggGroups': ['Water 1', 'Field'],
                    'gen': 6},
    'Naviathan': {   'num': -38,
                     'name': 'Naviathan',
                     'types': ['Water', 'Steel'],
                     'baseStats': {'hp': 103, 'atk': 110, 'def': 90, 'spa': 95, 'spd': 65, 'spe': 97},
                     'abilities': {'0': 'Guts', '1': 'Heatproof', 'H': 'Light Metal'},
                     'heightm': 3,
                     'weightkg': 510,
                     'color': 'Gray',
                     'prevo': 'Caimanoe',
                     'evoLevel': 40,
                     'eggGroups': ['Water 1', 'Field'],
                     'gen': 6},
    'Crucibelle': {   'num': -39,
                      'name': 'Crucibelle',
                      'types': ['Rock', 'Poison'],
                      'genderRatio': {'M': 0.25, 'F': 0.75},
                      'baseStats': {'hp': 106, 'atk': 105, 'def': 65, 'spa': 75, 'spd': 85, 'spe': 104},
                      'abilities': {'0': 'Regenerator', '1': 'Mold Breaker', 'H': 'Liquid Ooze'},
                      'heightm': 1.3,
                      'weightkg': 23.6,
                      'color': 'Purple',
                      'eggGroups': ['Amorphous', 'Mineral'],
                      'otherFormes': ['Crucibelle-Mega'],
                      'formeOrder': ['Crucibelle', 'Crucibelle-Mega'],
                      'gen': 6},
    'Crucibellemega': {   'num': -39,
                          'name': 'Crucibelle-Mega',
                          'baseSpecies': 'Crucibelle',
                          'forme': 'Mega',
                          'types': ['Rock', 'Poison'],
                          'genderRatio': {'M': 0.25, 'F': 0.75},
                          'baseStats': {'hp': 106, 'atk': 135, 'def': 75, 'spa': 91, 'spd': 125, 'spe': 108},
                          'abilities': {'0': 'Magic Guard'},
                          'heightm': 1.4,
                          'weightkg': 22.5,
                          'color': 'Purple',
                          'eggGroups': ['Amorphous', 'Mineral'],
                          'requiredItem': 'Crucibellite',
                          'gen': 6},
    'Pluffle': {   'num': -40,
                   'name': 'Pluffle',
                   'types': ['Fairy'],
                   'baseStats': {'hp': 74, 'atk': 38, 'def': 51, 'spa': 65, 'spd': 78, 'spe': 49},
                   'abilities': {'0': 'Natural Cure', '1': 'Aroma Veil', 'H': 'Friend Guard'},
                   'heightm': 0.8,
                   'weightkg': 1.8,
                   'color': 'Pink',
                   'evos': ['Kerfluffle'],
                   'eggGroups': ['Fairy', 'Human-Like'],
                   'gen': 6},
    'Kerfluffle': {   'num': -41,
                      'name': 'Kerfluffle',
                      'types': ['Fairy', 'Fighting'],
                      'baseStats': {'hp': 84, 'atk': 78, 'def': 86, 'spa': 115, 'spd': 88, 'spe': 119},
                      'abilities': {'0': 'Natural Cure', '1': 'Aroma Veil', 'H': 'Friend Guard'},
                      'heightm': 2.1,
                      'weightkg': 24.2,
                      'color': 'Pink',
                      'prevo': 'Pluffle',
                      'evoType': 'levelMove',
                      'evoMove': 'Play Rough',
                      'eggGroups': ['Fairy', 'Human-Like'],
                      'gen': 6},
    'Pajantom': {   'num': -42,
                    'name': 'Pajantom',
                    'types': ['Dragon', 'Ghost'],
                    'baseStats': {'hp': 84, 'atk': 133, 'def': 71, 'spa': 51, 'spd': 111, 'spe': 101},
                    'abilities': {'0': 'Comatose'},
                    'heightm': 1.1,
                    'weightkg': 3.1,
                    'color': 'Purple',
                    'eggGroups': ['Dragon', 'Monster'],
                    'gen': 7},
    'Mumbao': {   'num': -43,
                  'name': 'Mumbao',
                  'types': ['Grass', 'Fairy'],
                  'baseStats': {'hp': 55, 'atk': 30, 'def': 64, 'spa': 87, 'spd': 73, 'spe': 66},
                  'abilities': {'0': 'Trace', '1': 'Overcoat', 'H': 'Solar Power'},
                  'heightm': 1,
                  'weightkg': 83,
                  'color': 'Brown',
                  'evos': ['Jumbao'],
                  'eggGroups': ['Grass'],
                  'gen': 7},
    'Jumbao': {   'num': -44,
                  'name': 'Jumbao',
                  'types': ['Grass', 'Fairy'],
                  'baseStats': {'hp': 92, 'atk': 63, 'def': 97, 'spa': 124, 'spd': 104, 'spe': 96},
                  'abilities': {'0': 'Trace', '1': 'Overcoat', 'H': 'Drought'},
                  'heightm': 2.4,
                  'weightkg': 200,
                  'color': 'Brown',
                  'prevo': 'Mumbao',
                  'evoType': 'levelFriendship',
                  'evoCondition': 'during the day',
                  'eggGroups': ['Grass'],
                  'gen': 7},
    'Fawnifer': {   'num': -45,
                    'name': 'Fawnifer',
                    'types': ['Grass'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 49, 'atk': 61, 'def': 42, 'spa': 52, 'spd': 40, 'spe': 76},
                    'abilities': {'0': 'Overgrow', 'H': 'Lightning Rod'},
                    'heightm': 0.7,
                    'weightkg': 6.9,
                    'color': 'Green',
                    'evos': ['Electrelk'],
                    'eggGroups': ['Field'],
                    'gen': 7},
    'Electrelk': {   'num': -46,
                     'name': 'Electrelk',
                     'types': ['Grass', 'Electric'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 59, 'atk': 81, 'def': 67, 'spa': 57, 'spd': 55, 'spe': 101},
                     'abilities': {'0': 'Overgrow', 'H': 'Galvanize'},
                     'heightm': 1.4,
                     'weightkg': 41.5,
                     'color': 'Green',
                     'prevo': 'Fawnifer',
                     'evoLevel': 17,
                     'evos': ['Caribolt'],
                     'eggGroups': ['Field'],
                     'gen': 7},
    'Caribolt': {   'num': -47,
                    'name': 'Caribolt',
                    'types': ['Grass', 'Electric'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 84, 'atk': 106, 'def': 82, 'spa': 77, 'spd': 80, 'spe': 106},
                    'abilities': {'0': 'Overgrow', 'H': 'Galvanize'},
                    'heightm': 2.5,
                    'weightkg': 140,
                    'color': 'Green',
                    'prevo': 'Electrelk',
                    'evoLevel': 34,
                    'eggGroups': ['Field'],
                    'gen': 7},
    'Smogecko': {   'num': -48,
                    'name': 'Smogecko',
                    'types': ['Fire'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 48, 'atk': 66, 'def': 43, 'spa': 58, 'spd': 48, 'spe': 56},
                    'abilities': {'0': 'Blaze', 'H': 'Technician'},
                    'heightm': 0.5,
                    'weightkg': 8.5,
                    'color': 'Red',
                    'evos': ['Smoguana'],
                    'eggGroups': ['Field', 'Monster'],
                    'gen': 7},
    'Smoguana': {   'num': -49,
                    'name': 'Smoguana',
                    'types': ['Fire', 'Ground'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 68, 'atk': 86, 'def': 53, 'spa': 68, 'spd': 68, 'spe': 76},
                    'abilities': {'0': 'Blaze', 'H': 'Technician'},
                    'heightm': 1.5,
                    'weightkg': 22.2,
                    'color': 'Red',
                    'prevo': 'Smogecko',
                    'evoLevel': 15,
                    'evos': ['Smokomodo'],
                    'eggGroups': ['Field', 'Monster'],
                    'gen': 7},
    'Smokomodo': {   'num': -50,
                     'name': 'Smokomodo',
                     'types': ['Fire', 'Ground'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 88, 'atk': 116, 'def': 67, 'spa': 88, 'spd': 78, 'spe': 97},
                     'abilities': {'0': 'Blaze', 'H': 'Technician'},
                     'heightm': 2.2,
                     'weightkg': 205,
                     'color': 'Red',
                     'prevo': 'Smoguana',
                     'evoLevel': 36,
                     'eggGroups': ['Field', 'Monster'],
                     'gen': 7},
    'Swirlpool': {   'num': -51,
                     'name': 'Swirlpool',
                     'types': ['Water'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 61, 'atk': 49, 'def': 70, 'spa': 50, 'spd': 62, 'spe': 28},
                     'abilities': {'0': 'Torrent', 'H': 'Poison Heal'},
                     'heightm': 0.5,
                     'weightkg': 7,
                     'color': 'Blue',
                     'evos': ['Coribalis'],
                     'eggGroups': ['Water 1', 'Fairy'],
                     'gen': 7},
    'Coribalis': {   'num': -52,
                     'name': 'Coribalis',
                     'types': ['Water', 'Bug'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 76, 'atk': 69, 'def': 90, 'spa': 65, 'spd': 77, 'spe': 43},
                     'abilities': {'0': 'Torrent', 'H': 'Poison Heal'},
                     'heightm': 1.4,
                     'weightkg': 24.5,
                     'color': 'Blue',
                     'prevo': 'Swirlpool',
                     'evoLevel': 17,
                     'evos': ['Snaelstrom'],
                     'eggGroups': ['Water 1', 'Fairy'],
                     'gen': 7},
    'Snaelstrom': {   'num': -53,
                      'name': 'Snaelstrom',
                      'types': ['Water', 'Bug'],
                      'genderRatio': {'M': 0.875, 'F': 0.125},
                      'baseStats': {'hp': 91, 'atk': 94, 'def': 110, 'spa': 80, 'spd': 97, 'spe': 63},
                      'abilities': {'0': 'Torrent', 'H': 'Poison Heal'},
                      'heightm': 2,
                      'weightkg': 120,
                      'color': 'Blue',
                      'prevo': 'Coribalis',
                      'evoLevel': 34,
                      'eggGroups': ['Water 1', 'Fairy'],
                      'gen': 7},
    'Justyke': {   'num': -54,
                   'name': 'Justyke',
                   'types': ['Steel', 'Ground'],
                   'gender': 'N',
                   'baseStats': {'hp': 72, 'atk': 70, 'def': 56, 'spa': 83, 'spd': 68, 'spe': 30},
                   'abilities': {'0': 'Levitate', '1': 'Bulletproof', 'H': 'Justified'},
                   'heightm': 0.4,
                   'weightkg': 36.5,
                   'color': 'Brown',
                   'evos': ['Equilibra'],
                   'eggGroups': ['Mineral'],
                   'gen': 7},
    'Equilibra': {   'num': -55,
                     'name': 'Equilibra',
                     'types': ['Steel', 'Ground'],
                     'gender': 'N',
                     'baseStats': {'hp': 102, 'atk': 50, 'def': 96, 'spa': 133, 'spd': 118, 'spe': 60},
                     'abilities': {'0': 'Levitate', '1': 'Bulletproof', 'H': 'Justified'},
                     'heightm': 0.8,
                     'weightkg': 51.3,
                     'color': 'Brown',
                     'prevo': 'Justyke',
                     'evoLevel': 32,
                     'eggGroups': ['Mineral'],
                     'gen': 7},
    'Solotl': {   'num': -56,
                  'name': 'Solotl',
                  'types': ['Fire', 'Dragon'],
                  'baseStats': {'hp': 68, 'atk': 48, 'def': 34, 'spa': 72, 'spd': 24, 'spe': 84},
                  'abilities': {'0': 'Regenerator', '1': 'Vital Spirit', 'H': 'Magician'},
                  'heightm': 0.6,
                  'weightkg': 11.8,
                  'color': 'Red',
                  'evos': ['Astrolotl'],
                  'eggGroups': ['Dragon', 'Fairy'],
                  'gen': 8},
    'Astrolotl': {   'num': -57,
                     'name': 'Astrolotl',
                     'types': ['Fire', 'Dragon'],
                     'baseStats': {'hp': 108, 'atk': 108, 'def': 74, 'spa': 92, 'spd': 64, 'spe': 114},
                     'abilities': {'0': 'Regenerator', '1': 'Vital Spirit', 'H': 'Magician'},
                     'heightm': 1.9,
                     'weightkg': 50,
                     'color': 'Red',
                     'prevo': 'Solotl',
                     'evoLevel': 35,
                     'eggGroups': ['Dragon', 'Fairy'],
                     'gen': 8},
    'Miasmite': {   'num': -58,
                    'name': 'Miasmite',
                    'types': ['Bug', 'Dragon'],
                    'baseStats': {'hp': 40, 'atk': 85, 'def': 60, 'spa': 52, 'spd': 52, 'spe': 44},
                    'abilities': {'0': 'Neutralizing Gas', '1': 'Hyper Cutter', 'H': 'Compound Eyes'},
                    'heightm': 0.6,
                    'weightkg': 10.1,
                    'color': 'Green',
                    'evos': ['Miasmaw'],
                    'eggGroups': ['Bug', 'Dragon'],
                    'gen': 8},
    'Miasmaw': {   'num': -59,
                   'name': 'Miasmaw',
                   'types': ['Bug', 'Dragon'],
                   'baseStats': {'hp': 85, 'atk': 135, 'def': 60, 'spa': 88, 'spd': 105, 'spe': 99},
                   'abilities': {'0': 'Neutralizing Gas', '1': 'Hyper Cutter', 'H': 'Compound Eyes'},
                   'heightm': 1.2,
                   'weightkg': 57,
                   'color': 'Green',
                   'prevo': 'Miasmite',
                   'evoLevel': 30,
                   'eggGroups': ['Bug', 'Dragon'],
                   'gen': 8},
    'Chromera': {   'num': -60,
                    'name': 'Chromera',
                    'types': ['Dark', 'Normal'],
                    'gender': 'N',
                    'baseStats': {'hp': 85, 'atk': 85, 'def': 115, 'spa': 115, 'spd': 100, 'spe': 100},
                    'abilities': {'0': 'Color Change'},
                    'heightm': 2.5,
                    'weightkg': 215,
                    'color': 'Purple',
                    'eggGroups': ['Undiscovered'],
                    'gen': 8},
    'Nohface': {   'num': -61,
                   'name': 'Nohface',
                   'types': ['Ghost'],
                   'baseStats': {'hp': 50, 'atk': 73, 'def': 50, 'spa': 30, 'spd': 50, 'spe': 80},
                   'abilities': {'0': 'Frisk', '1': 'Limber', 'H': 'Unnerve'},
                   'heightm': 0.5,
                   'weightkg': 5.9,
                   'color': 'Blue',
                   'evos': ['Kitsunoh'],
                   'eggGroups': ['Field'],
                   'gen': 4},
    'Monohm': {   'num': -62,
                  'name': 'Monohm',
                  'types': ['Electric'],
                  'baseStats': {'hp': 53, 'atk': 40, 'def': 58, 'spa': 67, 'spd': 55, 'spe': 55},
                  'abilities': {'0': 'Shield Dust', '1': 'Static', 'H': 'Damp'},
                  'heightm': 0.6,
                  'weightkg': 4.1,
                  'color': 'Yellow',
                  'evos': ['Duohm'],
                  'eggGroups': ['Dragon', 'Monster'],
                  'gen': 4},
    'Duohm': {   'num': -63,
                 'name': 'Duohm',
                 'types': ['Electric', 'Dragon'],
                 'baseStats': {'hp': 88, 'atk': 40, 'def': 103, 'spa': 77, 'spd': 60, 'spe': 60},
                 'abilities': {'0': 'Shield Dust', '1': 'Static', 'H': 'Damp'},
                 'heightm': 1.1,
                 'weightkg': 19.2,
                 'color': 'Yellow',
                 'prevo': 'Monohm',
                 'evoLevel': 32,
                 'evos': ['Cyclohm'],
                 'eggGroups': ['Dragon', 'Monster'],
                 'gen': 4},
    'Dorsoil': {   'num': -64,
                   'name': 'Dorsoil',
                   'types': ['Ground'],
                   'baseStats': {'hp': 103, 'atk': 72, 'def': 52, 'spa': 61, 'spd': 52, 'spe': 65},
                   'abilities': {'0': 'Oblivious', '1': 'Guts', 'H': 'Unnerve'},
                   'heightm': 1.3,
                   'weightkg': 145,
                   'color': 'White',
                   'evos': ['Colossoil'],
                   'eggGroups': ['Water 2', 'Field'],
                   'gen': 4},
    'Protowatt': {   'num': -65,
                     'name': 'Protowatt',
                     'types': ['Electric', 'Water'],
                     'baseStats': {'hp': 51, 'atk': 44, 'def': 33, 'spa': 43, 'spd': 34, 'spe': 65},
                     'abilities': {'0': 'Trace', '1': 'Magic Guard', 'H': 'Minus'},
                     'heightm': 0.1,
                     'weightkg': 0.1,
                     'color': 'Red',
                     'evos': ['Krilowatt'],
                     'eggGroups': ['Water 1', 'Fairy'],
                     'gen': 4},
    'Venomicon': {   'num': -66,
                     'name': 'Venomicon',
                     'baseForme': 'Prologue',
                     'types': ['Poison', 'Flying'],
                     'gender': 'N',
                     'baseStats': {'hp': 85, 'atk': 50, 'def': 113, 'spa': 118, 'spd': 90, 'spe': 64},
                     'abilities': {'0': 'Stamina', 'H': 'Power of Alchemy'},
                     'heightm': 0.8,
                     'weightkg': 11.5,
                     'color': 'Purple',
                     'eggGroups': ['Amorphous'],
                     'otherFormes': ['Venomicon-Epilogue'],
                     'formeOrder': ['Venomicon', 'Venomicon-Epilogue'],
                     'gen': 8},
    'Venomiconepilogue': {   'num': -66,
                             'name': 'Venomicon-Epilogue',
                             'baseSpecies': 'Venomicon',
                             'forme': 'Epilogue',
                             'types': ['Poison', 'Flying'],
                             'gender': 'N',
                             'baseStats': {'hp': 85, 'atk': 102, 'def': 85, 'spa': 62, 'spd': 85, 'spe': 101},
                             'abilities': {'0': 'Tinted Lens'},
                             'heightm': 0.8,
                             'weightkg': 12.4,
                             'color': 'Purple',
                             'eggGroups': ['Amorphous'],
                             'requiredItem': 'Vile Vial',
                             'changesFrom': 'Venomicon',
                             'gen': 8},
    'Saharascal': {   'num': -67,
                      'name': 'Saharascal',
                      'types': ['Ground'],
                      'baseStats': {'hp': 50, 'atk': 80, 'def': 65, 'spa': 45, 'spd': 90, 'spe': 70},
                      'abilities': {'0': 'Water Absorb', '1': 'Pickpocket', 'H': 'Sand Spit'},
                      'heightm': 1.2,
                      'weightkg': 48,
                      'color': 'Brown',
                      'evos': ['Saharaja'],
                      'eggGroups': ['Field'],
                      'gen': 8},
    'Saharaja': {   'num': -68,
                    'name': 'Saharaja',
                    'types': ['Ground'],
                    'baseStats': {'hp': 70, 'atk': 112, 'def': 105, 'spa': 65, 'spd': 123, 'spe': 78},
                    'abilities': {'0': 'Water Absorb', '1': 'Serene Grace', 'H': 'Sand Spit'},
                    'heightm': 2.3,
                    'weightkg': 303.9,
                    'color': 'White',
                    'prevo': 'Saharascal',
                    'evoType': 'useItem',
                    'evoItem': 'Shiny Stone',
                    'eggGroups': ['Field'],
                    'gen': 8},
    'Ababo': {   'num': -69,
                 'name': 'Ababo',
                 'types': ['Fairy'],
                 'genderRatio': {'M': 0.75, 'F': 0.25},
                 'baseStats': {'hp': 42, 'atk': 35, 'def': 27, 'spa': 35, 'spd': 35, 'spe': 38},
                 'abilities': {'0': 'Pixilate', '1': 'Rattled', 'H': 'Own Tempo'},
                 'heightm': 0.5,
                 'weightkg': 3.5,
                 'color': 'White',
                 'evos': ['Scattervein'],
                 'eggGroups': ['Undiscovered'],
                 'canHatch': True,
                 'gen': 9},
    'Scattervein': {   'num': -70,
                       'name': 'Scattervein',
                       'types': ['Fairy'],
                       'genderRatio': {'M': 0.75, 'F': 0.25},
                       'baseStats': {'hp': 75, 'atk': 74, 'def': 87, 'spa': 62, 'spd': 89, 'spe': 63},
                       'abilities': {'0': 'Pixilate', '1': 'Intimidate', 'H': 'Own Tempo'},
                       'heightm': 1.5,
                       'weightkg': 25,
                       'color': 'Pink',
                       'prevo': 'Ababo',
                       'evoType': 'levelFriendship',
                       'evos': ['Hemogoblin'],
                       'eggGroups': ['Monster', 'Fairy'],
                       'canHatch': True,
                       'gen': 9},
    'Hemogoblin': {   'num': -71,
                      'name': 'Hemogoblin',
                      'types': ['Fairy', 'Fire'],
                      'genderRatio': {'M': 0.75, 'F': 0.25},
                      'baseStats': {'hp': 90, 'atk': 96, 'def': 87, 'spa': 96, 'spd': 89, 'spe': 55},
                      'abilities': {'0': 'Pixilate', '1': 'Intimidate', 'H': 'Own Tempo'},
                      'heightm': 1.4,
                      'weightkg': 85,
                      'color': 'Pink',
                      'prevo': 'Scattervein',
                      'evoType': 'useItem',
                      'evoItem': 'Fire Stone',
                      'eggGroups': ['Monster', 'Fairy'],
                      'gen': 9},
    'Cresceidon': {   'num': -72,
                      'name': 'Cresceidon',
                      'types': ['Water', 'Fairy'],
                      'baseStats': {'hp': 80, 'atk': 32, 'def': 111, 'spa': 88, 'spd': 99, 'spe': 124},
                      'abilities': {'0': 'Multiscale', '1': 'Rough Skin', 'H': 'Water Veil'},
                      'heightm': 10,
                      'weightkg': 999.9,
                      'color': 'Blue',
                      'eggGroups': ['Amorphous', 'Water 3'],
                      'gen': 9},
    'Chuggalong': {   'num': -75,
                      'name': 'Chuggalong',
                      'types': ['Dragon', 'Poison'],
                      'baseStats': {'hp': 45, 'atk': 43, 'def': 117, 'spa': 120, 'spd': 110, 'spe': 115},
                      'abilities': {'0': 'Armor Tail'},
                      'heightm': 6.2,
                      'weightkg': 201.6,
                      'color': 'Black',
                      'eggGroups': ['Undiscovered'],
                      'gen': 9},
    'Pokestarsmeargle': {   'num': -5000,
                            'name': 'Pokestar Smeargle',
                            'types': ['Normal'],
                            'baseStats': {'hp': 55, 'atk': 20, 'def': 35, 'spa': 20, 'spd': 45, 'spe': 75},
                            'abilities': {'0': 'Own Tempo', '1': 'Technician', 'H': 'Moody'},
                            'heightm': 1.5,
                            'weightkg': 61,
                            'color': 'White',
                            'eggGroups': ['Field'],
                            'gen': 5},
    'Pokestarufo': {   'num': -5001,
                       'name': 'Pokestar UFO',
                       'types': ['Flying', 'Electric'],
                       'gender': 'N',
                       'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                       'abilities': {'0': 'Levitate'},
                       'heightm': 1.5,
                       'weightkg': 61,
                       'color': 'White',
                       'eggGroups': ['Undiscovered'],
                       'otherFormes': ['Pokestar UFO-2', 'Pokestar UFO-PropU2'],
                       'cosmeticFormes': ['Pokestar UFO-PropU1'],
                       'gen': 5},
    'Pokestarufo2': {   'num': -5001,
                        'name': 'Pokestar UFO-2',
                        'baseSpecies': 'Pokestar UFO',
                        'forme': '2',
                        'types': ['Psychic', 'Electric'],
                        'gender': 'N',
                        'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                        'abilities': {'0': 'Levitate'},
                        'heightm': 1.5,
                        'weightkg': 61,
                        'color': 'White',
                        'eggGroups': ['Undiscovered'],
                        'gen': 5},
    'Pokestarbrycenman': {   'num': -5002,
                             'name': 'Pokestar Brycen-Man',
                             'types': ['Dark', 'Psychic'],
                             'gender': 'M',
                             'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                             'abilities': {'0': 'Levitate'},
                             'heightm': 1.5,
                             'weightkg': 61,
                             'color': 'White',
                             'eggGroups': ['Undiscovered'],
                             'cosmeticFormes': ['Pokestar Brycen-Man-Prop'],
                             'gen': 5},
    'Pokestarmt': {   'num': -5003,
                      'name': 'Pokestar MT',
                      'types': ['Steel'],
                      'gender': 'N',
                      'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                      'abilities': {'0': 'Analytic'},
                      'heightm': 1.5,
                      'weightkg': 61,
                      'color': 'White',
                      'eggGroups': ['Undiscovered'],
                      'cosmeticFormes': ['Pokestar MT-Prop'],
                      'gen': 5},
    'Pokestarmt2': {   'num': -5004,
                       'name': 'Pokestar MT2',
                       'types': ['Steel', 'Electric'],
                       'gender': 'N',
                       'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                       'abilities': {'0': 'Flash Fire'},
                       'heightm': 1.5,
                       'weightkg': 61,
                       'color': 'White',
                       'eggGroups': ['Undiscovered'],
                       'cosmeticFormes': ['Pokestar MT2-Prop'],
                       'gen': 5},
    'Pokestartransport': {   'num': -5005,
                             'name': 'Pokestar Transport',
                             'types': ['Steel'],
                             'gender': 'N',
                             'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                             'abilities': {'0': 'Motor Drive'},
                             'heightm': 1.5,
                             'weightkg': 61,
                             'color': 'White',
                             'eggGroups': ['Undiscovered'],
                             'cosmeticFormes': ['Pokestar Transport-Prop'],
                             'gen': 5},
    'Pokestargiant': {   'num': -5006,
                         'name': 'Pokestar Giant',
                         'types': ['Normal'],
                         'gender': 'F',
                         'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                         'abilities': {'0': 'Huge Power'},
                         'heightm': 1.5,
                         'weightkg': 61,
                         'color': 'White',
                         'eggGroups': ['Undiscovered'],
                         'cosmeticFormes': ['Pokestar Giant-2', 'Pokestar Giant-PropO1', 'Pokestar Giant-PropO2'],
                         'gen': 5},
    'Pokestarhumanoid': {   'num': -5007,
                            'name': 'Pokestar Humanoid',
                            'types': ['Normal'],
                            'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                            'abilities': {'0': 'Insomnia'},
                            'heightm': 1.5,
                            'weightkg': 61,
                            'color': 'White',
                            'eggGroups': ['Undiscovered'],
                            'cosmeticFormes': ['Pokestar Humanoid-Prop'],
                            'gen': 5},
    'Pokestarmonster': {   'num': -5008,
                           'name': 'Pokestar Monster',
                           'types': ['Dark'],
                           'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                           'abilities': {'0': 'Pressure'},
                           'heightm': 1.5,
                           'weightkg': 61,
                           'color': 'White',
                           'eggGroups': ['Undiscovered'],
                           'cosmeticFormes': ['Pokestar Monster-Prop'],
                           'gen': 5},
    'Pokestarf00': {   'num': -5009,
                       'name': 'Pokestar F-00',
                       'types': ['Steel', 'Normal'],
                       'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                       'abilities': {'0': 'Volt Absorb'},
                       'heightm': 1.5,
                       'weightkg': 61,
                       'color': 'White',
                       'eggGroups': ['Undiscovered'],
                       'cosmeticFormes': ['Pokestar F-00-Prop'],
                       'gen': 5},
    'Pokestarf002': {   'num': -5010,
                        'name': 'Pokestar F-002',
                        'types': ['Steel', 'Normal'],
                        'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                        'abilities': {'0': 'Reckless'},
                        'heightm': 1.5,
                        'weightkg': 61,
                        'color': 'White',
                        'eggGroups': ['Undiscovered'],
                        'cosmeticFormes': ['Pokestar F-002-Prop'],
                        'gen': 5},
    'Pokestarspirit': {   'num': -5011,
                          'name': 'Pokestar Spirit',
                          'types': ['Dark', 'Ghost'],
                          'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                          'abilities': {'0': 'Wonder Guard'},
                          'heightm': 1.5,
                          'weightkg': 61,
                          'color': 'White',
                          'eggGroups': ['Undiscovered'],
                          'cosmeticFormes': ['Pokestar Spirit-Prop'],
                          'gen': 5},
    'Pokestarblackdoor': {   'num': -5012,
                             'name': 'Pokestar Black Door',
                             'types': ['Grass'],
                             'gender': 'F',
                             'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                             'abilities': {'0': 'Early Bird'},
                             'heightm': 1.5,
                             'weightkg': 61,
                             'color': 'White',
                             'eggGroups': ['Undiscovered'],
                             'cosmeticFormes': ['Pokestar Black Door-Prop'],
                             'gen': 5},
    'Pokestarwhitedoor': {   'num': -5013,
                             'name': 'Pokestar White Door',
                             'types': ['Fire'],
                             'gender': 'M',
                             'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                             'abilities': {'0': 'Blaze'},
                             'heightm': 1.5,
                             'weightkg': 61,
                             'color': 'White',
                             'eggGroups': ['Undiscovered'],
                             'cosmeticFormes': ['Pokestar White Door-Prop'],
                             'gen': 5},
    'Pokestarblackbelt': {   'num': -5014,
                             'name': 'Pokestar Black Belt',
                             'types': ['Fighting'],
                             'gender': 'M',
                             'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                             'abilities': {'0': 'Huge Power'},
                             'heightm': 1.5,
                             'weightkg': 61,
                             'color': 'White',
                             'eggGroups': ['Undiscovered'],
                             'cosmeticFormes': ['Pokestar Black Belt-Prop'],
                             'gen': 5},
    'Pokestarufopropu2': {   'num': -5001,
                             'name': 'Pokestar UFO-PropU2',
                             'baseSpecies': 'Pokestar UFO',
                             'forme': 'PropU2',
                             'types': ['Psychic', 'Electric'],
                             'gender': 'N',
                             'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                             'abilities': {'0': 'Levitate'},
                             'heightm': 1.5,
                             'weightkg': 61,
                             'color': 'White',
                             'eggGroups': ['Undiscovered'],
                             'gen': 5}}
