"""Pokédex entries for Hoenn region."""

from ..functions.pokedex_funcs import *

pokedex = {
	"Treecko": {
		"num": 252,
		"name": "Treecko",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 40, "atk": 45, "def": 35, "spa": 65, "spd": 55, "spe": 70},
		"abilities": {"0": "Overgrow", "H": "Unburden"},
		"heightm": 0.5,
		"weightkg": 5,
		"color": "Green",
		"evos": ["Grovyle"],
		"eggGroups": ["Monster", "Dragon"],
	},
	"Grovyle": {
		"num": 253,
		"name": "Grovyle",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 50, "atk": 65, "def": 45, "spa": 85, "spd": 65, "spe": 95},
		"abilities": {"0": "Overgrow", "H": "Unburden"},
		"heightm": 0.9,
		"weightkg": 21.6,
		"color": "Green",
		"prevo": "Treecko",
		"evoLevel": 16,
		"evos": ["Sceptile"],
		"eggGroups": ["Monster", "Dragon"],
	},
	"Sceptile": {
		"num": 254,
		"name": "Sceptile",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 70, "atk": 85, "def": 65, "spa": 105, "spd": 85, "spe": 120},
		"abilities": {"0": "Overgrow", "H": "Unburden"},
		"heightm": 1.7,
		"weightkg": 52.2,
		"color": "Green",
		"prevo": "Grovyle",
		"evoLevel": 36,
		"eggGroups": ["Monster", "Dragon"],
		"otherFormes": ["Sceptile-Mega"],
		"formeOrder": ["Sceptile", "Sceptile-Mega"],
	},
	"Sceptilemega": {
		"num": 254,
		"name": "Sceptile-Mega",
		"baseSpecies": "Sceptile",
		"forme": "Mega",
		"types": ["Grass", "Dragon"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 70, "atk": 110, "def": 75, "spa": 145, "spd": 85, "spe": 145},
		"abilities": {"0": "Lightning Rod"},
		"heightm": 1.9,
		"weightkg": 55.2,
		"color": "Green",
		"eggGroups": ["Monster", "Dragon"],
		"requiredItem": "Sceptilite",
	},
	"Torchic": {
		"num": 255,
		"name": "Torchic",
		"types": ["Fire"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 45, "atk": 60, "def": 40, "spa": 70, "spd": 50, "spe": 45},
		"abilities": {"0": "Blaze", "H": "Speed Boost"},
		"heightm": 0.4,
		"weightkg": 2.5,
		"color": "Red",
		"evos": ["Combusken"],
		"eggGroups": ["Field"],
	},
	"Combusken": {
		"num": 256,
		"name": "Combusken",
		"types": ["Fire", "Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 60, "atk": 85, "def": 60, "spa": 85, "spd": 60, "spe": 55},
		"abilities": {"0": "Blaze", "H": "Speed Boost"},
		"heightm": 0.9,
		"weightkg": 19.5,
		"color": "Red",
		"prevo": "Torchic",
		"evoLevel": 16,
		"evos": ["Blaziken"],
		"eggGroups": ["Field"],
	},
	"Blaziken": {
		"num": 257,
		"name": "Blaziken",
		"types": ["Fire", "Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 80, "atk": 120, "def": 70, "spa": 110, "spd": 70, "spe": 80},
		"abilities": {"0": "Blaze", "H": "Speed Boost"},
		"heightm": 1.9,
		"weightkg": 52,
		"color": "Red",
		"prevo": "Combusken",
		"evoLevel": 36,
		"eggGroups": ["Field"],
		"otherFormes": ["Blaziken-Mega"],
		"formeOrder": ["Blaziken", "Blaziken-Mega"],
	},
	"Blazikenmega": {
		"num": 257,
		"name": "Blaziken-Mega",
		"baseSpecies": "Blaziken",
		"forme": "Mega",
		"types": ["Fire", "Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 80, "atk": 160, "def": 80, "spa": 130, "spd": 80, "spe": 100},
		"abilities": {"0": "Speed Boost"},
		"heightm": 1.9,
		"weightkg": 52,
		"color": "Red",
		"eggGroups": ["Field"],
		"requiredItem": "Blazikenite",
	},
	"Mudkip": {
		"num": 258,
		"name": "Mudkip",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 50, "atk": 70, "def": 50, "spa": 50, "spd": 50, "spe": 40},
		"abilities": {"0": "Torrent", "H": "Damp"},
		"heightm": 0.4,
		"weightkg": 7.6,
		"color": "Blue",
		"evos": ["Marshtomp"],
		"eggGroups": ["Monster", "Water 1"],
	},
	"Marshtomp": {
		"num": 259,
		"name": "Marshtomp",
		"types": ["Water", "Ground"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 70, "atk": 85, "def": 70, "spa": 60, "spd": 70, "spe": 50},
		"abilities": {"0": "Torrent", "H": "Damp"},
		"heightm": 0.7,
		"weightkg": 28,
		"color": "Blue",
		"prevo": "Mudkip",
		"evoLevel": 16,
		"evos": ["Swampert"],
		"eggGroups": ["Monster", "Water 1"],
	},
	"Swampert": {
		"num": 260,
		"name": "Swampert",
		"types": ["Water", "Ground"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 100, "atk": 110, "def": 90, "spa": 85, "spd": 90, "spe": 60},
		"abilities": {"0": "Torrent", "H": "Damp"},
		"heightm": 1.5,
		"weightkg": 81.9,
		"color": "Blue",
		"prevo": "Marshtomp",
		"evoLevel": 36,
		"eggGroups": ["Monster", "Water 1"],
		"otherFormes": ["Swampert-Mega"],
		"formeOrder": ["Swampert", "Swampert-Mega"],
	},
	"Swampertmega": {
		"num": 260,
		"name": "Swampert-Mega",
		"baseSpecies": "Swampert",
		"forme": "Mega",
		"types": ["Water", "Ground"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 100, "atk": 150, "def": 110, "spa": 95, "spd": 110, "spe": 70},
		"abilities": {"0": "Swift Swim"},
		"heightm": 1.9,
		"weightkg": 102,
		"color": "Blue",
		"eggGroups": ["Monster", "Water 1"],
		"requiredItem": "Swampertite",
	},
	"Poochyena": {
		"num": 261,
		"name": "Poochyena",
		"types": ["Dark"],
		"baseStats": {"hp": 35, "atk": 55, "def": 35, "spa": 30, "spd": 30, "spe": 35},
		"abilities": {"0": "Run Away", "1": "Quick Feet", "H": "Rattled"},
		"heightm": 0.5,
		"weightkg": 13.6,
		"color": "Gray",
		"evos": ["Mightyena"],
		"eggGroups": ["Field"],
	},
	"Mightyena": {
		"num": 262,
		"name": "Mightyena",
		"types": ["Dark"],
		"baseStats": {"hp": 70, "atk": 90, "def": 70, "spa": 60, "spd": 60, "spe": 70},
		"abilities": {"0": "Intimidate", "1": "Quick Feet", "H": "Moxie"},
		"heightm": 1,
		"weightkg": 37,
		"color": "Gray",
		"prevo": "Poochyena",
		"evoLevel": 18,
		"eggGroups": ["Field"],
	},
	"Zigzagoon": {
		"num": 263,
		"name": "Zigzagoon",
		"types": ["Normal"],
		"baseStats": {"hp": 38, "atk": 30, "def": 41, "spa": 30, "spd": 41, "spe": 60},
		"abilities": {"0": "Pickup", "1": "Gluttony", "H": "Quick Feet"},
		"heightm": 0.4,
		"weightkg": 17.5,
		"color": "Brown",
		"evos": ["Linoone"],
		"eggGroups": ["Field"],
		"otherFormes": ["Zigzagoon-Galar"],
		"formeOrder": ["Zigzagoon", "Zigzagoon-Galar"],
	},
	"Zigzagoongalar": {
		"num": 263,
		"name": "Zigzagoon-Galar",
		"baseSpecies": "Zigzagoon",
		"forme": "Galar",
		"types": ["Dark", "Normal"],
		"baseStats": {"hp": 38, "atk": 30, "def": 41, "spa": 30, "spd": 41, "spe": 60},
		"abilities": {"0": "Pickup", "1": "Gluttony", "H": "Quick Feet"},
		"heightm": 0.4,
		"weightkg": 17.5,
		"color": "White",
		"evos": ["Linoone-Galar"],
		"eggGroups": ["Field"],
	},
	"Linoone": {
		"num": 264,
		"name": "Linoone",
		"types": ["Normal"],
		"baseStats": {"hp": 78, "atk": 70, "def": 61, "spa": 50, "spd": 61, "spe": 100},
		"abilities": {"0": "Pickup", "1": "Gluttony", "H": "Quick Feet"},
		"heightm": 0.5,
		"weightkg": 32.5,
		"color": "White",
		"prevo": "Zigzagoon",
		"evoLevel": 20,
		"eggGroups": ["Field"],
		"otherFormes": ["Linoone-Galar"],
		"formeOrder": ["Linoone", "Linoone-Galar"],
	},
	"Linoonegalar": {
		"num": 264,
		"name": "Linoone-Galar",
		"baseSpecies": "Linoone",
		"forme": "Galar",
		"types": ["Dark", "Normal"],
		"baseStats": {"hp": 78, "atk": 70, "def": 61, "spa": 50, "spd": 61, "spe": 100},
		"abilities": {"0": "Pickup", "1": "Gluttony", "H": "Quick Feet"},
		"heightm": 0.5,
		"weightkg": 32.5,
		"color": "White",
		"prevo": "Zigzagoon-Galar",
		"evoLevel": 20,
		"evos": ["Obstagoon"],
		"eggGroups": ["Field"],
	},
	"Wurmple": {
		"num": 265,
		"name": "Wurmple",
		"types": ["Bug"],
		"baseStats": {"hp": 45, "atk": 45, "def": 35, "spa": 20, "spd": 30, "spe": 20},
		"abilities": {"0": "Shield Dust", "H": "Run Away"},
		"heightm": 0.3,
		"weightkg": 3.6,
		"color": "Red",
		"evos": ["Silcoon", "Cascoon"],
		"eggGroups": ["Bug"],
	},
	"Silcoon": {
		"num": 266,
		"name": "Silcoon",
		"types": ["Bug"],
		"baseStats": {"hp": 50, "atk": 35, "def": 55, "spa": 25, "spd": 25, "spe": 15},
		"abilities": {"0": "Shed Skin"},
		"heightm": 0.6,
		"weightkg": 10,
		"color": "White",
		"prevo": "Wurmple",
		"evoLevel": 7,
		"evos": ["Beautifly"],
		"eggGroups": ["Bug"],
	},
	"Beautifly": {
		"num": 267,
		"name": "Beautifly",
		"types": ["Bug", "Flying"],
		"baseStats": {"hp": 60, "atk": 70, "def": 50, "spa": 100, "spd": 50, "spe": 65},
		"abilities": {"0": "Swarm", "H": "Rivalry"},
		"heightm": 1,
		"weightkg": 28.4,
		"color": "Yellow",
		"prevo": "Silcoon",
		"evoLevel": 10,
		"eggGroups": ["Bug"],
	},
	"Cascoon": {
		"num": 268,
		"name": "Cascoon",
		"types": ["Bug"],
		"baseStats": {"hp": 50, "atk": 35, "def": 55, "spa": 25, "spd": 25, "spe": 15},
		"abilities": {"0": "Shed Skin"},
		"heightm": 0.7,
		"weightkg": 11.5,
		"color": "Purple",
		"prevo": "Wurmple",
		"evoLevel": 7,
		"evos": ["Dustox"],
		"eggGroups": ["Bug"],
	},
	"Dustox": {
		"num": 269,
		"name": "Dustox",
		"types": ["Bug", "Poison"],
		"baseStats": {"hp": 60, "atk": 50, "def": 70, "spa": 50, "spd": 90, "spe": 65},
		"abilities": {"0": "Shield Dust", "H": "Compound Eyes"},
		"heightm": 1.2,
		"weightkg": 31.6,
		"color": "Green",
		"prevo": "Cascoon",
		"evoLevel": 10,
		"eggGroups": ["Bug"],
	},
	"Lotad": {
		"num": 270,
		"name": "Lotad",
		"types": ["Water", "Grass"],
		"baseStats": {"hp": 40, "atk": 30, "def": 30, "spa": 40, "spd": 50, "spe": 30},
		"abilities": {"0": "Swift Swim", "1": "Rain Dish", "H": "Own Tempo"},
		"heightm": 0.5,
		"weightkg": 2.6,
		"color": "Green",
		"evos": ["Lombre"],
		"eggGroups": ["Water 1", "Grass"],
	},
	"Lombre": {
		"num": 271,
		"name": "Lombre",
		"types": ["Water", "Grass"],
		"baseStats": {"hp": 60, "atk": 50, "def": 50, "spa": 60, "spd": 70, "spe": 50},
		"abilities": {"0": "Swift Swim", "1": "Rain Dish", "H": "Own Tempo"},
		"heightm": 1.2,
		"weightkg": 32.5,
		"color": "Green",
		"prevo": "Lotad",
		"evoLevel": 14,
		"evos": ["Ludicolo"],
		"eggGroups": ["Water 1", "Grass"],
	},
	"Ludicolo": {
		"num": 272,
		"name": "Ludicolo",
		"types": ["Water", "Grass"],
		"baseStats": {"hp": 80, "atk": 70, "def": 70, "spa": 90, "spd": 100, "spe": 70},
		"abilities": {"0": "Swift Swim", "1": "Rain Dish", "H": "Own Tempo"},
		"heightm": 1.5,
		"weightkg": 55,
		"color": "Green",
		"prevo": "Lombre",
		"evoType": "useItem",
		"evoItem": "Water Stone",
		"eggGroups": ["Water 1", "Grass"],
	},
	"Seedot": {
		"num": 273,
		"name": "Seedot",
		"types": ["Grass"],
		"baseStats": {"hp": 40, "atk": 40, "def": 50, "spa": 30, "spd": 30, "spe": 30},
		"abilities": {"0": "Chlorophyll", "1": "Early Bird", "H": "Pickpocket"},
		"heightm": 0.5,
		"weightkg": 4,
		"color": "Brown",
		"evos": ["Nuzleaf"],
		"eggGroups": ["Field", "Grass"],
	},
	"Nuzleaf": {
		"num": 274,
		"name": "Nuzleaf",
		"types": ["Grass", "Dark"],
		"baseStats": {"hp": 70, "atk": 70, "def": 40, "spa": 60, "spd": 40, "spe": 60},
		"abilities": {"0": "Chlorophyll", "1": "Early Bird", "H": "Pickpocket"},
		"heightm": 1,
		"weightkg": 28,
		"color": "Brown",
		"prevo": "Seedot",
		"evoLevel": 14,
		"evos": ["Shiftry"],
		"eggGroups": ["Field", "Grass"],
	},
	"Shiftry": {
		"num": 275,
		"name": "Shiftry",
		"types": ["Grass", "Dark"],
		"baseStats": {"hp": 90, "atk": 100, "def": 60, "spa": 90, "spd": 60, "spe": 80},
		"abilities": {"0": "Chlorophyll", "1": "Wind Rider", "H": "Pickpocket"},
		"heightm": 1.3,
		"weightkg": 59.6,
		"color": "Brown",
		"prevo": "Nuzleaf",
		"evoType": "useItem",
		"evoItem": "Leaf Stone",
		"eggGroups": ["Field", "Grass"],
	},
	"Taillow": {
		"num": 276,
		"name": "Taillow",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 40, "atk": 55, "def": 30, "spa": 30, "spd": 30, "spe": 85},
		"abilities": {"0": "Guts", "H": "Scrappy"},
		"heightm": 0.3,
		"weightkg": 2.3,
		"color": "Blue",
		"evos": ["Swellow"],
		"eggGroups": ["Flying"],
	},
	"Swellow": {
		"num": 277,
		"name": "Swellow",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 60, "atk": 85, "def": 60, "spa": 75, "spd": 50, "spe": 125},
		"abilities": {"0": "Guts", "H": "Scrappy"},
		"heightm": 0.7,
		"weightkg": 19.8,
		"color": "Blue",
		"prevo": "Taillow",
		"evoLevel": 22,
		"eggGroups": ["Flying"],
	},
	"Wingull": {
		"num": 278,
		"name": "Wingull",
		"types": ["Water", "Flying"],
		"baseStats": {"hp": 40, "atk": 30, "def": 30, "spa": 55, "spd": 30, "spe": 85},
		"abilities": {"0": "Keen Eye", "1": "Hydration", "H": "Rain Dish"},
		"heightm": 0.6,
		"weightkg": 9.5,
		"color": "White",
		"evos": ["Pelipper"],
		"eggGroups": ["Water 1", "Flying"],
	},
	"Pelipper": {
		"num": 279,
		"name": "Pelipper",
		"types": ["Water", "Flying"],
		"baseStats": {"hp": 60, "atk": 50, "def": 100, "spa": 95, "spd": 70, "spe": 65},
		"abilities": {"0": "Keen Eye", "1": "Drizzle", "H": "Rain Dish"},
		"heightm": 1.2,
		"weightkg": 28,
		"color": "Yellow",
		"prevo": "Wingull",
		"evoLevel": 25,
		"eggGroups": ["Water 1", "Flying"],
	},
	"Ralts": {
		"num": 280,
		"name": "Ralts",
		"types": ["Psychic", "Fairy"],
		"baseStats": {"hp": 28, "atk": 25, "def": 25, "spa": 45, "spd": 35, "spe": 40},
		"abilities": {"0": "Synchronize", "1": "Trace", "H": "Telepathy"},
		"heightm": 0.4,
		"weightkg": 6.6,
		"color": "White",
		"evos": ["Kirlia"],
		"eggGroups": ["Human-Like", "Amorphous"],
	},
	"Kirlia": {
		"num": 281,
		"name": "Kirlia",
		"types": ["Psychic", "Fairy"],
		"baseStats": {"hp": 38, "atk": 35, "def": 35, "spa": 65, "spd": 55, "spe": 50},
		"abilities": {"0": "Synchronize", "1": "Trace", "H": "Telepathy"},
		"heightm": 0.8,
		"weightkg": 20.2,
		"color": "White",
		"prevo": "Ralts",
		"evoLevel": 20,
		"evos": ["Gardevoir", "Gallade"],
		"eggGroups": ["Human-Like", "Amorphous"],
	},
	"Gardevoir": {
		"num": 282,
		"name": "Gardevoir",
		"types": ["Psychic", "Fairy"],
		"baseStats": {"hp": 68, "atk": 65, "def": 65, "spa": 125, "spd": 115, "spe": 80},
		"abilities": {"0": "Synchronize", "1": "Trace", "H": "Telepathy"},
		"heightm": 1.6,
		"weightkg": 48.4,
		"color": "White",
		"prevo": "Kirlia",
		"evoLevel": 30,
		"eggGroups": ["Human-Like", "Amorphous"],
		"otherFormes": ["Gardevoir-Mega"],
		"formeOrder": ["Gardevoir", "Gardevoir-Mega"],
	},
	"Gardevoirmega": {
		"num": 282,
		"name": "Gardevoir-Mega",
		"baseSpecies": "Gardevoir",
		"forme": "Mega",
		"types": ["Psychic", "Fairy"],
		"baseStats": {"hp": 68, "atk": 85, "def": 65, "spa": 165, "spd": 135, "spe": 100},
		"abilities": {"0": "Pixilate"},
		"heightm": 1.6,
		"weightkg": 48.4,
		"color": "White",
		"eggGroups": ["Amorphous"],
		"requiredItem": "Gardevoirite",
	},
	"Surskit": {
		"num": 283,
		"name": "Surskit",
		"types": ["Bug", "Water"],
		"baseStats": {"hp": 40, "atk": 30, "def": 32, "spa": 50, "spd": 52, "spe": 65},
		"abilities": {"0": "Swift Swim", "H": "Rain Dish"},
		"heightm": 0.5,
		"weightkg": 1.7,
		"color": "Blue",
		"evos": ["Masquerain"],
		"eggGroups": ["Water 1", "Bug"],
	},
	"Masquerain": {
		"num": 284,
		"name": "Masquerain",
		"types": ["Bug", "Flying"],
		"baseStats": {"hp": 70, "atk": 60, "def": 62, "spa": 100, "spd": 82, "spe": 80},
		"abilities": {"0": "Intimidate", "H": "Unnerve"},
		"heightm": 0.8,
		"weightkg": 3.6,
		"color": "Blue",
		"prevo": "Surskit",
		"evoLevel": 22,
		"eggGroups": ["Water 1", "Bug"],
	},
	"Shroomish": {
		"num": 285,
		"name": "Shroomish",
		"types": ["Grass"],
		"baseStats": {"hp": 60, "atk": 40, "def": 60, "spa": 40, "spd": 60, "spe": 35},
		"abilities": {"0": "Effect Spore", "1": "Poison Heal", "H": "Quick Feet"},
		"heightm": 0.4,
		"weightkg": 4.5,
		"color": "Brown",
		"evos": ["Breloom"],
		"eggGroups": ["Fairy", "Grass"],
	},
	"Breloom": {
		"num": 286,
		"name": "Breloom",
		"types": ["Grass", "Fighting"],
		"baseStats": {"hp": 60, "atk": 130, "def": 80, "spa": 60, "spd": 60, "spe": 70},
		"abilities": {"0": "Effect Spore", "1": "Poison Heal", "H": "Technician"},
		"heightm": 1.2,
		"weightkg": 39.2,
		"color": "Green",
		"prevo": "Shroomish",
		"evoLevel": 23,
		"eggGroups": ["Fairy", "Grass"],
	},
	"Slakoth": {
		"num": 287,
		"name": "Slakoth",
		"types": ["Normal"],
		"baseStats": {"hp": 60, "atk": 60, "def": 60, "spa": 35, "spd": 35, "spe": 30},
		"abilities": {"0": "Truant"},
		"heightm": 0.8,
		"weightkg": 24,
		"color": "Brown",
		"evos": ["Vigoroth"],
		"eggGroups": ["Field"],
	},
	"Vigoroth": {
		"num": 288,
		"name": "Vigoroth",
		"types": ["Normal"],
		"baseStats": {"hp": 80, "atk": 80, "def": 80, "spa": 55, "spd": 55, "spe": 90},
		"abilities": {"0": "Vital Spirit"},
		"heightm": 1.4,
		"weightkg": 46.5,
		"color": "White",
		"prevo": "Slakoth",
		"evoLevel": 18,
		"evos": ["Slaking"],
		"eggGroups": ["Field"],
	},
	"Slaking": {
		"num": 289,
		"name": "Slaking",
		"types": ["Normal"],
		"baseStats": {"hp": 150, "atk": 160, "def": 100, "spa": 95, "spd": 65, "spe": 100},
		"abilities": {"0": "Truant"},
		"heightm": 2,
		"weightkg": 130.5,
		"color": "Brown",
		"prevo": "Vigoroth",
		"evoLevel": 36,
		"eggGroups": ["Field"],
	},
	"Nincada": {
		"num": 290,
		"name": "Nincada",
		"types": ["Bug", "Ground"],
		"baseStats": {"hp": 31, "atk": 45, "def": 90, "spa": 30, "spd": 30, "spe": 40},
		"abilities": {"0": "Compound Eyes", "H": "Run Away"},
		"heightm": 0.5,
		"weightkg": 5.5,
		"color": "Gray",
		"evos": ["Ninjask", "Shedinja"],
		"eggGroups": ["Bug"],
	},
	"Ninjask": {
		"num": 291,
		"name": "Ninjask",
		"types": ["Bug", "Flying"],
		"baseStats": {"hp": 61, "atk": 90, "def": 45, "spa": 50, "spd": 50, "spe": 160},
		"abilities": {"0": "Speed Boost", "H": "Infiltrator"},
		"heightm": 0.8,
		"weightkg": 12,
		"color": "Yellow",
		"prevo": "Nincada",
		"evoLevel": 20,
		"eggGroups": ["Bug"],
	},
	"Shedinja": {
		"num": 292,
		"name": "Shedinja",
		"types": ["Bug", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 1, "atk": 90, "def": 45, "spa": 30, "spd": 30, "spe": 40},
		"maxHP": 1,
		"abilities": {"0": "Wonder Guard"},
		"heightm": 0.8,
		"weightkg": 1.2,
		"color": "Brown",
		"prevo": "Nincada",
		"evoLevel": 20,
		"eggGroups": ["Mineral"],
	},
	"Whismur": {
		"num": 293,
		"name": "Whismur",
		"types": ["Normal"],
		"baseStats": {"hp": 64, "atk": 51, "def": 23, "spa": 51, "spd": 23, "spe": 28},
		"abilities": {"0": "Soundproof", "H": "Rattled"},
		"heightm": 0.6,
		"weightkg": 16.3,
		"color": "Pink",
		"evos": ["Loudred"],
		"eggGroups": ["Monster", "Field"],
	},
	"Loudred": {
		"num": 294,
		"name": "Loudred",
		"types": ["Normal"],
		"baseStats": {"hp": 84, "atk": 71, "def": 43, "spa": 71, "spd": 43, "spe": 48},
		"abilities": {"0": "Soundproof", "H": "Scrappy"},
		"heightm": 1,
		"weightkg": 40.5,
		"color": "Blue",
		"prevo": "Whismur",
		"evoLevel": 20,
		"evos": ["Exploud"],
		"eggGroups": ["Monster", "Field"],
	},
	"Exploud": {
		"num": 295,
		"name": "Exploud",
		"types": ["Normal"],
		"baseStats": {"hp": 104, "atk": 91, "def": 63, "spa": 91, "spd": 73, "spe": 68},
		"abilities": {"0": "Soundproof", "H": "Scrappy"},
		"heightm": 1.5,
		"weightkg": 84,
		"color": "Blue",
		"prevo": "Loudred",
		"evoLevel": 40,
		"eggGroups": ["Monster", "Field"],
	},
	"Makuhita": {
		"num": 296,
		"name": "Makuhita",
		"types": ["Fighting"],
		"genderRatio": {"M": 0.75, "F": 0.25},
		"baseStats": {"hp": 72, "atk": 60, "def": 30, "spa": 20, "spd": 30, "spe": 25},
		"abilities": {"0": "Thick Fat", "1": "Guts", "H": "Sheer Force"},
		"heightm": 1,
		"weightkg": 86.4,
		"color": "Yellow",
		"evos": ["Hariyama"],
		"eggGroups": ["Human-Like"],
	},
	"Hariyama": {
		"num": 297,
		"name": "Hariyama",
		"types": ["Fighting"],
		"genderRatio": {"M": 0.75, "F": 0.25},
		"baseStats": {"hp": 144, "atk": 120, "def": 60, "spa": 40, "spd": 60, "spe": 50},
		"abilities": {"0": "Thick Fat", "1": "Guts", "H": "Sheer Force"},
		"heightm": 2.3,
		"weightkg": 253.8,
		"color": "Brown",
		"prevo": "Makuhita",
		"evoLevel": 24,
		"eggGroups": ["Human-Like"],
	},
	"Azurill": {
		"num": 298,
		"name": "Azurill",
		"types": ["Normal", "Fairy"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 50, "atk": 20, "def": 40, "spa": 20, "spd": 40, "spe": 20},
		"abilities": {"0": "Thick Fat", "1": "Huge Power", "H": "Sap Sipper"},
		"heightm": 0.2,
		"weightkg": 2,
		"color": "Blue",
		"evos": ["Marill"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Nosepass": {
		"num": 299,
		"name": "Nosepass",
		"types": ["Rock"],
		"baseStats": {"hp": 30, "atk": 45, "def": 135, "spa": 45, "spd": 90, "spe": 30},
		"abilities": {"0": "Sturdy", "1": "Magnet Pull", "H": "Sand Force"},
		"heightm": 1,
		"weightkg": 97,
		"color": "Gray",
		"evos": ["Probopass"],
		"eggGroups": ["Mineral"],
	},
	"Skitty": {
		"num": 300,
		"name": "Skitty",
		"types": ["Normal"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 50, "atk": 45, "def": 45, "spa": 35, "spd": 35, "spe": 50},
		"abilities": {"0": "Cute Charm", "1": "Normalize", "H": "Wonder Skin"},
		"heightm": 0.6,
		"weightkg": 11,
		"color": "Pink",
		"evos": ["Delcatty"],
		"eggGroups": ["Field", "Fairy"],
	},
	"Delcatty": {
		"num": 301,
		"name": "Delcatty",
		"types": ["Normal"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 70, "atk": 65, "def": 65, "spa": 55, "spd": 55, "spe": 90},
		"abilities": {"0": "Cute Charm", "1": "Normalize", "H": "Wonder Skin"},
		"heightm": 1.1,
		"weightkg": 32.6,
		"color": "Purple",
		"prevo": "Skitty",
		"evoType": "useItem",
		"evoItem": "Moon Stone",
		"eggGroups": ["Field", "Fairy"],
	},
	"Sableye": {
		"num": 302,
		"name": "Sableye",
		"types": ["Dark", "Ghost"],
		"baseStats": {"hp": 50, "atk": 75, "def": 75, "spa": 65, "spd": 65, "spe": 50},
		"abilities": {"0": "Keen Eye", "1": "Stall", "H": "Prankster"},
		"heightm": 0.5,
		"weightkg": 11,
		"color": "Purple",
		"eggGroups": ["Human-Like"],
		"otherFormes": ["Sableye-Mega"],
		"formeOrder": ["Sableye", "Sableye-Mega"],
	},
	"Sableyemega": {
		"num": 302,
		"name": "Sableye-Mega",
		"baseSpecies": "Sableye",
		"forme": "Mega",
		"types": ["Dark", "Ghost"],
		"baseStats": {"hp": 50, "atk": 85, "def": 125, "spa": 85, "spd": 115, "spe": 20},
		"abilities": {"0": "Magic Bounce"},
		"heightm": 0.5,
		"weightkg": 161,
		"color": "Purple",
		"eggGroups": ["Human-Like"],
		"requiredItem": "Sablenite",
	},
	"Mawile": {
		"num": 303,
		"name": "Mawile",
		"types": ["Steel", "Fairy"],
		"baseStats": {"hp": 50, "atk": 85, "def": 85, "spa": 55, "spd": 55, "spe": 50},
		"abilities": {"0": "Hyper Cutter", "1": "Intimidate", "H": "Sheer Force"},
		"heightm": 0.6,
		"weightkg": 11.5,
		"color": "Black",
		"eggGroups": ["Field", "Fairy"],
		"otherFormes": ["Mawile-Mega"],
		"formeOrder": ["Mawile", "Mawile-Mega"],
	},
	"Mawilemega": {
		"num": 303,
		"name": "Mawile-Mega",
		"baseSpecies": "Mawile",
		"forme": "Mega",
		"types": ["Steel", "Fairy"],
		"baseStats": {"hp": 50, "atk": 105, "def": 125, "spa": 55, "spd": 95, "spe": 50},
		"abilities": {"0": "Huge Power"},
		"heightm": 1,
		"weightkg": 23.5,
		"color": "Black",
		"eggGroups": ["Field", "Fairy"],
		"requiredItem": "Mawilite",
	},
	"Aron": {
		"num": 304,
		"name": "Aron",
		"types": ["Steel", "Rock"],
		"baseStats": {"hp": 50, "atk": 70, "def": 100, "spa": 40, "spd": 40, "spe": 30},
		"abilities": {"0": "Sturdy", "1": "Rock Head", "H": "Heavy Metal"},
		"heightm": 0.4,
		"weightkg": 60,
		"color": "Gray",
		"evos": ["Lairon"],
		"eggGroups": ["Monster"],
	},
	"Lairon": {
		"num": 305,
		"name": "Lairon",
		"types": ["Steel", "Rock"],
		"baseStats": {"hp": 60, "atk": 90, "def": 140, "spa": 50, "spd": 50, "spe": 40},
		"abilities": {"0": "Sturdy", "1": "Rock Head", "H": "Heavy Metal"},
		"heightm": 0.9,
		"weightkg": 120,
		"color": "Gray",
		"prevo": "Aron",
		"evoLevel": 32,
		"evos": ["Aggron"],
		"eggGroups": ["Monster"],
	},
	"Aggron": {
		"num": 306,
		"name": "Aggron",
		"types": ["Steel", "Rock"],
		"baseStats": {"hp": 70, "atk": 110, "def": 180, "spa": 60, "spd": 60, "spe": 50},
		"abilities": {"0": "Sturdy", "1": "Rock Head", "H": "Heavy Metal"},
		"heightm": 2.1,
		"weightkg": 360,
		"color": "Gray",
		"prevo": "Lairon",
		"evoLevel": 42,
		"eggGroups": ["Monster"],
		"otherFormes": ["Aggron-Mega"],
		"formeOrder": ["Aggron", "Aggron-Mega"],
	},
	"Aggronmega": {
		"num": 306,
		"name": "Aggron-Mega",
		"baseSpecies": "Aggron",
		"forme": "Mega",
		"types": ["Steel"],
		"baseStats": {"hp": 70, "atk": 140, "def": 230, "spa": 60, "spd": 80, "spe": 50},
		"abilities": {"0": "Filter"},
		"heightm": 2.2,
		"weightkg": 395,
		"color": "Gray",
		"eggGroups": ["Monster"],
		"requiredItem": "Aggronite",
	},
	"Meditite": {
		"num": 307,
		"name": "Meditite",
		"types": ["Fighting", "Psychic"],
		"baseStats": {"hp": 30, "atk": 40, "def": 55, "spa": 40, "spd": 55, "spe": 60},
		"abilities": {"0": "Pure Power", "H": "Telepathy"},
		"heightm": 0.6,
		"weightkg": 11.2,
		"color": "Blue",
		"evos": ["Medicham"],
		"eggGroups": ["Human-Like"],
	},
	"Medicham": {
		"num": 308,
		"name": "Medicham",
		"types": ["Fighting", "Psychic"],
		"baseStats": {"hp": 60, "atk": 60, "def": 75, "spa": 60, "spd": 75, "spe": 80},
		"abilities": {"0": "Pure Power", "H": "Telepathy"},
		"heightm": 1.3,
		"weightkg": 31.5,
		"color": "Red",
		"prevo": "Meditite",
		"evoLevel": 37,
		"eggGroups": ["Human-Like"],
		"otherFormes": ["Medicham-Mega"],
		"formeOrder": ["Medicham", "Medicham-Mega"],
	},
	"Medichammega": {
		"num": 308,
		"name": "Medicham-Mega",
		"baseSpecies": "Medicham",
		"forme": "Mega",
		"types": ["Fighting", "Psychic"],
		"baseStats": {"hp": 60, "atk": 100, "def": 85, "spa": 80, "spd": 85, "spe": 100},
		"abilities": {"0": "Pure Power"},
		"heightm": 1.3,
		"weightkg": 31.5,
		"color": "Red",
		"eggGroups": ["Human-Like"],
		"requiredItem": "Medichamite",
	},
	"Electrike": {
		"num": 309,
		"name": "Electrike",
		"types": ["Electric"],
		"baseStats": {"hp": 40, "atk": 45, "def": 40, "spa": 65, "spd": 40, "spe": 65},
		"abilities": {"0": "Static", "1": "Lightning Rod", "H": "Minus"},
		"heightm": 0.6,
		"weightkg": 15.2,
		"color": "Green",
		"evos": ["Manectric"],
		"eggGroups": ["Field"],
	},
	"Manectric": {
		"num": 310,
		"name": "Manectric",
		"types": ["Electric"],
		"baseStats": {"hp": 70, "atk": 75, "def": 60, "spa": 105, "spd": 60, "spe": 105},
		"abilities": {"0": "Static", "1": "Lightning Rod", "H": "Minus"},
		"heightm": 1.5,
		"weightkg": 40.2,
		"color": "Yellow",
		"prevo": "Electrike",
		"evoLevel": 26,
		"eggGroups": ["Field"],
		"otherFormes": ["Manectric-Mega"],
		"formeOrder": ["Manectric", "Manectric-Mega"],
	},
	"Manectricmega": {
		"num": 310,
		"name": "Manectric-Mega",
		"baseSpecies": "Manectric",
		"forme": "Mega",
		"types": ["Electric"],
		"baseStats": {"hp": 70, "atk": 75, "def": 80, "spa": 135, "spd": 80, "spe": 135},
		"abilities": {"0": "Intimidate"},
		"heightm": 1.8,
		"weightkg": 44,
		"color": "Yellow",
		"eggGroups": ["Field"],
		"requiredItem": "Manectite",
	},
	"Plusle": {
		"num": 311,
		"name": "Plusle",
		"types": ["Electric"],
		"baseStats": {"hp": 60, "atk": 50, "def": 40, "spa": 85, "spd": 75, "spe": 95},
		"abilities": {"0": "Plus", "H": "Lightning Rod"},
		"heightm": 0.4,
		"weightkg": 4.2,
		"color": "Yellow",
		"eggGroups": ["Fairy"],
	},
	"Minun": {
		"num": 312,
		"name": "Minun",
		"types": ["Electric"],
		"baseStats": {"hp": 60, "atk": 40, "def": 50, "spa": 75, "spd": 85, "spe": 95},
		"abilities": {"0": "Minus", "H": "Volt Absorb"},
		"heightm": 0.4,
		"weightkg": 4.2,
		"color": "Yellow",
		"eggGroups": ["Fairy"],
	},
	"Volbeat": {
		"num": 313,
		"name": "Volbeat",
		"types": ["Bug"],
		"gender": "M",
		"baseStats": {"hp": 65, "atk": 73, "def": 75, "spa": 47, "spd": 85, "spe": 85},
		"abilities": {"0": "Illuminate", "1": "Swarm", "H": "Prankster"},
		"heightm": 0.7,
		"weightkg": 17.7,
		"color": "Gray",
		"eggGroups": ["Bug", "Human-Like"],
		"mother": "illumise",
	},
	"Illumise": {
		"num": 314,
		"name": "Illumise",
		"types": ["Bug"],
		"gender": "F",
		"baseStats": {"hp": 65, "atk": 47, "def": 75, "spa": 73, "spd": 85, "spe": 85},
		"abilities": {"0": "Oblivious", "1": "Tinted Lens", "H": "Prankster"},
		"heightm": 0.6,
		"weightkg": 17.7,
		"color": "Purple",
		"eggGroups": ["Bug", "Human-Like"],
	},
	"Roselia": {
		"num": 315,
		"name": "Roselia",
		"types": ["Grass", "Poison"],
		"baseStats": {"hp": 50, "atk": 60, "def": 45, "spa": 100, "spd": 80, "spe": 65},
		"abilities": {"0": "Natural Cure", "1": "Poison Point", "H": "Leaf Guard"},
		"heightm": 0.3,
		"weightkg": 2,
		"color": "Green",
		"prevo": "Budew",
		"evoType": "levelFriendship",
		"evoCondition": "during the day",
		"evos": ["Roserade"],
		"eggGroups": ["Fairy", "Grass"],
		"canHatch": True,
	},
	"Gulpin": {
		"num": 316,
		"name": "Gulpin",
		"types": ["Poison"],
		"baseStats": {"hp": 70, "atk": 43, "def": 53, "spa": 43, "spd": 53, "spe": 40},
		"abilities": {"0": "Liquid Ooze", "1": "Sticky Hold", "H": "Gluttony"},
		"heightm": 0.4,
		"weightkg": 10.3,
		"color": "Green",
		"evos": ["Swalot"],
		"eggGroups": ["Amorphous"],
	},
	"Swalot": {
		"num": 317,
		"name": "Swalot",
		"types": ["Poison"],
		"baseStats": {"hp": 100, "atk": 73, "def": 83, "spa": 73, "spd": 83, "spe": 55},
		"abilities": {"0": "Liquid Ooze", "1": "Sticky Hold", "H": "Gluttony"},
		"heightm": 1.7,
		"weightkg": 80,
		"color": "Purple",
		"prevo": "Gulpin",
		"evoLevel": 26,
		"eggGroups": ["Amorphous"],
	},
	"Carvanha": {
		"num": 318,
		"name": "Carvanha",
		"types": ["Water", "Dark"],
		"baseStats": {"hp": 45, "atk": 90, "def": 20, "spa": 65, "spd": 20, "spe": 65},
		"abilities": {"0": "Rough Skin", "H": "Speed Boost"},
		"heightm": 0.8,
		"weightkg": 20.8,
		"color": "Red",
		"evos": ["Sharpedo"],
		"eggGroups": ["Water 2"],
	},
	"Sharpedo": {
		"num": 319,
		"name": "Sharpedo",
		"types": ["Water", "Dark"],
		"baseStats": {"hp": 70, "atk": 120, "def": 40, "spa": 95, "spd": 40, "spe": 95},
		"abilities": {"0": "Rough Skin", "H": "Speed Boost"},
		"heightm": 1.8,
		"weightkg": 88.8,
		"color": "Blue",
		"prevo": "Carvanha",
		"evoLevel": 30,
		"eggGroups": ["Water 2"],
		"otherFormes": ["Sharpedo-Mega"],
		"formeOrder": ["Sharpedo", "Sharpedo-Mega"],
	},
	"Sharpedomega": {
		"num": 319,
		"name": "Sharpedo-Mega",
		"baseSpecies": "Sharpedo",
		"forme": "Mega",
		"types": ["Water", "Dark"],
		"baseStats": {"hp": 70, "atk": 140, "def": 70, "spa": 110, "spd": 65, "spe": 105},
		"abilities": {"0": "Strong Jaw"},
		"heightm": 2.5,
		"weightkg": 130.3,
		"color": "Blue",
		"eggGroups": ["Water 2"],
		"requiredItem": "Sharpedonite",
	},
	"Wailmer": {
		"num": 320,
		"name": "Wailmer",
		"types": ["Water"],
		"baseStats": {"hp": 130, "atk": 70, "def": 35, "spa": 70, "spd": 35, "spe": 60},
		"abilities": {"0": "Water Veil", "1": "Oblivious", "H": "Pressure"},
		"heightm": 2,
		"weightkg": 130,
		"color": "Blue",
		"evos": ["Wailord"],
		"eggGroups": ["Field", "Water 2"],
	},
	"Wailord": {
		"num": 321,
		"name": "Wailord",
		"types": ["Water"],
		"baseStats": {"hp": 170, "atk": 90, "def": 45, "spa": 90, "spd": 45, "spe": 60},
		"abilities": {"0": "Water Veil", "1": "Oblivious", "H": "Pressure"},
		"heightm": 14.5,
		"weightkg": 398,
		"color": "Blue",
		"prevo": "Wailmer",
		"evoLevel": 40,
		"eggGroups": ["Field", "Water 2"],
	},
	"Numel": {
		"num": 322,
		"name": "Numel",
		"types": ["Fire", "Ground"],
		"baseStats": {"hp": 60, "atk": 60, "def": 40, "spa": 65, "spd": 45, "spe": 35},
		"abilities": {"0": "Oblivious", "1": "Simple", "H": "Own Tempo"},
		"heightm": 0.7,
		"weightkg": 24,
		"color": "Yellow",
		"evos": ["Camerupt"],
		"eggGroups": ["Field"],
	},
	"Camerupt": {
		"num": 323,
		"name": "Camerupt",
		"types": ["Fire", "Ground"],
		"baseStats": {"hp": 70, "atk": 100, "def": 70, "spa": 105, "spd": 75, "spe": 40},
		"abilities": {"0": "Magma Armor", "1": "Solid Rock", "H": "Anger Point"},
		"heightm": 1.9,
		"weightkg": 220,
		"color": "Red",
		"prevo": "Numel",
		"evoLevel": 33,
		"eggGroups": ["Field"],
		"otherFormes": ["Camerupt-Mega"],
		"formeOrder": ["Camerupt", "Camerupt-Mega"],
	},
	"Cameruptmega": {
		"num": 323,
		"name": "Camerupt-Mega",
		"baseSpecies": "Camerupt",
		"forme": "Mega",
		"types": ["Fire", "Ground"],
		"baseStats": {"hp": 70, "atk": 120, "def": 100, "spa": 145, "spd": 105, "spe": 20},
		"abilities": {"0": "Sheer Force"},
		"heightm": 2.5,
		"weightkg": 320.5,
		"color": "Red",
		"eggGroups": ["Field"],
		"requiredItem": "Cameruptite",
	},
	"Torkoal": {
		"num": 324,
		"name": "Torkoal",
		"types": ["Fire"],
		"baseStats": {"hp": 70, "atk": 85, "def": 140, "spa": 85, "spd": 70, "spe": 20},
		"abilities": {"0": "White Smoke", "1": "Drought", "H": "Shell Armor"},
		"heightm": 0.5,
		"weightkg": 80.4,
		"color": "Brown",
		"eggGroups": ["Field"],
	},
	"Spoink": {
		"num": 325,
		"name": "Spoink",
		"types": ["Psychic"],
		"baseStats": {"hp": 60, "atk": 25, "def": 35, "spa": 70, "spd": 80, "spe": 60},
		"abilities": {"0": "Thick Fat", "1": "Own Tempo", "H": "Gluttony"},
		"heightm": 0.7,
		"weightkg": 30.6,
		"color": "Black",
		"evos": ["Grumpig"],
		"eggGroups": ["Field"],
	},
	"Grumpig": {
		"num": 326,
		"name": "Grumpig",
		"types": ["Psychic"],
		"baseStats": {"hp": 80, "atk": 45, "def": 65, "spa": 90, "spd": 110, "spe": 80},
		"abilities": {"0": "Thick Fat", "1": "Own Tempo", "H": "Gluttony"},
		"heightm": 0.9,
		"weightkg": 71.5,
		"color": "Purple",
		"prevo": "Spoink",
		"evoLevel": 32,
		"eggGroups": ["Field"],
	},
	"Spinda": {
		"num": 327,
		"name": "Spinda",
		"types": ["Normal"],
		"baseStats": {"hp": 60, "atk": 60, "def": 60, "spa": 60, "spd": 60, "spe": 60},
		"abilities": {"0": "Own Tempo", "1": "Tangled Feet", "H": "Contrary"},
		"heightm": 1.1,
		"weightkg": 5,
		"color": "Brown",
		"eggGroups": ["Field", "Human-Like"],
	},
	"Trapinch": {
		"num": 328,
		"name": "Trapinch",
		"types": ["Ground"],
		"baseStats": {"hp": 45, "atk": 100, "def": 45, "spa": 45, "spd": 45, "spe": 10},
		"abilities": {"0": "Hyper Cutter", "1": "Arena Trap", "H": "Sheer Force"},
		"heightm": 0.7,
		"weightkg": 15,
		"color": "Brown",
		"evos": ["Vibrava"],
		"eggGroups": ["Bug", "Dragon"],
	},
	"Vibrava": {
		"num": 329,
		"name": "Vibrava",
		"types": ["Ground", "Dragon"],
		"baseStats": {"hp": 50, "atk": 70, "def": 50, "spa": 50, "spd": 50, "spe": 70},
		"abilities": {"0": "Levitate"},
		"heightm": 1.1,
		"weightkg": 15.3,
		"color": "Green",
		"prevo": "Trapinch",
		"evoLevel": 35,
		"evos": ["Flygon"],
		"eggGroups": ["Bug", "Dragon"],
	},
	"Flygon": {
		"num": 330,
		"name": "Flygon",
		"types": ["Ground", "Dragon"],
		"baseStats": {"hp": 80, "atk": 100, "def": 80, "spa": 80, "spd": 80, "spe": 100},
		"abilities": {"0": "Levitate"},
		"heightm": 2,
		"weightkg": 82,
		"color": "Green",
		"prevo": "Vibrava",
		"evoLevel": 45,
		"eggGroups": ["Bug", "Dragon"],
	},
	"Cacnea": {
		"num": 331,
		"name": "Cacnea",
		"types": ["Grass"],
		"baseStats": {"hp": 50, "atk": 85, "def": 40, "spa": 85, "spd": 40, "spe": 35},
		"abilities": {"0": "Sand Veil", "H": "Water Absorb"},
		"heightm": 0.4,
		"weightkg": 51.3,
		"color": "Green",
		"evos": ["Cacturne"],
		"eggGroups": ["Grass", "Human-Like"],
	},
	"Cacturne": {
		"num": 332,
		"name": "Cacturne",
		"types": ["Grass", "Dark"],
		"baseStats": {"hp": 70, "atk": 115, "def": 60, "spa": 115, "spd": 60, "spe": 55},
		"abilities": {"0": "Sand Veil", "H": "Water Absorb"},
		"heightm": 1.3,
		"weightkg": 77.4,
		"color": "Green",
		"prevo": "Cacnea",
		"evoLevel": 32,
		"eggGroups": ["Grass", "Human-Like"],
	},
	"Swablu": {
		"num": 333,
		"name": "Swablu",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 45, "atk": 40, "def": 60, "spa": 40, "spd": 75, "spe": 50},
		"abilities": {"0": "Natural Cure", "H": "Cloud Nine"},
		"heightm": 0.4,
		"weightkg": 1.2,
		"color": "Blue",
		"evos": ["Altaria"],
		"eggGroups": ["Flying", "Dragon"],
	},
	"Altaria": {
		"num": 334,
		"name": "Altaria",
		"types": ["Dragon", "Flying"],
		"baseStats": {"hp": 75, "atk": 70, "def": 90, "spa": 70, "spd": 105, "spe": 80},
		"abilities": {"0": "Natural Cure", "H": "Cloud Nine"},
		"heightm": 1.1,
		"weightkg": 20.6,
		"color": "Blue",
		"prevo": "Swablu",
		"evoLevel": 35,
		"eggGroups": ["Flying", "Dragon"],
		"otherFormes": ["Altaria-Mega"],
		"formeOrder": ["Altaria", "Altaria-Mega"],
	},
	"Altariamega": {
		"num": 334,
		"name": "Altaria-Mega",
		"baseSpecies": "Altaria",
		"forme": "Mega",
		"types": ["Dragon", "Fairy"],
		"baseStats": {"hp": 75, "atk": 110, "def": 110, "spa": 110, "spd": 105, "spe": 80},
		"abilities": {"0": "Pixilate"},
		"heightm": 1.5,
		"weightkg": 20.6,
		"color": "Blue",
		"eggGroups": ["Flying", "Dragon"],
		"requiredItem": "Altarianite",
	},
	"Zangoose": {
		"num": 335,
		"name": "Zangoose",
		"types": ["Normal"],
		"baseStats": {"hp": 73, "atk": 115, "def": 60, "spa": 60, "spd": 60, "spe": 90},
		"abilities": {"0": "Immunity", "H": "Toxic Boost"},
		"heightm": 1.3,
		"weightkg": 40.3,
		"color": "White",
		"eggGroups": ["Field"],
	},
	"Seviper": {
		"num": 336,
		"name": "Seviper",
		"types": ["Poison"],
		"baseStats": {"hp": 73, "atk": 100, "def": 60, "spa": 100, "spd": 60, "spe": 65},
		"abilities": {"0": "Shed Skin", "H": "Infiltrator"},
		"heightm": 2.7,
		"weightkg": 52.5,
		"color": "Black",
		"eggGroups": ["Field", "Dragon"],
	},
	"Lunatone": {
		"num": 337,
		"name": "Lunatone",
		"types": ["Rock", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 90, "atk": 55, "def": 65, "spa": 95, "spd": 85, "spe": 70},
		"abilities": {"0": "Levitate"},
		"heightm": 1,
		"weightkg": 168,
		"color": "Yellow",
		"eggGroups": ["Mineral"],
	},
	"Solrock": {
		"num": 338,
		"name": "Solrock",
		"types": ["Rock", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 90, "atk": 95, "def": 85, "spa": 55, "spd": 65, "spe": 70},
		"abilities": {"0": "Levitate"},
		"heightm": 1.2,
		"weightkg": 154,
		"color": "Red",
		"eggGroups": ["Mineral"],
	},
	"Barboach": {
		"num": 339,
		"name": "Barboach",
		"types": ["Water", "Ground"],
		"baseStats": {"hp": 50, "atk": 48, "def": 43, "spa": 46, "spd": 41, "spe": 60},
		"abilities": {"0": "Oblivious", "1": "Anticipation", "H": "Hydration"},
		"heightm": 0.4,
		"weightkg": 1.9,
		"color": "Gray",
		"evos": ["Whiscash"],
		"eggGroups": ["Water 2"],
	},
	"Whiscash": {
		"num": 340,
		"name": "Whiscash",
		"types": ["Water", "Ground"],
		"baseStats": {"hp": 110, "atk": 78, "def": 73, "spa": 76, "spd": 71, "spe": 60},
		"abilities": {"0": "Oblivious", "1": "Anticipation", "H": "Hydration"},
		"heightm": 0.9,
		"weightkg": 23.6,
		"color": "Blue",
		"prevo": "Barboach",
		"evoLevel": 30,
		"eggGroups": ["Water 2"],
	},
	"Corphish": {
		"num": 341,
		"name": "Corphish",
		"types": ["Water"],
		"baseStats": {"hp": 43, "atk": 80, "def": 65, "spa": 50, "spd": 35, "spe": 35},
		"abilities": {"0": "Hyper Cutter", "1": "Shell Armor", "H": "Adaptability"},
		"heightm": 0.6,
		"weightkg": 11.5,
		"color": "Red",
		"evos": ["Crawdaunt"],
		"eggGroups": ["Water 1", "Water 3"],
	},
	"Crawdaunt": {
		"num": 342,
		"name": "Crawdaunt",
		"types": ["Water", "Dark"],
		"baseStats": {"hp": 63, "atk": 120, "def": 85, "spa": 90, "spd": 55, "spe": 55},
		"abilities": {"0": "Hyper Cutter", "1": "Shell Armor", "H": "Adaptability"},
		"heightm": 1.1,
		"weightkg": 32.8,
		"color": "Red",
		"prevo": "Corphish",
		"evoLevel": 30,
		"eggGroups": ["Water 1", "Water 3"],
	},
	"Baltoy": {
		"num": 343,
		"name": "Baltoy",
		"types": ["Ground", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 40, "atk": 40, "def": 55, "spa": 40, "spd": 70, "spe": 55},
		"abilities": {"0": "Levitate"},
		"heightm": 0.5,
		"weightkg": 21.5,
		"color": "Brown",
		"evos": ["Claydol"],
		"eggGroups": ["Mineral"],
	},
	"Claydol": {
		"num": 344,
		"name": "Claydol",
		"types": ["Ground", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 60, "atk": 70, "def": 105, "spa": 70, "spd": 120, "spe": 75},
		"abilities": {"0": "Levitate"},
		"heightm": 1.5,
		"weightkg": 108,
		"color": "Black",
		"prevo": "Baltoy",
		"evoLevel": 36,
		"eggGroups": ["Mineral"],
	},
	"Lileep": {
		"num": 345,
		"name": "Lileep",
		"types": ["Rock", "Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 66, "atk": 41, "def": 77, "spa": 61, "spd": 87, "spe": 23},
		"abilities": {"0": "Suction Cups", "H": "Storm Drain"},
		"heightm": 1,
		"weightkg": 23.8,
		"color": "Purple",
		"evos": ["Cradily"],
		"eggGroups": ["Water 3"],
	},
	"Cradily": {
		"num": 346,
		"name": "Cradily",
		"types": ["Rock", "Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 86, "atk": 81, "def": 97, "spa": 81, "spd": 107, "spe": 43},
		"abilities": {"0": "Suction Cups", "H": "Storm Drain"},
		"heightm": 1.5,
		"weightkg": 60.4,
		"color": "Green",
		"prevo": "Lileep",
		"evoLevel": 40,
		"eggGroups": ["Water 3"],
	},
	"Anorith": {
		"num": 347,
		"name": "Anorith",
		"types": ["Rock", "Bug"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 45, "atk": 95, "def": 50, "spa": 40, "spd": 50, "spe": 75},
		"abilities": {"0": "Battle Armor", "H": "Swift Swim"},
		"heightm": 0.7,
		"weightkg": 12.5,
		"color": "Gray",
		"evos": ["Armaldo"],
		"eggGroups": ["Water 3"],
	},
	"Armaldo": {
		"num": 348,
		"name": "Armaldo",
		"types": ["Rock", "Bug"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 75, "atk": 125, "def": 100, "spa": 70, "spd": 80, "spe": 45},
		"abilities": {"0": "Battle Armor", "H": "Swift Swim"},
		"heightm": 1.5,
		"weightkg": 68.2,
		"color": "Gray",
		"prevo": "Anorith",
		"evoLevel": 40,
		"eggGroups": ["Water 3"],
	},
	"Feebas": {
		"num": 349,
		"name": "Feebas",
		"types": ["Water"],
		"baseStats": {"hp": 20, "atk": 15, "def": 20, "spa": 10, "spd": 55, "spe": 80},
		"abilities": {"0": "Swift Swim", "1": "Oblivious", "H": "Adaptability"},
		"heightm": 0.6,
		"weightkg": 7.4,
		"color": "Brown",
		"evos": ["Milotic"],
		"eggGroups": ["Water 1", "Dragon"],
	},
	"Milotic": {
		"num": 350,
		"name": "Milotic",
		"types": ["Water"],
		"baseStats": {"hp": 95, "atk": 60, "def": 79, "spa": 100, "spd": 125, "spe": 81},
		"abilities": {"0": "Marvel Scale", "1": "Competitive", "H": "Cute Charm"},
		"heightm": 6.2,
		"weightkg": 162,
		"color": "Pink",
		"prevo": "Feebas",
		"evoType": "trade",
		"evoItem": "Prism Scale",
		"eggGroups": ["Water 1", "Dragon"],
	},
	"Castform": {
		"num": 351,
		"name": "Castform",
		"types": ["Normal"],
		"baseStats": {"hp": 70, "atk": 70, "def": 70, "spa": 70, "spd": 70, "spe": 70},
		"abilities": {"0": "Forecast"},
		"heightm": 0.3,
		"weightkg": 0.8,
		"color": "Gray",
		"eggGroups": ["Fairy", "Amorphous"],
		"otherFormes": ["Castform-Sunny", "Castform-Rainy", "Castform-Snowy"],
		"formeOrder": ["Castform", "Castform-Sunny", "Castform-Rainy", "Castform-Snowy"],
	},
	"Castformsunny": {
		"num": 351,
		"name": "Castform-Sunny",
		"baseSpecies": "Castform",
		"forme": "Sunny",
		"types": ["Fire"],
		"baseStats": {"hp": 70, "atk": 70, "def": 70, "spa": 70, "spd": 70, "spe": 70},
		"abilities": {"0": "Forecast"},
		"heightm": 0.3,
		"weightkg": 0.8,
		"color": "Red",
		"eggGroups": ["Fairy", "Amorphous"],
		"requiredAbility": "Forecast",
		"battleOnly": "Castform",
	},
	"Castformrainy": {
		"num": 351,
		"name": "Castform-Rainy",
		"baseSpecies": "Castform",
		"forme": "Rainy",
		"types": ["Water"],
		"baseStats": {"hp": 70, "atk": 70, "def": 70, "spa": 70, "spd": 70, "spe": 70},
		"abilities": {"0": "Forecast"},
		"heightm": 0.3,
		"weightkg": 0.8,
		"color": "Blue",
		"eggGroups": ["Fairy", "Amorphous"],
		"requiredAbility": "Forecast",
		"battleOnly": "Castform",
	},
	"Castformsnowy": {
		"num": 351,
		"name": "Castform-Snowy",
		"baseSpecies": "Castform",
		"forme": "Snowy",
		"types": ["Ice"],
		"baseStats": {"hp": 70, "atk": 70, "def": 70, "spa": 70, "spd": 70, "spe": 70},
		"abilities": {"0": "Forecast"},
		"heightm": 0.3,
		"weightkg": 0.8,
		"color": "White",
		"eggGroups": ["Fairy", "Amorphous"],
		"requiredAbility": "Forecast",
		"battleOnly": "Castform",
	},
	"Kecleon": {
		"num": 352,
		"name": "Kecleon",
		"types": ["Normal"],
		"baseStats": {"hp": 60, "atk": 90, "def": 70, "spa": 60, "spd": 120, "spe": 40},
		"abilities": {"0": "Color Change", "H": "Protean"},
		"heightm": 1,
		"weightkg": 22,
		"color": "Green",
		"eggGroups": ["Field"],
	},
	"Shuppet": {
		"num": 353,
		"name": "Shuppet",
		"types": ["Ghost"],
		"baseStats": {"hp": 44, "atk": 75, "def": 35, "spa": 63, "spd": 33, "spe": 45},
		"abilities": {"0": "Insomnia", "1": "Frisk", "H": "Cursed Body"},
		"heightm": 0.6,
		"weightkg": 2.3,
		"color": "Black",
		"evos": ["Banette"],
		"eggGroups": ["Amorphous"],
	},
	"Banette": {
		"num": 354,
		"name": "Banette",
		"types": ["Ghost"],
		"baseStats": {"hp": 64, "atk": 115, "def": 65, "spa": 83, "spd": 63, "spe": 65},
		"abilities": {"0": "Insomnia", "1": "Frisk", "H": "Cursed Body"},
		"heightm": 1.1,
		"weightkg": 12.5,
		"color": "Black",
		"prevo": "Shuppet",
		"evoLevel": 37,
		"eggGroups": ["Amorphous"],
		"otherFormes": ["Banette-Mega"],
		"formeOrder": ["Banette", "Banette-Mega"],
	},
	"Banettemega": {
		"num": 354,
		"name": "Banette-Mega",
		"baseSpecies": "Banette",
		"forme": "Mega",
		"types": ["Ghost"],
		"baseStats": {"hp": 64, "atk": 165, "def": 75, "spa": 93, "spd": 83, "spe": 75},
		"abilities": {"0": "Prankster"},
		"heightm": 1.2,
		"weightkg": 13,
		"color": "Black",
		"eggGroups": ["Amorphous"],
		"requiredItem": "Banettite",
	},
	"Duskull": {
		"num": 355,
		"name": "Duskull",
		"types": ["Ghost"],
		"baseStats": {"hp": 20, "atk": 40, "def": 90, "spa": 30, "spd": 90, "spe": 25},
		"abilities": {"0": "Levitate", "H": "Frisk"},
		"heightm": 0.8,
		"weightkg": 15,
		"color": "Black",
		"evos": ["Dusclops"],
		"eggGroups": ["Amorphous"],
	},
	"Dusclops": {
		"num": 356,
		"name": "Dusclops",
		"types": ["Ghost"],
		"baseStats": {"hp": 40, "atk": 70, "def": 130, "spa": 60, "spd": 130, "spe": 25},
		"abilities": {"0": "Pressure", "H": "Frisk"},
		"heightm": 1.6,
		"weightkg": 30.6,
		"color": "Black",
		"prevo": "Duskull",
		"evoLevel": 37,
		"evos": ["Dusknoir"],
		"eggGroups": ["Amorphous"],
	},
	"Tropius": {
		"num": 357,
		"name": "Tropius",
		"types": ["Grass", "Flying"],
		"baseStats": {"hp": 99, "atk": 68, "def": 83, "spa": 72, "spd": 87, "spe": 51},
		"abilities": {"0": "Chlorophyll", "1": "Solar Power", "H": "Harvest"},
		"heightm": 2,
		"weightkg": 100,
		"color": "Green",
		"eggGroups": ["Monster", "Grass"],
	},
	"Chimecho": {
		"num": 358,
		"name": "Chimecho",
		"types": ["Psychic"],
		"baseStats": {"hp": 75, "atk": 50, "def": 80, "spa": 95, "spd": 90, "spe": 65},
		"abilities": {"0": "Levitate"},
		"heightm": 0.6,
		"weightkg": 1,
		"color": "Blue",
		"prevo": "Chingling",
		"evoType": "levelFriendship",
		"evoCondition": "at night",
		"eggGroups": ["Amorphous"],
		"canHatch": True,
	},
	"Absol": {
		"num": 359,
		"name": "Absol",
		"types": ["Dark"],
		"baseStats": {"hp": 65, "atk": 130, "def": 60, "spa": 75, "spd": 60, "spe": 75},
		"abilities": {"0": "Pressure", "1": "Super Luck", "H": "Justified"},
		"heightm": 1.2,
		"weightkg": 47,
		"color": "White",
		"eggGroups": ["Field"],
		"otherFormes": ["Absol-Mega"],
		"formeOrder": ["Absol", "Absol-Mega"],
	},
	"Absolmega": {
		"num": 359,
		"name": "Absol-Mega",
		"baseSpecies": "Absol",
		"forme": "Mega",
		"types": ["Dark"],
		"baseStats": {"hp": 65, "atk": 150, "def": 60, "spa": 115, "spd": 60, "spe": 115},
		"abilities": {"0": "Magic Bounce"},
		"heightm": 1.2,
		"weightkg": 49,
		"color": "White",
		"eggGroups": ["Field"],
		"requiredItem": "Absolite",
	},
	"Wynaut": {
		"num": 360,
		"name": "Wynaut",
		"types": ["Psychic"],
		"baseStats": {"hp": 95, "atk": 23, "def": 48, "spa": 23, "spd": 48, "spe": 23},
		"abilities": {"0": "Shadow Tag", "H": "Telepathy"},
		"heightm": 0.6,
		"weightkg": 14,
		"color": "Blue",
		"evos": ["Wobbuffet"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Snorunt": {
		"num": 361,
		"name": "Snorunt",
		"types": ["Ice"],
		"baseStats": {"hp": 50, "atk": 50, "def": 50, "spa": 50, "spd": 50, "spe": 50},
		"abilities": {"0": "Inner Focus", "1": "Ice Body", "H": "Moody"},
		"heightm": 0.7,
		"weightkg": 16.8,
		"color": "Gray",
		"evos": ["Glalie", "Froslass"],
		"eggGroups": ["Fairy", "Mineral"],
	},
	"Glalie": {
		"num": 362,
		"name": "Glalie",
		"types": ["Ice"],
		"baseStats": {"hp": 80, "atk": 80, "def": 80, "spa": 80, "spd": 80, "spe": 80},
		"abilities": {"0": "Inner Focus", "1": "Ice Body", "H": "Moody"},
		"heightm": 1.5,
		"weightkg": 256.5,
		"color": "Gray",
		"prevo": "Snorunt",
		"evoLevel": 42,
		"eggGroups": ["Fairy", "Mineral"],
		"otherFormes": ["Glalie-Mega"],
		"formeOrder": ["Glalie", "Glalie-Mega"],
	},
	"Glaliemega": {
		"num": 362,
		"name": "Glalie-Mega",
		"baseSpecies": "Glalie",
		"forme": "Mega",
		"types": ["Ice"],
		"baseStats": {"hp": 80, "atk": 120, "def": 80, "spa": 120, "spd": 80, "spe": 100},
		"abilities": {"0": "Refrigerate"},
		"heightm": 2.1,
		"weightkg": 350.2,
		"color": "Gray",
		"eggGroups": ["Fairy", "Mineral"],
		"requiredItem": "Glalitite",
	},
	"Spheal": {
		"num": 363,
		"name": "Spheal",
		"types": ["Ice", "Water"],
		"baseStats": {"hp": 70, "atk": 40, "def": 50, "spa": 55, "spd": 50, "spe": 25},
		"abilities": {"0": "Thick Fat", "1": "Ice Body", "H": "Oblivious"},
		"heightm": 0.8,
		"weightkg": 39.5,
		"color": "Blue",
		"evos": ["Sealeo"],
		"eggGroups": ["Water 1", "Field"],
	},
	"Sealeo": {
		"num": 364,
		"name": "Sealeo",
		"types": ["Ice", "Water"],
		"baseStats": {"hp": 90, "atk": 60, "def": 70, "spa": 75, "spd": 70, "spe": 45},
		"abilities": {"0": "Thick Fat", "1": "Ice Body", "H": "Oblivious"},
		"heightm": 1.1,
		"weightkg": 87.6,
		"color": "Blue",
		"prevo": "Spheal",
		"evoLevel": 32,
		"evos": ["Walrein"],
		"eggGroups": ["Water 1", "Field"],
	},
	"Walrein": {
		"num": 365,
		"name": "Walrein",
		"types": ["Ice", "Water"],
		"baseStats": {"hp": 110, "atk": 80, "def": 90, "spa": 95, "spd": 90, "spe": 65},
		"abilities": {"0": "Thick Fat", "1": "Ice Body", "H": "Oblivious"},
		"heightm": 1.4,
		"weightkg": 150.6,
		"color": "Blue",
		"prevo": "Sealeo",
		"evoLevel": 44,
		"eggGroups": ["Water 1", "Field"],
	},
	"Clamperl": {
		"num": 366,
		"name": "Clamperl",
		"types": ["Water"],
		"baseStats": {"hp": 35, "atk": 64, "def": 85, "spa": 74, "spd": 55, "spe": 32},
		"abilities": {"0": "Shell Armor", "H": "Rattled"},
		"heightm": 0.4,
		"weightkg": 52.5,
		"color": "Blue",
		"evos": ["Huntail", "Gorebyss"],
		"eggGroups": ["Water 1"],
	},
	"Huntail": {
		"num": 367,
		"name": "Huntail",
		"types": ["Water"],
		"baseStats": {"hp": 55, "atk": 104, "def": 105, "spa": 94, "spd": 75, "spe": 52},
		"abilities": {"0": "Swift Swim", "H": "Water Veil"},
		"heightm": 1.7,
		"weightkg": 27,
		"color": "Blue",
		"prevo": "Clamperl",
		"evoType": "trade",
		"evoItem": "Deep Sea Tooth",
		"eggGroups": ["Water 1"],
	},
	"Gorebyss": {
		"num": 368,
		"name": "Gorebyss",
		"types": ["Water"],
		"baseStats": {"hp": 55, "atk": 84, "def": 105, "spa": 114, "spd": 75, "spe": 52},
		"abilities": {"0": "Swift Swim", "H": "Hydration"},
		"heightm": 1.8,
		"weightkg": 22.6,
		"color": "Pink",
		"prevo": "Clamperl",
		"evoType": "trade",
		"evoItem": "Deep Sea Scale",
		"eggGroups": ["Water 1"],
	},
	"Relicanth": {
		"num": 369,
		"name": "Relicanth",
		"types": ["Water", "Rock"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 100, "atk": 90, "def": 130, "spa": 45, "spd": 65, "spe": 55},
		"abilities": {"0": "Swift Swim", "1": "Rock Head", "H": "Sturdy"},
		"heightm": 1,
		"weightkg": 23.4,
		"color": "Gray",
		"eggGroups": ["Water 1", "Water 2"],
	},
	"Luvdisc": {
		"num": 370,
		"name": "Luvdisc",
		"types": ["Water"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 43, "atk": 30, "def": 55, "spa": 40, "spd": 65, "spe": 97},
		"abilities": {"0": "Swift Swim", "H": "Hydration"},
		"heightm": 0.6,
		"weightkg": 8.7,
		"color": "Pink",
		"eggGroups": ["Water 2"],
	},
	"Bagon": {
		"num": 371,
		"name": "Bagon",
		"types": ["Dragon"],
		"baseStats": {"hp": 45, "atk": 75, "def": 60, "spa": 40, "spd": 30, "spe": 50},
		"abilities": {"0": "Rock Head", "H": "Sheer Force"},
		"heightm": 0.6,
		"weightkg": 42.1,
		"color": "Blue",
		"evos": ["Shelgon"],
		"eggGroups": ["Dragon"],
	},
	"Shelgon": {
		"num": 372,
		"name": "Shelgon",
		"types": ["Dragon"],
		"baseStats": {"hp": 65, "atk": 95, "def": 100, "spa": 60, "spd": 50, "spe": 50},
		"abilities": {"0": "Rock Head", "H": "Overcoat"},
		"heightm": 1.1,
		"weightkg": 110.5,
		"color": "White",
		"prevo": "Bagon",
		"evoLevel": 30,
		"evos": ["Salamence"],
		"eggGroups": ["Dragon"],
	},
	"Salamence": {
		"num": 373,
		"name": "Salamence",
		"types": ["Dragon", "Flying"],
		"baseStats": {"hp": 95, "atk": 135, "def": 80, "spa": 110, "spd": 80, "spe": 100},
		"abilities": {"0": "Intimidate", "H": "Moxie"},
		"heightm": 1.5,
		"weightkg": 102.6,
		"color": "Blue",
		"prevo": "Shelgon",
		"evoLevel": 50,
		"eggGroups": ["Dragon"],
		"otherFormes": ["Salamence-Mega"],
		"formeOrder": ["Salamence", "Salamence-Mega"],
	},
	"Salamencemega": {
		"num": 373,
		"name": "Salamence-Mega",
		"baseSpecies": "Salamence",
		"forme": "Mega",
		"types": ["Dragon", "Flying"],
		"baseStats": {"hp": 95, "atk": 145, "def": 130, "spa": 120, "spd": 90, "spe": 120},
		"abilities": {"0": "Aerilate"},
		"heightm": 1.8,
		"weightkg": 112.6,
		"color": "Blue",
		"eggGroups": ["Dragon"],
		"requiredItem": "Salamencite",
	},
	"Beldum": {
		"num": 374,
		"name": "Beldum",
		"types": ["Steel", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 40, "atk": 55, "def": 80, "spa": 35, "spd": 60, "spe": 30},
		"abilities": {"0": "Clear Body", "H": "Light Metal"},
		"heightm": 0.6,
		"weightkg": 95.2,
		"color": "Blue",
		"evos": ["Metang"],
		"eggGroups": ["Mineral"],
	},
	"Metang": {
		"num": 375,
		"name": "Metang",
		"types": ["Steel", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 60, "atk": 75, "def": 100, "spa": 55, "spd": 80, "spe": 50},
		"abilities": {"0": "Clear Body", "H": "Light Metal"},
		"heightm": 1.2,
		"weightkg": 202.5,
		"color": "Blue",
		"prevo": "Beldum",
		"evoLevel": 20,
		"evos": ["Metagross"],
		"eggGroups": ["Mineral"],
	},
	"Metagross": {
		"num": 376,
		"name": "Metagross",
		"types": ["Steel", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 135, "def": 130, "spa": 95, "spd": 90, "spe": 70},
		"abilities": {"0": "Clear Body", "H": "Light Metal"},
		"heightm": 1.6,
		"weightkg": 550,
		"color": "Blue",
		"prevo": "Metang",
		"evoLevel": 45,
		"eggGroups": ["Mineral"],
		"otherFormes": ["Metagross-Mega"],
		"formeOrder": ["Metagross", "Metagross-Mega"],
	},
	"Metagrossmega": {
		"num": 376,
		"name": "Metagross-Mega",
		"baseSpecies": "Metagross",
		"forme": "Mega",
		"types": ["Steel", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 145, "def": 150, "spa": 105, "spd": 110, "spe": 110},
		"abilities": {"0": "Tough Claws"},
		"heightm": 2.5,
		"weightkg": 942.9,
		"color": "Blue",
		"eggGroups": ["Mineral"],
		"requiredItem": "Metagrossite",
	},
	"Regirock": {
		"num": 377,
		"name": "Regirock",
		"types": ["Rock"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 100, "def": 200, "spa": 50, "spd": 100, "spe": 50},
		"abilities": {"0": "Clear Body", "H": "Sturdy"},
		"heightm": 1.7,
		"weightkg": 230,
		"color": "Brown",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Regice": {
		"num": 378,
		"name": "Regice",
		"types": ["Ice"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 50, "def": 100, "spa": 100, "spd": 200, "spe": 50},
		"abilities": {"0": "Clear Body", "H": "Ice Body"},
		"heightm": 1.8,
		"weightkg": 175,
		"color": "Blue",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Registeel": {
		"num": 379,
		"name": "Registeel",
		"types": ["Steel"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 75, "def": 150, "spa": 75, "spd": 150, "spe": 50},
		"abilities": {"0": "Clear Body", "H": "Light Metal"},
		"heightm": 1.9,
		"weightkg": 205,
		"color": "Gray",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Latias": {
		"num": 380,
		"name": "Latias",
		"types": ["Dragon", "Psychic"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 80, "def": 90, "spa": 110, "spd": 130, "spe": 110},
		"abilities": {"0": "Levitate"},
		"heightm": 1.4,
		"weightkg": 40,
		"color": "Red",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Latias-Mega"],
		"formeOrder": ["Latias", "Latias-Mega"],
	},
	"Latiasmega": {
		"num": 380,
		"name": "Latias-Mega",
		"baseSpecies": "Latias",
		"forme": "Mega",
		"types": ["Dragon", "Psychic"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 100, "def": 120, "spa": 140, "spd": 150, "spe": 110},
		"abilities": {"0": "Levitate"},
		"heightm": 1.8,
		"weightkg": 52,
		"color": "Purple",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Latiasite",
	},
	"Latios": {
		"num": 381,
		"name": "Latios",
		"types": ["Dragon", "Psychic"],
		"gender": "M",
		"baseStats": {"hp": 80, "atk": 90, "def": 80, "spa": 130, "spd": 110, "spe": 110},
		"abilities": {"0": "Levitate"},
		"heightm": 2,
		"weightkg": 60,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
		"tags": ["Sub-Legendary"],
		"otherFormes": ["Latios-Mega"],
		"formeOrder": ["Latios", "Latios-Mega"],
	},
	"Latiosmega": {
		"num": 381,
		"name": "Latios-Mega",
		"baseSpecies": "Latios",
		"forme": "Mega",
		"types": ["Dragon", "Psychic"],
		"gender": "M",
		"baseStats": {"hp": 80, "atk": 130, "def": 100, "spa": 160, "spd": 120, "spe": 110},
		"abilities": {"0": "Levitate"},
		"heightm": 2.3,
		"weightkg": 70,
		"color": "Purple",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Latiosite",
	},
	"Kyogre": {
		"num": 382,
		"name": "Kyogre",
		"types": ["Water"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 100, "def": 90, "spa": 150, "spd": 140, "spe": 90},
		"abilities": {"0": "Drizzle"},
		"heightm": 4.5,
		"weightkg": 352,
		"color": "Blue",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Kyogre-Primal"],
		"formeOrder": ["Kyogre", "Kyogre-Primal"],
	},
	"Kyogreprimal": {
		"num": 382,
		"name": "Kyogre-Primal",
		"baseSpecies": "Kyogre",
		"forme": "Primal",
		"types": ["Water"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 150, "def": 90, "spa": 180, "spd": 160, "spe": 90},
		"abilities": {"0": "Primordial Sea"},
		"heightm": 9.8,
		"weightkg": 430,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Blue Orb",
	},
	"Groudon": {
		"num": 383,
		"name": "Groudon",
		"types": ["Ground"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 150, "def": 140, "spa": 100, "spd": 90, "spe": 90},
		"abilities": {"0": "Drought"},
		"heightm": 3.5,
		"weightkg": 950,
		"color": "Red",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Groudon-Primal"],
		"formeOrder": ["Groudon", "Groudon-Primal"],
	},
	"Groudonprimal": {
		"num": 383,
		"name": "Groudon-Primal",
		"baseSpecies": "Groudon",
		"forme": "Primal",
		"types": ["Ground", "Fire"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 180, "def": 160, "spa": 150, "spd": 90, "spe": 90},
		"abilities": {"0": "Desolate Land"},
		"heightm": 5,
		"weightkg": 999.7,
		"color": "Red",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Red Orb",
	},
	"Rayquaza": {
		"num": 384,
		"name": "Rayquaza",
		"types": ["Dragon", "Flying"],
		"gender": "N",
		"baseStats": {"hp": 105, "atk": 150, "def": 90, "spa": 150, "spd": 90, "spe": 95},
		"abilities": {"0": "Air Lock"},
		"heightm": 7,
		"weightkg": 206.5,
		"color": "Green",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Rayquaza-Mega"],
		"formeOrder": ["Rayquaza", "Rayquaza-Mega"],
	},
	"Rayquazamega": {
		"num": 384,
		"name": "Rayquaza-Mega",
		"baseSpecies": "Rayquaza",
		"forme": "Mega",
		"types": ["Dragon", "Flying"],
		"gender": "N",
		"baseStats": {"hp": 105, "atk": 180, "def": 100, "spa": 180, "spd": 100, "spe": 115},
		"abilities": {"0": "Delta Stream"},
		"heightm": 10.8,
		"weightkg": 392,
		"color": "Green",
		"eggGroups": ["Undiscovered"],
		"requiredMove": "Dragon Ascent",
	},
	"Jirachi": {
		"num": 385,
		"name": "Jirachi",
		"types": ["Steel", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 100, "def": 100, "spa": 100, "spd": 100, "spe": 100},
		"abilities": {"0": "Serene Grace"},
		"heightm": 0.3,
		"weightkg": 1.1,
		"color": "Yellow",
		"tags": ["Mythical"],
		"eggGroups": ["Undiscovered"],
	},
	"Deoxys": {
		"num": 386,
		"name": "Deoxys",
		"baseForme": "Normal",
		"types": ["Psychic"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 150, "def": 50, "spa": 150, "spd": 50, "spe": 150},
		"abilities": {"0": "Pressure"},
		"heightm": 1.7,
		"weightkg": 60.8,
		"color": "Red",
		"eggGroups": ["Undiscovered"],
		"tags": ["Mythical"],
		"otherFormes": ["Deoxys-Attack", "Deoxys-Defense", "Deoxys-Speed"],
		"formeOrder": ["Deoxys", "Deoxys-Attack", "Deoxys-Defense", "Deoxys-Speed"],
	},
	"Deoxysattack": {
		"num": 386,
		"name": "Deoxys-Attack",
		"baseSpecies": "Deoxys",
		"forme": "Attack",
		"types": ["Psychic"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 180, "def": 20, "spa": 180, "spd": 20, "spe": 150},
		"abilities": {"0": "Pressure"},
		"heightm": 1.7,
		"weightkg": 60.8,
		"color": "Red",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Deoxys",
	},
	"Deoxysdefense": {
		"num": 386,
		"name": "Deoxys-Defense",
		"baseSpecies": "Deoxys",
		"forme": "Defense",
		"types": ["Psychic"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 70, "def": 160, "spa": 70, "spd": 160, "spe": 90},
		"abilities": {"0": "Pressure"},
		"heightm": 1.7,
		"weightkg": 60.8,
		"color": "Red",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Deoxys",
	},
	"Deoxysspeed": {
		"num": 386,
		"name": "Deoxys-Speed",
		"baseSpecies": "Deoxys",
		"forme": "Speed",
		"types": ["Psychic"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 95, "def": 90, "spa": 95, "spd": 90, "spe": 180},
		"abilities": {"0": "Pressure"},
		"heightm": 1.7,
		"weightkg": 60.8,
		"color": "Red",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Deoxys",
	},
}
