"""Pokédex entries for Johto region."""
from ..functions.pokedex_funcs import *

pokedex = {
    'Chikorita': {   'num': 152,
                     'name': 'Chikorita',
                     'types': ['Grass'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 45, 'atk': 49, 'def': 65, 'spa': 49, 'spd': 65, 'spe': 45},
                     'abilities': {'0': 'Overgrow', 'H': 'Leaf Guard'},
                     'heightm': 0.9,
                     'weightkg': 6.4,
                     'color': 'Green',
                     'evos': ['Bayleef'],
                     'eggGroups': ['Monster', 'Grass']},
    'Bayleef': {   'num': 153,
                   'name': 'Bayleef',
                   'types': ['Grass'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 60, 'atk': 62, 'def': 80, 'spa': 63, 'spd': 80, 'spe': 60},
                   'abilities': {'0': 'Overgrow', 'H': 'Leaf Guard'},
                   'heightm': 1.2,
                   'weightkg': 15.8,
                   'color': 'Green',
                   'prevo': 'Chikorita',
                   'evoLevel': 16,
                   'evos': ['Meganium'],
                   'eggGroups': ['Monster', 'Grass']},
    'Meganium': {   'num': 154,
                    'name': 'Meganium',
                    'types': ['Grass'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 80, 'atk': 82, 'def': 100, 'spa': 83, 'spd': 100, 'spe': 80},
                    'abilities': {'0': 'Overgrow', 'H': 'Leaf Guard'},
                    'heightm': 1.8,
                    'weightkg': 100.5,
                    'color': 'Green',
                    'prevo': 'Bayleef',
                    'evoLevel': 32,
                    'eggGroups': ['Monster', 'Grass']},
    'Cyndaquil': {   'num': 155,
                     'name': 'Cyndaquil',
                     'types': ['Fire'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 39, 'atk': 52, 'def': 43, 'spa': 60, 'spd': 50, 'spe': 65},
                     'abilities': {'0': 'Blaze', 'H': 'Flash Fire'},
                     'heightm': 0.5,
                     'weightkg': 7.9,
                     'color': 'Yellow',
                     'evos': ['Quilava'],
                     'eggGroups': ['Field']},
    'Quilava': {   'num': 156,
                   'name': 'Quilava',
                   'types': ['Fire'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 58, 'atk': 64, 'def': 58, 'spa': 80, 'spd': 65, 'spe': 80},
                   'abilities': {'0': 'Blaze', 'H': 'Flash Fire'},
                   'heightm': 0.9,
                   'weightkg': 19,
                   'color': 'Yellow',
                   'prevo': 'Cyndaquil',
                   'evoLevel': 14,
                   'evos': ['Typhlosion', 'Typhlosion-Hisui'],
                   'eggGroups': ['Field']},
    'Typhlosion': {   'num': 157,
                      'name': 'Typhlosion',
                      'types': ['Fire'],
                      'genderRatio': {'M': 0.875, 'F': 0.125},
                      'baseStats': {'hp': 78, 'atk': 84, 'def': 78, 'spa': 109, 'spd': 85, 'spe': 100},
                      'abilities': {'0': 'Blaze', 'H': 'Flash Fire'},
                      'heightm': 1.7,
                      'weightkg': 79.5,
                      'color': 'Yellow',
                      'prevo': 'Quilava',
                      'evoLevel': 36,
                      'eggGroups': ['Field'],
                      'otherFormes': ['Typhlosion-Hisui'],
                      'formeOrder': ['Typhlosion', 'Typhlosion-Hisui']},
    'Typhlosionhisui': {   'num': 157,
                           'name': 'Typhlosion-Hisui',
                           'baseSpecies': 'Typhlosion',
                           'forme': 'Hisui',
                           'types': ['Fire', 'Ghost'],
                           'genderRatio': {'M': 0.875, 'F': 0.125},
                           'baseStats': {'hp': 73, 'atk': 84, 'def': 78, 'spa': 119, 'spd': 85, 'spe': 95},
                           'abilities': {'0': 'Blaze', 'H': 'Frisk'},
                           'heightm': 1.6,
                           'weightkg': 69.8,
                           'color': 'Yellow',
                           'prevo': 'Quilava',
                           'evoLevel': 36,
                           'eggGroups': ['Field']},
    'Totodile': {   'num': 158,
                    'name': 'Totodile',
                    'types': ['Water'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 50, 'atk': 65, 'def': 64, 'spa': 44, 'spd': 48, 'spe': 43},
                    'abilities': {'0': 'Torrent', 'H': 'Sheer Force'},
                    'heightm': 0.6,
                    'weightkg': 9.5,
                    'color': 'Blue',
                    'evos': ['Croconaw'],
                    'eggGroups': ['Monster', 'Water 1']},
    'Croconaw': {   'num': 159,
                    'name': 'Croconaw',
                    'types': ['Water'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 65, 'atk': 80, 'def': 80, 'spa': 59, 'spd': 63, 'spe': 58},
                    'abilities': {'0': 'Torrent', 'H': 'Sheer Force'},
                    'heightm': 1.1,
                    'weightkg': 25,
                    'color': 'Blue',
                    'prevo': 'Totodile',
                    'evoLevel': 18,
                    'evos': ['Feraligatr'],
                    'eggGroups': ['Monster', 'Water 1']},
    'Feraligatr': {   'num': 160,
                      'name': 'Feraligatr',
                      'types': ['Water'],
                      'genderRatio': {'M': 0.875, 'F': 0.125},
                      'baseStats': {'hp': 85, 'atk': 105, 'def': 100, 'spa': 79, 'spd': 83, 'spe': 78},
                      'abilities': {'0': 'Torrent', 'H': 'Sheer Force'},
                      'heightm': 2.3,
                      'weightkg': 88.8,
                      'color': 'Blue',
                      'prevo': 'Croconaw',
                      'evoLevel': 30,
                      'eggGroups': ['Monster', 'Water 1']},
    'Sentret': {   'num': 161,
                   'name': 'Sentret',
                   'types': ['Normal'],
                   'baseStats': {'hp': 35, 'atk': 46, 'def': 34, 'spa': 35, 'spd': 45, 'spe': 20},
                   'abilities': {'0': 'Run Away', '1': 'Keen Eye', 'H': 'Frisk'},
                   'heightm': 0.8,
                   'weightkg': 6,
                   'color': 'Brown',
                   'evos': ['Furret'],
                   'eggGroups': ['Field']},
    'Furret': {   'num': 162,
                  'name': 'Furret',
                  'types': ['Normal'],
                  'baseStats': {'hp': 85, 'atk': 76, 'def': 64, 'spa': 45, 'spd': 55, 'spe': 90},
                  'abilities': {'0': 'Run Away', '1': 'Keen Eye', 'H': 'Frisk'},
                  'heightm': 1.8,
                  'weightkg': 32.5,
                  'color': 'Brown',
                  'prevo': 'Sentret',
                  'evoLevel': 15,
                  'eggGroups': ['Field']},
    'Hoothoot': {   'num': 163,
                    'name': 'Hoothoot',
                    'types': ['Normal', 'Flying'],
                    'baseStats': {'hp': 60, 'atk': 30, 'def': 30, 'spa': 36, 'spd': 56, 'spe': 50},
                    'abilities': {'0': 'Insomnia', '1': 'Keen Eye', 'H': 'Tinted Lens'},
                    'heightm': 0.7,
                    'weightkg': 21.2,
                    'color': 'Brown',
                    'evos': ['Noctowl'],
                    'eggGroups': ['Flying']},
    'Noctowl': {   'num': 164,
                   'name': 'Noctowl',
                   'types': ['Normal', 'Flying'],
                   'baseStats': {'hp': 100, 'atk': 50, 'def': 50, 'spa': 86, 'spd': 96, 'spe': 70},
                   'abilities': {'0': 'Insomnia', '1': 'Keen Eye', 'H': 'Tinted Lens'},
                   'heightm': 1.6,
                   'weightkg': 40.8,
                   'color': 'Brown',
                   'prevo': 'Hoothoot',
                   'evoLevel': 20,
                   'eggGroups': ['Flying']},
    'Ledyba': {   'num': 165,
                  'name': 'Ledyba',
                  'types': ['Bug', 'Flying'],
                  'baseStats': {'hp': 40, 'atk': 20, 'def': 30, 'spa': 40, 'spd': 80, 'spe': 55},
                  'abilities': {'0': 'Swarm', '1': 'Early Bird', 'H': 'Rattled'},
                  'heightm': 1,
                  'weightkg': 10.8,
                  'color': 'Red',
                  'evos': ['Ledian'],
                  'eggGroups': ['Bug']},
    'Ledian': {   'num': 166,
                  'name': 'Ledian',
                  'types': ['Bug', 'Flying'],
                  'baseStats': {'hp': 55, 'atk': 35, 'def': 50, 'spa': 55, 'spd': 110, 'spe': 85},
                  'abilities': {'0': 'Swarm', '1': 'Early Bird', 'H': 'Iron Fist'},
                  'heightm': 1.4,
                  'weightkg': 35.6,
                  'color': 'Red',
                  'prevo': 'Ledyba',
                  'evoLevel': 18,
                  'eggGroups': ['Bug']},
    'Spinarak': {   'num': 167,
                    'name': 'Spinarak',
                    'types': ['Bug', 'Poison'],
                    'baseStats': {'hp': 40, 'atk': 60, 'def': 40, 'spa': 40, 'spd': 40, 'spe': 30},
                    'abilities': {'0': 'Swarm', '1': 'Insomnia', 'H': 'Sniper'},
                    'heightm': 0.5,
                    'weightkg': 8.5,
                    'color': 'Green',
                    'evos': ['Ariados'],
                    'eggGroups': ['Bug']},
    'Ariados': {   'num': 168,
                   'name': 'Ariados',
                   'types': ['Bug', 'Poison'],
                   'baseStats': {'hp': 70, 'atk': 90, 'def': 70, 'spa': 60, 'spd': 70, 'spe': 40},
                   'abilities': {'0': 'Swarm', '1': 'Insomnia', 'H': 'Sniper'},
                   'heightm': 1.1,
                   'weightkg': 33.5,
                   'color': 'Red',
                   'prevo': 'Spinarak',
                   'evoLevel': 22,
                   'eggGroups': ['Bug']},
    'Crobat': {   'num': 169,
                  'name': 'Crobat',
                  'types': ['Poison', 'Flying'],
                  'baseStats': {'hp': 85, 'atk': 90, 'def': 80, 'spa': 70, 'spd': 80, 'spe': 130},
                  'abilities': {'0': 'Inner Focus', 'H': 'Infiltrator'},
                  'heightm': 1.8,
                  'weightkg': 75,
                  'color': 'Purple',
                  'prevo': 'Golbat',
                  'evoType': 'levelFriendship',
                  'eggGroups': ['Flying']},
    'Chinchou': {   'num': 170,
                    'name': 'Chinchou',
                    'types': ['Water', 'Electric'],
                    'baseStats': {'hp': 75, 'atk': 38, 'def': 38, 'spa': 56, 'spd': 56, 'spe': 67},
                    'abilities': {'0': 'Volt Absorb', '1': 'Illuminate', 'H': 'Water Absorb'},
                    'heightm': 0.5,
                    'weightkg': 12,
                    'color': 'Blue',
                    'evos': ['Lanturn'],
                    'eggGroups': ['Water 2']},
    'Lanturn': {   'num': 171,
                   'name': 'Lanturn',
                   'types': ['Water', 'Electric'],
                   'baseStats': {'hp': 125, 'atk': 58, 'def': 58, 'spa': 76, 'spd': 76, 'spe': 67},
                   'abilities': {'0': 'Volt Absorb', '1': 'Illuminate', 'H': 'Water Absorb'},
                   'heightm': 1.2,
                   'weightkg': 22.5,
                   'color': 'Blue',
                   'prevo': 'Chinchou',
                   'evoLevel': 27,
                   'eggGroups': ['Water 2']},
    'Pichu': {   'num': 172,
                 'name': 'Pichu',
                 'types': ['Electric'],
                 'baseStats': {'hp': 20, 'atk': 40, 'def': 15, 'spa': 35, 'spd': 35, 'spe': 60},
                 'abilities': {'0': 'Static', 'H': 'Lightning Rod'},
                 'heightm': 0.3,
                 'weightkg': 2,
                 'color': 'Yellow',
                 'evos': ['Pikachu'],
                 'eggGroups': ['Undiscovered'],
                 'canHatch': True,
                 'otherFormes': ['Pichu-Spiky-eared'],
                 'formeOrder': ['Pichu', 'Pichu-Spiky-eared']},
    'Pichuspikyeared': {   'num': 172,
                           'name': 'Pichu-Spiky-eared',
                           'baseSpecies': 'Pichu',
                           'forme': 'Spiky-eared',
                           'types': ['Electric'],
                           'baseStats': {'hp': 20, 'atk': 40, 'def': 15, 'spa': 35, 'spd': 35, 'spe': 60},
                           'abilities': {'0': 'Static'},
                           'heightm': 0.3,
                           'weightkg': 2,
                           'color': 'Yellow',
                           'eggGroups': ['Undiscovered'],
                           'gen': 4},
    'Cleffa': {   'num': 173,
                  'name': 'Cleffa',
                  'types': ['Fairy'],
                  'genderRatio': {'M': 0.25, 'F': 0.75},
                  'baseStats': {'hp': 50, 'atk': 25, 'def': 28, 'spa': 45, 'spd': 55, 'spe': 15},
                  'abilities': {'0': 'Cute Charm', '1': 'Magic Guard', 'H': 'Friend Guard'},
                  'heightm': 0.3,
                  'weightkg': 3,
                  'color': 'Pink',
                  'evos': ['Clefairy'],
                  'eggGroups': ['Undiscovered'],
                  'canHatch': True},
    'Igglybuff': {   'num': 174,
                     'name': 'Igglybuff',
                     'types': ['Normal', 'Fairy'],
                     'genderRatio': {'M': 0.25, 'F': 0.75},
                     'baseStats': {'hp': 90, 'atk': 30, 'def': 15, 'spa': 40, 'spd': 20, 'spe': 15},
                     'abilities': {'0': 'Cute Charm', '1': 'Competitive', 'H': 'Friend Guard'},
                     'heightm': 0.3,
                     'weightkg': 1,
                     'color': 'Pink',
                     'evos': ['Jigglypuff'],
                     'eggGroups': ['Undiscovered'],
                     'canHatch': True},
    'Togepi': {   'num': 175,
                  'name': 'Togepi',
                  'types': ['Fairy'],
                  'genderRatio': {'M': 0.875, 'F': 0.125},
                  'baseStats': {'hp': 35, 'atk': 20, 'def': 65, 'spa': 40, 'spd': 65, 'spe': 20},
                  'abilities': {'0': 'Hustle', '1': 'Serene Grace', 'H': 'Super Luck'},
                  'heightm': 0.3,
                  'weightkg': 1.5,
                  'color': 'White',
                  'evos': ['Togetic'],
                  'eggGroups': ['Undiscovered'],
                  'canHatch': True},
    'Togetic': {   'num': 176,
                   'name': 'Togetic',
                   'types': ['Fairy', 'Flying'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 55, 'atk': 40, 'def': 85, 'spa': 80, 'spd': 105, 'spe': 40},
                   'abilities': {'0': 'Hustle', '1': 'Serene Grace', 'H': 'Super Luck'},
                   'heightm': 0.6,
                   'weightkg': 3.2,
                   'color': 'White',
                   'prevo': 'Togepi',
                   'evoType': 'levelFriendship',
                   'evos': ['Togekiss'],
                   'eggGroups': ['Flying', 'Fairy']},
    'Natu': {   'num': 177,
                'name': 'Natu',
                'types': ['Psychic', 'Flying'],
                'baseStats': {'hp': 40, 'atk': 50, 'def': 45, 'spa': 70, 'spd': 45, 'spe': 70},
                'abilities': {'0': 'Synchronize', '1': 'Early Bird', 'H': 'Magic Bounce'},
                'heightm': 0.2,
                'weightkg': 2,
                'color': 'Green',
                'evos': ['Xatu'],
                'eggGroups': ['Flying']},
    'Xatu': {   'num': 178,
                'name': 'Xatu',
                'types': ['Psychic', 'Flying'],
                'baseStats': {'hp': 65, 'atk': 75, 'def': 70, 'spa': 95, 'spd': 70, 'spe': 95},
                'abilities': {'0': 'Synchronize', '1': 'Early Bird', 'H': 'Magic Bounce'},
                'heightm': 1.5,
                'weightkg': 15,
                'color': 'Green',
                'prevo': 'Natu',
                'evoLevel': 25,
                'eggGroups': ['Flying']},
    'Mareep': {   'num': 179,
                  'name': 'Mareep',
                  'types': ['Electric'],
                  'baseStats': {'hp': 55, 'atk': 40, 'def': 40, 'spa': 65, 'spd': 45, 'spe': 35},
                  'abilities': {'0': 'Static', 'H': 'Plus'},
                  'heightm': 0.6,
                  'weightkg': 7.8,
                  'color': 'White',
                  'evos': ['Flaaffy'],
                  'eggGroups': ['Monster', 'Field']},
    'Flaaffy': {   'num': 180,
                   'name': 'Flaaffy',
                   'types': ['Electric'],
                   'baseStats': {'hp': 70, 'atk': 55, 'def': 55, 'spa': 80, 'spd': 60, 'spe': 45},
                   'abilities': {'0': 'Static', 'H': 'Plus'},
                   'heightm': 0.8,
                   'weightkg': 13.3,
                   'color': 'Pink',
                   'prevo': 'Mareep',
                   'evoLevel': 15,
                   'evos': ['Ampharos'],
                   'eggGroups': ['Monster', 'Field']},
    'Ampharos': {   'num': 181,
                    'name': 'Ampharos',
                    'types': ['Electric'],
                    'baseStats': {'hp': 90, 'atk': 75, 'def': 85, 'spa': 115, 'spd': 90, 'spe': 55},
                    'abilities': {'0': 'Static', 'H': 'Plus'},
                    'heightm': 1.4,
                    'weightkg': 61.5,
                    'color': 'Yellow',
                    'prevo': 'Flaaffy',
                    'evoLevel': 30,
                    'eggGroups': ['Monster', 'Field'],
                    'otherFormes': ['Ampharos-Mega'],
                    'formeOrder': ['Ampharos', 'Ampharos-Mega']},
    'Ampharosmega': {   'num': 181,
                        'name': 'Ampharos-Mega',
                        'baseSpecies': 'Ampharos',
                        'forme': 'Mega',
                        'types': ['Electric', 'Dragon'],
                        'baseStats': {'hp': 90, 'atk': 95, 'def': 105, 'spa': 165, 'spd': 110, 'spe': 45},
                        'abilities': {'0': 'Mold Breaker'},
                        'heightm': 1.4,
                        'weightkg': 61.5,
                        'color': 'Yellow',
                        'eggGroups': ['Monster', 'Field'],
                        'requiredItem': 'Ampharosite'},
    'Bellossom': {   'num': 182,
                     'name': 'Bellossom',
                     'types': ['Grass'],
                     'baseStats': {'hp': 75, 'atk': 80, 'def': 95, 'spa': 90, 'spd': 100, 'spe': 50},
                     'abilities': {'0': 'Chlorophyll', 'H': 'Healer'},
                     'heightm': 0.4,
                     'weightkg': 5.8,
                     'color': 'Green',
                     'prevo': 'Gloom',
                     'evoType': 'useItem',
                     'evoItem': 'Sun Stone',
                     'eggGroups': ['Grass']},
    'Marill': {   'num': 183,
                  'name': 'Marill',
                  'types': ['Water', 'Fairy'],
                  'baseStats': {'hp': 70, 'atk': 20, 'def': 50, 'spa': 20, 'spd': 50, 'spe': 40},
                  'abilities': {'0': 'Thick Fat', '1': 'Huge Power', 'H': 'Sap Sipper'},
                  'heightm': 0.4,
                  'weightkg': 8.5,
                  'color': 'Blue',
                  'prevo': 'Azurill',
                  'evoType': 'levelFriendship',
                  'evos': ['Azumarill'],
                  'eggGroups': ['Water 1', 'Fairy'],
                  'canHatch': True},
    'Azumarill': {   'num': 184,
                     'name': 'Azumarill',
                     'types': ['Water', 'Fairy'],
                     'baseStats': {'hp': 100, 'atk': 50, 'def': 80, 'spa': 60, 'spd': 80, 'spe': 50},
                     'abilities': {'0': 'Thick Fat', '1': 'Huge Power', 'H': 'Sap Sipper'},
                     'heightm': 0.8,
                     'weightkg': 28.5,
                     'color': 'Blue',
                     'prevo': 'Marill',
                     'evoLevel': 18,
                     'eggGroups': ['Water 1', 'Fairy']},
    'Sudowoodo': {   'num': 185,
                     'name': 'Sudowoodo',
                     'types': ['Rock'],
                     'baseStats': {'hp': 70, 'atk': 100, 'def': 115, 'spa': 30, 'spd': 65, 'spe': 30},
                     'abilities': {'0': 'Sturdy', '1': 'Rock Head', 'H': 'Rattled'},
                     'heightm': 1.2,
                     'weightkg': 38,
                     'color': 'Brown',
                     'prevo': 'Bonsly',
                     'evoType': 'levelMove',
                     'evoMove': 'Mimic',
                     'eggGroups': ['Mineral'],
                     'canHatch': True},
    'Politoed': {   'num': 186,
                    'name': 'Politoed',
                    'types': ['Water'],
                    'baseStats': {'hp': 90, 'atk': 75, 'def': 75, 'spa': 90, 'spd': 100, 'spe': 70},
                    'abilities': {'0': 'Water Absorb', '1': 'Damp', 'H': 'Drizzle'},
                    'heightm': 1.1,
                    'weightkg': 33.9,
                    'color': 'Green',
                    'prevo': 'Poliwhirl',
                    'evoType': 'trade',
                    'evoItem': "King's Rock",
                    'eggGroups': ['Water 1']},
    'Hoppip': {   'num': 187,
                  'name': 'Hoppip',
                  'types': ['Grass', 'Flying'],
                  'baseStats': {'hp': 35, 'atk': 35, 'def': 40, 'spa': 35, 'spd': 55, 'spe': 50},
                  'abilities': {'0': 'Chlorophyll', '1': 'Leaf Guard', 'H': 'Infiltrator'},
                  'heightm': 0.4,
                  'weightkg': 0.5,
                  'color': 'Pink',
                  'evos': ['Skiploom'],
                  'eggGroups': ['Fairy', 'Grass']},
    'Skiploom': {   'num': 188,
                    'name': 'Skiploom',
                    'types': ['Grass', 'Flying'],
                    'baseStats': {'hp': 55, 'atk': 45, 'def': 50, 'spa': 45, 'spd': 65, 'spe': 80},
                    'abilities': {'0': 'Chlorophyll', '1': 'Leaf Guard', 'H': 'Infiltrator'},
                    'heightm': 0.6,
                    'weightkg': 1,
                    'color': 'Green',
                    'prevo': 'Hoppip',
                    'evoLevel': 18,
                    'evos': ['Jumpluff'],
                    'eggGroups': ['Fairy', 'Grass']},
    'Jumpluff': {   'num': 189,
                    'name': 'Jumpluff',
                    'types': ['Grass', 'Flying'],
                    'baseStats': {'hp': 75, 'atk': 55, 'def': 70, 'spa': 55, 'spd': 95, 'spe': 110},
                    'abilities': {'0': 'Chlorophyll', '1': 'Leaf Guard', 'H': 'Infiltrator'},
                    'heightm': 0.8,
                    'weightkg': 3,
                    'color': 'Blue',
                    'prevo': 'Skiploom',
                    'evoLevel': 27,
                    'eggGroups': ['Fairy', 'Grass']},
    'Aipom': {   'num': 190,
                 'name': 'Aipom',
                 'types': ['Normal'],
                 'baseStats': {'hp': 55, 'atk': 70, 'def': 55, 'spa': 40, 'spd': 55, 'spe': 85},
                 'abilities': {'0': 'Run Away', '1': 'Pickup', 'H': 'Skill Link'},
                 'heightm': 0.8,
                 'weightkg': 11.5,
                 'color': 'Purple',
                 'evos': ['Ambipom'],
                 'eggGroups': ['Field']},
    'Sunkern': {   'num': 191,
                   'name': 'Sunkern',
                   'types': ['Grass'],
                   'baseStats': {'hp': 30, 'atk': 30, 'def': 30, 'spa': 30, 'spd': 30, 'spe': 30},
                   'abilities': {'0': 'Chlorophyll', '1': 'Solar Power', 'H': 'Early Bird'},
                   'heightm': 0.3,
                   'weightkg': 1.8,
                   'color': 'Yellow',
                   'evos': ['Sunflora'],
                   'eggGroups': ['Grass']},
    'Sunflora': {   'num': 192,
                    'name': 'Sunflora',
                    'types': ['Grass'],
                    'baseStats': {'hp': 75, 'atk': 75, 'def': 55, 'spa': 105, 'spd': 85, 'spe': 30},
                    'abilities': {'0': 'Chlorophyll', '1': 'Solar Power', 'H': 'Early Bird'},
                    'heightm': 0.8,
                    'weightkg': 8.5,
                    'color': 'Yellow',
                    'prevo': 'Sunkern',
                    'evoType': 'useItem',
                    'evoItem': 'Sun Stone',
                    'eggGroups': ['Grass']},
    'Yanma': {   'num': 193,
                 'name': 'Yanma',
                 'types': ['Bug', 'Flying'],
                 'baseStats': {'hp': 65, 'atk': 65, 'def': 45, 'spa': 75, 'spd': 45, 'spe': 95},
                 'abilities': {'0': 'Speed Boost', '1': 'Compound Eyes', 'H': 'Frisk'},
                 'heightm': 1.2,
                 'weightkg': 38,
                 'color': 'Red',
                 'evos': ['Yanmega'],
                 'eggGroups': ['Bug']},
    'Wooper': {   'num': 194,
                  'name': 'Wooper',
                  'types': ['Water', 'Ground'],
                  'baseStats': {'hp': 55, 'atk': 45, 'def': 45, 'spa': 25, 'spd': 25, 'spe': 15},
                  'abilities': {'0': 'Damp', '1': 'Water Absorb', 'H': 'Unaware'},
                  'heightm': 0.4,
                  'weightkg': 8.5,
                  'color': 'Blue',
                  'evos': ['Quagsire'],
                  'eggGroups': ['Water 1', 'Field'],
                  'otherFormes': ['Wooper-Paldea'],
                  'formeOrder': ['Wooper', 'Wooper-Paldea']},
    'Wooperpaldea': {   'num': 194,
                        'name': 'Wooper-Paldea',
                        'baseSpecies': 'Wooper',
                        'forme': 'Paldea',
                        'types': ['Poison', 'Ground'],
                        'baseStats': {'hp': 55, 'atk': 45, 'def': 45, 'spa': 25, 'spd': 25, 'spe': 15},
                        'abilities': {'0': 'Poison Point', '1': 'Water Absorb', 'H': 'Unaware'},
                        'heightm': 0.4,
                        'weightkg': 11,
                        'color': 'Brown',
                        'evos': ['Clodsire'],
                        'eggGroups': ['Water 1', 'Field']},
    'Quagsire': {   'num': 195,
                    'name': 'Quagsire',
                    'types': ['Water', 'Ground'],
                    'baseStats': {'hp': 95, 'atk': 85, 'def': 85, 'spa': 65, 'spd': 65, 'spe': 35},
                    'abilities': {'0': 'Damp', '1': 'Water Absorb', 'H': 'Unaware'},
                    'heightm': 1.4,
                    'weightkg': 75,
                    'color': 'Blue',
                    'prevo': 'Wooper',
                    'evoLevel': 20,
                    'eggGroups': ['Water 1', 'Field']},
    'Espeon': {   'num': 196,
                  'name': 'Espeon',
                  'types': ['Psychic'],
                  'genderRatio': {'M': 0.875, 'F': 0.125},
                  'baseStats': {'hp': 65, 'atk': 65, 'def': 60, 'spa': 130, 'spd': 95, 'spe': 110},
                  'abilities': {'0': 'Synchronize', 'H': 'Magic Bounce'},
                  'heightm': 0.9,
                  'weightkg': 26.5,
                  'color': 'Purple',
                  'prevo': 'Eevee',
                  'evoType': 'levelFriendship',
                  'evoCondition': 'during the day',
                  'eggGroups': ['Field']},
    'Umbreon': {   'num': 197,
                   'name': 'Umbreon',
                   'types': ['Dark'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 95, 'atk': 65, 'def': 110, 'spa': 60, 'spd': 130, 'spe': 65},
                   'abilities': {'0': 'Synchronize', 'H': 'Inner Focus'},
                   'heightm': 1,
                   'weightkg': 27,
                   'color': 'Black',
                   'prevo': 'Eevee',
                   'evoType': 'levelFriendship',
                   'evoCondition': 'at night',
                   'eggGroups': ['Field']},
    'Murkrow': {   'num': 198,
                   'name': 'Murkrow',
                   'types': ['Dark', 'Flying'],
                   'baseStats': {'hp': 60, 'atk': 85, 'def': 42, 'spa': 85, 'spd': 42, 'spe': 91},
                   'abilities': {'0': 'Insomnia', '1': 'Super Luck', 'H': 'Prankster'},
                   'heightm': 0.5,
                   'weightkg': 2.1,
                   'color': 'Black',
                   'evos': ['Honchkrow'],
                   'eggGroups': ['Flying']},
    'Slowking': {   'num': 199,
                    'name': 'Slowking',
                    'types': ['Water', 'Psychic'],
                    'baseStats': {'hp': 95, 'atk': 75, 'def': 80, 'spa': 100, 'spd': 110, 'spe': 30},
                    'abilities': {'0': 'Oblivious', '1': 'Own Tempo', 'H': 'Regenerator'},
                    'heightm': 2,
                    'weightkg': 79.5,
                    'color': 'Pink',
                    'prevo': 'Slowpoke',
                    'evoType': 'trade',
                    'evoItem': "King's Rock",
                    'eggGroups': ['Monster', 'Water 1'],
                    'otherFormes': ['Slowking-Galar'],
                    'formeOrder': ['Slowking', 'Slowking-Galar']},
    'Slowkinggalar': {   'num': 199,
                         'name': 'Slowking-Galar',
                         'baseSpecies': 'Slowking',
                         'forme': 'Galar',
                         'types': ['Poison', 'Psychic'],
                         'baseStats': {'hp': 95, 'atk': 65, 'def': 80, 'spa': 110, 'spd': 110, 'spe': 30},
                         'abilities': {'0': 'Curious Medicine', '1': 'Own Tempo', 'H': 'Regenerator'},
                         'heightm': 1.8,
                         'weightkg': 79.5,
                         'color': 'Pink',
                         'prevo': 'Slowpoke-Galar',
                         'evoType': 'useItem',
                         'evoItem': 'Galarica Wreath',
                         'eggGroups': ['Monster', 'Water 1']},
    'Misdreavus': {   'num': 200,
                      'name': 'Misdreavus',
                      'types': ['Ghost'],
                      'baseStats': {'hp': 60, 'atk': 60, 'def': 60, 'spa': 85, 'spd': 85, 'spe': 85},
                      'abilities': {'0': 'Levitate'},
                      'heightm': 0.7,
                      'weightkg': 1,
                      'color': 'Gray',
                      'evos': ['Mismagius'],
                      'eggGroups': ['Amorphous']},
    'Unown': {   'num': 201,
                 'name': 'Unown',
                 'baseForme': 'A',
                 'types': ['Psychic'],
                 'gender': 'N',
                 'baseStats': {'hp': 48, 'atk': 72, 'def': 48, 'spa': 72, 'spd': 48, 'spe': 48},
                 'abilities': {'0': 'Levitate'},
                 'heightm': 0.5,
                 'weightkg': 5,
                 'color': 'Black',
                 'eggGroups': ['Undiscovered'],
                 'cosmeticFormes': [   'Unown-B',
                                       'Unown-C',
                                       'Unown-D',
                                       'Unown-E',
                                       'Unown-F',
                                       'Unown-G',
                                       'Unown-H',
                                       'Unown-I',
                                       'Unown-J',
                                       'Unown-K',
                                       'Unown-L',
                                       'Unown-M',
                                       'Unown-N',
                                       'Unown-O',
                                       'Unown-P',
                                       'Unown-Q',
                                       'Unown-R',
                                       'Unown-S',
                                       'Unown-T',
                                       'Unown-U',
                                       'Unown-V',
                                       'Unown-W',
                                       'Unown-X',
                                       'Unown-Y',
                                       'Unown-Z',
                                       'Unown-Exclamation',
                                       'Unown-Question'],
                 'formeOrder': [   'Unown',
                                   'Unown-B',
                                   'Unown-C',
                                   'Unown-D',
                                   'Unown-E',
                                   'Unown-F',
                                   'Unown-G',
                                   'Unown-H',
                                   'Unown-I',
                                   'Unown-J',
                                   'Unown-K',
                                   'Unown-L',
                                   'Unown-M',
                                   'Unown-N',
                                   'Unown-O',
                                   'Unown-P',
                                   'Unown-Q',
                                   'Unown-R',
                                   'Unown-S',
                                   'Unown-T',
                                   'Unown-U',
                                   'Unown-V',
                                   'Unown-W',
                                   'Unown-X',
                                   'Unown-Y',
                                   'Unown-Z',
                                   'Unown-Exclamation',
                                   'Unown-Question']},
    'Wobbuffet': {   'num': 202,
                     'name': 'Wobbuffet',
                     'types': ['Psychic'],
                     'baseStats': {'hp': 190, 'atk': 33, 'def': 58, 'spa': 33, 'spd': 58, 'spe': 33},
                     'abilities': {'0': 'Shadow Tag', 'H': 'Telepathy'},
                     'heightm': 1.3,
                     'weightkg': 28.5,
                     'color': 'Blue',
                     'prevo': 'Wynaut',
                     'evoLevel': 15,
                     'eggGroups': ['Amorphous'],
                     'canHatch': True},
    'Girafarig': {   'num': 203,
                     'name': 'Girafarig',
                     'types': ['Normal', 'Psychic'],
                     'baseStats': {'hp': 70, 'atk': 80, 'def': 65, 'spa': 90, 'spd': 65, 'spe': 85},
                     'abilities': {'0': 'Inner Focus', '1': 'Early Bird', 'H': 'Sap Sipper'},
                     'heightm': 1.5,
                     'weightkg': 41.5,
                     'color': 'Yellow',
                     'evos': ['Farigiraf'],
                     'eggGroups': ['Field']},
    'Pineco': {   'num': 204,
                  'name': 'Pineco',
                  'types': ['Bug'],
                  'baseStats': {'hp': 50, 'atk': 65, 'def': 90, 'spa': 35, 'spd': 35, 'spe': 15},
                  'abilities': {'0': 'Sturdy', 'H': 'Overcoat'},
                  'heightm': 0.6,
                  'weightkg': 7.2,
                  'color': 'Gray',
                  'evos': ['Forretress'],
                  'eggGroups': ['Bug']},
    'Forretress': {   'num': 205,
                      'name': 'Forretress',
                      'types': ['Bug', 'Steel'],
                      'baseStats': {'hp': 75, 'atk': 90, 'def': 140, 'spa': 60, 'spd': 60, 'spe': 40},
                      'abilities': {'0': 'Sturdy', 'H': 'Overcoat'},
                      'heightm': 1.2,
                      'weightkg': 125.8,
                      'color': 'Purple',
                      'prevo': 'Pineco',
                      'evoLevel': 31,
                      'eggGroups': ['Bug']},
    'Dunsparce': {   'num': 206,
                     'name': 'Dunsparce',
                     'types': ['Normal'],
                     'baseStats': {'hp': 100, 'atk': 70, 'def': 70, 'spa': 65, 'spd': 65, 'spe': 45},
                     'abilities': {'0': 'Serene Grace', '1': 'Run Away', 'H': 'Rattled'},
                     'heightm': 1.5,
                     'weightkg': 14,
                     'color': 'Yellow',
                     'evos': ['Dudunsparce', 'Dudunsparce-Three-Segment'],
                     'eggGroups': ['Field']},
    'Gligar': {   'num': 207,
                  'name': 'Gligar',
                  'types': ['Ground', 'Flying'],
                  'baseStats': {'hp': 65, 'atk': 75, 'def': 105, 'spa': 35, 'spd': 65, 'spe': 85},
                  'abilities': {'0': 'Hyper Cutter', '1': 'Sand Veil', 'H': 'Immunity'},
                  'heightm': 1.1,
                  'weightkg': 64.8,
                  'color': 'Purple',
                  'evos': ['Gliscor'],
                  'eggGroups': ['Bug']},
    'Steelix': {   'num': 208,
                   'name': 'Steelix',
                   'types': ['Steel', 'Ground'],
                   'baseStats': {'hp': 75, 'atk': 85, 'def': 200, 'spa': 55, 'spd': 65, 'spe': 30},
                   'abilities': {'0': 'Rock Head', '1': 'Sturdy', 'H': 'Sheer Force'},
                   'heightm': 9.2,
                   'weightkg': 400,
                   'color': 'Gray',
                   'prevo': 'Onix',
                   'evoType': 'trade',
                   'evoItem': 'Metal Coat',
                   'eggGroups': ['Mineral'],
                   'otherFormes': ['Steelix-Mega'],
                   'formeOrder': ['Steelix', 'Steelix-Mega']},
    'Steelixmega': {   'num': 208,
                       'name': 'Steelix-Mega',
                       'baseSpecies': 'Steelix',
                       'forme': 'Mega',
                       'types': ['Steel', 'Ground'],
                       'baseStats': {'hp': 75, 'atk': 125, 'def': 230, 'spa': 55, 'spd': 95, 'spe': 30},
                       'abilities': {'0': 'Sand Force'},
                       'heightm': 10.5,
                       'weightkg': 740,
                       'color': 'Gray',
                       'eggGroups': ['Mineral'],
                       'requiredItem': 'Steelixite'},
    'Snubbull': {   'num': 209,
                    'name': 'Snubbull',
                    'types': ['Fairy'],
                    'genderRatio': {'M': 0.25, 'F': 0.75},
                    'baseStats': {'hp': 60, 'atk': 80, 'def': 50, 'spa': 40, 'spd': 40, 'spe': 30},
                    'abilities': {'0': 'Intimidate', '1': 'Run Away', 'H': 'Rattled'},
                    'heightm': 0.6,
                    'weightkg': 7.8,
                    'color': 'Pink',
                    'evos': ['Granbull'],
                    'eggGroups': ['Field', 'Fairy']},
    'Granbull': {   'num': 210,
                    'name': 'Granbull',
                    'types': ['Fairy'],
                    'genderRatio': {'M': 0.25, 'F': 0.75},
                    'baseStats': {'hp': 90, 'atk': 120, 'def': 75, 'spa': 60, 'spd': 60, 'spe': 45},
                    'abilities': {'0': 'Intimidate', '1': 'Quick Feet', 'H': 'Rattled'},
                    'heightm': 1.4,
                    'weightkg': 48.7,
                    'color': 'Purple',
                    'prevo': 'Snubbull',
                    'evoLevel': 23,
                    'eggGroups': ['Field', 'Fairy']},
    'Qwilfish': {   'num': 211,
                    'name': 'Qwilfish',
                    'types': ['Water', 'Poison'],
                    'baseStats': {'hp': 65, 'atk': 95, 'def': 85, 'spa': 55, 'spd': 55, 'spe': 85},
                    'abilities': {'0': 'Poison Point', '1': 'Swift Swim', 'H': 'Intimidate'},
                    'heightm': 0.5,
                    'weightkg': 3.9,
                    'color': 'Gray',
                    'eggGroups': ['Water 2'],
                    'otherFormes': ['Qwilfish-Hisui'],
                    'formeOrder': ['Qwilfish', 'Qwilfish-Hisui']},
    'Qwilfishhisui': {   'num': 211,
                         'name': 'Qwilfish-Hisui',
                         'baseSpecies': 'Qwilfish',
                         'forme': 'Hisui',
                         'types': ['Dark', 'Poison'],
                         'baseStats': {'hp': 65, 'atk': 95, 'def': 85, 'spa': 55, 'spd': 55, 'spe': 85},
                         'abilities': {'0': 'Poison Point', '1': 'Swift Swim', 'H': 'Intimidate'},
                         'heightm': 0.5,
                         'weightkg': 3.9,
                         'color': 'Black',
                         'evos': ['Overqwil'],
                         'eggGroups': ['Water 2']},
    'Scizor': {   'num': 212,
                  'name': 'Scizor',
                  'types': ['Bug', 'Steel'],
                  'baseStats': {'hp': 70, 'atk': 130, 'def': 100, 'spa': 55, 'spd': 80, 'spe': 65},
                  'abilities': {'0': 'Swarm', '1': 'Technician', 'H': 'Light Metal'},
                  'heightm': 1.8,
                  'weightkg': 118,
                  'color': 'Red',
                  'prevo': 'Scyther',
                  'evoType': 'trade',
                  'evoItem': 'Metal Coat',
                  'eggGroups': ['Bug'],
                  'otherFormes': ['Scizor-Mega'],
                  'formeOrder': ['Scizor', 'Scizor-Mega']},
    'Scizormega': {   'num': 212,
                      'name': 'Scizor-Mega',
                      'baseSpecies': 'Scizor',
                      'forme': 'Mega',
                      'types': ['Bug', 'Steel'],
                      'baseStats': {'hp': 70, 'atk': 150, 'def': 140, 'spa': 65, 'spd': 100, 'spe': 75},
                      'abilities': {'0': 'Technician'},
                      'heightm': 2,
                      'weightkg': 125,
                      'color': 'Red',
                      'eggGroups': ['Bug'],
                      'requiredItem': 'Scizorite'},
    'Shuckle': {   'num': 213,
                   'name': 'Shuckle',
                   'types': ['Bug', 'Rock'],
                   'baseStats': {'hp': 20, 'atk': 10, 'def': 230, 'spa': 10, 'spd': 230, 'spe': 5},
                   'abilities': {'0': 'Sturdy', '1': 'Gluttony', 'H': 'Contrary'},
                   'heightm': 0.6,
                   'weightkg': 20.5,
                   'color': 'Yellow',
                   'eggGroups': ['Bug']},
    'Heracross': {   'num': 214,
                     'name': 'Heracross',
                     'types': ['Bug', 'Fighting'],
                     'baseStats': {'hp': 80, 'atk': 125, 'def': 75, 'spa': 40, 'spd': 95, 'spe': 85},
                     'abilities': {'0': 'Swarm', '1': 'Guts', 'H': 'Moxie'},
                     'heightm': 1.5,
                     'weightkg': 54,
                     'color': 'Blue',
                     'eggGroups': ['Bug'],
                     'otherFormes': ['Heracross-Mega'],
                     'formeOrder': ['Heracross', 'Heracross-Mega']},
    'Heracrossmega': {   'num': 214,
                         'name': 'Heracross-Mega',
                         'baseSpecies': 'Heracross',
                         'forme': 'Mega',
                         'types': ['Bug', 'Fighting'],
                         'baseStats': {'hp': 80, 'atk': 185, 'def': 115, 'spa': 40, 'spd': 105, 'spe': 75},
                         'abilities': {'0': 'Skill Link'},
                         'heightm': 1.7,
                         'weightkg': 62.5,
                         'color': 'Blue',
                         'eggGroups': ['Bug'],
                         'requiredItem': 'Heracronite'},
    'Sneasel': {   'num': 215,
                   'name': 'Sneasel',
                   'types': ['Dark', 'Ice'],
                   'baseStats': {'hp': 55, 'atk': 95, 'def': 55, 'spa': 35, 'spd': 75, 'spe': 115},
                   'abilities': {'0': 'Inner Focus', '1': 'Keen Eye', 'H': 'Pickpocket'},
                   'heightm': 0.9,
                   'weightkg': 28,
                   'color': 'Black',
                   'evos': ['Weavile'],
                   'eggGroups': ['Field'],
                   'otherFormes': ['Sneasel-Hisui'],
                   'formeOrder': ['Sneasel', 'Sneasel-Hisui']},
    'Sneaselhisui': {   'num': 215,
                        'name': 'Sneasel-Hisui',
                        'baseSpecies': 'Sneasel',
                        'forme': 'Hisui',
                        'types': ['Fighting', 'Poison'],
                        'baseStats': {'hp': 55, 'atk': 95, 'def': 55, 'spa': 35, 'spd': 75, 'spe': 115},
                        'abilities': {'0': 'Inner Focus', '1': 'Keen Eye', 'H': 'Pickpocket'},
                        'heightm': 0.9,
                        'weightkg': 27,
                        'color': 'Gray',
                        'evos': ['Sneasler'],
                        'eggGroups': ['Field']},
    'Teddiursa': {   'num': 216,
                     'name': 'Teddiursa',
                     'types': ['Normal'],
                     'baseStats': {'hp': 60, 'atk': 80, 'def': 50, 'spa': 50, 'spd': 50, 'spe': 40},
                     'abilities': {'0': 'Pickup', '1': 'Quick Feet', 'H': 'Honey Gather'},
                     'heightm': 0.6,
                     'weightkg': 8.8,
                     'color': 'Brown',
                     'evos': ['Ursaring'],
                     'eggGroups': ['Field']},
    'Ursaring': {   'num': 217,
                    'name': 'Ursaring',
                    'types': ['Normal'],
                    'baseStats': {'hp': 90, 'atk': 130, 'def': 75, 'spa': 75, 'spd': 75, 'spe': 55},
                    'abilities': {'0': 'Guts', '1': 'Quick Feet', 'H': 'Unnerve'},
                    'heightm': 1.8,
                    'weightkg': 125.8,
                    'color': 'Brown',
                    'prevo': 'Teddiursa',
                    'evoLevel': 30,
                    'evos': ['Ursaluna'],
                    'eggGroups': ['Field']},
    'Slugma': {   'num': 218,
                  'name': 'Slugma',
                  'types': ['Fire'],
                  'baseStats': {'hp': 40, 'atk': 40, 'def': 40, 'spa': 70, 'spd': 40, 'spe': 20},
                  'abilities': {'0': 'Magma Armor', '1': 'Flame Body', 'H': 'Weak Armor'},
                  'heightm': 0.7,
                  'weightkg': 35,
                  'color': 'Red',
                  'evos': ['Magcargo'],
                  'eggGroups': ['Amorphous']},
    'Magcargo': {   'num': 219,
                    'name': 'Magcargo',
                    'types': ['Fire', 'Rock'],
                    'baseStats': {'hp': 60, 'atk': 50, 'def': 120, 'spa': 90, 'spd': 80, 'spe': 30},
                    'abilities': {'0': 'Magma Armor', '1': 'Flame Body', 'H': 'Weak Armor'},
                    'heightm': 0.8,
                    'weightkg': 55,
                    'color': 'Red',
                    'prevo': 'Slugma',
                    'evoLevel': 38,
                    'eggGroups': ['Amorphous']},
    'Swinub': {   'num': 220,
                  'name': 'Swinub',
                  'types': ['Ice', 'Ground'],
                  'baseStats': {'hp': 50, 'atk': 50, 'def': 40, 'spa': 30, 'spd': 30, 'spe': 50},
                  'abilities': {'0': 'Oblivious', '1': 'Snow Cloak', 'H': 'Thick Fat'},
                  'heightm': 0.4,
                  'weightkg': 6.5,
                  'color': 'Brown',
                  'evos': ['Piloswine'],
                  'eggGroups': ['Field']},
    'Piloswine': {   'num': 221,
                     'name': 'Piloswine',
                     'types': ['Ice', 'Ground'],
                     'baseStats': {'hp': 100, 'atk': 100, 'def': 80, 'spa': 60, 'spd': 60, 'spe': 50},
                     'abilities': {'0': 'Oblivious', '1': 'Snow Cloak', 'H': 'Thick Fat'},
                     'heightm': 1.1,
                     'weightkg': 55.8,
                     'color': 'Brown',
                     'prevo': 'Swinub',
                     'evoLevel': 33,
                     'evos': ['Mamoswine'],
                     'eggGroups': ['Field']},
    'Corsola': {   'num': 222,
                   'name': 'Corsola',
                   'types': ['Water', 'Rock'],
                   'genderRatio': {'M': 0.25, 'F': 0.75},
                   'baseStats': {'hp': 65, 'atk': 55, 'def': 95, 'spa': 65, 'spd': 95, 'spe': 35},
                   'abilities': {'0': 'Hustle', '1': 'Natural Cure', 'H': 'Regenerator'},
                   'heightm': 0.6,
                   'weightkg': 5,
                   'color': 'Pink',
                   'eggGroups': ['Water 1', 'Water 3'],
                   'otherFormes': ['Corsola-Galar'],
                   'formeOrder': ['Corsola', 'Corsola-Galar']},
    'Corsolagalar': {   'num': 222,
                        'name': 'Corsola-Galar',
                        'baseSpecies': 'Corsola',
                        'forme': 'Galar',
                        'types': ['Ghost'],
                        'genderRatio': {'M': 0.25, 'F': 0.75},
                        'baseStats': {'hp': 60, 'atk': 55, 'def': 100, 'spa': 65, 'spd': 100, 'spe': 30},
                        'abilities': {'0': 'Weak Armor', 'H': 'Cursed Body'},
                        'heightm': 0.6,
                        'weightkg': 0.5,
                        'color': 'White',
                        'evos': ['Cursola'],
                        'eggGroups': ['Water 1', 'Water 3']},
    'Remoraid': {   'num': 223,
                    'name': 'Remoraid',
                    'types': ['Water'],
                    'baseStats': {'hp': 35, 'atk': 65, 'def': 35, 'spa': 65, 'spd': 35, 'spe': 65},
                    'abilities': {'0': 'Hustle', '1': 'Sniper', 'H': 'Moody'},
                    'heightm': 0.6,
                    'weightkg': 12,
                    'color': 'Gray',
                    'evos': ['Octillery'],
                    'eggGroups': ['Water 1', 'Water 2']},
    'Octillery': {   'num': 224,
                     'name': 'Octillery',
                     'types': ['Water'],
                     'baseStats': {'hp': 75, 'atk': 105, 'def': 75, 'spa': 105, 'spd': 75, 'spe': 45},
                     'abilities': {'0': 'Suction Cups', '1': 'Sniper', 'H': 'Moody'},
                     'heightm': 0.9,
                     'weightkg': 28.5,
                     'color': 'Red',
                     'prevo': 'Remoraid',
                     'evoLevel': 25,
                     'eggGroups': ['Water 1', 'Water 2']},
    'Delibird': {   'num': 225,
                    'name': 'Delibird',
                    'types': ['Ice', 'Flying'],
                    'baseStats': {'hp': 45, 'atk': 55, 'def': 45, 'spa': 65, 'spd': 45, 'spe': 75},
                    'abilities': {'0': 'Vital Spirit', '1': 'Hustle', 'H': 'Insomnia'},
                    'heightm': 0.9,
                    'weightkg': 16,
                    'color': 'Red',
                    'eggGroups': ['Water 1', 'Field']},
    'Mantine': {   'num': 226,
                   'name': 'Mantine',
                   'types': ['Water', 'Flying'],
                   'baseStats': {'hp': 85, 'atk': 40, 'def': 70, 'spa': 80, 'spd': 140, 'spe': 70},
                   'abilities': {'0': 'Swift Swim', '1': 'Water Absorb', 'H': 'Water Veil'},
                   'heightm': 2.1,
                   'weightkg': 220,
                   'color': 'Purple',
                   'prevo': 'Mantyke',
                   'evoType': 'levelExtra',
                   'evoCondition': 'with a Remoraid in party',
                   'eggGroups': ['Water 1'],
                   'canHatch': True},
    'Skarmory': {   'num': 227,
                    'name': 'Skarmory',
                    'types': ['Steel', 'Flying'],
                    'baseStats': {'hp': 65, 'atk': 80, 'def': 140, 'spa': 40, 'spd': 70, 'spe': 70},
                    'abilities': {'0': 'Keen Eye', '1': 'Sturdy', 'H': 'Weak Armor'},
                    'heightm': 1.7,
                    'weightkg': 50.5,
                    'color': 'Gray',
                    'eggGroups': ['Flying']},
    'Houndour': {   'num': 228,
                    'name': 'Houndour',
                    'types': ['Dark', 'Fire'],
                    'baseStats': {'hp': 45, 'atk': 60, 'def': 30, 'spa': 80, 'spd': 50, 'spe': 65},
                    'abilities': {'0': 'Early Bird', '1': 'Flash Fire', 'H': 'Unnerve'},
                    'heightm': 0.6,
                    'weightkg': 10.8,
                    'color': 'Black',
                    'evos': ['Houndoom'],
                    'eggGroups': ['Field']},
    'Houndoom': {   'num': 229,
                    'name': 'Houndoom',
                    'types': ['Dark', 'Fire'],
                    'baseStats': {'hp': 75, 'atk': 90, 'def': 50, 'spa': 110, 'spd': 80, 'spe': 95},
                    'abilities': {'0': 'Early Bird', '1': 'Flash Fire', 'H': 'Unnerve'},
                    'heightm': 1.4,
                    'weightkg': 35,
                    'color': 'Black',
                    'prevo': 'Houndour',
                    'evoLevel': 24,
                    'eggGroups': ['Field'],
                    'otherFormes': ['Houndoom-Mega'],
                    'formeOrder': ['Houndoom', 'Houndoom-Mega']},
    'Houndoommega': {   'num': 229,
                        'name': 'Houndoom-Mega',
                        'baseSpecies': 'Houndoom',
                        'forme': 'Mega',
                        'types': ['Dark', 'Fire'],
                        'baseStats': {'hp': 75, 'atk': 90, 'def': 90, 'spa': 140, 'spd': 90, 'spe': 115},
                        'abilities': {'0': 'Solar Power'},
                        'heightm': 1.9,
                        'weightkg': 49.5,
                        'color': 'Black',
                        'eggGroups': ['Field'],
                        'requiredItem': 'Houndoominite'},
    'Kingdra': {   'num': 230,
                   'name': 'Kingdra',
                   'types': ['Water', 'Dragon'],
                   'baseStats': {'hp': 75, 'atk': 95, 'def': 95, 'spa': 95, 'spd': 95, 'spe': 85},
                   'abilities': {'0': 'Swift Swim', '1': 'Sniper', 'H': 'Damp'},
                   'heightm': 1.8,
                   'weightkg': 152,
                   'color': 'Blue',
                   'prevo': 'Seadra',
                   'evoType': 'trade',
                   'evoItem': 'Dragon Scale',
                   'eggGroups': ['Water 1', 'Dragon']},
    'Phanpy': {   'num': 231,
                  'name': 'Phanpy',
                  'types': ['Ground'],
                  'baseStats': {'hp': 90, 'atk': 60, 'def': 60, 'spa': 40, 'spd': 40, 'spe': 40},
                  'abilities': {'0': 'Pickup', 'H': 'Sand Veil'},
                  'heightm': 0.5,
                  'weightkg': 33.5,
                  'color': 'Blue',
                  'evos': ['Donphan'],
                  'eggGroups': ['Field']},
    'Donphan': {   'num': 232,
                   'name': 'Donphan',
                   'types': ['Ground'],
                   'baseStats': {'hp': 90, 'atk': 120, 'def': 120, 'spa': 60, 'spd': 60, 'spe': 50},
                   'abilities': {'0': 'Sturdy', 'H': 'Sand Veil'},
                   'heightm': 1.1,
                   'weightkg': 120,
                   'color': 'Gray',
                   'prevo': 'Phanpy',
                   'evoLevel': 25,
                   'eggGroups': ['Field']},
    'Porygon2': {   'num': 233,
                    'name': 'Porygon2',
                    'types': ['Normal'],
                    'gender': 'N',
                    'baseStats': {'hp': 85, 'atk': 80, 'def': 90, 'spa': 105, 'spd': 95, 'spe': 60},
                    'abilities': {'0': 'Trace', '1': 'Download', 'H': 'Analytic'},
                    'heightm': 0.6,
                    'weightkg': 32.5,
                    'color': 'Red',
                    'prevo': 'Porygon',
                    'evoType': 'trade',
                    'evoItem': 'Up-Grade',
                    'evos': ['Porygon-Z'],
                    'eggGroups': ['Mineral']},
    'Stantler': {   'num': 234,
                    'name': 'Stantler',
                    'types': ['Normal'],
                    'baseStats': {'hp': 73, 'atk': 95, 'def': 62, 'spa': 85, 'spd': 65, 'spe': 85},
                    'abilities': {'0': 'Intimidate', '1': 'Frisk', 'H': 'Sap Sipper'},
                    'heightm': 1.4,
                    'weightkg': 71.2,
                    'color': 'Brown',
                    'evos': ['Wyrdeer'],
                    'eggGroups': ['Field']},
    'Smeargle': {   'num': 235,
                    'name': 'Smeargle',
                    'types': ['Normal'],
                    'baseStats': {'hp': 55, 'atk': 20, 'def': 35, 'spa': 20, 'spd': 45, 'spe': 75},
                    'abilities': {'0': 'Own Tempo', '1': 'Technician', 'H': 'Moody'},
                    'heightm': 1.2,
                    'weightkg': 58,
                    'color': 'White',
                    'eggGroups': ['Field']},
    'Tyrogue': {   'num': 236,
                   'name': 'Tyrogue',
                   'types': ['Fighting'],
                   'gender': 'M',
                   'baseStats': {'hp': 35, 'atk': 35, 'def': 35, 'spa': 35, 'spd': 35, 'spe': 35},
                   'abilities': {'0': 'Guts', '1': 'Steadfast', 'H': 'Vital Spirit'},
                   'heightm': 0.7,
                   'weightkg': 21,
                   'color': 'Purple',
                   'evos': ['Hitmonlee', 'Hitmonchan', 'Hitmontop'],
                   'eggGroups': ['Undiscovered'],
                   'canHatch': True},
    'Hitmontop': {   'num': 237,
                     'name': 'Hitmontop',
                     'types': ['Fighting'],
                     'gender': 'M',
                     'baseStats': {'hp': 50, 'atk': 95, 'def': 95, 'spa': 35, 'spd': 110, 'spe': 70},
                     'abilities': {'0': 'Intimidate', '1': 'Technician', 'H': 'Steadfast'},
                     'heightm': 1.4,
                     'weightkg': 48,
                     'color': 'Brown',
                     'prevo': 'Tyrogue',
                     'evoLevel': 20,
                     'evoCondition': 'with an Atk stat equal to its Def stat',
                     'eggGroups': ['Human-Like']},
    'Smoochum': {   'num': 238,
                    'name': 'Smoochum',
                    'types': ['Ice', 'Psychic'],
                    'gender': 'F',
                    'baseStats': {'hp': 45, 'atk': 30, 'def': 15, 'spa': 85, 'spd': 65, 'spe': 65},
                    'abilities': {'0': 'Oblivious', '1': 'Forewarn', 'H': 'Hydration'},
                    'heightm': 0.4,
                    'weightkg': 6,
                    'color': 'Pink',
                    'evos': ['Jynx'],
                    'eggGroups': ['Undiscovered'],
                    'canHatch': True},
    'Elekid': {   'num': 239,
                  'name': 'Elekid',
                  'types': ['Electric'],
                  'genderRatio': {'M': 0.75, 'F': 0.25},
                  'baseStats': {'hp': 45, 'atk': 63, 'def': 37, 'spa': 65, 'spd': 55, 'spe': 95},
                  'abilities': {'0': 'Static', 'H': 'Vital Spirit'},
                  'heightm': 0.6,
                  'weightkg': 23.5,
                  'color': 'Yellow',
                  'evos': ['Electabuzz'],
                  'eggGroups': ['Undiscovered'],
                  'canHatch': True},
    'Magby': {   'num': 240,
                 'name': 'Magby',
                 'types': ['Fire'],
                 'genderRatio': {'M': 0.75, 'F': 0.25},
                 'baseStats': {'hp': 45, 'atk': 75, 'def': 37, 'spa': 70, 'spd': 55, 'spe': 83},
                 'abilities': {'0': 'Flame Body', 'H': 'Vital Spirit'},
                 'heightm': 0.7,
                 'weightkg': 21.4,
                 'color': 'Red',
                 'evos': ['Magmar'],
                 'eggGroups': ['Undiscovered'],
                 'canHatch': True},
    'Miltank': {   'num': 241,
                   'name': 'Miltank',
                   'types': ['Normal'],
                   'gender': 'F',
                   'baseStats': {'hp': 95, 'atk': 80, 'def': 105, 'spa': 40, 'spd': 70, 'spe': 100},
                   'abilities': {'0': 'Thick Fat', '1': 'Scrappy', 'H': 'Sap Sipper'},
                   'heightm': 1.2,
                   'weightkg': 75.5,
                   'color': 'Pink',
                   'eggGroups': ['Field']},
    'Blissey': {   'num': 242,
                   'name': 'Blissey',
                   'types': ['Normal'],
                   'gender': 'F',
                   'baseStats': {'hp': 255, 'atk': 10, 'def': 10, 'spa': 75, 'spd': 135, 'spe': 55},
                   'abilities': {'0': 'Natural Cure', '1': 'Serene Grace', 'H': 'Healer'},
                   'heightm': 1.5,
                   'weightkg': 46.8,
                   'color': 'Pink',
                   'prevo': 'Chansey',
                   'evoType': 'levelFriendship',
                   'eggGroups': ['Fairy']},
    'Raikou': {   'num': 243,
                  'name': 'Raikou',
                  'types': ['Electric'],
                  'gender': 'N',
                  'baseStats': {'hp': 90, 'atk': 85, 'def': 75, 'spa': 115, 'spd': 100, 'spe': 115},
                  'abilities': {'0': 'Pressure', 'H': 'Inner Focus'},
                  'heightm': 1.9,
                  'weightkg': 178,
                  'color': 'Yellow',
                  'tags': ['Sub-Legendary'],
                  'eggGroups': ['Undiscovered']},
    'Entei': {   'num': 244,
                 'name': 'Entei',
                 'types': ['Fire'],
                 'gender': 'N',
                 'baseStats': {'hp': 115, 'atk': 115, 'def': 85, 'spa': 90, 'spd': 75, 'spe': 100},
                 'abilities': {'0': 'Pressure', 'H': 'Inner Focus'},
                 'heightm': 2.1,
                 'weightkg': 198,
                 'color': 'Brown',
                 'tags': ['Sub-Legendary'],
                 'eggGroups': ['Undiscovered']},
    'Suicune': {   'num': 245,
                   'name': 'Suicune',
                   'types': ['Water'],
                   'gender': 'N',
                   'baseStats': {'hp': 100, 'atk': 75, 'def': 115, 'spa': 90, 'spd': 115, 'spe': 85},
                   'abilities': {'0': 'Pressure', 'H': 'Inner Focus'},
                   'heightm': 2,
                   'weightkg': 187,
                   'color': 'Blue',
                   'tags': ['Sub-Legendary'],
                   'eggGroups': ['Undiscovered']},
    'Larvitar': {   'num': 246,
                    'name': 'Larvitar',
                    'types': ['Rock', 'Ground'],
                    'baseStats': {'hp': 50, 'atk': 64, 'def': 50, 'spa': 45, 'spd': 50, 'spe': 41},
                    'abilities': {'0': 'Guts', 'H': 'Sand Veil'},
                    'heightm': 0.6,
                    'weightkg': 72,
                    'color': 'Green',
                    'evos': ['Pupitar'],
                    'eggGroups': ['Monster']},
    'Pupitar': {   'num': 247,
                   'name': 'Pupitar',
                   'types': ['Rock', 'Ground'],
                   'baseStats': {'hp': 70, 'atk': 84, 'def': 70, 'spa': 65, 'spd': 70, 'spe': 51},
                   'abilities': {'0': 'Shed Skin'},
                   'heightm': 1.2,
                   'weightkg': 152,
                   'color': 'Gray',
                   'prevo': 'Larvitar',
                   'evoLevel': 30,
                   'evos': ['Tyranitar'],
                   'eggGroups': ['Monster']},
    'Tyranitar': {   'num': 248,
                     'name': 'Tyranitar',
                     'types': ['Rock', 'Dark'],
                     'baseStats': {'hp': 100, 'atk': 134, 'def': 110, 'spa': 95, 'spd': 100, 'spe': 61},
                     'abilities': {'0': 'Sand Stream', 'H': 'Unnerve'},
                     'heightm': 2,
                     'weightkg': 202,
                     'color': 'Green',
                     'prevo': 'Pupitar',
                     'evoLevel': 55,
                     'eggGroups': ['Monster'],
                     'otherFormes': ['Tyranitar-Mega'],
                     'formeOrder': ['Tyranitar', 'Tyranitar-Mega']},
    'Tyranitarmega': {   'num': 248,
                         'name': 'Tyranitar-Mega',
                         'baseSpecies': 'Tyranitar',
                         'forme': 'Mega',
                         'types': ['Rock', 'Dark'],
                         'baseStats': {'hp': 100, 'atk': 164, 'def': 150, 'spa': 95, 'spd': 120, 'spe': 71},
                         'abilities': {'0': 'Sand Stream'},
                         'heightm': 2.5,
                         'weightkg': 255,
                         'color': 'Green',
                         'eggGroups': ['Monster'],
                         'requiredItem': 'Tyranitarite'},
    'Lugia': {   'num': 249,
                 'name': 'Lugia',
                 'types': ['Psychic', 'Flying'],
                 'gender': 'N',
                 'baseStats': {'hp': 106, 'atk': 90, 'def': 130, 'spa': 90, 'spd': 154, 'spe': 110},
                 'abilities': {'0': 'Pressure', 'H': 'Multiscale'},
                 'heightm': 5.2,
                 'weightkg': 216,
                 'color': 'White',
                 'tags': ['Restricted Legendary'],
                 'eggGroups': ['Undiscovered']},
    'Hooh': {   'num': 250,
                'name': 'Ho-Oh',
                'types': ['Fire', 'Flying'],
                'gender': 'N',
                'baseStats': {'hp': 106, 'atk': 130, 'def': 90, 'spa': 110, 'spd': 154, 'spe': 90},
                'abilities': {'0': 'Pressure', 'H': 'Regenerator'},
                'heightm': 3.8,
                'weightkg': 199,
                'color': 'Red',
                'tags': ['Restricted Legendary'],
                'eggGroups': ['Undiscovered']},
    'Celebi': {   'num': 251,
                  'name': 'Celebi',
                  'types': ['Psychic', 'Grass'],
                  'gender': 'N',
                  'baseStats': {'hp': 100, 'atk': 100, 'def': 100, 'spa': 100, 'spd': 100, 'spe': 100},
                  'abilities': {'0': 'Natural Cure'},
                  'heightm': 0.6,
                  'weightkg': 5,
                  'color': 'Green',
                  'tags': ['Mythical'],
                  'eggGroups': ['Undiscovered']}}
