"""Pokédex entries for Kalos region."""
from ..functions.pokedex_funcs import *

pokedex = {
    'Chespin': {   'num': 650,
                   'name': 'Chespin',
                   'types': ['Grass'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 56, 'atk': 61, 'def': 65, 'spa': 48, 'spd': 45, 'spe': 38},
                   'abilities': {'0': 'Overgrow', 'H': 'Bulletproof'},
                   'heightm': 0.4,
                   'weightkg': 9,
                   'color': 'Green',
                   'evos': ['Quilladin'],
                   'eggGroups': ['Field']},
    'Quilladin': {   'num': 651,
                     'name': 'Quilladin',
                     'types': ['Grass'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 61, 'atk': 78, 'def': 95, 'spa': 56, 'spd': 58, 'spe': 57},
                     'abilities': {'0': 'Overgrow', 'H': 'Bulletproof'},
                     'heightm': 0.7,
                     'weightkg': 29,
                     'color': 'Green',
                     'prevo': 'Chespin',
                     'evoLevel': 16,
                     'evos': ['Chesnaught'],
                     'eggGroups': ['Field']},
    'Chesnaught': {   'num': 652,
                      'name': 'Chesnaught',
                      'types': ['Grass', 'Fighting'],
                      'genderRatio': {'M': 0.875, 'F': 0.125},
                      'baseStats': {'hp': 88, 'atk': 107, 'def': 122, 'spa': 74, 'spd': 75, 'spe': 64},
                      'abilities': {'0': 'Overgrow', 'H': 'Bulletproof'},
                      'heightm': 1.6,
                      'weightkg': 90,
                      'color': 'Green',
                      'prevo': 'Quilladin',
                      'evoLevel': 36,
                      'eggGroups': ['Field']},
    'Fennekin': {   'num': 653,
                    'name': 'Fennekin',
                    'types': ['Fire'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 40, 'atk': 45, 'def': 40, 'spa': 62, 'spd': 60, 'spe': 60},
                    'abilities': {'0': 'Blaze', 'H': 'Magician'},
                    'heightm': 0.4,
                    'weightkg': 9.4,
                    'color': 'Red',
                    'evos': ['Braixen'],
                    'eggGroups': ['Field']},
    'Braixen': {   'num': 654,
                   'name': 'Braixen',
                   'types': ['Fire'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 59, 'atk': 59, 'def': 58, 'spa': 90, 'spd': 70, 'spe': 73},
                   'abilities': {'0': 'Blaze', 'H': 'Magician'},
                   'heightm': 1,
                   'weightkg': 14.5,
                   'color': 'Red',
                   'prevo': 'Fennekin',
                   'evoLevel': 16,
                   'evos': ['Delphox'],
                   'eggGroups': ['Field']},
    'Delphox': {   'num': 655,
                   'name': 'Delphox',
                   'types': ['Fire', 'Psychic'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 75, 'atk': 69, 'def': 72, 'spa': 114, 'spd': 100, 'spe': 104},
                   'abilities': {'0': 'Blaze', 'H': 'Magician'},
                   'heightm': 1.5,
                   'weightkg': 39,
                   'color': 'Red',
                   'prevo': 'Braixen',
                   'evoLevel': 36,
                   'eggGroups': ['Field']},
    'Froakie': {   'num': 656,
                   'name': 'Froakie',
                   'types': ['Water'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 41, 'atk': 56, 'def': 40, 'spa': 62, 'spd': 44, 'spe': 71},
                   'abilities': {'0': 'Torrent', 'H': 'Protean'},
                   'heightm': 0.3,
                   'weightkg': 7,
                   'color': 'Blue',
                   'evos': ['Frogadier'],
                   'eggGroups': ['Water 1']},
    'Frogadier': {   'num': 657,
                     'name': 'Frogadier',
                     'types': ['Water'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 54, 'atk': 63, 'def': 52, 'spa': 83, 'spd': 56, 'spe': 97},
                     'abilities': {'0': 'Torrent', 'H': 'Protean'},
                     'heightm': 0.6,
                     'weightkg': 10.9,
                     'color': 'Blue',
                     'prevo': 'Froakie',
                     'evoLevel': 16,
                     'evos': ['Greninja'],
                     'eggGroups': ['Water 1']},
    'Greninja': {   'num': 658,
                    'name': 'Greninja',
                    'types': ['Water', 'Dark'],
                    'genderRatio': {'M': 0.875, 'F': 0.125},
                    'baseStats': {'hp': 72, 'atk': 95, 'def': 67, 'spa': 103, 'spd': 71, 'spe': 122},
                    'abilities': {'0': 'Torrent', 'H': 'Protean', 'S': 'Battle Bond'},
                    'heightm': 1.5,
                    'weightkg': 40,
                    'color': 'Blue',
                    'prevo': 'Frogadier',
                    'evoLevel': 36,
                    'eggGroups': ['Water 1'],
                    'otherFormes': ['Greninja-Bond', 'Greninja-Ash'],
                    'formeOrder': ['Greninja', 'Greninja-Bond', 'Greninja-Ash']},
    'Greninjabond': {   'num': 658,
                        'name': 'Greninja-Bond',
                        'baseSpecies': 'Greninja',
                        'forme': 'Bond',
                        'types': ['Water', 'Dark'],
                        'gender': 'M',
                        'baseStats': {'hp': 72, 'atk': 95, 'def': 67, 'spa': 103, 'spd': 71, 'spe': 122},
                        'abilities': {'0': 'Battle Bond'},
                        'heightm': 1.5,
                        'weightkg': 40,
                        'color': 'Blue',
                        'eggGroups': ['Undiscovered'],
                        'gen': 7},
    'Greninjaash': {   'num': 658,
                       'name': 'Greninja-Ash',
                       'baseSpecies': 'Greninja',
                       'forme': 'Ash',
                       'types': ['Water', 'Dark'],
                       'gender': 'M',
                       'baseStats': {'hp': 72, 'atk': 145, 'def': 67, 'spa': 153, 'spd': 71, 'spe': 132},
                       'abilities': {'0': 'Battle Bond'},
                       'heightm': 1.5,
                       'weightkg': 40,
                       'color': 'Blue',
                       'eggGroups': ['Undiscovered'],
                       'requiredAbility': 'Battle Bond',
                       'battleOnly': 'Greninja-Bond',
                       'gen': 7},
    'Bunnelby': {   'num': 659,
                    'name': 'Bunnelby',
                    'types': ['Normal'],
                    'baseStats': {'hp': 38, 'atk': 36, 'def': 38, 'spa': 32, 'spd': 36, 'spe': 57},
                    'abilities': {'0': 'Pickup', '1': 'Cheek Pouch', 'H': 'Huge Power'},
                    'heightm': 0.4,
                    'weightkg': 5,
                    'color': 'Brown',
                    'evos': ['Diggersby'],
                    'eggGroups': ['Field']},
    'Diggersby': {   'num': 660,
                     'name': 'Diggersby',
                     'types': ['Normal', 'Ground'],
                     'baseStats': {'hp': 85, 'atk': 56, 'def': 77, 'spa': 50, 'spd': 77, 'spe': 78},
                     'abilities': {'0': 'Pickup', '1': 'Cheek Pouch', 'H': 'Huge Power'},
                     'heightm': 1,
                     'weightkg': 42.4,
                     'color': 'Brown',
                     'prevo': 'Bunnelby',
                     'evoLevel': 20,
                     'eggGroups': ['Field']},
    'Fletchling': {   'num': 661,
                      'name': 'Fletchling',
                      'types': ['Normal', 'Flying'],
                      'baseStats': {'hp': 45, 'atk': 50, 'def': 43, 'spa': 40, 'spd': 38, 'spe': 62},
                      'abilities': {'0': 'Big Pecks', 'H': 'Gale Wings'},
                      'heightm': 0.3,
                      'weightkg': 1.7,
                      'color': 'Red',
                      'evos': ['Fletchinder'],
                      'eggGroups': ['Flying']},
    'Fletchinder': {   'num': 662,
                       'name': 'Fletchinder',
                       'types': ['Fire', 'Flying'],
                       'baseStats': {'hp': 62, 'atk': 73, 'def': 55, 'spa': 56, 'spd': 52, 'spe': 84},
                       'abilities': {'0': 'Flame Body', 'H': 'Gale Wings'},
                       'heightm': 0.7,
                       'weightkg': 16,
                       'color': 'Red',
                       'prevo': 'Fletchling',
                       'evoLevel': 17,
                       'evos': ['Talonflame'],
                       'eggGroups': ['Flying']},
    'Talonflame': {   'num': 663,
                      'name': 'Talonflame',
                      'types': ['Fire', 'Flying'],
                      'baseStats': {'hp': 78, 'atk': 81, 'def': 71, 'spa': 74, 'spd': 69, 'spe': 126},
                      'abilities': {'0': 'Flame Body', 'H': 'Gale Wings'},
                      'heightm': 1.2,
                      'weightkg': 24.5,
                      'color': 'Red',
                      'prevo': 'Fletchinder',
                      'evoLevel': 35,
                      'eggGroups': ['Flying']},
    'Scatterbug': {   'num': 664,
                      'name': 'Scatterbug',
                      'types': ['Bug'],
                      'baseStats': {'hp': 38, 'atk': 35, 'def': 40, 'spa': 27, 'spd': 25, 'spe': 35},
                      'abilities': {'0': 'Shield Dust', '1': 'Compound Eyes', 'H': 'Friend Guard'},
                      'heightm': 0.3,
                      'weightkg': 2.5,
                      'color': 'Black',
                      'evos': ['Spewpa'],
                      'eggGroups': ['Bug']},
    'Spewpa': {   'num': 665,
                  'name': 'Spewpa',
                  'types': ['Bug'],
                  'baseStats': {'hp': 45, 'atk': 22, 'def': 60, 'spa': 27, 'spd': 30, 'spe': 29},
                  'abilities': {'0': 'Shed Skin', 'H': 'Friend Guard'},
                  'heightm': 0.3,
                  'weightkg': 8.4,
                  'color': 'Black',
                  'prevo': 'Scatterbug',
                  'evoLevel': 9,
                  'evos': ['Vivillon', 'Vivillon-Fancy'],
                  'eggGroups': ['Bug']},
    'Vivillon': {   'num': 666,
                    'name': 'Vivillon',
                    'baseForme': 'Meadow',
                    'types': ['Bug', 'Flying'],
                    'baseStats': {'hp': 80, 'atk': 52, 'def': 50, 'spa': 90, 'spd': 50, 'spe': 89},
                    'abilities': {'0': 'Shield Dust', '1': 'Compound Eyes', 'H': 'Friend Guard'},
                    'heightm': 1.2,
                    'weightkg': 17,
                    'color': 'White',
                    'prevo': 'Spewpa',
                    'evoLevel': 12,
                    'eggGroups': ['Bug'],
                    'otherFormes': ['Vivillon-Fancy', 'Vivillon-Pokeball'],
                    'cosmeticFormes': [   'Vivillon-Archipelago',
                                          'Vivillon-Continental',
                                          'Vivillon-Elegant',
                                          'Vivillon-Garden',
                                          'Vivillon-High Plains',
                                          'Vivillon-Icy Snow',
                                          'Vivillon-Jungle',
                                          'Vivillon-Marine',
                                          'Vivillon-Modern',
                                          'Vivillon-Monsoon',
                                          'Vivillon-Ocean',
                                          'Vivillon-Polar',
                                          'Vivillon-River',
                                          'Vivillon-Sandstorm',
                                          'Vivillon-Savanna',
                                          'Vivillon-Sun',
                                          'Vivillon-Tundra'],
                    'formeOrder': [   'Vivillon-Icy Snow',
                                      'Vivillon-Polar',
                                      'Vivillon-Tundra',
                                      'Vivillon-Continental',
                                      'Vivillon-Garden',
                                      'Vivillon-Elegant',
                                      'Vivillon',
                                      'Vivillon-Modern',
                                      'Vivillon-Marine',
                                      'Vivillon-Archipelago',
                                      'Vivillon-High Plains',
                                      'Vivillon-Sandstorm',
                                      'Vivillon-River',
                                      'Vivillon-Monsoon',
                                      'Vivillon-Savanna',
                                      'Vivillon-Sun',
                                      'Vivillon-Ocean',
                                      'Vivillon-Jungle',
                                      'Vivillon-Fancy',
                                      'Vivillon-Pokeball']},
    'Vivillonfancy': {   'num': 666,
                         'name': 'Vivillon-Fancy',
                         'baseSpecies': 'Vivillon',
                         'forme': 'Fancy',
                         'types': ['Bug', 'Flying'],
                         'baseStats': {'hp': 80, 'atk': 52, 'def': 50, 'spa': 90, 'spd': 50, 'spe': 89},
                         'abilities': {'0': 'Shield Dust', '1': 'Compound Eyes', 'H': 'Friend Guard'},
                         'heightm': 1.2,
                         'weightkg': 17,
                         'color': 'Black',
                         'prevo': 'Spewpa',
                         'evoLevel': 12,
                         'eggGroups': ['Bug']},
    'Vivillonpokeball': {   'num': 666,
                            'name': 'Vivillon-Pokeball',
                            'baseSpecies': 'Vivillon',
                            'forme': 'Pokeball',
                            'types': ['Bug', 'Flying'],
                            'baseStats': {'hp': 80, 'atk': 52, 'def': 50, 'spa': 90, 'spd': 50, 'spe': 89},
                            'abilities': {'0': 'Shield Dust', '1': 'Compound Eyes', 'H': 'Friend Guard'},
                            'heightm': 1.2,
                            'weightkg': 17,
                            'color': 'Black',
                            'eggGroups': ['Bug']},
    'Litleo': {   'num': 667,
                  'name': 'Litleo',
                  'types': ['Fire', 'Normal'],
                  'genderRatio': {'M': 0.125, 'F': 0.875},
                  'baseStats': {'hp': 62, 'atk': 50, 'def': 58, 'spa': 73, 'spd': 54, 'spe': 72},
                  'abilities': {'0': 'Rivalry', '1': 'Unnerve', 'H': 'Moxie'},
                  'heightm': 0.6,
                  'weightkg': 13.5,
                  'color': 'Brown',
                  'evos': ['Pyroar'],
                  'eggGroups': ['Field']},
    'Pyroar': {   'num': 668,
                  'name': 'Pyroar',
                  'types': ['Fire', 'Normal'],
                  'genderRatio': {'M': 0.125, 'F': 0.875},
                  'baseStats': {'hp': 86, 'atk': 68, 'def': 72, 'spa': 109, 'spd': 66, 'spe': 106},
                  'abilities': {'0': 'Rivalry', '1': 'Unnerve', 'H': 'Moxie'},
                  'heightm': 1.5,
                  'weightkg': 81.5,
                  'color': 'Brown',
                  'prevo': 'Litleo',
                  'evoLevel': 35,
                  'eggGroups': ['Field']},
    'Flabebe': {   'num': 669,
                   'name': 'Flabébé',
                   'baseForme': 'Red',
                   'types': ['Fairy'],
                   'gender': 'F',
                   'baseStats': {'hp': 44, 'atk': 38, 'def': 39, 'spa': 61, 'spd': 79, 'spe': 42},
                   'abilities': {'0': 'Flower Veil', 'H': 'Symbiosis'},
                   'heightm': 0.1,
                   'weightkg': 0.1,
                   'color': 'White',
                   'evos': ['Floette'],
                   'eggGroups': ['Fairy'],
                   'cosmeticFormes': ['Flabébé-Blue', 'Flabébé-Orange', 'Flabébé-White', 'Flabébé-Yellow'],
                   'formeOrder': [   'Flabébé',
                                     'Flabébé-Blue',
                                     'Flabébé-Orange',
                                     'Flabébé-White',
                                     'Flabébé-Yellow']},
    'Floette': {   'num': 670,
                   'name': 'Floette',
                   'baseForme': 'Red',
                   'types': ['Fairy'],
                   'gender': 'F',
                   'baseStats': {'hp': 54, 'atk': 45, 'def': 47, 'spa': 75, 'spd': 98, 'spe': 52},
                   'abilities': {'0': 'Flower Veil', 'H': 'Symbiosis'},
                   'heightm': 0.2,
                   'weightkg': 0.9,
                   'color': 'White',
                   'prevo': 'Flabébé',
                   'evoLevel': 19,
                   'evos': ['Florges'],
                   'eggGroups': ['Fairy'],
                   'otherFormes': ['Floette-Eternal'],
                   'cosmeticFormes': ['Floette-Blue', 'Floette-Orange', 'Floette-White', 'Floette-Yellow'],
                   'formeOrder': [   'Floette',
                                     'Floette-Blue',
                                     'Floette-Orange',
                                     'Floette-White',
                                     'Floette-Yellow',
                                     'Floette-Eternal']},
    'Floetteeternal': {   'num': 670,
                          'name': 'Floette-Eternal',
                          'baseSpecies': 'Floette',
                          'forme': 'Eternal',
                          'types': ['Fairy'],
                          'gender': 'F',
                          'baseStats': {'hp': 74, 'atk': 65, 'def': 67, 'spa': 125, 'spd': 128, 'spe': 92},
                          'abilities': {'0': 'Flower Veil'},
                          'heightm': 0.2,
                          'weightkg': 0.9,
                          'color': 'White',
                          'eggGroups': ['Undiscovered']},
    'Florges': {   'num': 671,
                   'name': 'Florges',
                   'baseForme': 'Red',
                   'types': ['Fairy'],
                   'gender': 'F',
                   'baseStats': {'hp': 78, 'atk': 65, 'def': 68, 'spa': 112, 'spd': 154, 'spe': 75},
                   'abilities': {'0': 'Flower Veil', 'H': 'Symbiosis'},
                   'heightm': 1.1,
                   'weightkg': 10,
                   'color': 'White',
                   'prevo': 'Floette',
                   'evoType': 'useItem',
                   'evoItem': 'Shiny Stone',
                   'eggGroups': ['Fairy'],
                   'cosmeticFormes': ['Florges-Blue', 'Florges-Orange', 'Florges-White', 'Florges-Yellow'],
                   'formeOrder': ['Florges', 'Florges-Blue', 'Florges-Orange', 'Florges-White', 'Florges-Yellow']},
    'Skiddo': {   'num': 672,
                  'name': 'Skiddo',
                  'types': ['Grass'],
                  'baseStats': {'hp': 66, 'atk': 65, 'def': 48, 'spa': 62, 'spd': 57, 'spe': 52},
                  'abilities': {'0': 'Sap Sipper', 'H': 'Grass Pelt'},
                  'heightm': 0.9,
                  'weightkg': 31,
                  'color': 'Brown',
                  'evos': ['Gogoat'],
                  'eggGroups': ['Field']},
    'Gogoat': {   'num': 673,
                  'name': 'Gogoat',
                  'types': ['Grass'],
                  'baseStats': {'hp': 123, 'atk': 100, 'def': 62, 'spa': 97, 'spd': 81, 'spe': 68},
                  'abilities': {'0': 'Sap Sipper', 'H': 'Grass Pelt'},
                  'heightm': 1.7,
                  'weightkg': 91,
                  'color': 'Brown',
                  'prevo': 'Skiddo',
                  'evoLevel': 32,
                  'eggGroups': ['Field']},
    'Pancham': {   'num': 674,
                   'name': 'Pancham',
                   'types': ['Fighting'],
                   'baseStats': {'hp': 67, 'atk': 82, 'def': 62, 'spa': 46, 'spd': 48, 'spe': 43},
                   'abilities': {'0': 'Iron Fist', '1': 'Mold Breaker', 'H': 'Scrappy'},
                   'heightm': 0.6,
                   'weightkg': 8,
                   'color': 'White',
                   'evos': ['Pangoro'],
                   'eggGroups': ['Field', 'Human-Like']},
    'Pangoro': {   'num': 675,
                   'name': 'Pangoro',
                   'types': ['Fighting', 'Dark'],
                   'baseStats': {'hp': 95, 'atk': 124, 'def': 78, 'spa': 69, 'spd': 71, 'spe': 58},
                   'abilities': {'0': 'Iron Fist', '1': 'Mold Breaker', 'H': 'Scrappy'},
                   'heightm': 2.1,
                   'weightkg': 136,
                   'color': 'White',
                   'prevo': 'Pancham',
                   'evoLevel': 32,
                   'evoCondition': 'with a Dark-type in the party',
                   'eggGroups': ['Field', 'Human-Like']},
    'Furfrou': {   'num': 676,
                   'name': 'Furfrou',
                   'baseForme': 'Natural',
                   'types': ['Normal'],
                   'baseStats': {'hp': 75, 'atk': 80, 'def': 60, 'spa': 65, 'spd': 90, 'spe': 102},
                   'abilities': {'0': 'Fur Coat'},
                   'heightm': 1.2,
                   'weightkg': 28,
                   'color': 'White',
                   'eggGroups': ['Field'],
                   'cosmeticFormes': [   'Furfrou-Dandy',
                                         'Furfrou-Debutante',
                                         'Furfrou-Diamond',
                                         'Furfrou-Heart',
                                         'Furfrou-Kabuki',
                                         'Furfrou-La Reine',
                                         'Furfrou-Matron',
                                         'Furfrou-Pharaoh',
                                         'Furfrou-Star'],
                   'formeOrder': [   'Furfrou',
                                     'Furfrou-Heart',
                                     'Furfrou-Star',
                                     'Furfrou-Diamond',
                                     'Furfrou-Debutante',
                                     'Furfrou-Matron',
                                     'Furfrou-Dandy',
                                     'Furfrou-La Reine',
                                     'Furfrou-Kabuki',
                                     'Furfrou-Pharaoh']},
    'Espurr': {   'num': 677,
                  'name': 'Espurr',
                  'types': ['Psychic'],
                  'baseStats': {'hp': 62, 'atk': 48, 'def': 54, 'spa': 63, 'spd': 60, 'spe': 68},
                  'abilities': {'0': 'Keen Eye', '1': 'Infiltrator', 'H': 'Own Tempo'},
                  'heightm': 0.3,
                  'weightkg': 3.5,
                  'color': 'Gray',
                  'evos': ['Meowstic', 'Meowstic-F'],
                  'eggGroups': ['Field']},
    'Meowstic': {   'num': 678,
                    'name': 'Meowstic',
                    'baseForme': 'M',
                    'types': ['Psychic'],
                    'gender': 'M',
                    'baseStats': {'hp': 74, 'atk': 48, 'def': 76, 'spa': 83, 'spd': 81, 'spe': 104},
                    'abilities': {'0': 'Keen Eye', '1': 'Infiltrator', 'H': 'Prankster'},
                    'heightm': 0.6,
                    'weightkg': 8.5,
                    'color': 'Blue',
                    'prevo': 'Espurr',
                    'evoLevel': 25,
                    'eggGroups': ['Field'],
                    'otherFormes': ['Meowstic-F'],
                    'formeOrder': ['Meowstic', 'Meowstic-F']},
    'Meowsticf': {   'num': 678,
                     'name': 'Meowstic-F',
                     'baseSpecies': 'Meowstic',
                     'forme': 'F',
                     'types': ['Psychic'],
                     'gender': 'F',
                     'baseStats': {'hp': 74, 'atk': 48, 'def': 76, 'spa': 83, 'spd': 81, 'spe': 104},
                     'abilities': {'0': 'Keen Eye', '1': 'Infiltrator', 'H': 'Competitive'},
                     'heightm': 0.6,
                     'weightkg': 8.5,
                     'color': 'White',
                     'prevo': 'Espurr',
                     'evoLevel': 25,
                     'eggGroups': ['Field']},
    'Honedge': {   'num': 679,
                   'name': 'Honedge',
                   'types': ['Steel', 'Ghost'],
                   'baseStats': {'hp': 45, 'atk': 80, 'def': 100, 'spa': 35, 'spd': 37, 'spe': 28},
                   'abilities': {'0': 'No Guard'},
                   'heightm': 0.8,
                   'weightkg': 2,
                   'color': 'Brown',
                   'evos': ['Doublade'],
                   'eggGroups': ['Mineral']},
    'Doublade': {   'num': 680,
                    'name': 'Doublade',
                    'types': ['Steel', 'Ghost'],
                    'baseStats': {'hp': 59, 'atk': 110, 'def': 150, 'spa': 45, 'spd': 49, 'spe': 35},
                    'abilities': {'0': 'No Guard'},
                    'heightm': 0.8,
                    'weightkg': 4.5,
                    'color': 'Brown',
                    'prevo': 'Honedge',
                    'evoLevel': 35,
                    'evos': ['Aegislash'],
                    'eggGroups': ['Mineral']},
    'Aegislash': {   'num': 681,
                     'name': 'Aegislash',
                     'baseForme': 'Shield',
                     'types': ['Steel', 'Ghost'],
                     'baseStats': {'hp': 60, 'atk': 50, 'def': 140, 'spa': 50, 'spd': 140, 'spe': 60},
                     'abilities': {'0': 'Stance Change'},
                     'heightm': 1.7,
                     'weightkg': 53,
                     'color': 'Brown',
                     'prevo': 'Doublade',
                     'evoType': 'useItem',
                     'evoItem': 'Dusk Stone',
                     'eggGroups': ['Mineral'],
                     'otherFormes': ['Aegislash-Blade'],
                     'formeOrder': ['Aegislash', 'Aegislash-Blade']},
    'Aegislashblade': {   'num': 681,
                          'name': 'Aegislash-Blade',
                          'baseSpecies': 'Aegislash',
                          'forme': 'Blade',
                          'types': ['Steel', 'Ghost'],
                          'baseStats': {'hp': 60, 'atk': 140, 'def': 50, 'spa': 140, 'spd': 50, 'spe': 60},
                          'abilities': {'0': 'Stance Change'},
                          'heightm': 1.7,
                          'weightkg': 53,
                          'color': 'Brown',
                          'eggGroups': ['Mineral'],
                          'requiredAbility': 'Stance Change',
                          'battleOnly': 'Aegislash'},
    'Spritzee': {   'num': 682,
                    'name': 'Spritzee',
                    'types': ['Fairy'],
                    'baseStats': {'hp': 78, 'atk': 52, 'def': 60, 'spa': 63, 'spd': 65, 'spe': 23},
                    'abilities': {'0': 'Healer', 'H': 'Aroma Veil'},
                    'heightm': 0.2,
                    'weightkg': 0.5,
                    'color': 'Pink',
                    'evos': ['Aromatisse'],
                    'eggGroups': ['Fairy']},
    'Aromatisse': {   'num': 683,
                      'name': 'Aromatisse',
                      'types': ['Fairy'],
                      'baseStats': {'hp': 101, 'atk': 72, 'def': 72, 'spa': 99, 'spd': 89, 'spe': 29},
                      'abilities': {'0': 'Healer', 'H': 'Aroma Veil'},
                      'heightm': 0.8,
                      'weightkg': 15.5,
                      'color': 'Pink',
                      'prevo': 'Spritzee',
                      'evoType': 'trade',
                      'evoItem': 'Sachet',
                      'eggGroups': ['Fairy']},
    'Swirlix': {   'num': 684,
                   'name': 'Swirlix',
                   'types': ['Fairy'],
                   'baseStats': {'hp': 62, 'atk': 48, 'def': 66, 'spa': 59, 'spd': 57, 'spe': 49},
                   'abilities': {'0': 'Sweet Veil', 'H': 'Unburden'},
                   'heightm': 0.4,
                   'weightkg': 3.5,
                   'color': 'White',
                   'evos': ['Slurpuff'],
                   'eggGroups': ['Fairy']},
    'Slurpuff': {   'num': 685,
                    'name': 'Slurpuff',
                    'types': ['Fairy'],
                    'baseStats': {'hp': 82, 'atk': 80, 'def': 86, 'spa': 85, 'spd': 75, 'spe': 72},
                    'abilities': {'0': 'Sweet Veil', 'H': 'Unburden'},
                    'heightm': 0.8,
                    'weightkg': 5,
                    'color': 'White',
                    'prevo': 'Swirlix',
                    'evoType': 'trade',
                    'evoItem': 'Whipped Dream',
                    'eggGroups': ['Fairy']},
    'Inkay': {   'num': 686,
                 'name': 'Inkay',
                 'types': ['Dark', 'Psychic'],
                 'baseStats': {'hp': 53, 'atk': 54, 'def': 53, 'spa': 37, 'spd': 46, 'spe': 45},
                 'abilities': {'0': 'Contrary', '1': 'Suction Cups', 'H': 'Infiltrator'},
                 'heightm': 0.4,
                 'weightkg': 3.5,
                 'color': 'Blue',
                 'evos': ['Malamar'],
                 'eggGroups': ['Water 1', 'Water 2']},
    'Malamar': {   'num': 687,
                   'name': 'Malamar',
                   'types': ['Dark', 'Psychic'],
                   'baseStats': {'hp': 86, 'atk': 92, 'def': 88, 'spa': 68, 'spd': 75, 'spe': 73},
                   'abilities': {'0': 'Contrary', '1': 'Suction Cups', 'H': 'Infiltrator'},
                   'heightm': 1.5,
                   'weightkg': 47,
                   'color': 'Blue',
                   'prevo': 'Inkay',
                   'evoLevel': 30,
                   'evoCondition': 'with the console turned upside-down',
                   'eggGroups': ['Water 1', 'Water 2']},
    'Binacle': {   'num': 688,
                   'name': 'Binacle',
                   'types': ['Rock', 'Water'],
                   'baseStats': {'hp': 42, 'atk': 52, 'def': 67, 'spa': 39, 'spd': 56, 'spe': 50},
                   'abilities': {'0': 'Tough Claws', '1': 'Sniper', 'H': 'Pickpocket'},
                   'heightm': 0.5,
                   'weightkg': 31,
                   'color': 'Brown',
                   'evos': ['Barbaracle'],
                   'eggGroups': ['Water 3']},
    'Barbaracle': {   'num': 689,
                      'name': 'Barbaracle',
                      'types': ['Rock', 'Water'],
                      'baseStats': {'hp': 72, 'atk': 105, 'def': 115, 'spa': 54, 'spd': 86, 'spe': 68},
                      'abilities': {'0': 'Tough Claws', '1': 'Sniper', 'H': 'Pickpocket'},
                      'heightm': 1.3,
                      'weightkg': 96,
                      'color': 'Brown',
                      'prevo': 'Binacle',
                      'evoLevel': 39,
                      'eggGroups': ['Water 3']},
    'Skrelp': {   'num': 690,
                  'name': 'Skrelp',
                  'types': ['Poison', 'Water'],
                  'baseStats': {'hp': 50, 'atk': 60, 'def': 60, 'spa': 60, 'spd': 60, 'spe': 30},
                  'abilities': {'0': 'Poison Point', '1': 'Poison Touch', 'H': 'Adaptability'},
                  'heightm': 0.5,
                  'weightkg': 7.3,
                  'color': 'Brown',
                  'evos': ['Dragalge'],
                  'eggGroups': ['Water 1', 'Dragon']},
    'Dragalge': {   'num': 691,
                    'name': 'Dragalge',
                    'types': ['Poison', 'Dragon'],
                    'baseStats': {'hp': 65, 'atk': 75, 'def': 90, 'spa': 97, 'spd': 123, 'spe': 44},
                    'abilities': {'0': 'Poison Point', '1': 'Poison Touch', 'H': 'Adaptability'},
                    'heightm': 1.8,
                    'weightkg': 81.5,
                    'color': 'Brown',
                    'prevo': 'Skrelp',
                    'evoLevel': 48,
                    'eggGroups': ['Water 1', 'Dragon']},
    'Clauncher': {   'num': 692,
                     'name': 'Clauncher',
                     'types': ['Water'],
                     'baseStats': {'hp': 50, 'atk': 53, 'def': 62, 'spa': 58, 'spd': 63, 'spe': 44},
                     'abilities': {'0': 'Mega Launcher'},
                     'heightm': 0.5,
                     'weightkg': 8.3,
                     'color': 'Blue',
                     'evos': ['Clawitzer'],
                     'eggGroups': ['Water 1', 'Water 3']},
    'Clawitzer': {   'num': 693,
                     'name': 'Clawitzer',
                     'types': ['Water'],
                     'baseStats': {'hp': 71, 'atk': 73, 'def': 88, 'spa': 120, 'spd': 89, 'spe': 59},
                     'abilities': {'0': 'Mega Launcher'},
                     'heightm': 1.3,
                     'weightkg': 35.3,
                     'color': 'Blue',
                     'prevo': 'Clauncher',
                     'evoLevel': 37,
                     'eggGroups': ['Water 1', 'Water 3']},
    'Helioptile': {   'num': 694,
                      'name': 'Helioptile',
                      'types': ['Electric', 'Normal'],
                      'baseStats': {'hp': 44, 'atk': 38, 'def': 33, 'spa': 61, 'spd': 43, 'spe': 70},
                      'abilities': {'0': 'Dry Skin', '1': 'Sand Veil', 'H': 'Solar Power'},
                      'heightm': 0.5,
                      'weightkg': 6,
                      'color': 'Yellow',
                      'evos': ['Heliolisk'],
                      'eggGroups': ['Monster', 'Dragon']},
    'Heliolisk': {   'num': 695,
                     'name': 'Heliolisk',
                     'types': ['Electric', 'Normal'],
                     'baseStats': {'hp': 62, 'atk': 55, 'def': 52, 'spa': 109, 'spd': 94, 'spe': 109},
                     'abilities': {'0': 'Dry Skin', '1': 'Sand Veil', 'H': 'Solar Power'},
                     'heightm': 1,
                     'weightkg': 21,
                     'color': 'Yellow',
                     'prevo': 'Helioptile',
                     'evoType': 'useItem',
                     'evoItem': 'Sun Stone',
                     'eggGroups': ['Monster', 'Dragon']},
    'Tyrunt': {   'num': 696,
                  'name': 'Tyrunt',
                  'types': ['Rock', 'Dragon'],
                  'genderRatio': {'M': 0.875, 'F': 0.125},
                  'baseStats': {'hp': 58, 'atk': 89, 'def': 77, 'spa': 45, 'spd': 45, 'spe': 48},
                  'abilities': {'0': 'Strong Jaw', 'H': 'Sturdy'},
                  'heightm': 0.8,
                  'weightkg': 26,
                  'color': 'Brown',
                  'evos': ['Tyrantrum'],
                  'eggGroups': ['Monster', 'Dragon']},
    'Tyrantrum': {   'num': 697,
                     'name': 'Tyrantrum',
                     'types': ['Rock', 'Dragon'],
                     'genderRatio': {'M': 0.875, 'F': 0.125},
                     'baseStats': {'hp': 82, 'atk': 121, 'def': 119, 'spa': 69, 'spd': 59, 'spe': 71},
                     'abilities': {'0': 'Strong Jaw', 'H': 'Rock Head'},
                     'heightm': 2.5,
                     'weightkg': 270,
                     'color': 'Red',
                     'prevo': 'Tyrunt',
                     'evoLevel': 39,
                     'evoCondition': 'during the day',
                     'eggGroups': ['Monster', 'Dragon']},
    'Amaura': {   'num': 698,
                  'name': 'Amaura',
                  'types': ['Rock', 'Ice'],
                  'genderRatio': {'M': 0.875, 'F': 0.125},
                  'baseStats': {'hp': 77, 'atk': 59, 'def': 50, 'spa': 67, 'spd': 63, 'spe': 46},
                  'abilities': {'0': 'Refrigerate', 'H': 'Snow Warning'},
                  'heightm': 1.3,
                  'weightkg': 25.2,
                  'color': 'Blue',
                  'evos': ['Aurorus'],
                  'eggGroups': ['Monster']},
    'Aurorus': {   'num': 699,
                   'name': 'Aurorus',
                   'types': ['Rock', 'Ice'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 123, 'atk': 77, 'def': 72, 'spa': 99, 'spd': 92, 'spe': 58},
                   'abilities': {'0': 'Refrigerate', 'H': 'Snow Warning'},
                   'heightm': 2.7,
                   'weightkg': 225,
                   'color': 'Blue',
                   'prevo': 'Amaura',
                   'evoLevel': 39,
                   'evoCondition': 'at night',
                   'eggGroups': ['Monster']},
    'Sylveon': {   'num': 700,
                   'name': 'Sylveon',
                   'types': ['Fairy'],
                   'genderRatio': {'M': 0.875, 'F': 0.125},
                   'baseStats': {'hp': 95, 'atk': 65, 'def': 65, 'spa': 110, 'spd': 130, 'spe': 60},
                   'abilities': {'0': 'Cute Charm', 'H': 'Pixilate'},
                   'heightm': 1,
                   'weightkg': 23.5,
                   'color': 'Pink',
                   'prevo': 'Eevee',
                   'evoType': 'levelExtra',
                   'evoCondition': 'with a Fairy-type move and two levels of Affection',
                   'eggGroups': ['Field']},
    'Hawlucha': {   'num': 701,
                    'name': 'Hawlucha',
                    'types': ['Fighting', 'Flying'],
                    'baseStats': {'hp': 78, 'atk': 92, 'def': 75, 'spa': 74, 'spd': 63, 'spe': 118},
                    'abilities': {'0': 'Limber', '1': 'Unburden', 'H': 'Mold Breaker'},
                    'heightm': 0.8,
                    'weightkg': 21.5,
                    'color': 'Green',
                    'eggGroups': ['Flying', 'Human-Like']},
    'Dedenne': {   'num': 702,
                   'name': 'Dedenne',
                   'types': ['Electric', 'Fairy'],
                   'baseStats': {'hp': 67, 'atk': 58, 'def': 57, 'spa': 81, 'spd': 67, 'spe': 101},
                   'abilities': {'0': 'Cheek Pouch', '1': 'Pickup', 'H': 'Plus'},
                   'heightm': 0.2,
                   'weightkg': 2.2,
                   'color': 'Yellow',
                   'eggGroups': ['Field', 'Fairy']},
    'Carbink': {   'num': 703,
                   'name': 'Carbink',
                   'types': ['Rock', 'Fairy'],
                   'gender': 'N',
                   'baseStats': {'hp': 50, 'atk': 50, 'def': 150, 'spa': 50, 'spd': 150, 'spe': 50},
                   'abilities': {'0': 'Clear Body', 'H': 'Sturdy'},
                   'heightm': 0.3,
                   'weightkg': 5.7,
                   'color': 'Gray',
                   'eggGroups': ['Fairy', 'Mineral']},
    'Goomy': {   'num': 704,
                 'name': 'Goomy',
                 'types': ['Dragon'],
                 'baseStats': {'hp': 45, 'atk': 50, 'def': 35, 'spa': 55, 'spd': 75, 'spe': 40},
                 'abilities': {'0': 'Sap Sipper', '1': 'Hydration', 'H': 'Gooey'},
                 'heightm': 0.3,
                 'weightkg': 2.8,
                 'color': 'Purple',
                 'evos': ['Sliggoo', 'Sliggoo-Hisui'],
                 'eggGroups': ['Dragon']},
    'Sliggoo': {   'num': 705,
                   'name': 'Sliggoo',
                   'types': ['Dragon'],
                   'baseStats': {'hp': 68, 'atk': 75, 'def': 53, 'spa': 83, 'spd': 113, 'spe': 60},
                   'abilities': {'0': 'Sap Sipper', '1': 'Hydration', 'H': 'Gooey'},
                   'heightm': 0.8,
                   'weightkg': 17.5,
                   'color': 'Purple',
                   'prevo': 'Goomy',
                   'evoLevel': 40,
                   'evos': ['Goodra'],
                   'eggGroups': ['Dragon'],
                   'otherFormes': ['Sliggoo-Hisui'],
                   'formeOrder': ['Sliggoo', 'Sliggoo-Hisui']},
    'Sliggoohisui': {   'num': 705,
                        'name': 'Sliggoo-Hisui',
                        'baseSpecies': 'Sliggoo',
                        'forme': 'Hisui',
                        'types': ['Steel', 'Dragon'],
                        'baseStats': {'hp': 58, 'atk': 75, 'def': 83, 'spa': 83, 'spd': 113, 'spe': 40},
                        'abilities': {'0': 'Sap Sipper', '1': 'Shell Armor', 'H': 'Gooey'},
                        'heightm': 0.7,
                        'weightkg': 68.5,
                        'color': 'Purple',
                        'prevo': 'Goomy',
                        'evoLevel': 40,
                        'evos': ['Goodra-Hisui'],
                        'eggGroups': ['Dragon']},
    'Goodra': {   'num': 706,
                  'name': 'Goodra',
                  'types': ['Dragon'],
                  'baseStats': {'hp': 90, 'atk': 100, 'def': 70, 'spa': 110, 'spd': 150, 'spe': 80},
                  'abilities': {'0': 'Sap Sipper', '1': 'Hydration', 'H': 'Gooey'},
                  'heightm': 2,
                  'weightkg': 150.5,
                  'color': 'Purple',
                  'prevo': 'Sliggoo',
                  'evoLevel': 50,
                  'evoCondition': 'during rain',
                  'eggGroups': ['Dragon'],
                  'otherFormes': ['Goodra-Hisui'],
                  'formeOrder': ['Goodra', 'Goodra-Hisui']},
    'Goodrahisui': {   'num': 706,
                       'name': 'Goodra-Hisui',
                       'baseSpecies': 'Goodra',
                       'forme': 'Hisui',
                       'types': ['Steel', 'Dragon'],
                       'baseStats': {'hp': 80, 'atk': 100, 'def': 100, 'spa': 110, 'spd': 150, 'spe': 60},
                       'abilities': {'0': 'Sap Sipper', '1': 'Shell Armor', 'H': 'Gooey'},
                       'heightm': 1.7,
                       'weightkg': 334.1,
                       'color': 'Purple',
                       'prevo': 'Sliggoo-Hisui',
                       'evoLevel': 50,
                       'evoCondition': 'during rain',
                       'eggGroups': ['Dragon']},
    'Klefki': {   'num': 707,
                  'name': 'Klefki',
                  'types': ['Steel', 'Fairy'],
                  'baseStats': {'hp': 57, 'atk': 80, 'def': 91, 'spa': 80, 'spd': 87, 'spe': 75},
                  'abilities': {'0': 'Prankster', 'H': 'Magician'},
                  'heightm': 0.2,
                  'weightkg': 3,
                  'color': 'Gray',
                  'eggGroups': ['Mineral']},
    'Phantump': {   'num': 708,
                    'name': 'Phantump',
                    'types': ['Ghost', 'Grass'],
                    'baseStats': {'hp': 43, 'atk': 70, 'def': 48, 'spa': 50, 'spd': 60, 'spe': 38},
                    'abilities': {'0': 'Natural Cure', '1': 'Frisk', 'H': 'Harvest'},
                    'heightm': 0.4,
                    'weightkg': 7,
                    'color': 'Brown',
                    'evos': ['Trevenant'],
                    'eggGroups': ['Grass', 'Amorphous']},
    'Trevenant': {   'num': 709,
                     'name': 'Trevenant',
                     'types': ['Ghost', 'Grass'],
                     'baseStats': {'hp': 85, 'atk': 110, 'def': 76, 'spa': 65, 'spd': 82, 'spe': 56},
                     'abilities': {'0': 'Natural Cure', '1': 'Frisk', 'H': 'Harvest'},
                     'heightm': 1.5,
                     'weightkg': 71,
                     'color': 'Brown',
                     'prevo': 'Phantump',
                     'evoType': 'trade',
                     'eggGroups': ['Grass', 'Amorphous']},
    'Pumpkaboo': {   'num': 710,
                     'name': 'Pumpkaboo',
                     'baseForme': 'Average',
                     'types': ['Ghost', 'Grass'],
                     'baseStats': {'hp': 49, 'atk': 66, 'def': 70, 'spa': 44, 'spd': 55, 'spe': 51},
                     'abilities': {'0': 'Pickup', '1': 'Frisk', 'H': 'Insomnia'},
                     'heightm': 0.4,
                     'weightkg': 5,
                     'color': 'Brown',
                     'evos': ['Gourgeist'],
                     'eggGroups': ['Amorphous'],
                     'otherFormes': ['Pumpkaboo-Small', 'Pumpkaboo-Large', 'Pumpkaboo-Super'],
                     'formeOrder': ['Pumpkaboo', 'Pumpkaboo-Small', 'Pumpkaboo-Large', 'Pumpkaboo-Super']},
    'Pumpkaboosmall': {   'num': 710,
                          'name': 'Pumpkaboo-Small',
                          'baseSpecies': 'Pumpkaboo',
                          'forme': 'Small',
                          'types': ['Ghost', 'Grass'],
                          'baseStats': {'hp': 44, 'atk': 66, 'def': 70, 'spa': 44, 'spd': 55, 'spe': 56},
                          'abilities': {'0': 'Pickup', '1': 'Frisk', 'H': 'Insomnia'},
                          'heightm': 0.3,
                          'weightkg': 3.5,
                          'color': 'Brown',
                          'evos': ['Gourgeist-Small'],
                          'eggGroups': ['Amorphous']},
    'Pumpkaboolarge': {   'num': 710,
                          'name': 'Pumpkaboo-Large',
                          'baseSpecies': 'Pumpkaboo',
                          'forme': 'Large',
                          'types': ['Ghost', 'Grass'],
                          'baseStats': {'hp': 54, 'atk': 66, 'def': 70, 'spa': 44, 'spd': 55, 'spe': 46},
                          'abilities': {'0': 'Pickup', '1': 'Frisk', 'H': 'Insomnia'},
                          'heightm': 0.5,
                          'weightkg': 7.5,
                          'color': 'Brown',
                          'evos': ['Gourgeist-Large'],
                          'eggGroups': ['Amorphous']},
    'Pumpkaboosuper': {   'num': 710,
                          'name': 'Pumpkaboo-Super',
                          'baseSpecies': 'Pumpkaboo',
                          'forme': 'Super',
                          'types': ['Ghost', 'Grass'],
                          'baseStats': {'hp': 59, 'atk': 66, 'def': 70, 'spa': 44, 'spd': 55, 'spe': 41},
                          'abilities': {'0': 'Pickup', '1': 'Frisk', 'H': 'Insomnia'},
                          'heightm': 0.8,
                          'weightkg': 15,
                          'color': 'Brown',
                          'evos': ['Gourgeist-Super'],
                          'eggGroups': ['Amorphous']},
    'Gourgeist': {   'num': 711,
                     'name': 'Gourgeist',
                     'baseForme': 'Average',
                     'types': ['Ghost', 'Grass'],
                     'baseStats': {'hp': 65, 'atk': 90, 'def': 122, 'spa': 58, 'spd': 75, 'spe': 84},
                     'abilities': {'0': 'Pickup', '1': 'Frisk', 'H': 'Insomnia'},
                     'heightm': 0.9,
                     'weightkg': 12.5,
                     'color': 'Brown',
                     'prevo': 'Pumpkaboo',
                     'evoType': 'trade',
                     'eggGroups': ['Amorphous'],
                     'otherFormes': ['Gourgeist-Small', 'Gourgeist-Large', 'Gourgeist-Super'],
                     'formeOrder': ['Gourgeist', 'Gourgeist-Small', 'Gourgeist-Large', 'Gourgeist-Super']},
    'Gourgeistsmall': {   'num': 711,
                          'name': 'Gourgeist-Small',
                          'baseSpecies': 'Gourgeist',
                          'forme': 'Small',
                          'types': ['Ghost', 'Grass'],
                          'baseStats': {'hp': 55, 'atk': 85, 'def': 122, 'spa': 58, 'spd': 75, 'spe': 99},
                          'abilities': {'0': 'Pickup', '1': 'Frisk', 'H': 'Insomnia'},
                          'heightm': 0.7,
                          'weightkg': 9.5,
                          'color': 'Brown',
                          'prevo': 'Pumpkaboo-Small',
                          'evoType': 'trade',
                          'eggGroups': ['Amorphous']},
    'Gourgeistlarge': {   'num': 711,
                          'name': 'Gourgeist-Large',
                          'baseSpecies': 'Gourgeist',
                          'forme': 'Large',
                          'types': ['Ghost', 'Grass'],
                          'baseStats': {'hp': 75, 'atk': 95, 'def': 122, 'spa': 58, 'spd': 75, 'spe': 69},
                          'abilities': {'0': 'Pickup', '1': 'Frisk', 'H': 'Insomnia'},
                          'heightm': 1.1,
                          'weightkg': 14,
                          'color': 'Brown',
                          'prevo': 'Pumpkaboo-Large',
                          'evoType': 'trade',
                          'eggGroups': ['Amorphous']},
    'Gourgeistsuper': {   'num': 711,
                          'name': 'Gourgeist-Super',
                          'baseSpecies': 'Gourgeist',
                          'forme': 'Super',
                          'types': ['Ghost', 'Grass'],
                          'baseStats': {'hp': 85, 'atk': 100, 'def': 122, 'spa': 58, 'spd': 75, 'spe': 54},
                          'abilities': {'0': 'Pickup', '1': 'Frisk', 'H': 'Insomnia'},
                          'heightm': 1.7,
                          'weightkg': 39,
                          'color': 'Brown',
                          'prevo': 'Pumpkaboo-Super',
                          'evoType': 'trade',
                          'eggGroups': ['Amorphous']},
    'Bergmite': {   'num': 712,
                    'name': 'Bergmite',
                    'types': ['Ice'],
                    'baseStats': {'hp': 55, 'atk': 69, 'def': 85, 'spa': 32, 'spd': 35, 'spe': 28},
                    'abilities': {'0': 'Own Tempo', '1': 'Ice Body', 'H': 'Sturdy'},
                    'heightm': 1,
                    'weightkg': 99.5,
                    'color': 'Blue',
                    'evos': ['Avalugg', 'Avalugg-Hisui'],
                    'eggGroups': ['Monster', 'Mineral']},
    'Avalugg': {   'num': 713,
                   'name': 'Avalugg',
                   'types': ['Ice'],
                   'baseStats': {'hp': 95, 'atk': 117, 'def': 184, 'spa': 44, 'spd': 46, 'spe': 28},
                   'abilities': {'0': 'Own Tempo', '1': 'Ice Body', 'H': 'Sturdy'},
                   'heightm': 2,
                   'weightkg': 505,
                   'color': 'Blue',
                   'prevo': 'Bergmite',
                   'evoLevel': 37,
                   'eggGroups': ['Monster', 'Mineral'],
                   'otherFormes': ['Avalugg-Hisui'],
                   'formeOrder': ['Avalugg', 'Avalugg-Hisui']},
    'Avalugghisui': {   'num': 713,
                        'name': 'Avalugg-Hisui',
                        'baseSpecies': 'Avalugg',
                        'forme': 'Hisui',
                        'types': ['Ice', 'Rock'],
                        'baseStats': {'hp': 95, 'atk': 127, 'def': 184, 'spa': 34, 'spd': 36, 'spe': 38},
                        'abilities': {'0': 'Strong Jaw', '1': 'Ice Body', 'H': 'Sturdy'},
                        'heightm': 1.4,
                        'weightkg': 262.4,
                        'color': 'Blue',
                        'prevo': 'Bergmite',
                        'evoLevel': 37,
                        'eggGroups': ['Monster', 'Mineral']},
    'Noibat': {   'num': 714,
                  'name': 'Noibat',
                  'types': ['Flying', 'Dragon'],
                  'baseStats': {'hp': 40, 'atk': 30, 'def': 35, 'spa': 45, 'spd': 40, 'spe': 55},
                  'abilities': {'0': 'Frisk', '1': 'Infiltrator', 'H': 'Telepathy'},
                  'heightm': 0.5,
                  'weightkg': 8,
                  'color': 'Purple',
                  'evos': ['Noivern'],
                  'eggGroups': ['Flying', 'Dragon']},
    'Noivern': {   'num': 715,
                   'name': 'Noivern',
                   'types': ['Flying', 'Dragon'],
                   'baseStats': {'hp': 85, 'atk': 70, 'def': 80, 'spa': 97, 'spd': 80, 'spe': 123},
                   'abilities': {'0': 'Frisk', '1': 'Infiltrator', 'H': 'Telepathy'},
                   'heightm': 1.5,
                   'weightkg': 85,
                   'color': 'Purple',
                   'prevo': 'Noibat',
                   'evoLevel': 48,
                   'eggGroups': ['Flying', 'Dragon']},
    'Xerneas': {   'num': 716,
                   'name': 'Xerneas',
                   'baseForme': 'Active',
                   'types': ['Fairy'],
                   'gender': 'N',
                   'baseStats': {'hp': 126, 'atk': 131, 'def': 95, 'spa': 131, 'spd': 98, 'spe': 99},
                   'abilities': {'0': 'Fairy Aura'},
                   'heightm': 3,
                   'weightkg': 215,
                   'color': 'Blue',
                   'eggGroups': ['Undiscovered'],
                   'tags': ['Restricted Legendary'],
                   'otherFormes': ['Xerneas-Neutral'],
                   'formeOrder': ['Xerneas-Neutral', 'Xerneas']},
    'Xerneasneutral': {   'num': 716,
                          'name': 'Xerneas-Neutral',
                          'baseSpecies': 'Xerneas',
                          'forme': 'Neutral',
                          'types': ['Fairy'],
                          'gender': 'N',
                          'baseStats': {'hp': 126, 'atk': 131, 'def': 95, 'spa': 131, 'spd': 98, 'spe': 99},
                          'abilities': {'0': 'Fairy Aura'},
                          'heightm': 3,
                          'weightkg': 215,
                          'color': 'Blue',
                          'eggGroups': ['Undiscovered']},
    'Yveltal': {   'num': 717,
                   'name': 'Yveltal',
                   'types': ['Dark', 'Flying'],
                   'gender': 'N',
                   'baseStats': {'hp': 126, 'atk': 131, 'def': 95, 'spa': 131, 'spd': 98, 'spe': 99},
                   'abilities': {'0': 'Dark Aura'},
                   'heightm': 5.8,
                   'weightkg': 203,
                   'color': 'Red',
                   'tags': ['Restricted Legendary'],
                   'eggGroups': ['Undiscovered']},
    'Zygarde': {   'num': 718,
                   'name': 'Zygarde',
                   'baseForme': '50%',
                   'types': ['Dragon', 'Ground'],
                   'gender': 'N',
                   'baseStats': {'hp': 108, 'atk': 100, 'def': 121, 'spa': 81, 'spd': 95, 'spe': 95},
                   'abilities': {'0': 'Aura Break', 'S': 'Power Construct'},
                   'heightm': 5,
                   'weightkg': 305,
                   'color': 'Green',
                   'tags': ['Restricted Legendary'],
                   'eggGroups': ['Undiscovered'],
                   'otherFormes': ['Zygarde-10%', 'Zygarde-Complete'],
                   'formeOrder': ['Zygarde', 'Zygarde-10%', 'Zygarde-10%', 'Zygarde', 'Zygarde-Complete']},
    'Zygarde10': {   'num': 718,
                     'name': 'Zygarde-10%',
                     'baseSpecies': 'Zygarde',
                     'forme': '10%',
                     'types': ['Dragon', 'Ground'],
                     'gender': 'N',
                     'baseStats': {'hp': 54, 'atk': 100, 'def': 71, 'spa': 61, 'spd': 85, 'spe': 115},
                     'abilities': {'0': 'Aura Break', 'S': 'Power Construct'},
                     'heightm': 1.2,
                     'weightkg': 33.5,
                     'color': 'Black',
                     'eggGroups': ['Undiscovered'],
                     'changesFrom': 'Zygarde',
                     'gen': 7},
    'Zygardecomplete': {   'num': 718,
                           'name': 'Zygarde-Complete',
                           'baseSpecies': 'Zygarde',
                           'forme': 'Complete',
                           'types': ['Dragon', 'Ground'],
                           'gender': 'N',
                           'baseStats': {'hp': 216, 'atk': 100, 'def': 121, 'spa': 91, 'spd': 95, 'spe': 85},
                           'abilities': {'0': 'Power Construct'},
                           'heightm': 4.5,
                           'weightkg': 610,
                           'color': 'Black',
                           'eggGroups': ['Undiscovered'],
                           'requiredAbility': 'Power Construct',
                           'battleOnly': ['Zygarde', 'Zygarde-10%'],
                           'gen': 7},
    'Diancie': {   'num': 719,
                   'name': 'Diancie',
                   'types': ['Rock', 'Fairy'],
                   'gender': 'N',
                   'baseStats': {'hp': 50, 'atk': 100, 'def': 150, 'spa': 100, 'spd': 150, 'spe': 50},
                   'abilities': {'0': 'Clear Body'},
                   'heightm': 0.7,
                   'weightkg': 8.8,
                   'color': 'Pink',
                   'eggGroups': ['Undiscovered'],
                   'tags': ['Mythical'],
                   'otherFormes': ['Diancie-Mega'],
                   'formeOrder': ['Diancie', 'Diancie-Mega']},
    'Dianciemega': {   'num': 719,
                       'name': 'Diancie-Mega',
                       'baseSpecies': 'Diancie',
                       'forme': 'Mega',
                       'types': ['Rock', 'Fairy'],
                       'gender': 'N',
                       'baseStats': {'hp': 50, 'atk': 160, 'def': 110, 'spa': 160, 'spd': 110, 'spe': 110},
                       'abilities': {'0': 'Magic Bounce'},
                       'heightm': 1.1,
                       'weightkg': 27.8,
                       'color': 'Pink',
                       'eggGroups': ['Undiscovered'],
                       'requiredItem': 'Diancite'},
    'Hoopa': {   'num': 720,
                 'name': 'Hoopa',
                 'baseForme': 'Confined',
                 'types': ['Psychic', 'Ghost'],
                 'gender': 'N',
                 'baseStats': {'hp': 80, 'atk': 110, 'def': 60, 'spa': 150, 'spd': 130, 'spe': 70},
                 'abilities': {'0': 'Magician'},
                 'heightm': 0.5,
                 'weightkg': 9,
                 'color': 'Purple',
                 'eggGroups': ['Undiscovered'],
                 'tags': ['Mythical'],
                 'otherFormes': ['Hoopa-Unbound'],
                 'formeOrder': ['Hoopa', 'Hoopa-Unbound']},
    'Hoopaunbound': {   'num': 720,
                        'name': 'Hoopa-Unbound',
                        'baseSpecies': 'Hoopa',
                        'forme': 'Unbound',
                        'types': ['Psychic', 'Dark'],
                        'gender': 'N',
                        'baseStats': {'hp': 80, 'atk': 160, 'def': 60, 'spa': 170, 'spd': 130, 'spe': 80},
                        'abilities': {'0': 'Magician'},
                        'heightm': 6.5,
                        'weightkg': 490,
                        'color': 'Purple',
                        'eggGroups': ['Undiscovered'],
                        'changesFrom': 'Hoopa'},
    'Volcanion': {   'num': 721,
                     'name': 'Volcanion',
                     'types': ['Fire', 'Water'],
                     'gender': 'N',
                     'baseStats': {'hp': 80, 'atk': 110, 'def': 120, 'spa': 130, 'spd': 90, 'spe': 70},
                     'abilities': {'0': 'Water Absorb'},
                     'heightm': 1.7,
                     'weightkg': 195,
                     'color': 'Brown',
                     'tags': ['Mythical'],
                     'eggGroups': ['Undiscovered']}}
