"""Pokédex entries for Paldea region."""

from ..functions.pokedex_funcs import *

pokedex = {
	"Sprigatito": {
		"num": 906,
		"name": "Sprigatito",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 40, "atk": 61, "def": 54, "spa": 45, "spd": 45, "spe": 65},
		"abilities": {"0": "Overgrow", "H": "Protean"},
		"heightm": 0.4,
		"weightkg": 4.1,
		"color": "Green",
		"evos": ["Floragato"],
		"eggGroups": ["Field", "Grass"],
	},
	"Floragato": {
		"num": 907,
		"name": "Floragato",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 61, "atk": 80, "def": 63, "spa": 60, "spd": 63, "spe": 83},
		"abilities": {"0": "Overgrow", "H": "Protean"},
		"heightm": 0.9,
		"weightkg": 12.2,
		"color": "Green",
		"prevo": "Sprigatito",
		"evoLevel": 16,
		"evos": ["Meowscarada"],
		"eggGroups": ["Field", "Grass"],
	},
	"Meowscarada": {
		"num": 908,
		"name": "Meowscarada",
		"types": ["Grass", "Dark"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 76, "atk": 110, "def": 70, "spa": 81, "spd": 70, "spe": 123},
		"abilities": {"0": "Overgrow", "H": "Protean"},
		"heightm": 1.5,
		"weightkg": 31.2,
		"color": "Green",
		"prevo": "Floragato",
		"evoLevel": 36,
		"eggGroups": ["Field", "Grass"],
	},
	"Fuecoco": {
		"num": 909,
		"name": "Fuecoco",
		"types": ["Fire"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 67, "atk": 45, "def": 59, "spa": 63, "spd": 40, "spe": 36},
		"abilities": {"0": "Blaze", "H": "Unaware"},
		"heightm": 0.4,
		"weightkg": 9.8,
		"color": "Red",
		"evos": ["Crocalor"],
		"eggGroups": ["Field"],
	},
	"Crocalor": {
		"num": 910,
		"name": "Crocalor",
		"types": ["Fire"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 81, "atk": 55, "def": 78, "spa": 90, "spd": 58, "spe": 49},
		"abilities": {"0": "Blaze", "H": "Unaware"},
		"heightm": 1,
		"weightkg": 30.7,
		"color": "Red",
		"prevo": "Fuecoco",
		"evoLevel": 16,
		"evos": ["Skeledirge"],
		"eggGroups": ["Field"],
	},
	"Skeledirge": {
		"num": 911,
		"name": "Skeledirge",
		"types": ["Fire", "Ghost"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 104, "atk": 75, "def": 100, "spa": 110, "spd": 75, "spe": 66},
		"abilities": {"0": "Blaze", "H": "Unaware"},
		"heightm": 1.6,
		"weightkg": 326.5,
		"color": "Red",
		"prevo": "Crocalor",
		"evoLevel": 36,
		"eggGroups": ["Field"],
	},
	"Quaxly": {
		"num": 912,
		"name": "Quaxly",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 55, "atk": 65, "def": 45, "spa": 50, "spd": 45, "spe": 50},
		"abilities": {"0": "Torrent", "H": "Moxie"},
		"heightm": 0.5,
		"weightkg": 6.1,
		"color": "Blue",
		"evos": ["Quaxwell"],
		"eggGroups": ["Flying", "Water 1"],
	},
	"Quaxwell": {
		"num": 913,
		"name": "Quaxwell",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 70, "atk": 85, "def": 65, "spa": 65, "spd": 60, "spe": 65},
		"abilities": {"0": "Torrent", "H": "Moxie"},
		"heightm": 1.2,
		"weightkg": 21.5,
		"color": "Blue",
		"prevo": "Quaxly",
		"evoLevel": 16,
		"evos": ["Quaquaval"],
		"eggGroups": ["Flying", "Water 1"],
	},
	"Quaquaval": {
		"num": 914,
		"name": "Quaquaval",
		"types": ["Water", "Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 85, "atk": 120, "def": 80, "spa": 85, "spd": 75, "spe": 85},
		"abilities": {"0": "Torrent", "H": "Moxie"},
		"heightm": 1.8,
		"weightkg": 61.9,
		"color": "Blue",
		"prevo": "Quaxwell",
		"evoLevel": 36,
		"eggGroups": ["Flying", "Water 1"],
	},
	"Lechonk": {
		"num": 915,
		"name": "Lechonk",
		"types": ["Normal"],
		"baseStats": {"hp": 54, "atk": 45, "def": 40, "spa": 35, "spd": 45, "spe": 35},
		"abilities": {"0": "Aroma Veil", "1": "Gluttony", "H": "Thick Fat"},
		"heightm": 0.5,
		"weightkg": 10.2,
		"color": "Gray",
		"evos": ["Oinkologne", "Oinkologne-F"],
		"eggGroups": ["Field"],
	},
	"Oinkologne": {
		"num": 916,
		"name": "Oinkologne",
		"baseForme": "M",
		"types": ["Normal"],
		"gender": "M",
		"baseStats": {"hp": 110, "atk": 100, "def": 75, "spa": 59, "spd": 80, "spe": 65},
		"abilities": {"0": "Lingering Aroma", "1": "Gluttony", "H": "Thick Fat"},
		"heightm": 1,
		"weightkg": 120,
		"color": "Gray",
		"prevo": "Lechonk",
		"evoLevel": 18,
		"otherFormes": ["Oinkologne-F"],
		"formeOrder": ["Oinkologne", "Oinkologne-F"],
		"eggGroups": ["Field"],
	},
	"Oinkolognef": {
		"num": 916,
		"name": "Oinkologne-F",
		"baseSpecies": "Oinkologne",
		"forme": "F",
		"types": ["Normal"],
		"gender": "F",
		"baseStats": {"hp": 115, "atk": 90, "def": 70, "spa": 59, "spd": 90, "spe": 65},
		"abilities": {"0": "Aroma Veil", "1": "Gluttony", "H": "Thick Fat"},
		"heightm": 1,
		"weightkg": 120,
		"color": "Brown",
		"prevo": "Lechonk",
		"evoLevel": 18,
		"eggGroups": ["Field"],
	},
	"Tarountula": {
		"num": 917,
		"name": "Tarountula",
		"types": ["Bug"],
		"baseStats": {"hp": 35, "atk": 41, "def": 45, "spa": 29, "spd": 40, "spe": 20},
		"abilities": {"0": "Insomnia", "H": "Stakeout"},
		"heightm": 0.3,
		"weightkg": 4,
		"color": "White",
		"evos": ["Spidops"],
		"eggGroups": ["Bug"],
	},
	"Spidops": {
		"num": 918,
		"name": "Spidops",
		"types": ["Bug"],
		"baseStats": {"hp": 60, "atk": 79, "def": 92, "spa": 52, "spd": 86, "spe": 35},
		"abilities": {"0": "Insomnia", "H": "Stakeout"},
		"heightm": 1,
		"weightkg": 16.5,
		"color": "Green",
		"prevo": "Tarountula",
		"evoLevel": 15,
		"eggGroups": ["Bug"],
	},
	"Nymble": {
		"num": 919,
		"name": "Nymble",
		"types": ["Bug"],
		"baseStats": {"hp": 33, "atk": 46, "def": 40, "spa": 21, "spd": 25, "spe": 45},
		"abilities": {"0": "Swarm", "H": "Tinted Lens"},
		"heightm": 0.2,
		"weightkg": 1,
		"color": "Gray",
		"evos": ["Lokix"],
		"eggGroups": ["Bug"],
	},
	"Lokix": {
		"num": 920,
		"name": "Lokix",
		"types": ["Bug", "Dark"],
		"baseStats": {"hp": 71, "atk": 102, "def": 78, "spa": 52, "spd": 55, "spe": 92},
		"abilities": {"0": "Swarm", "H": "Tinted Lens"},
		"heightm": 1,
		"weightkg": 17.5,
		"color": "Gray",
		"prevo": "Nymble",
		"evoLevel": 24,
		"eggGroups": ["Bug"],
	},
	"Pawmi": {
		"num": 921,
		"name": "Pawmi",
		"types": ["Electric"],
		"baseStats": {"hp": 45, "atk": 50, "def": 20, "spa": 40, "spd": 25, "spe": 60},
		"abilities": {"0": "Static", "1": "Natural Cure", "H": "Iron Fist"},
		"heightm": 0.3,
		"weightkg": 2.5,
		"color": "Yellow",
		"evos": ["Pawmo"],
		"eggGroups": ["Field"],
	},
	"Pawmo": {
		"num": 922,
		"name": "Pawmo",
		"types": ["Electric", "Fighting"],
		"baseStats": {"hp": 60, "atk": 75, "def": 40, "spa": 50, "spd": 40, "spe": 85},
		"abilities": {"0": "Volt Absorb", "1": "Natural Cure", "H": "Iron Fist"},
		"heightm": 0.4,
		"weightkg": 6.5,
		"color": "Yellow",
		"prevo": "Pawmi",
		"evoLevel": 18,
		"evos": ["Pawmot"],
		"eggGroups": ["Field"],
	},
	"Pawmot": {
		"num": 923,
		"name": "Pawmot",
		"types": ["Electric", "Fighting"],
		"baseStats": {"hp": 70, "atk": 115, "def": 70, "spa": 70, "spd": 60, "spe": 105},
		"abilities": {"0": "Volt Absorb", "1": "Natural Cure", "H": "Iron Fist"},
		"heightm": 0.9,
		"weightkg": 41,
		"color": "Yellow",
		"prevo": "Pawmo",
		"evoType": "other",
		"evoCondition": "walk 1000 steps in Let's Go",
		"eggGroups": ["Field"],
	},
	"Tandemaus": {
		"num": 924,
		"name": "Tandemaus",
		"types": ["Normal"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 50, "def": 45, "spa": 40, "spd": 45, "spe": 75},
		"abilities": {"0": "Run Away", "1": "Pickup", "H": "Own Tempo"},
		"heightm": 0.3,
		"weightkg": 1.8,
		"color": "White",
		"evos": ["Maushold", "Maushold-Four"],
		"eggGroups": ["Field", "Fairy"],
	},
	"Maushold": {
		"num": 925,
		"name": "Maushold",
		"baseForme": "Three",
		"types": ["Normal"],
		"gender": "N",
		"baseStats": {"hp": 74, "atk": 75, "def": 70, "spa": 65, "spd": 75, "spe": 111},
		"abilities": {"0": "Friend Guard", "1": "Cheek Pouch", "H": "Technician"},
		"heightm": 0.3,
		"weightkg": 2.3,
		"color": "White",
		"prevo": "Tandemaus",
		"evoLevel": 25,
		"otherFormes": ["Maushold-Four"],
		"formeOrder": ["Maushold", "Maushold-Four"],
		"eggGroups": ["Field", "Fairy"],
	},
	"Mausholdfour": {
		"num": 925,
		"name": "Maushold-Four",
		"baseSpecies": "Maushold",
		"forme": "Four",
		"types": ["Normal"],
		"gender": "N",
		"baseStats": {"hp": 74, "atk": 75, "def": 70, "spa": 65, "spd": 75, "spe": 111},
		"abilities": {"0": "Friend Guard", "1": "Cheek Pouch", "H": "Technician"},
		"heightm": 0.3,
		"weightkg": 2.8,
		"color": "White",
		"prevo": "Tandemaus",
		"evoLevel": 25,
		"eggGroups": ["Field", "Fairy"],
	},
	"Fidough": {
		"num": 926,
		"name": "Fidough",
		"types": ["Fairy"],
		"baseStats": {"hp": 37, "atk": 55, "def": 70, "spa": 30, "spd": 55, "spe": 65},
		"abilities": {"0": "Own Tempo", "H": "Klutz"},
		"heightm": 0.3,
		"weightkg": 10.9,
		"color": "Yellow",
		"evos": ["Dachsbun"],
		"eggGroups": ["Field", "Mineral"],
	},
	"Dachsbun": {
		"num": 927,
		"name": "Dachsbun",
		"types": ["Fairy"],
		"baseStats": {"hp": 57, "atk": 80, "def": 115, "spa": 50, "spd": 80, "spe": 95},
		"abilities": {"0": "Well-Baked Body", "H": "Aroma Veil"},
		"heightm": 0.5,
		"weightkg": 14.9,
		"color": "Brown",
		"prevo": "Fidough",
		"evoLevel": 26,
		"eggGroups": ["Field", "Mineral"],
	},
	"Smoliv": {
		"num": 928,
		"name": "Smoliv",
		"types": ["Grass", "Normal"],
		"baseStats": {"hp": 41, "atk": 35, "def": 45, "spa": 58, "spd": 51, "spe": 30},
		"abilities": {"0": "Early Bird", "H": "Harvest"},
		"heightm": 0.3,
		"weightkg": 6.5,
		"color": "Green",
		"evos": ["Dolliv"],
		"eggGroups": ["Grass"],
	},
	"Dolliv": {
		"num": 929,
		"name": "Dolliv",
		"types": ["Grass", "Normal"],
		"baseStats": {"hp": 52, "atk": 53, "def": 60, "spa": 78, "spd": 78, "spe": 33},
		"abilities": {"0": "Early Bird", "H": "Harvest"},
		"heightm": 0.6,
		"weightkg": 11.9,
		"color": "Green",
		"prevo": "Smoliv",
		"evoLevel": 25,
		"evos": ["Arboliva"],
		"eggGroups": ["Grass"],
	},
	"Arboliva": {
		"num": 930,
		"name": "Arboliva",
		"types": ["Grass", "Normal"],
		"baseStats": {"hp": 78, "atk": 69, "def": 90, "spa": 125, "spd": 109, "spe": 39},
		"abilities": {"0": "Seed Sower", "H": "Harvest"},
		"heightm": 1.4,
		"weightkg": 48.2,
		"color": "Green",
		"prevo": "Dolliv",
		"evoLevel": 35,
		"eggGroups": ["Grass"],
	},
	"Squawkabilly": {
		"num": 931,
		"name": "Squawkabilly",
		"baseForme": "Green",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 82, "atk": 96, "def": 51, "spa": 45, "spd": 51, "spe": 92},
		"abilities": {"0": "Intimidate", "1": "Hustle", "H": "Guts"},
		"heightm": 0.6,
		"weightkg": 2.4,
		"color": "Green",
		"otherFormes": ["Squawkabilly-Blue", "Squawkabilly-Yellow", "Squawkabilly-White"],
		"formeOrder": ["Squawkabilly", "Squawkabilly-Blue", "Squawkabilly-Yellow", "Squawkabilly-White"],
		"eggGroups": ["Flying"],
	},
	"Squawkabillyblue": {
		"num": 931,
		"name": "Squawkabilly-Blue",
		"baseSpecies": "Squawkabilly",
		"forme": "Blue",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 82, "atk": 96, "def": 51, "spa": 45, "spd": 51, "spe": 92},
		"abilities": {"0": "Intimidate", "1": "Hustle", "H": "Guts"},
		"heightm": 0.6,
		"weightkg": 2.4,
		"color": "Blue",
		"eggGroups": ["Flying"],
	},
	"Squawkabillyyellow": {
		"num": 931,
		"name": "Squawkabilly-Yellow",
		"baseSpecies": "Squawkabilly",
		"forme": "Yellow",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 82, "atk": 96, "def": 51, "spa": 45, "spd": 51, "spe": 92},
		"abilities": {"0": "Intimidate", "1": "Hustle", "H": "Sheer Force"},
		"heightm": 0.6,
		"weightkg": 2.4,
		"color": "Yellow",
		"eggGroups": ["Flying"],
	},
	"Squawkabillywhite": {
		"num": 931,
		"name": "Squawkabilly-White",
		"baseSpecies": "Squawkabilly",
		"forme": "White",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 82, "atk": 96, "def": 51, "spa": 45, "spd": 51, "spe": 92},
		"abilities": {"0": "Intimidate", "1": "Hustle", "H": "Sheer Force"},
		"heightm": 0.6,
		"weightkg": 2.4,
		"color": "White",
		"eggGroups": ["Flying"],
	},
	"Nacli": {
		"num": 932,
		"name": "Nacli",
		"types": ["Rock"],
		"baseStats": {"hp": 55, "atk": 55, "def": 75, "spa": 35, "spd": 35, "spe": 25},
		"abilities": {"0": "Purifying Salt", "1": "Sturdy", "H": "Clear Body"},
		"heightm": 0.4,
		"weightkg": 16,
		"color": "Brown",
		"evos": ["Naclstack"],
		"eggGroups": ["Mineral"],
	},
	"Naclstack": {
		"num": 933,
		"name": "Naclstack",
		"types": ["Rock"],
		"baseStats": {"hp": 60, "atk": 60, "def": 100, "spa": 35, "spd": 65, "spe": 35},
		"abilities": {"0": "Purifying Salt", "1": "Sturdy", "H": "Clear Body"},
		"heightm": 0.6,
		"weightkg": 105,
		"color": "Brown",
		"prevo": "Nacli",
		"evoLevel": 24,
		"evos": ["Garganacl"],
		"eggGroups": ["Mineral"],
	},
	"Garganacl": {
		"num": 934,
		"name": "Garganacl",
		"types": ["Rock"],
		"baseStats": {"hp": 100, "atk": 100, "def": 130, "spa": 45, "spd": 90, "spe": 35},
		"abilities": {"0": "Purifying Salt", "1": "Sturdy", "H": "Clear Body"},
		"heightm": 2.3,
		"weightkg": 240,
		"color": "Brown",
		"prevo": "Naclstack",
		"evoLevel": 38,
		"eggGroups": ["Mineral"],
	},
	"Charcadet": {
		"num": 935,
		"name": "Charcadet",
		"types": ["Fire"],
		"baseStats": {"hp": 40, "atk": 50, "def": 40, "spa": 50, "spd": 40, "spe": 35},
		"abilities": {"0": "Flash Fire", "H": "Flame Body"},
		"heightm": 0.6,
		"weightkg": 10.5,
		"color": "Red",
		"evos": ["Armarouge", "Ceruledge"],
		"eggGroups": ["Human-Like"],
	},
	"Armarouge": {
		"num": 936,
		"name": "Armarouge",
		"types": ["Fire", "Psychic"],
		"baseStats": {"hp": 85, "atk": 60, "def": 100, "spa": 125, "spd": 80, "spe": 75},
		"abilities": {"0": "Flash Fire", "H": "Weak Armor"},
		"heightm": 1.5,
		"weightkg": 85,
		"color": "Red",
		"prevo": "Charcadet",
		"evoType": "useItem",
		"evoItem": "Auspicious Armor",
		"eggGroups": ["Human-Like"],
	},
	"Ceruledge": {
		"num": 937,
		"name": "Ceruledge",
		"types": ["Fire", "Ghost"],
		"baseStats": {"hp": 75, "atk": 125, "def": 80, "spa": 60, "spd": 100, "spe": 85},
		"abilities": {"0": "Flash Fire", "H": "Weak Armor"},
		"heightm": 1.6,
		"weightkg": 62,
		"color": "Purple",
		"prevo": "Charcadet",
		"evoType": "useItem",
		"evoItem": "Malicious Armor",
		"eggGroups": ["Human-Like"],
	},
	"Tadbulb": {
		"num": 938,
		"name": "Tadbulb",
		"types": ["Electric"],
		"baseStats": {"hp": 61, "atk": 31, "def": 41, "spa": 59, "spd": 35, "spe": 45},
		"abilities": {"0": "Own Tempo", "1": "Static", "H": "Damp"},
		"heightm": 0.3,
		"weightkg": 0.4,
		"color": "Yellow",
		"evos": ["Bellibolt"],
		"eggGroups": ["Water 1"],
	},
	"Bellibolt": {
		"num": 939,
		"name": "Bellibolt",
		"types": ["Electric"],
		"baseStats": {"hp": 109, "atk": 64, "def": 91, "spa": 103, "spd": 83, "spe": 45},
		"abilities": {"0": "Electromorphosis", "1": "Static", "H": "Damp"},
		"heightm": 1.2,
		"weightkg": 113,
		"color": "Green",
		"prevo": "Tadbulb",
		"evoType": "useItem",
		"evoItem": "Thunder Stone",
		"eggGroups": ["Water 1"],
	},
	"Wattrel": {
		"num": 940,
		"name": "Wattrel",
		"types": ["Electric", "Flying"],
		"baseStats": {"hp": 40, "atk": 40, "def": 35, "spa": 55, "spd": 40, "spe": 70},
		"abilities": {"0": "Wind Power", "1": "Volt Absorb", "H": "Competitive"},
		"heightm": 0.4,
		"weightkg": 3.6,
		"color": "Black",
		"evos": ["Kilowattrel"],
		"eggGroups": ["Water 1", "Flying"],
	},
	"Kilowattrel": {
		"num": 941,
		"name": "Kilowattrel",
		"types": ["Electric", "Flying"],
		"baseStats": {"hp": 70, "atk": 70, "def": 60, "spa": 105, "spd": 60, "spe": 125},
		"abilities": {"0": "Wind Power", "1": "Volt Absorb", "H": "Competitive"},
		"heightm": 1.4,
		"weightkg": 38.6,
		"color": "Yellow",
		"prevo": "Wattrel",
		"evoLevel": 25,
		"eggGroups": ["Water 1", "Flying"],
	},
	"Maschiff": {
		"num": 942,
		"name": "Maschiff",
		"types": ["Dark"],
		"baseStats": {"hp": 60, "atk": 78, "def": 60, "spa": 40, "spd": 51, "spe": 51},
		"abilities": {"0": "Intimidate", "1": "Run Away", "H": "Stakeout"},
		"heightm": 0.5,
		"weightkg": 16,
		"color": "Brown",
		"evos": ["Mabosstiff"],
		"eggGroups": ["Field"],
	},
	"Mabosstiff": {
		"num": 943,
		"name": "Mabosstiff",
		"types": ["Dark"],
		"baseStats": {"hp": 80, "atk": 120, "def": 90, "spa": 60, "spd": 70, "spe": 85},
		"abilities": {"0": "Intimidate", "1": "Guard Dog", "H": "Stakeout"},
		"heightm": 1.1,
		"weightkg": 61,
		"color": "Gray",
		"prevo": "Maschiff",
		"evoLevel": 30,
		"eggGroups": ["Field"],
	},
	"Shroodle": {
		"num": 944,
		"name": "Shroodle",
		"types": ["Poison", "Normal"],
		"baseStats": {"hp": 40, "atk": 65, "def": 35, "spa": 40, "spd": 35, "spe": 75},
		"abilities": {"0": "Unburden", "1": "Pickpocket", "H": "Prankster"},
		"heightm": 0.2,
		"weightkg": 0.7,
		"color": "Gray",
		"evos": ["Grafaiai"],
		"eggGroups": ["Field"],
	},
	"Grafaiai": {
		"num": 945,
		"name": "Grafaiai",
		"types": ["Poison", "Normal"],
		"baseStats": {"hp": 63, "atk": 95, "def": 65, "spa": 80, "spd": 72, "spe": 110},
		"abilities": {"0": "Unburden", "1": "Poison Touch", "H": "Prankster"},
		"heightm": 0.7,
		"weightkg": 27.2,
		"color": "Gray",
		"prevo": "Shroodle",
		"evoLevel": 28,
		"eggGroups": ["Field"],
	},
	"Bramblin": {
		"num": 946,
		"name": "Bramblin",
		"types": ["Grass", "Ghost"],
		"baseStats": {"hp": 40, "atk": 65, "def": 30, "spa": 45, "spd": 35, "spe": 60},
		"abilities": {"0": "Wind Rider", "H": "Infiltrator"},
		"heightm": 0.6,
		"weightkg": 0.6,
		"color": "Brown",
		"evos": ["Brambleghast"],
		"eggGroups": ["Grass"],
	},
	"Brambleghast": {
		"num": 947,
		"name": "Brambleghast",
		"types": ["Grass", "Ghost"],
		"baseStats": {"hp": 55, "atk": 115, "def": 70, "spa": 80, "spd": 70, "spe": 90},
		"abilities": {"0": "Wind Rider", "H": "Infiltrator"},
		"heightm": 1.2,
		"weightkg": 6,
		"color": "Brown",
		"prevo": "Bramblin",
		"evoType": "other",
		"evoCondition": "Walk 1000 steps in Let's Go",
		"eggGroups": ["Grass"],
	},
	"Toedscool": {
		"num": 948,
		"name": "Toedscool",
		"types": ["Ground", "Grass"],
		"baseStats": {"hp": 40, "atk": 40, "def": 35, "spa": 50, "spd": 100, "spe": 70},
		"abilities": {"0": "Mycelium Might"},
		"heightm": 0.9,
		"weightkg": 33,
		"color": "Yellow",
		"evos": ["Toedscruel"],
		"eggGroups": ["Field"],
	},
	"Toedscruel": {
		"num": 949,
		"name": "Toedscruel",
		"types": ["Ground", "Grass"],
		"baseStats": {"hp": 80, "atk": 70, "def": 65, "spa": 80, "spd": 120, "spe": 100},
		"abilities": {"0": "Mycelium Might"},
		"heightm": 1.9,
		"weightkg": 58,
		"color": "Black",
		"prevo": "Toedscool",
		"evoLevel": 30,
		"eggGroups": ["Field"],
	},
	"Klawf": {
		"num": 950,
		"name": "Klawf",
		"types": ["Rock"],
		"baseStats": {"hp": 70, "atk": 100, "def": 115, "spa": 35, "spd": 55, "spe": 75},
		"abilities": {"0": "Anger Shell", "1": "Shell Armor", "H": "Regenerator"},
		"heightm": 1.3,
		"weightkg": 79,
		"color": "Red",
		"eggGroups": ["Water 3"],
	},
	"Capsakid": {
		"num": 951,
		"name": "Capsakid",
		"types": ["Grass"],
		"baseStats": {"hp": 50, "atk": 62, "def": 40, "spa": 62, "spd": 40, "spe": 50},
		"abilities": {"0": "Chlorophyll", "1": "Insomnia", "H": "Klutz"},
		"heightm": 0.3,
		"weightkg": 3,
		"color": "Green",
		"evos": ["Scovillain"],
		"eggGroups": ["Grass"],
	},
	"Scovillain": {
		"num": 952,
		"name": "Scovillain",
		"types": ["Grass", "Fire"],
		"baseStats": {"hp": 65, "atk": 108, "def": 65, "spa": 108, "spd": 65, "spe": 75},
		"abilities": {"0": "Chlorophyll", "1": "Insomnia", "H": "Moody"},
		"heightm": 0.9,
		"weightkg": 15,
		"color": "Green",
		"prevo": "Capsakid",
		"evoType": "useItem",
		"evoItem": "Fire Stone",
		"eggGroups": ["Grass"],
	},
	"Rellor": {
		"num": 953,
		"name": "Rellor",
		"types": ["Bug"],
		"baseStats": {"hp": 41, "atk": 50, "def": 60, "spa": 31, "spd": 58, "spe": 30},
		"abilities": {"0": "Compound Eyes", "H": "Shed Skin"},
		"heightm": 0.2,
		"weightkg": 1,
		"color": "Brown",
		"evos": ["Rabsca"],
		"eggGroups": ["Bug"],
	},
	"Rabsca": {
		"num": 954,
		"name": "Rabsca",
		"types": ["Bug", "Psychic"],
		"baseStats": {"hp": 75, "atk": 50, "def": 85, "spa": 115, "spd": 100, "spe": 45},
		"abilities": {"0": "Synchronize", "H": "Telepathy"},
		"heightm": 0.3,
		"weightkg": 3.5,
		"color": "Green",
		"prevo": "Rellor",
		"evoType": "other",
		"evoCondition": "walk 1000 steps in Let's Go",
		"eggGroups": ["Bug"],
	},
	"Flittle": {
		"num": 955,
		"name": "Flittle",
		"types": ["Psychic"],
		"baseStats": {"hp": 30, "atk": 35, "def": 30, "spa": 55, "spd": 30, "spe": 75},
		"abilities": {"0": "Anticipation", "1": "Frisk", "H": "Speed Boost"},
		"heightm": 0.2,
		"weightkg": 1.5,
		"color": "Yellow",
		"evos": ["Espathra"],
		"eggGroups": ["Flying"],
	},
	"Espathra": {
		"num": 956,
		"name": "Espathra",
		"types": ["Psychic"],
		"baseStats": {"hp": 95, "atk": 60, "def": 60, "spa": 101, "spd": 60, "spe": 105},
		"abilities": {"0": "Opportunist", "1": "Frisk", "H": "Speed Boost"},
		"heightm": 1.9,
		"weightkg": 90,
		"color": "Yellow",
		"prevo": "Flittle",
		"evoLevel": 35,
		"eggGroups": ["Flying"],
	},
	"Tinkatink": {
		"num": 957,
		"name": "Tinkatink",
		"types": ["Fairy", "Steel"],
		"gender": "F",
		"baseStats": {"hp": 50, "atk": 45, "def": 45, "spa": 35, "spd": 64, "spe": 58},
		"abilities": {"0": "Mold Breaker", "1": "Own Tempo", "H": "Pickpocket"},
		"heightm": 0.4,
		"weightkg": 8.9,
		"color": "Pink",
		"evos": ["Tinkatuff"],
		"eggGroups": ["Fairy"],
	},
	"Tinkatuff": {
		"num": 958,
		"name": "Tinkatuff",
		"types": ["Fairy", "Steel"],
		"gender": "F",
		"baseStats": {"hp": 65, "atk": 55, "def": 55, "spa": 45, "spd": 82, "spe": 78},
		"abilities": {"0": "Mold Breaker", "1": "Own Tempo", "H": "Pickpocket"},
		"heightm": 0.7,
		"weightkg": 59.1,
		"color": "Pink",
		"prevo": "Tinkatink",
		"evoLevel": 24,
		"evos": ["Tinkaton"],
		"eggGroups": ["Fairy"],
	},
	"Tinkaton": {
		"num": 959,
		"name": "Tinkaton",
		"types": ["Fairy", "Steel"],
		"gender": "F",
		"baseStats": {"hp": 85, "atk": 75, "def": 77, "spa": 70, "spd": 105, "spe": 94},
		"abilities": {"0": "Mold Breaker", "1": "Own Tempo", "H": "Pickpocket"},
		"heightm": 0.7,
		"weightkg": 112.8,
		"color": "Pink",
		"prevo": "Tinkatuff",
		"evoLevel": 38,
		"eggGroups": ["Fairy"],
	},
	"Wiglett": {
		"num": 960,
		"name": "Wiglett",
		"types": ["Water"],
		"baseStats": {"hp": 10, "atk": 55, "def": 25, "spa": 35, "spd": 25, "spe": 95},
		"abilities": {"0": "Gooey", "1": "Rattled", "H": "Sand Veil"},
		"heightm": 1.2,
		"weightkg": 1.8,
		"color": "White",
		"evos": ["Wugtrio"],
		"eggGroups": ["Water 3"],
	},
	"Wugtrio": {
		"num": 961,
		"name": "Wugtrio",
		"types": ["Water"],
		"baseStats": {"hp": 35, "atk": 100, "def": 50, "spa": 50, "spd": 70, "spe": 120},
		"abilities": {"0": "Gooey", "1": "Rattled", "H": "Sand Veil"},
		"heightm": 1.2,
		"weightkg": 5.4,
		"color": "Red",
		"prevo": "Wiglett",
		"evoLevel": 26,
		"eggGroups": ["Water 3"],
	},
	"Bombirdier": {
		"num": 962,
		"name": "Bombirdier",
		"types": ["Flying", "Dark"],
		"baseStats": {"hp": 70, "atk": 103, "def": 85, "spa": 60, "spd": 85, "spe": 82},
		"abilities": {"0": "Big Pecks", "1": "Keen Eye", "H": "Rocky Payload"},
		"heightm": 1.5,
		"weightkg": 42.9,
		"color": "White",
		"eggGroups": ["Flying"],
	},
	"Finizen": {
		"num": 963,
		"name": "Finizen",
		"types": ["Water"],
		"baseStats": {"hp": 70, "atk": 45, "def": 40, "spa": 45, "spd": 40, "spe": 75},
		"abilities": {"0": "Water Veil"},
		"heightm": 1.3,
		"weightkg": 60.2,
		"color": "Blue",
		"evos": ["Palafin"],
		"eggGroups": ["Field", "Water 2"],
	},
	"Palafin": {
		"num": 964,
		"name": "Palafin",
		"baseForme": "Zero",
		"types": ["Water"],
		"baseStats": {"hp": 100, "atk": 70, "def": 72, "spa": 53, "spd": 62, "spe": 100},
		"abilities": {"0": "Zero to Hero"},
		"heightm": 1.3,
		"weightkg": 60.2,
		"color": "Blue",
		"prevo": "Finizen",
		"evoLevel": 38,
		"otherFormes": ["Palafin-Hero"],
		"formeOrder": ["Palafin", "Palafin-Hero"],
		"eggGroups": ["Field", "Water 2"],
	},
	"Palafinhero": {
		"num": 964,
		"name": "Palafin-Hero",
		"baseSpecies": "Palafin",
		"forme": "Hero",
		"types": ["Water"],
		"baseStats": {"hp": 100, "atk": 160, "def": 97, "spa": 106, "spd": 87, "spe": 100},
		"abilities": {"0": "Zero to Hero"},
		"heightm": 1.8,
		"weightkg": 97.4,
		"color": "Blue",
		"eggGroups": ["Field", "Water 2"],
		"requiredAbility": "Zero to Hero",
		"battleOnly": "Palafin",
	},
	"Varoom": {
		"num": 965,
		"name": "Varoom",
		"types": ["Steel", "Poison"],
		"baseStats": {"hp": 45, "atk": 70, "def": 63, "spa": 30, "spd": 45, "spe": 47},
		"abilities": {"0": "Overcoat", "H": "Slow Start"},
		"heightm": 1,
		"weightkg": 35,
		"color": "Gray",
		"evos": ["Revavroom"],
		"eggGroups": ["Mineral"],
	},
	"Revavroom": {
		"num": 966,
		"name": "Revavroom",
		"types": ["Steel", "Poison"],
		"baseStats": {"hp": 80, "atk": 119, "def": 90, "spa": 54, "spd": 67, "spe": 90},
		"abilities": {"0": "Overcoat", "H": "Filter"},
		"heightm": 1.8,
		"weightkg": 120,
		"color": "Gray",
		"prevo": "Varoom",
		"evoLevel": 40,
		"eggGroups": ["Mineral"],
	},
	"Cyclizar": {
		"num": 967,
		"name": "Cyclizar",
		"types": ["Dragon", "Normal"],
		"baseStats": {"hp": 70, "atk": 95, "def": 65, "spa": 85, "spd": 65, "spe": 121},
		"abilities": {"0": "Shed Skin", "H": "Regenerator"},
		"heightm": 1.6,
		"weightkg": 63,
		"color": "Green",
		"eggGroups": ["Field"],
	},
	"Orthworm": {
		"num": 968,
		"name": "Orthworm",
		"types": ["Steel"],
		"baseStats": {"hp": 70, "atk": 85, "def": 145, "spa": 60, "spd": 55, "spe": 65},
		"abilities": {"0": "Earth Eater", "H": "Sand Veil"},
		"heightm": 2.5,
		"weightkg": 310,
		"color": "Pink",
		"eggGroups": ["Field"],
	},
	"Glimmet": {
		"num": 969,
		"name": "Glimmet",
		"types": ["Rock", "Poison"],
		"baseStats": {"hp": 48, "atk": 35, "def": 42, "spa": 105, "spd": 60, "spe": 60},
		"abilities": {"0": "Toxic Debris", "H": "Corrosion"},
		"heightm": 0.7,
		"weightkg": 8,
		"color": "Blue",
		"evos": ["Glimmora"],
		"eggGroups": ["Mineral"],
	},
	"Glimmora": {
		"num": 970,
		"name": "Glimmora",
		"types": ["Rock", "Poison"],
		"baseStats": {"hp": 83, "atk": 55, "def": 90, "spa": 130, "spd": 81, "spe": 86},
		"abilities": {"0": "Toxic Debris", "H": "Corrosion"},
		"heightm": 1.5,
		"weightkg": 45,
		"color": "Blue",
		"prevo": "Glimmet",
		"evoLevel": 35,
		"eggGroups": ["Mineral"],
	},
	"Greavard": {
		"num": 971,
		"name": "Greavard",
		"types": ["Ghost"],
		"baseStats": {"hp": 50, "atk": 61, "def": 60, "spa": 30, "spd": 55, "spe": 34},
		"abilities": {"0": "Pickup", "H": "Fluffy"},
		"heightm": 0.6,
		"weightkg": 35,
		"color": "White",
		"evos": ["Houndstone"],
		"eggGroups": ["Field"],
	},
	"Houndstone": {
		"num": 972,
		"name": "Houndstone",
		"types": ["Ghost"],
		"baseStats": {"hp": 72, "atk": 101, "def": 100, "spa": 50, "spd": 97, "spe": 68},
		"abilities": {"0": "Sand Rush", "H": "Fluffy"},
		"heightm": 2,
		"weightkg": 15,
		"color": "White",
		"prevo": "Greavard",
		"evoLevel": 30,
		"evoCondition": "at night",
		"eggGroups": ["Field"],
	},
	"Flamigo": {
		"num": 973,
		"name": "Flamigo",
		"types": ["Flying", "Fighting"],
		"baseStats": {"hp": 82, "atk": 115, "def": 74, "spa": 75, "spd": 64, "spe": 90},
		"abilities": {"0": "Scrappy", "1": "Tangled Feet", "H": "Costar"},
		"heightm": 1.6,
		"weightkg": 37,
		"color": "Pink",
		"eggGroups": ["Flying"],
	},
	"Cetoddle": {
		"num": 974,
		"name": "Cetoddle",
		"types": ["Ice"],
		"baseStats": {"hp": 108, "atk": 68, "def": 45, "spa": 30, "spd": 40, "spe": 43},
		"abilities": {"0": "Thick Fat", "1": "Snow Cloak", "H": "Sheer Force"},
		"heightm": 1.2,
		"weightkg": 45,
		"color": "White",
		"evos": ["Cetitan"],
		"eggGroups": ["Field"],
	},
	"Cetitan": {
		"num": 975,
		"name": "Cetitan",
		"types": ["Ice"],
		"baseStats": {"hp": 170, "atk": 113, "def": 65, "spa": 45, "spd": 55, "spe": 73},
		"abilities": {"0": "Thick Fat", "1": "Slush Rush", "H": "Sheer Force"},
		"heightm": 4.5,
		"weightkg": 700,
		"color": "White",
		"prevo": "Cetoddle",
		"evoType": "useItem",
		"evoItem": "Ice Stone",
		"eggGroups": ["Field"],
	},
	"Veluza": {
		"num": 976,
		"name": "Veluza",
		"types": ["Water", "Psychic"],
		"baseStats": {"hp": 90, "atk": 102, "def": 73, "spa": 78, "spd": 65, "spe": 70},
		"abilities": {"0": "Mold Breaker", "H": "Sharpness"},
		"heightm": 2.5,
		"weightkg": 90,
		"color": "Gray",
		"eggGroups": ["Water 2"],
	},
	"Dondozo": {
		"num": 977,
		"name": "Dondozo",
		"types": ["Water"],
		"baseStats": {"hp": 150, "atk": 100, "def": 115, "spa": 65, "spd": 65, "spe": 35},
		"abilities": {"0": "Unaware", "1": "Oblivious", "H": "Water Veil"},
		"heightm": 12,
		"weightkg": 220,
		"color": "Blue",
		"eggGroups": ["Water 2"],
	},
	"Tatsugiri": {
		"num": 978,
		"name": "Tatsugiri",
		"baseForme": "Curly",
		"types": ["Dragon", "Water"],
		"baseStats": {"hp": 68, "atk": 50, "def": 60, "spa": 120, "spd": 95, "spe": 82},
		"abilities": {"0": "Commander", "H": "Storm Drain"},
		"heightm": 0.3,
		"weightkg": 8,
		"color": "Red",
		"cosmeticFormes": ["Tatsugiri-Droopy", "Tatsugiri-Stretchy"],
		"formeOrder": ["Tatsugiri", "Tatsugiri-Droopy", "Tatsugiri-Stretchy"],
		"eggGroups": ["Water 2"],
	},
	"Annihilape": {
		"num": 979,
		"name": "Annihilape",
		"types": ["Fighting", "Ghost"],
		"baseStats": {"hp": 110, "atk": 115, "def": 80, "spa": 50, "spd": 90, "spe": 90},
		"abilities": {"0": "Vital Spirit", "1": "Inner Focus", "H": "Defiant"},
		"heightm": 1.2,
		"weightkg": 56,
		"color": "Gray",
		"prevo": "Primeape",
		"evoType": "other",
		"evoCondition": "Use Rage Fist 20 times and level-up",
		"eggGroups": ["Field"],
	},
	"Clodsire": {
		"num": 980,
		"name": "Clodsire",
		"types": ["Poison", "Ground"],
		"baseStats": {"hp": 130, "atk": 75, "def": 60, "spa": 45, "spd": 100, "spe": 20},
		"abilities": {"0": "Poison Point", "1": "Water Absorb", "H": "Unaware"},
		"heightm": 1.8,
		"weightkg": 223,
		"color": "Brown",
		"prevo": "Wooper-Paldea",
		"evoLevel": 20,
		"eggGroups": ["Water 1", "Field"],
	},
	"Farigiraf": {
		"num": 981,
		"name": "Farigiraf",
		"types": ["Normal", "Psychic"],
		"baseStats": {"hp": 120, "atk": 90, "def": 70, "spa": 110, "spd": 70, "spe": 60},
		"abilities": {"0": "Cud Chew", "1": "Armor Tail", "H": "Sap Sipper"},
		"heightm": 3.2,
		"weightkg": 160,
		"color": "Brown",
		"prevo": "Girafarig",
		"evoType": "levelMove",
		"evoMove": "Twin Beam",
		"eggGroups": ["Field"],
	},
	"Dudunsparce": {
		"num": 982,
		"name": "Dudunsparce",
		"baseForme": "Two-Segment",
		"types": ["Normal"],
		"baseStats": {"hp": 125, "atk": 100, "def": 80, "spa": 85, "spd": 75, "spe": 55},
		"abilities": {"0": "Serene Grace", "1": "Run Away", "H": "Rattled"},
		"heightm": 3.6,
		"weightkg": 39.2,
		"color": "Yellow",
		"prevo": "Dunsparce",
		"evoType": "levelMove",
		"evoMove": "Hyper Drill",
		"otherFormes": ["Dudunsparce-Three-Segment"],
		"formeOrder": ["Dudunsparce", "Dudunsparce-Three-Segment"],
		"eggGroups": ["Field"],
	},
	"Dudunsparcethreesegment": {
		"num": 982,
		"name": "Dudunsparce-Three-Segment",
		"baseSpecies": "Dudunsparce",
		"forme": "Three-Segment",
		"types": ["Normal"],
		"baseStats": {"hp": 125, "atk": 100, "def": 80, "spa": 85, "spd": 75, "spe": 55},
		"abilities": {"0": "Serene Grace", "1": "Run Away", "H": "Rattled"},
		"heightm": 4.5,
		"weightkg": 47.4,
		"color": "Yellow",
		"prevo": "Dunsparce",
		"evoType": "levelMove",
		"evoMove": "Hyper Drill",
		"eggGroups": ["Field"],
	},
	"Kingambit": {
		"num": 983,
		"name": "Kingambit",
		"types": ["Dark", "Steel"],
		"baseStats": {"hp": 100, "atk": 135, "def": 120, "spa": 60, "spd": 85, "spe": 50},
		"abilities": {"0": "Defiant", "1": "Supreme Overlord", "H": "Pressure"},
		"heightm": 2,
		"weightkg": 120,
		"color": "Black",
		"prevo": "Bisharp",
		"evoType": "other",
		"evoCondition": "Defeat 3 Bisharp leading Pawniard and level-up",
		"eggGroups": ["Human-Like"],
	},
	"Greattusk": {
		"num": 984,
		"name": "Great Tusk",
		"types": ["Ground", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 115, "atk": 131, "def": 131, "spa": 53, "spd": 53, "spe": 87},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 2.2,
		"weightkg": 320,
		"color": "Purple",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Screamtail": {
		"num": 985,
		"name": "Scream Tail",
		"types": ["Fairy", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 115, "atk": 65, "def": 99, "spa": 65, "spd": 115, "spe": 111},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 1.2,
		"weightkg": 8,
		"color": "Pink",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Brutebonnet": {
		"num": 986,
		"name": "Brute Bonnet",
		"types": ["Grass", "Dark"],
		"gender": "N",
		"baseStats": {"hp": 111, "atk": 127, "def": 99, "spa": 79, "spd": 99, "spe": 55},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 1.2,
		"weightkg": 21,
		"color": "White",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Fluttermane": {
		"num": 987,
		"name": "Flutter Mane",
		"types": ["Ghost", "Fairy"],
		"gender": "N",
		"baseStats": {"hp": 55, "atk": 55, "def": 55, "spa": 135, "spd": 135, "spe": 135},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 1.4,
		"weightkg": 4,
		"color": "Gray",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Slitherwing": {
		"num": 988,
		"name": "Slither Wing",
		"types": ["Bug", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 85, "atk": 135, "def": 79, "spa": 85, "spd": 105, "spe": 81},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 3.2,
		"weightkg": 92,
		"color": "White",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Sandyshocks": {
		"num": 989,
		"name": "Sandy Shocks",
		"types": ["Electric", "Ground"],
		"gender": "N",
		"baseStats": {"hp": 85, "atk": 81, "def": 97, "spa": 121, "spd": 85, "spe": 101},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 2.3,
		"weightkg": 60,
		"color": "Gray",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Irontreads": {
		"num": 990,
		"name": "Iron Treads",
		"types": ["Ground", "Steel"],
		"gender": "N",
		"baseStats": {"hp": 90, "atk": 112, "def": 120, "spa": 72, "spd": 70, "spe": 106},
		"abilities": {"0": "Quark Drive"},
		"heightm": 0.9,
		"weightkg": 240,
		"color": "Gray",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Ironbundle": {
		"num": 991,
		"name": "Iron Bundle",
		"types": ["Ice", "Water"],
		"gender": "N",
		"baseStats": {"hp": 56, "atk": 80, "def": 114, "spa": 124, "spd": 60, "spe": 136},
		"abilities": {"0": "Quark Drive"},
		"heightm": 0.6,
		"weightkg": 11,
		"color": "Red",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Ironhands": {
		"num": 992,
		"name": "Iron Hands",
		"types": ["Fighting", "Electric"],
		"gender": "N",
		"baseStats": {"hp": 154, "atk": 140, "def": 108, "spa": 50, "spd": 68, "spe": 50},
		"abilities": {"0": "Quark Drive"},
		"heightm": 1.8,
		"weightkg": 380.7,
		"color": "Gray",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Ironjugulis": {
		"num": 993,
		"name": "Iron Jugulis",
		"types": ["Dark", "Flying"],
		"gender": "N",
		"baseStats": {"hp": 94, "atk": 80, "def": 86, "spa": 122, "spd": 80, "spe": 108},
		"abilities": {"0": "Quark Drive"},
		"heightm": 1.3,
		"weightkg": 111,
		"color": "Blue",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Ironmoth": {
		"num": 994,
		"name": "Iron Moth",
		"types": ["Fire", "Poison"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 70, "def": 60, "spa": 140, "spd": 110, "spe": 110},
		"abilities": {"0": "Quark Drive"},
		"heightm": 1.2,
		"weightkg": 36,
		"color": "White",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Ironthorns": {
		"num": 995,
		"name": "Iron Thorns",
		"types": ["Rock", "Electric"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 134, "def": 110, "spa": 70, "spd": 84, "spe": 72},
		"abilities": {"0": "Quark Drive"},
		"heightm": 1.6,
		"weightkg": 303,
		"color": "Green",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Frigibax": {
		"num": 996,
		"name": "Frigibax",
		"types": ["Dragon", "Ice"],
		"baseStats": {"hp": 65, "atk": 75, "def": 45, "spa": 35, "spd": 45, "spe": 55},
		"abilities": {"0": "Thermal Exchange", "H": "Ice Body"},
		"heightm": 0.5,
		"weightkg": 17,
		"color": "Gray",
		"evos": ["Arctibax"],
		"eggGroups": ["Dragon", "Mineral"],
	},
	"Arctibax": {
		"num": 997,
		"name": "Arctibax",
		"types": ["Dragon", "Ice"],
		"baseStats": {"hp": 90, "atk": 95, "def": 66, "spa": 45, "spd": 65, "spe": 62},
		"abilities": {"0": "Thermal Exchange", "H": "Ice Body"},
		"heightm": 0.8,
		"weightkg": 30,
		"color": "Blue",
		"prevo": "Frigibax",
		"evoLevel": 35,
		"evos": ["Baxcalibur"],
		"eggGroups": ["Dragon", "Mineral"],
	},
	"Baxcalibur": {
		"num": 998,
		"name": "Baxcalibur",
		"types": ["Dragon", "Ice"],
		"baseStats": {"hp": 115, "atk": 145, "def": 92, "spa": 75, "spd": 86, "spe": 87},
		"abilities": {"0": "Thermal Exchange", "H": "Ice Body"},
		"heightm": 2.1,
		"weightkg": 210,
		"color": "Blue",
		"prevo": "Arctibax",
		"evoLevel": 54,
		"eggGroups": ["Dragon", "Mineral"],
	},
	"Gimmighoul": {
		"num": 999,
		"name": "Gimmighoul",
		"baseForme": "Chest",
		"types": ["Ghost"],
		"gender": "N",
		"baseStats": {"hp": 45, "atk": 30, "def": 70, "spa": 75, "spd": 70, "spe": 10},
		"abilities": {"0": "Rattled"},
		"heightm": 0.3,
		"weightkg": 5,
		"color": "Red",
		"evos": ["Gholdengo"],
		"otherFormes": ["Gimmighoul-Roaming"],
		"formeOrder": ["Gimmighoul", "Gimmighoul-Roaming"],
		"eggGroups": ["Undiscovered"],
	},
	"Gimmighoulroaming": {
		"num": 999,
		"name": "Gimmighoul-Roaming",
		"baseSpecies": "Gimmighoul",
		"forme": "Roaming",
		"types": ["Ghost"],
		"gender": "N",
		"baseStats": {"hp": 45, "atk": 30, "def": 25, "spa": 75, "spd": 45, "spe": 80},
		"abilities": {"0": "Run Away"},
		"heightm": 0.1,
		"weightkg": 0.1,
		"color": "Gray",
		"evos": ["Gholdengo"],
		"eggGroups": ["Undiscovered"],
	},
	"Gholdengo": {
		"num": 1000,
		"name": "Gholdengo",
		"types": ["Steel", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 87, "atk": 60, "def": 95, "spa": 133, "spd": 91, "spe": 84},
		"abilities": {"0": "Good as Gold"},
		"heightm": 1.2,
		"weightkg": 30,
		"color": "Yellow",
		"prevo": "Gimmighoul",
		"evoType": "other",
		"evoCondition": "Level up with 999 Coins in the bag",
		"eggGroups": ["Undiscovered"],
	},
	"Wochien": {
		"num": 1001,
		"name": "Wo-Chien",
		"types": ["Dark", "Grass"],
		"gender": "N",
		"baseStats": {"hp": 85, "atk": 85, "def": 100, "spa": 95, "spd": 135, "spe": 70},
		"abilities": {"0": "Tablets of Ruin"},
		"heightm": 1.5,
		"weightkg": 74.2,
		"color": "Brown",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Chienpao": {
		"num": 1002,
		"name": "Chien-Pao",
		"types": ["Dark", "Ice"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 120, "def": 80, "spa": 90, "spd": 65, "spe": 135},
		"abilities": {"0": "Sword of Ruin"},
		"heightm": 1.9,
		"weightkg": 152.2,
		"color": "White",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Tinglu": {
		"num": 1003,
		"name": "Ting-Lu",
		"types": ["Dark", "Ground"],
		"gender": "N",
		"baseStats": {"hp": 155, "atk": 110, "def": 125, "spa": 55, "spd": 80, "spe": 45},
		"abilities": {"0": "Vessel of Ruin"},
		"heightm": 2.7,
		"weightkg": 699.7,
		"color": "Brown",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Chiyu": {
		"num": 1004,
		"name": "Chi-Yu",
		"types": ["Dark", "Fire"],
		"gender": "N",
		"baseStats": {"hp": 55, "atk": 80, "def": 80, "spa": 135, "spd": 120, "spe": 100},
		"abilities": {"0": "Beads of Ruin"},
		"heightm": 0.4,
		"weightkg": 4.9,
		"color": "Red",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Roaringmoon": {
		"num": 1005,
		"name": "Roaring Moon",
		"types": ["Dragon", "Dark"],
		"gender": "N",
		"baseStats": {"hp": 105, "atk": 139, "def": 71, "spa": 55, "spd": 101, "spe": 119},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 2,
		"weightkg": 380,
		"color": "Blue",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Ironvaliant": {
		"num": 1006,
		"name": "Iron Valiant",
		"types": ["Fairy", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 74, "atk": 130, "def": 90, "spa": 120, "spd": 60, "spe": 116},
		"abilities": {"0": "Quark Drive"},
		"heightm": 1.4,
		"weightkg": 35,
		"color": "White",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Koraidon": {
		"num": 1007,
		"name": "Koraidon",
		"types": ["Fighting", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 135, "def": 115, "spa": 85, "spd": 100, "spe": 135},
		"abilities": {"0": "Orichalcum Pulse"},
		"heightm": 2.5,
		"weightkg": 303,
		"color": "Red",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Miraidon": {
		"num": 1008,
		"name": "Miraidon",
		"types": ["Electric", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 85, "def": 100, "spa": 135, "spd": 115, "spe": 135},
		"abilities": {"0": "Hadron Engine"},
		"heightm": 3.5,
		"weightkg": 240,
		"color": "Purple",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Walkingwake": {
		"num": 1009,
		"name": "Walking Wake",
		"types": ["Water", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 99, "atk": 83, "def": 91, "spa": 125, "spd": 83, "spe": 109},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 3.5,
		"weightkg": 280,
		"color": "Blue",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Ironleaves": {
		"num": 1010,
		"name": "Iron Leaves",
		"types": ["Grass", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 90, "atk": 130, "def": 88, "spa": 70, "spd": 108, "spe": 104},
		"abilities": {"0": "Quark Drive"},
		"heightm": 1.5,
		"weightkg": 125,
		"color": "Green",
		"tags": ["Paradox"],
		"eggGroups": ["Undiscovered"],
	},
	"Dipplin": {
		"num": 1011,
		"name": "Dipplin",
		"types": ["Grass", "Dragon"],
		"baseStats": {"hp": 80, "atk": 80, "def": 110, "spa": 95, "spd": 80, "spe": 40},
		"abilities": {"0": "Supersweet Syrup", "1": "Gluttony", "H": "Sticky Hold"},
		"heightm": 0.4,
		"weightkg": 4.4,
		"color": "Green",
		"prevo": "Applin",
		"evos": ["Hydrapple"],
		"evoType": "useItem",
		"evoItem": "Syrupy Apple",
		"eggGroups": ["Grass", "Dragon"],
	},
	"Poltchageist": {
		"num": 1012,
		"name": "Poltchageist",
		"baseForme": "Counterfeit",
		"types": ["Grass", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 40, "atk": 45, "def": 45, "spa": 74, "spd": 54, "spe": 50},
		"abilities": {"0": "Hospitality", "H": "Heatproof"},
		"heightm": 0.1,
		"weightkg": 1.1,
		"color": "Green",
		"evos": ["Sinistcha"],
		"eggGroups": ["Mineral", "Amorphous"],
		"otherFormes": ["Poltchageist-Artisan"],
		"formeOrder": ["Poltchageist", "Poltchageist-Artisan"],
	},
	"Poltchageistartisan": {
		"num": 1012,
		"name": "Poltchageist-Artisan",
		"baseSpecies": "Poltchageist",
		"forme": "Artisan",
		"types": ["Grass", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 40, "atk": 45, "def": 45, "spa": 74, "spd": 54, "spe": 50},
		"abilities": {"0": "Hospitality", "H": "Heatproof"},
		"heightm": 0.1,
		"weightkg": 1.1,
		"color": "Green",
		"evos": ["Sinistcha-Masterpiece"],
		"eggGroups": ["Undiscovered"],
	},
	"Sinistcha": {
		"num": 1013,
		"name": "Sinistcha",
		"baseForme": "Unremarkable",
		"types": ["Grass", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 71, "atk": 60, "def": 106, "spa": 121, "spd": 80, "spe": 70},
		"abilities": {"0": "Hospitality", "H": "Heatproof"},
		"heightm": 0.2,
		"weightkg": 2.2,
		"color": "Green",
		"prevo": "Poltchageist",
		"evoType": "useItem",
		"evoItem": "Unremarkable Teacup",
		"eggGroups": ["Mineral", "Amorphous"],
		"otherFormes": ["Sinistcha-Masterpiece"],
		"formeOrder": ["Sinistcha", "Sinistcha-Masterpiece"],
	},
	"Sinistchamasterpiece": {
		"num": 1013,
		"name": "Sinistcha-Masterpiece",
		"baseSpecies": "Sinistcha",
		"forme": "Masterpiece",
		"types": ["Grass", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 71, "atk": 60, "def": 106, "spa": 121, "spd": 80, "spe": 70},
		"abilities": {"0": "Hospitality", "H": "Heatproof"},
		"heightm": 0.2,
		"weightkg": 2.2,
		"color": "Green",
		"prevo": "Poltchageist-Artisan",
		"evoType": "useItem",
		"evoItem": "Masterpiece Teacup",
		"eggGroups": ["Undiscovered"],
	},
	"Okidogi": {
		"num": 1014,
		"name": "Okidogi",
		"types": ["Poison", "Fighting"],
		"gender": "M",
		"baseStats": {"hp": 88, "atk": 128, "def": 115, "spa": 58, "spd": 86, "spe": 80},
		"abilities": {"0": "Toxic Chain", "H": "Guard Dog"},
		"heightm": 1.8,
		"weightkg": 92,
		"color": "Black",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Munkidori": {
		"num": 1015,
		"name": "Munkidori",
		"types": ["Poison", "Psychic"],
		"gender": "M",
		"baseStats": {"hp": 88, "atk": 75, "def": 66, "spa": 130, "spd": 90, "spe": 106},
		"abilities": {"0": "Toxic Chain", "H": "Frisk"},
		"heightm": 1,
		"weightkg": 12.2,
		"color": "Black",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Fezandipiti": {
		"num": 1016,
		"name": "Fezandipiti",
		"types": ["Poison", "Fairy"],
		"gender": "M",
		"baseStats": {"hp": 88, "atk": 91, "def": 82, "spa": 70, "spd": 125, "spe": 99},
		"abilities": {"0": "Toxic Chain", "H": "Technician"},
		"heightm": 1.4,
		"weightkg": 30.1,
		"color": "Black",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Ogerpon": {
		"num": 1017,
		"name": "Ogerpon",
		"baseForme": "Teal",
		"types": ["Grass"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 120, "def": 84, "spa": 60, "spd": 96, "spe": 110},
		"abilities": {"0": "Defiant"},
		"heightm": 1.2,
		"weightkg": 39.8,
		"color": "Green",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": [
			"Ogerpon-Wellspring",
			"Ogerpon-Hearthflame",
			"Ogerpon-Cornerstone",
			"Ogerpon-Teal-Tera",
			"Ogerpon-Wellspring-Tera",
			"Ogerpon-Hearthflame-Tera",
			"Ogerpon-Cornerstone-Tera",
		],
		"formeOrder": [
			"Ogerpon",
			"Ogerpon-Wellspring",
			"Ogerpon-Hearthflame",
			"Ogerpon-Cornerstone",
			"Ogerpon-Teal-Tera",
			"Ogerpon-Wellspring-Tera",
			"Ogerpon-Hearthflame-Tera",
			"Ogerpon-Cornerstone-Tera",
		],
		"forceTeraType": "Grass",
	},
	"Ogerponwellspring": {
		"num": 1017,
		"name": "Ogerpon-Wellspring",
		"baseSpecies": "Ogerpon",
		"forme": "Wellspring",
		"types": ["Grass", "Water"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 120, "def": 84, "spa": 60, "spd": 96, "spe": 110},
		"abilities": {"0": "Water Absorb"},
		"heightm": 1.2,
		"weightkg": 39.8,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Wellspring Mask",
		"changesFrom": "Ogerpon",
		"forceTeraType": "Water",
	},
	"Ogerponhearthflame": {
		"num": 1017,
		"name": "Ogerpon-Hearthflame",
		"baseSpecies": "Ogerpon",
		"forme": "Hearthflame",
		"types": ["Grass", "Fire"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 120, "def": 84, "spa": 60, "spd": 96, "spe": 110},
		"abilities": {"0": "Mold Breaker"},
		"heightm": 1.2,
		"weightkg": 39.8,
		"color": "Red",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Hearthflame Mask",
		"changesFrom": "Ogerpon",
		"forceTeraType": "Fire",
	},
	"Ogerponcornerstone": {
		"num": 1017,
		"name": "Ogerpon-Cornerstone",
		"baseSpecies": "Ogerpon",
		"forme": "Cornerstone",
		"types": ["Grass", "Rock"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 120, "def": 84, "spa": 60, "spd": 96, "spe": 110},
		"abilities": {"0": "Sturdy"},
		"heightm": 1.2,
		"weightkg": 39.8,
		"color": "Gray",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Cornerstone Mask",
		"changesFrom": "Ogerpon",
		"forceTeraType": "Rock",
	},
	"Ogerpontealtera": {
		"num": 1017,
		"name": "Ogerpon-Teal-Tera",
		"baseSpecies": "Ogerpon",
		"forme": "Teal-Tera",
		"types": ["Grass"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 120, "def": 84, "spa": 60, "spd": 96, "spe": 110},
		"abilities": {"0": "Embody Aspect (Teal)"},
		"heightm": 1.2,
		"weightkg": 39.8,
		"color": "Green",
		"eggGroups": ["Undiscovered"],
		"battleOnly": "Ogerpon",
		"forceTeraType": "Grass",
	},
	"Ogerponwellspringtera": {
		"num": 1017,
		"name": "Ogerpon-Wellspring-Tera",
		"baseSpecies": "Ogerpon",
		"forme": "Wellspring-Tera",
		"types": ["Grass", "Water"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 120, "def": 84, "spa": 60, "spd": 96, "spe": 110},
		"abilities": {"0": "Embody Aspect (Wellspring)"},
		"heightm": 1.2,
		"weightkg": 39.8,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Wellspring Mask",
		"battleOnly": "Ogerpon-Wellspring",
		"forceTeraType": "Water",
	},
	"Ogerponhearthflametera": {
		"num": 1017,
		"name": "Ogerpon-Hearthflame-Tera",
		"baseSpecies": "Ogerpon",
		"forme": "Hearthflame-Tera",
		"types": ["Grass", "Fire"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 120, "def": 84, "spa": 60, "spd": 96, "spe": 110},
		"abilities": {"0": "Embody Aspect (Hearthflame)"},
		"heightm": 1.2,
		"weightkg": 39.8,
		"color": "Red",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Hearthflame Mask",
		"battleOnly": "Ogerpon-Hearthflame",
		"forceTeraType": "Fire",
	},
	"Ogerponcornerstonetera": {
		"num": 1017,
		"name": "Ogerpon-Cornerstone-Tera",
		"baseSpecies": "Ogerpon",
		"forme": "Cornerstone-Tera",
		"types": ["Grass", "Rock"],
		"gender": "F",
		"baseStats": {"hp": 80, "atk": 120, "def": 84, "spa": 60, "spd": 96, "spe": 110},
		"abilities": {"0": "Embody Aspect (Cornerstone)"},
		"heightm": 1.2,
		"weightkg": 39.8,
		"color": "Gray",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Cornerstone Mask",
		"battleOnly": "Ogerpon-Cornerstone",
		"forceTeraType": "Rock",
	},
	"Archaludon": {
		"num": 1018,
		"name": "Archaludon",
		"types": ["Steel", "Dragon"],
		"baseStats": {"hp": 90, "atk": 105, "def": 130, "spa": 125, "spd": 65, "spe": 85},
		"abilities": {"0": "Stamina", "1": "Sturdy", "H": "Stalwart"},
		"heightm": 2,
		"weightkg": 60,
		"color": "White",
		"prevo": "Duraludon",
		"evoType": "useItem",
		"evoItem": "Metal Alloy",
		"eggGroups": ["Mineral", "Dragon"],
	},
	"Hydrapple": {
		"num": 1019,
		"name": "Hydrapple",
		"types": ["Grass", "Dragon"],
		"baseStats": {"hp": 106, "atk": 80, "def": 110, "spa": 120, "spd": 80, "spe": 44},
		"abilities": {"0": "Supersweet Syrup", "1": "Regenerator", "H": "Sticky Hold"},
		"heightm": 1.8,
		"weightkg": 93,
		"color": "Green",
		"prevo": "Dipplin",
		"evoType": "levelMove",
		"evoMove": "Dragon Cheer",
		"eggGroups": ["Grass", "Dragon"],
	},
	"Gougingfire": {
		"num": 1020,
		"name": "Gouging Fire",
		"types": ["Fire", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 105, "atk": 115, "def": 121, "spa": 65, "spd": 93, "spe": 91},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 3.5,
		"weightkg": 590,
		"color": "Brown",
		"eggGroups": ["Undiscovered"],
	},
	"Ragingbolt": {
		"num": 1021,
		"name": "Raging Bolt",
		"types": ["Electric", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 125, "atk": 73, "def": 91, "spa": 137, "spd": 89, "spe": 75},
		"abilities": {"0": "Protosynthesis"},
		"heightm": 5.2,
		"weightkg": 480,
		"color": "Yellow",
		"eggGroups": ["Undiscovered"],
	},
	"Ironboulder": {
		"num": 1022,
		"name": "Iron Boulder",
		"types": ["Rock", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 90, "atk": 120, "def": 80, "spa": 68, "spd": 108, "spe": 124},
		"abilities": {"0": "Quark Drive"},
		"heightm": 1.5,
		"weightkg": 162.5,
		"color": "Gray",
		"eggGroups": ["Undiscovered"],
	},
	"Ironcrown": {
		"num": 1023,
		"name": "Iron Crown",
		"types": ["Steel", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 90, "atk": 72, "def": 100, "spa": 122, "spd": 108, "spe": 98},
		"abilities": {"0": "Quark Drive"},
		"heightm": 1.6,
		"weightkg": 156,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
	},
	"Terapagos": {
		"num": 1024,
		"name": "Terapagos",
		"types": ["Normal"],
		"baseStats": {"hp": 90, "atk": 65, "def": 85, "spa": 65, "spd": 85, "spe": 60},
		"abilities": {"0": "Tera Shift"},
		"heightm": 0.2,
		"weightkg": 6.5,
		"color": "Blue",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Terapagos-Terastal", "Terapagos-Stellar"],
		"formeOrder": ["Terapagos", "Terapagos-Terastal", "Terapagos-Stellar"],
		"forceTeraType": "Stellar",
	},
	"Terapagosterastal": {
		"num": 1024,
		"name": "Terapagos-Terastal",
		"baseSpecies": "Terapagos",
		"forme": "Terastal",
		"types": ["Normal"],
		"baseStats": {"hp": 95, "atk": 95, "def": 110, "spa": 105, "spd": 110, "spe": 85},
		"abilities": {"0": "Tera Shell"},
		"heightm": 0.3,
		"weightkg": 16,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
		"battleOnly": "Terapagos",
		"forceTeraType": "Stellar",
	},
	"Terapagosstellar": {
		"num": 1024,
		"name": "Terapagos-Stellar",
		"baseSpecies": "Terapagos",
		"forme": "Stellar",
		"types": ["Normal"],
		"baseStats": {"hp": 160, "atk": 105, "def": 110, "spa": 130, "spd": 110, "spe": 85},
		"abilities": {"0": "Teraform Zero"},
		"heightm": 1.7,
		"weightkg": 77,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
		"battleOnly": "Terapagos",
		"forceTeraType": "Stellar",
	},
	"Pecharunt": {
		"num": 1025,
		"name": "Pecharunt",
		"types": ["Poison", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 88, "atk": 88, "def": 160, "spa": 88, "spd": 88, "spe": 88},
		"abilities": {"0": "Poison Puppeteer"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Purple",
		"tags": ["Mythical"],
		"eggGroups": ["Undiscovered"],
	},
}
