"""Pokédex entries for Sinnoh region."""

from ..functions.pokedex_funcs import *

pokedex = {
	"Turtwig": {
		"num": 387,
		"name": "Turtwig",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 55, "atk": 68, "def": 64, "spa": 45, "spd": 55, "spe": 31},
		"abilities": {"0": "Overgrow", "H": "Shell Armor"},
		"heightm": 0.4,
		"weightkg": 10.2,
		"color": "Green",
		"evos": ["Grotle"],
		"eggGroups": ["Monster", "Grass"],
	},
	"Grotle": {
		"num": 388,
		"name": "Grotle",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 75, "atk": 89, "def": 85, "spa": 55, "spd": 65, "spe": 36},
		"abilities": {"0": "Overgrow", "H": "Shell Armor"},
		"heightm": 1.1,
		"weightkg": 97,
		"color": "Green",
		"prevo": "Turtwig",
		"evoLevel": 18,
		"evos": ["Torterra"],
		"eggGroups": ["Monster", "Grass"],
	},
	"Torterra": {
		"num": 389,
		"name": "Torterra",
		"types": ["Grass", "Ground"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 95, "atk": 109, "def": 105, "spa": 75, "spd": 85, "spe": 56},
		"abilities": {"0": "Overgrow", "H": "Shell Armor"},
		"heightm": 2.2,
		"weightkg": 310,
		"color": "Green",
		"prevo": "Grotle",
		"evoLevel": 32,
		"eggGroups": ["Monster", "Grass"],
	},
	"Chimchar": {
		"num": 390,
		"name": "Chimchar",
		"types": ["Fire"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 44, "atk": 58, "def": 44, "spa": 58, "spd": 44, "spe": 61},
		"abilities": {"0": "Blaze", "H": "Iron Fist"},
		"heightm": 0.5,
		"weightkg": 6.2,
		"color": "Brown",
		"evos": ["Monferno"],
		"eggGroups": ["Field", "Human-Like"],
	},
	"Monferno": {
		"num": 391,
		"name": "Monferno",
		"types": ["Fire", "Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 64, "atk": 78, "def": 52, "spa": 78, "spd": 52, "spe": 81},
		"abilities": {"0": "Blaze", "H": "Iron Fist"},
		"heightm": 0.9,
		"weightkg": 22,
		"color": "Brown",
		"prevo": "Chimchar",
		"evoLevel": 14,
		"evos": ["Infernape"],
		"eggGroups": ["Field", "Human-Like"],
	},
	"Infernape": {
		"num": 392,
		"name": "Infernape",
		"types": ["Fire", "Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 76, "atk": 104, "def": 71, "spa": 104, "spd": 71, "spe": 108},
		"abilities": {"0": "Blaze", "H": "Iron Fist"},
		"heightm": 1.2,
		"weightkg": 55,
		"color": "Brown",
		"prevo": "Monferno",
		"evoLevel": 36,
		"eggGroups": ["Field", "Human-Like"],
	},
	"Piplup": {
		"num": 393,
		"name": "Piplup",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 53, "atk": 51, "def": 53, "spa": 61, "spd": 56, "spe": 40},
		"abilities": {"0": "Torrent", "H": "Competitive"},
		"heightm": 0.4,
		"weightkg": 5.2,
		"color": "Blue",
		"evos": ["Prinplup"],
		"eggGroups": ["Water 1", "Field"],
	},
	"Prinplup": {
		"num": 394,
		"name": "Prinplup",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 64, "atk": 66, "def": 68, "spa": 81, "spd": 76, "spe": 50},
		"abilities": {"0": "Torrent", "H": "Competitive"},
		"heightm": 0.8,
		"weightkg": 23,
		"color": "Blue",
		"prevo": "Piplup",
		"evoLevel": 16,
		"evos": ["Empoleon"],
		"eggGroups": ["Water 1", "Field"],
	},
	"Empoleon": {
		"num": 395,
		"name": "Empoleon",
		"types": ["Water", "Steel"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 84, "atk": 86, "def": 88, "spa": 111, "spd": 101, "spe": 60},
		"abilities": {"0": "Torrent", "H": "Competitive"},
		"heightm": 1.7,
		"weightkg": 84.5,
		"color": "Blue",
		"prevo": "Prinplup",
		"evoLevel": 36,
		"eggGroups": ["Water 1", "Field"],
	},
	"Starly": {
		"num": 396,
		"name": "Starly",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 40, "atk": 55, "def": 30, "spa": 30, "spd": 30, "spe": 60},
		"abilities": {"0": "Keen Eye", "H": "Reckless"},
		"heightm": 0.3,
		"weightkg": 2,
		"color": "Brown",
		"evos": ["Staravia"],
		"eggGroups": ["Flying"],
	},
	"Staravia": {
		"num": 397,
		"name": "Staravia",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 55, "atk": 75, "def": 50, "spa": 40, "spd": 40, "spe": 80},
		"abilities": {"0": "Intimidate", "H": "Reckless"},
		"heightm": 0.6,
		"weightkg": 15.5,
		"color": "Brown",
		"prevo": "Starly",
		"evoLevel": 14,
		"evos": ["Staraptor"],
		"eggGroups": ["Flying"],
	},
	"Staraptor": {
		"num": 398,
		"name": "Staraptor",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 85, "atk": 120, "def": 70, "spa": 50, "spd": 60, "spe": 100},
		"abilities": {"0": "Intimidate", "H": "Reckless"},
		"heightm": 1.2,
		"weightkg": 24.9,
		"color": "Brown",
		"prevo": "Staravia",
		"evoLevel": 34,
		"eggGroups": ["Flying"],
	},
	"Bidoof": {
		"num": 399,
		"name": "Bidoof",
		"types": ["Normal"],
		"baseStats": {"hp": 59, "atk": 45, "def": 40, "spa": 35, "spd": 40, "spe": 31},
		"abilities": {"0": "Simple", "1": "Unaware", "H": "Moody"},
		"heightm": 0.5,
		"weightkg": 20,
		"color": "Brown",
		"evos": ["Bibarel"],
		"eggGroups": ["Water 1", "Field"],
	},
	"Bibarel": {
		"num": 400,
		"name": "Bibarel",
		"types": ["Normal", "Water"],
		"baseStats": {"hp": 79, "atk": 85, "def": 60, "spa": 55, "spd": 60, "spe": 71},
		"abilities": {"0": "Simple", "1": "Unaware", "H": "Moody"},
		"heightm": 1,
		"weightkg": 31.5,
		"color": "Brown",
		"prevo": "Bidoof",
		"evoLevel": 15,
		"eggGroups": ["Water 1", "Field"],
	},
	"Kricketot": {
		"num": 401,
		"name": "Kricketot",
		"types": ["Bug"],
		"baseStats": {"hp": 37, "atk": 25, "def": 41, "spa": 25, "spd": 41, "spe": 25},
		"abilities": {"0": "Shed Skin", "H": "Run Away"},
		"heightm": 0.3,
		"weightkg": 2.2,
		"color": "Red",
		"evos": ["Kricketune"],
		"eggGroups": ["Bug"],
	},
	"Kricketune": {
		"num": 402,
		"name": "Kricketune",
		"types": ["Bug"],
		"baseStats": {"hp": 77, "atk": 85, "def": 51, "spa": 55, "spd": 51, "spe": 65},
		"abilities": {"0": "Swarm", "H": "Technician"},
		"heightm": 1,
		"weightkg": 25.5,
		"color": "Red",
		"prevo": "Kricketot",
		"evoLevel": 10,
		"eggGroups": ["Bug"],
	},
	"Shinx": {
		"num": 403,
		"name": "Shinx",
		"types": ["Electric"],
		"baseStats": {"hp": 45, "atk": 65, "def": 34, "spa": 40, "spd": 34, "spe": 45},
		"abilities": {"0": "Rivalry", "1": "Intimidate", "H": "Guts"},
		"heightm": 0.5,
		"weightkg": 9.5,
		"color": "Blue",
		"evos": ["Luxio"],
		"eggGroups": ["Field"],
	},
	"Luxio": {
		"num": 404,
		"name": "Luxio",
		"types": ["Electric"],
		"baseStats": {"hp": 60, "atk": 85, "def": 49, "spa": 60, "spd": 49, "spe": 60},
		"abilities": {"0": "Rivalry", "1": "Intimidate", "H": "Guts"},
		"heightm": 0.9,
		"weightkg": 30.5,
		"color": "Blue",
		"prevo": "Shinx",
		"evoLevel": 15,
		"evos": ["Luxray"],
		"eggGroups": ["Field"],
	},
	"Luxray": {
		"num": 405,
		"name": "Luxray",
		"types": ["Electric"],
		"baseStats": {"hp": 80, "atk": 120, "def": 79, "spa": 95, "spd": 79, "spe": 70},
		"abilities": {"0": "Rivalry", "1": "Intimidate", "H": "Guts"},
		"heightm": 1.4,
		"weightkg": 42,
		"color": "Blue",
		"prevo": "Luxio",
		"evoLevel": 30,
		"eggGroups": ["Field"],
	},
	"Budew": {
		"num": 406,
		"name": "Budew",
		"types": ["Grass", "Poison"],
		"baseStats": {"hp": 40, "atk": 30, "def": 35, "spa": 50, "spd": 70, "spe": 55},
		"abilities": {"0": "Natural Cure", "1": "Poison Point", "H": "Leaf Guard"},
		"heightm": 0.2,
		"weightkg": 1.2,
		"color": "Green",
		"evos": ["Roselia"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Roserade": {
		"num": 407,
		"name": "Roserade",
		"types": ["Grass", "Poison"],
		"baseStats": {"hp": 60, "atk": 70, "def": 65, "spa": 125, "spd": 105, "spe": 90},
		"abilities": {"0": "Natural Cure", "1": "Poison Point", "H": "Technician"},
		"heightm": 0.9,
		"weightkg": 14.5,
		"color": "Green",
		"prevo": "Roselia",
		"evoType": "useItem",
		"evoItem": "Shiny Stone",
		"eggGroups": ["Fairy", "Grass"],
	},
	"Cranidos": {
		"num": 408,
		"name": "Cranidos",
		"types": ["Rock"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 67, "atk": 125, "def": 40, "spa": 30, "spd": 30, "spe": 58},
		"abilities": {"0": "Mold Breaker", "H": "Sheer Force"},
		"heightm": 0.9,
		"weightkg": 31.5,
		"color": "Blue",
		"evos": ["Rampardos"],
		"eggGroups": ["Monster"],
	},
	"Rampardos": {
		"num": 409,
		"name": "Rampardos",
		"types": ["Rock"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 97, "atk": 165, "def": 60, "spa": 65, "spd": 50, "spe": 58},
		"abilities": {"0": "Mold Breaker", "H": "Sheer Force"},
		"heightm": 1.6,
		"weightkg": 102.5,
		"color": "Blue",
		"prevo": "Cranidos",
		"evoLevel": 30,
		"eggGroups": ["Monster"],
	},
	"Shieldon": {
		"num": 410,
		"name": "Shieldon",
		"types": ["Rock", "Steel"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 30, "atk": 42, "def": 118, "spa": 42, "spd": 88, "spe": 30},
		"abilities": {"0": "Sturdy", "H": "Soundproof"},
		"heightm": 0.5,
		"weightkg": 57,
		"color": "Gray",
		"evos": ["Bastiodon"],
		"eggGroups": ["Monster"],
	},
	"Bastiodon": {
		"num": 411,
		"name": "Bastiodon",
		"types": ["Rock", "Steel"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 60, "atk": 52, "def": 168, "spa": 47, "spd": 138, "spe": 30},
		"abilities": {"0": "Sturdy", "H": "Soundproof"},
		"heightm": 1.3,
		"weightkg": 149.5,
		"color": "Gray",
		"prevo": "Shieldon",
		"evoLevel": 30,
		"eggGroups": ["Monster"],
	},
	"Burmy": {
		"num": 412,
		"name": "Burmy",
		"baseForme": "Plant",
		"types": ["Bug"],
		"baseStats": {"hp": 40, "atk": 29, "def": 45, "spa": 29, "spd": 45, "spe": 36},
		"abilities": {"0": "Shed Skin", "H": "Overcoat"},
		"heightm": 0.2,
		"weightkg": 3.4,
		"color": "Green",
		"evos": ["Wormadam", "Wormadam-Sandy", "Wormadam-Trash", "Mothim"],
		"eggGroups": ["Bug"],
		"cosmeticFormes": ["Burmy-Sandy", "Burmy-Trash"],
		"formeOrder": ["Burmy", "Burmy-Sandy", "Burmy-Trash"],
	},
	"Wormadam": {
		"num": 413,
		"name": "Wormadam",
		"baseForme": "Plant",
		"types": ["Bug", "Grass"],
		"gender": "F",
		"baseStats": {"hp": 60, "atk": 59, "def": 85, "spa": 79, "spd": 105, "spe": 36},
		"abilities": {"0": "Anticipation", "H": "Overcoat"},
		"heightm": 0.5,
		"weightkg": 6.5,
		"color": "Green",
		"prevo": "Burmy",
		"evoLevel": 20,
		"eggGroups": ["Bug"],
		"otherFormes": ["Wormadam-Sandy", "Wormadam-Trash"],
		"formeOrder": ["Wormadam", "Wormadam-Sandy", "Wormadam-Trash"],
	},
	"Wormadamsandy": {
		"num": 413,
		"name": "Wormadam-Sandy",
		"baseSpecies": "Wormadam",
		"forme": "Sandy",
		"types": ["Bug", "Ground"],
		"gender": "F",
		"baseStats": {"hp": 60, "atk": 79, "def": 105, "spa": 59, "spd": 85, "spe": 36},
		"abilities": {"0": "Anticipation", "H": "Overcoat"},
		"heightm": 0.5,
		"weightkg": 6.5,
		"color": "Brown",
		"prevo": "Burmy",
		"evoLevel": 20,
		"eggGroups": ["Bug"],
	},
	"Wormadamtrash": {
		"num": 413,
		"name": "Wormadam-Trash",
		"baseSpecies": "Wormadam",
		"forme": "Trash",
		"types": ["Bug", "Steel"],
		"gender": "F",
		"baseStats": {"hp": 60, "atk": 69, "def": 95, "spa": 69, "spd": 95, "spe": 36},
		"abilities": {"0": "Anticipation", "H": "Overcoat"},
		"heightm": 0.5,
		"weightkg": 6.5,
		"color": "Red",
		"prevo": "Burmy",
		"evoLevel": 20,
		"eggGroups": ["Bug"],
	},
	"Mothim": {
		"num": 414,
		"name": "Mothim",
		"types": ["Bug", "Flying"],
		"gender": "M",
		"baseStats": {"hp": 70, "atk": 94, "def": 50, "spa": 94, "spd": 50, "spe": 66},
		"abilities": {"0": "Swarm", "H": "Tinted Lens"},
		"heightm": 0.9,
		"weightkg": 23.3,
		"color": "Yellow",
		"prevo": "Burmy",
		"evoLevel": 20,
		"eggGroups": ["Bug"],
	},
	"Combee": {
		"num": 415,
		"name": "Combee",
		"types": ["Bug", "Flying"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 30, "atk": 30, "def": 42, "spa": 30, "spd": 42, "spe": 70},
		"abilities": {"0": "Honey Gather", "H": "Hustle"},
		"heightm": 0.3,
		"weightkg": 5.5,
		"color": "Yellow",
		"evos": ["Vespiquen"],
		"eggGroups": ["Bug"],
	},
	"Vespiquen": {
		"num": 416,
		"name": "Vespiquen",
		"types": ["Bug", "Flying"],
		"gender": "F",
		"baseStats": {"hp": 70, "atk": 80, "def": 102, "spa": 80, "spd": 102, "spe": 40},
		"abilities": {"0": "Pressure", "H": "Unnerve"},
		"heightm": 1.2,
		"weightkg": 38.5,
		"color": "Yellow",
		"prevo": "Combee",
		"evoLevel": 21,
		"eggGroups": ["Bug"],
	},
	"Pachirisu": {
		"num": 417,
		"name": "Pachirisu",
		"types": ["Electric"],
		"baseStats": {"hp": 60, "atk": 45, "def": 70, "spa": 45, "spd": 90, "spe": 95},
		"abilities": {"0": "Run Away", "1": "Pickup", "H": "Volt Absorb"},
		"heightm": 0.4,
		"weightkg": 3.9,
		"color": "White",
		"eggGroups": ["Field", "Fairy"],
	},
	"Buizel": {
		"num": 418,
		"name": "Buizel",
		"types": ["Water"],
		"baseStats": {"hp": 55, "atk": 65, "def": 35, "spa": 60, "spd": 30, "spe": 85},
		"abilities": {"0": "Swift Swim", "H": "Water Veil"},
		"heightm": 0.7,
		"weightkg": 29.5,
		"color": "Brown",
		"evos": ["Floatzel"],
		"eggGroups": ["Water 1", "Field"],
	},
	"Floatzel": {
		"num": 419,
		"name": "Floatzel",
		"types": ["Water"],
		"baseStats": {"hp": 85, "atk": 105, "def": 55, "spa": 85, "spd": 50, "spe": 115},
		"abilities": {"0": "Swift Swim", "H": "Water Veil"},
		"heightm": 1.1,
		"weightkg": 33.5,
		"color": "Brown",
		"prevo": "Buizel",
		"evoLevel": 26,
		"eggGroups": ["Water 1", "Field"],
	},
	"Cherubi": {
		"num": 420,
		"name": "Cherubi",
		"types": ["Grass"],
		"baseStats": {"hp": 45, "atk": 35, "def": 45, "spa": 62, "spd": 53, "spe": 35},
		"abilities": {"0": "Chlorophyll"},
		"heightm": 0.4,
		"weightkg": 3.3,
		"color": "Pink",
		"evos": ["Cherrim"],
		"eggGroups": ["Fairy", "Grass"],
	},
	"Cherrim": {
		"num": 421,
		"name": "Cherrim",
		"baseForme": "Overcast",
		"types": ["Grass"],
		"baseStats": {"hp": 70, "atk": 60, "def": 70, "spa": 87, "spd": 78, "spe": 85},
		"abilities": {"0": "Flower Gift"},
		"heightm": 0.5,
		"weightkg": 9.3,
		"color": "Purple",
		"prevo": "Cherubi",
		"evoLevel": 25,
		"eggGroups": ["Fairy", "Grass"],
		"otherFormes": ["Cherrim-Sunshine"],
		"formeOrder": ["Cherrim", "Cherrim-Sunshine"],
	},
	"Cherrimsunshine": {
		"num": 421,
		"name": "Cherrim-Sunshine",
		"baseSpecies": "Cherrim",
		"forme": "Sunshine",
		"types": ["Grass"],
		"baseStats": {"hp": 70, "atk": 60, "def": 70, "spa": 87, "spd": 78, "spe": 85},
		"abilities": {"0": "Flower Gift"},
		"heightm": 0.5,
		"weightkg": 9.3,
		"color": "Pink",
		"eggGroups": ["Fairy", "Grass"],
		"requiredAbility": "Flower Gift",
		"battleOnly": "Cherrim",
	},
	"Shellos": {
		"num": 422,
		"name": "Shellos",
		"baseForme": "West",
		"types": ["Water"],
		"baseStats": {"hp": 76, "atk": 48, "def": 48, "spa": 57, "spd": 62, "spe": 34},
		"abilities": {"0": "Sticky Hold", "1": "Storm Drain", "H": "Sand Force"},
		"heightm": 0.3,
		"weightkg": 6.3,
		"color": "Purple",
		"evos": ["Gastrodon"],
		"eggGroups": ["Water 1", "Amorphous"],
		"cosmeticFormes": ["Shellos-East"],
		"formeOrder": ["Shellos", "Shellos-East"],
	},
	"Gastrodon": {
		"num": 423,
		"name": "Gastrodon",
		"baseForme": "West",
		"types": ["Water", "Ground"],
		"baseStats": {"hp": 111, "atk": 83, "def": 68, "spa": 92, "spd": 82, "spe": 39},
		"abilities": {"0": "Sticky Hold", "1": "Storm Drain", "H": "Sand Force"},
		"heightm": 0.9,
		"weightkg": 29.9,
		"color": "Purple",
		"prevo": "Shellos",
		"evoLevel": 30,
		"eggGroups": ["Water 1", "Amorphous"],
		"cosmeticFormes": ["Gastrodon-East"],
		"formeOrder": ["Gastrodon", "Gastrodon-East"],
	},
	"Ambipom": {
		"num": 424,
		"name": "Ambipom",
		"types": ["Normal"],
		"baseStats": {"hp": 75, "atk": 100, "def": 66, "spa": 60, "spd": 66, "spe": 115},
		"abilities": {"0": "Technician", "1": "Pickup", "H": "Skill Link"},
		"heightm": 1.2,
		"weightkg": 20.3,
		"color": "Purple",
		"prevo": "Aipom",
		"evoType": "levelMove",
		"evoMove": "Double Hit",
		"eggGroups": ["Field"],
	},
	"Drifloon": {
		"num": 425,
		"name": "Drifloon",
		"types": ["Ghost", "Flying"],
		"baseStats": {"hp": 90, "atk": 50, "def": 34, "spa": 60, "spd": 44, "spe": 70},
		"abilities": {"0": "Aftermath", "1": "Unburden", "H": "Flare Boost"},
		"heightm": 0.4,
		"weightkg": 1.2,
		"color": "Purple",
		"evos": ["Drifblim"],
		"eggGroups": ["Amorphous"],
	},
	"Drifblim": {
		"num": 426,
		"name": "Drifblim",
		"types": ["Ghost", "Flying"],
		"baseStats": {"hp": 150, "atk": 80, "def": 44, "spa": 90, "spd": 54, "spe": 80},
		"abilities": {"0": "Aftermath", "1": "Unburden", "H": "Flare Boost"},
		"heightm": 1.2,
		"weightkg": 15,
		"color": "Purple",
		"prevo": "Drifloon",
		"evoLevel": 28,
		"eggGroups": ["Amorphous"],
	},
	"Buneary": {
		"num": 427,
		"name": "Buneary",
		"types": ["Normal"],
		"baseStats": {"hp": 55, "atk": 66, "def": 44, "spa": 44, "spd": 56, "spe": 85},
		"abilities": {"0": "Run Away", "1": "Klutz", "H": "Limber"},
		"heightm": 0.4,
		"weightkg": 5.5,
		"color": "Brown",
		"evos": ["Lopunny"],
		"eggGroups": ["Field", "Human-Like"],
	},
	"Lopunny": {
		"num": 428,
		"name": "Lopunny",
		"types": ["Normal"],
		"baseStats": {"hp": 65, "atk": 76, "def": 84, "spa": 54, "spd": 96, "spe": 105},
		"abilities": {"0": "Cute Charm", "1": "Klutz", "H": "Limber"},
		"heightm": 1.2,
		"weightkg": 33.3,
		"color": "Brown",
		"prevo": "Buneary",
		"evoType": "levelFriendship",
		"eggGroups": ["Field", "Human-Like"],
		"otherFormes": ["Lopunny-Mega"],
		"formeOrder": ["Lopunny", "Lopunny-Mega"],
	},
	"Lopunnymega": {
		"num": 428,
		"name": "Lopunny-Mega",
		"baseSpecies": "Lopunny",
		"forme": "Mega",
		"types": ["Normal", "Fighting"],
		"baseStats": {"hp": 65, "atk": 136, "def": 94, "spa": 54, "spd": 96, "spe": 135},
		"abilities": {"0": "Scrappy"},
		"heightm": 1.3,
		"weightkg": 28.3,
		"color": "Brown",
		"eggGroups": ["Field", "Human-Like"],
		"requiredItem": "Lopunnite",
	},
	"Mismagius": {
		"num": 429,
		"name": "Mismagius",
		"types": ["Ghost"],
		"baseStats": {"hp": 60, "atk": 60, "def": 60, "spa": 105, "spd": 105, "spe": 105},
		"abilities": {"0": "Levitate"},
		"heightm": 0.9,
		"weightkg": 4.4,
		"color": "Purple",
		"prevo": "Misdreavus",
		"evoType": "useItem",
		"evoItem": "Dusk Stone",
		"eggGroups": ["Amorphous"],
	},
	"Honchkrow": {
		"num": 430,
		"name": "Honchkrow",
		"types": ["Dark", "Flying"],
		"baseStats": {"hp": 100, "atk": 125, "def": 52, "spa": 105, "spd": 52, "spe": 71},
		"abilities": {"0": "Insomnia", "1": "Super Luck", "H": "Moxie"},
		"heightm": 0.9,
		"weightkg": 27.3,
		"color": "Black",
		"prevo": "Murkrow",
		"evoType": "useItem",
		"evoItem": "Dusk Stone",
		"eggGroups": ["Flying"],
	},
	"Glameow": {
		"num": 431,
		"name": "Glameow",
		"types": ["Normal"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 49, "atk": 55, "def": 42, "spa": 42, "spd": 37, "spe": 85},
		"abilities": {"0": "Limber", "1": "Own Tempo", "H": "Keen Eye"},
		"heightm": 0.5,
		"weightkg": 3.9,
		"color": "Gray",
		"evos": ["Purugly"],
		"eggGroups": ["Field"],
	},
	"Purugly": {
		"num": 432,
		"name": "Purugly",
		"types": ["Normal"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 71, "atk": 82, "def": 64, "spa": 64, "spd": 59, "spe": 112},
		"abilities": {"0": "Thick Fat", "1": "Own Tempo", "H": "Defiant"},
		"heightm": 1,
		"weightkg": 43.8,
		"color": "Gray",
		"prevo": "Glameow",
		"evoLevel": 38,
		"eggGroups": ["Field"],
	},
	"Chingling": {
		"num": 433,
		"name": "Chingling",
		"types": ["Psychic"],
		"baseStats": {"hp": 45, "atk": 30, "def": 50, "spa": 65, "spd": 50, "spe": 45},
		"abilities": {"0": "Levitate"},
		"heightm": 0.2,
		"weightkg": 0.6,
		"color": "Yellow",
		"evos": ["Chimecho"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Stunky": {
		"num": 434,
		"name": "Stunky",
		"types": ["Poison", "Dark"],
		"baseStats": {"hp": 63, "atk": 63, "def": 47, "spa": 41, "spd": 41, "spe": 74},
		"abilities": {"0": "Stench", "1": "Aftermath", "H": "Keen Eye"},
		"heightm": 0.4,
		"weightkg": 19.2,
		"color": "Purple",
		"evos": ["Skuntank"],
		"eggGroups": ["Field"],
	},
	"Skuntank": {
		"num": 435,
		"name": "Skuntank",
		"types": ["Poison", "Dark"],
		"baseStats": {"hp": 103, "atk": 93, "def": 67, "spa": 71, "spd": 61, "spe": 84},
		"abilities": {"0": "Stench", "1": "Aftermath", "H": "Keen Eye"},
		"heightm": 1,
		"weightkg": 38,
		"color": "Purple",
		"prevo": "Stunky",
		"evoLevel": 34,
		"eggGroups": ["Field"],
	},
	"Bronzor": {
		"num": 436,
		"name": "Bronzor",
		"types": ["Steel", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 57, "atk": 24, "def": 86, "spa": 24, "spd": 86, "spe": 23},
		"abilities": {"0": "Levitate", "1": "Heatproof", "H": "Heavy Metal"},
		"heightm": 0.5,
		"weightkg": 60.5,
		"color": "Green",
		"evos": ["Bronzong"],
		"eggGroups": ["Mineral"],
	},
	"Bronzong": {
		"num": 437,
		"name": "Bronzong",
		"types": ["Steel", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 67, "atk": 89, "def": 116, "spa": 79, "spd": 116, "spe": 33},
		"abilities": {"0": "Levitate", "1": "Heatproof", "H": "Heavy Metal"},
		"heightm": 1.3,
		"weightkg": 187,
		"color": "Green",
		"prevo": "Bronzor",
		"evoLevel": 33,
		"eggGroups": ["Mineral"],
	},
	"Bonsly": {
		"num": 438,
		"name": "Bonsly",
		"types": ["Rock"],
		"baseStats": {"hp": 50, "atk": 80, "def": 95, "spa": 10, "spd": 45, "spe": 10},
		"abilities": {"0": "Sturdy", "1": "Rock Head", "H": "Rattled"},
		"heightm": 0.5,
		"weightkg": 15,
		"color": "Brown",
		"evos": ["Sudowoodo"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Mimejr": {
		"num": 439,
		"name": "Mime Jr.",
		"types": ["Psychic", "Fairy"],
		"baseStats": {"hp": 20, "atk": 25, "def": 45, "spa": 70, "spd": 90, "spe": 60},
		"abilities": {"0": "Soundproof", "1": "Filter", "H": "Technician"},
		"heightm": 0.6,
		"weightkg": 13,
		"color": "Pink",
		"evos": ["Mr. Mime", "Mr. Mime-Galar"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Happiny": {
		"num": 440,
		"name": "Happiny",
		"types": ["Normal"],
		"gender": "F",
		"baseStats": {"hp": 100, "atk": 5, "def": 5, "spa": 15, "spd": 65, "spe": 30},
		"abilities": {"0": "Natural Cure", "1": "Serene Grace", "H": "Friend Guard"},
		"heightm": 0.6,
		"weightkg": 24.4,
		"color": "Pink",
		"evos": ["Chansey"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Chatot": {
		"num": 441,
		"name": "Chatot",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 76, "atk": 65, "def": 45, "spa": 92, "spd": 42, "spe": 91},
		"abilities": {"0": "Keen Eye", "1": "Tangled Feet", "H": "Big Pecks"},
		"heightm": 0.5,
		"weightkg": 1.9,
		"color": "Black",
		"eggGroups": ["Flying"],
	},
	"Spiritomb": {
		"num": 442,
		"name": "Spiritomb",
		"types": ["Ghost", "Dark"],
		"baseStats": {"hp": 50, "atk": 92, "def": 108, "spa": 92, "spd": 108, "spe": 35},
		"abilities": {"0": "Pressure", "H": "Infiltrator"},
		"heightm": 1,
		"weightkg": 108,
		"color": "Purple",
		"eggGroups": ["Amorphous"],
	},
	"Gible": {
		"num": 443,
		"name": "Gible",
		"types": ["Dragon", "Ground"],
		"baseStats": {"hp": 58, "atk": 70, "def": 45, "spa": 40, "spd": 45, "spe": 42},
		"abilities": {"0": "Sand Veil", "H": "Rough Skin"},
		"heightm": 0.7,
		"weightkg": 20.5,
		"color": "Blue",
		"evos": ["Gabite"],
		"eggGroups": ["Monster", "Dragon"],
	},
	"Gabite": {
		"num": 444,
		"name": "Gabite",
		"types": ["Dragon", "Ground"],
		"baseStats": {"hp": 68, "atk": 90, "def": 65, "spa": 50, "spd": 55, "spe": 82},
		"abilities": {"0": "Sand Veil", "H": "Rough Skin"},
		"heightm": 1.4,
		"weightkg": 56,
		"color": "Blue",
		"prevo": "Gible",
		"evoLevel": 24,
		"evos": ["Garchomp"],
		"eggGroups": ["Monster", "Dragon"],
	},
	"Garchomp": {
		"num": 445,
		"name": "Garchomp",
		"types": ["Dragon", "Ground"],
		"baseStats": {"hp": 108, "atk": 130, "def": 95, "spa": 80, "spd": 85, "spe": 102},
		"abilities": {"0": "Sand Veil", "H": "Rough Skin"},
		"heightm": 1.9,
		"weightkg": 95,
		"color": "Blue",
		"prevo": "Gabite",
		"evoLevel": 48,
		"eggGroups": ["Monster", "Dragon"],
		"otherFormes": ["Garchomp-Mega"],
		"formeOrder": ["Garchomp", "Garchomp-Mega"],
	},
	"Garchompmega": {
		"num": 445,
		"name": "Garchomp-Mega",
		"baseSpecies": "Garchomp",
		"forme": "Mega",
		"types": ["Dragon", "Ground"],
		"baseStats": {"hp": 108, "atk": 170, "def": 115, "spa": 120, "spd": 95, "spe": 92},
		"abilities": {"0": "Sand Force"},
		"heightm": 1.9,
		"weightkg": 95,
		"color": "Blue",
		"eggGroups": ["Monster", "Dragon"],
		"requiredItem": "Garchompite",
	},
	"Munchlax": {
		"num": 446,
		"name": "Munchlax",
		"types": ["Normal"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 135, "atk": 85, "def": 40, "spa": 40, "spd": 85, "spe": 5},
		"abilities": {"0": "Pickup", "1": "Thick Fat", "H": "Gluttony"},
		"heightm": 0.6,
		"weightkg": 105,
		"color": "Black",
		"evos": ["Snorlax"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Riolu": {
		"num": 447,
		"name": "Riolu",
		"types": ["Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 40, "atk": 70, "def": 40, "spa": 35, "spd": 40, "spe": 60},
		"abilities": {"0": "Steadfast", "1": "Inner Focus", "H": "Prankster"},
		"heightm": 0.7,
		"weightkg": 20.2,
		"color": "Blue",
		"evos": ["Lucario"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Lucario": {
		"num": 448,
		"name": "Lucario",
		"types": ["Fighting", "Steel"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 70, "atk": 110, "def": 70, "spa": 115, "spd": 70, "spe": 90},
		"abilities": {"0": "Steadfast", "1": "Inner Focus", "H": "Justified"},
		"heightm": 1.2,
		"weightkg": 54,
		"color": "Blue",
		"prevo": "Riolu",
		"evoType": "levelFriendship",
		"evoCondition": "during the day",
		"eggGroups": ["Field", "Human-Like"],
		"otherFormes": ["Lucario-Mega"],
		"formeOrder": ["Lucario", "Lucario-Mega"],
	},
	"Lucariomega": {
		"num": 448,
		"name": "Lucario-Mega",
		"baseSpecies": "Lucario",
		"forme": "Mega",
		"types": ["Fighting", "Steel"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 70, "atk": 145, "def": 88, "spa": 140, "spd": 70, "spe": 112},
		"abilities": {"0": "Adaptability"},
		"heightm": 1.3,
		"weightkg": 57.5,
		"color": "Blue",
		"eggGroups": ["Field", "Human-Like"],
		"requiredItem": "Lucarionite",
	},
	"Hippopotas": {
		"num": 449,
		"name": "Hippopotas",
		"types": ["Ground"],
		"baseStats": {"hp": 68, "atk": 72, "def": 78, "spa": 38, "spd": 42, "spe": 32},
		"abilities": {"0": "Sand Stream", "H": "Sand Force"},
		"heightm": 0.8,
		"weightkg": 49.5,
		"color": "Brown",
		"evos": ["Hippowdon"],
		"eggGroups": ["Field"],
	},
	"Hippowdon": {
		"num": 450,
		"name": "Hippowdon",
		"types": ["Ground"],
		"baseStats": {"hp": 108, "atk": 112, "def": 118, "spa": 68, "spd": 72, "spe": 47},
		"abilities": {"0": "Sand Stream", "H": "Sand Force"},
		"heightm": 2,
		"weightkg": 300,
		"color": "Brown",
		"prevo": "Hippopotas",
		"evoLevel": 34,
		"eggGroups": ["Field"],
	},
	"Skorupi": {
		"num": 451,
		"name": "Skorupi",
		"types": ["Poison", "Bug"],
		"baseStats": {"hp": 40, "atk": 50, "def": 90, "spa": 30, "spd": 55, "spe": 65},
		"abilities": {"0": "Battle Armor", "1": "Sniper", "H": "Keen Eye"},
		"heightm": 0.8,
		"weightkg": 12,
		"color": "Purple",
		"evos": ["Drapion"],
		"eggGroups": ["Bug", "Water 3"],
	},
	"Drapion": {
		"num": 452,
		"name": "Drapion",
		"types": ["Poison", "Dark"],
		"baseStats": {"hp": 70, "atk": 90, "def": 110, "spa": 60, "spd": 75, "spe": 95},
		"abilities": {"0": "Battle Armor", "1": "Sniper", "H": "Keen Eye"},
		"heightm": 1.3,
		"weightkg": 61.5,
		"color": "Purple",
		"prevo": "Skorupi",
		"evoLevel": 40,
		"eggGroups": ["Bug", "Water 3"],
	},
	"Croagunk": {
		"num": 453,
		"name": "Croagunk",
		"types": ["Poison", "Fighting"],
		"baseStats": {"hp": 48, "atk": 61, "def": 40, "spa": 61, "spd": 40, "spe": 50},
		"abilities": {"0": "Anticipation", "1": "Dry Skin", "H": "Poison Touch"},
		"heightm": 0.7,
		"weightkg": 23,
		"color": "Blue",
		"evos": ["Toxicroak"],
		"eggGroups": ["Human-Like"],
	},
	"Toxicroak": {
		"num": 454,
		"name": "Toxicroak",
		"types": ["Poison", "Fighting"],
		"baseStats": {"hp": 83, "atk": 106, "def": 65, "spa": 86, "spd": 65, "spe": 85},
		"abilities": {"0": "Anticipation", "1": "Dry Skin", "H": "Poison Touch"},
		"heightm": 1.3,
		"weightkg": 44.4,
		"color": "Blue",
		"prevo": "Croagunk",
		"evoLevel": 37,
		"eggGroups": ["Human-Like"],
	},
	"Carnivine": {
		"num": 455,
		"name": "Carnivine",
		"types": ["Grass"],
		"baseStats": {"hp": 74, "atk": 100, "def": 72, "spa": 90, "spd": 72, "spe": 46},
		"abilities": {"0": "Levitate"},
		"heightm": 1.4,
		"weightkg": 27,
		"color": "Green",
		"eggGroups": ["Grass"],
	},
	"Finneon": {
		"num": 456,
		"name": "Finneon",
		"types": ["Water"],
		"baseStats": {"hp": 49, "atk": 49, "def": 56, "spa": 49, "spd": 61, "spe": 66},
		"abilities": {"0": "Swift Swim", "1": "Storm Drain", "H": "Water Veil"},
		"heightm": 0.4,
		"weightkg": 7,
		"color": "Blue",
		"evos": ["Lumineon"],
		"eggGroups": ["Water 2"],
	},
	"Lumineon": {
		"num": 457,
		"name": "Lumineon",
		"types": ["Water"],
		"baseStats": {"hp": 69, "atk": 69, "def": 76, "spa": 69, "spd": 86, "spe": 91},
		"abilities": {"0": "Swift Swim", "1": "Storm Drain", "H": "Water Veil"},
		"heightm": 1.2,
		"weightkg": 24,
		"color": "Blue",
		"prevo": "Finneon",
		"evoLevel": 31,
		"eggGroups": ["Water 2"],
	},
	"Mantyke": {
		"num": 458,
		"name": "Mantyke",
		"types": ["Water", "Flying"],
		"baseStats": {"hp": 45, "atk": 20, "def": 50, "spa": 60, "spd": 120, "spe": 50},
		"abilities": {"0": "Swift Swim", "1": "Water Absorb", "H": "Water Veil"},
		"heightm": 1,
		"weightkg": 65,
		"color": "Blue",
		"evos": ["Mantine"],
		"eggGroups": ["Undiscovered"],
		"canHatch": True,
	},
	"Snover": {
		"num": 459,
		"name": "Snover",
		"types": ["Grass", "Ice"],
		"baseStats": {"hp": 60, "atk": 62, "def": 50, "spa": 62, "spd": 60, "spe": 40},
		"abilities": {"0": "Snow Warning", "H": "Soundproof"},
		"heightm": 1,
		"weightkg": 50.5,
		"color": "White",
		"evos": ["Abomasnow"],
		"eggGroups": ["Monster", "Grass"],
	},
	"Abomasnow": {
		"num": 460,
		"name": "Abomasnow",
		"types": ["Grass", "Ice"],
		"baseStats": {"hp": 90, "atk": 92, "def": 75, "spa": 92, "spd": 85, "spe": 60},
		"abilities": {"0": "Snow Warning", "H": "Soundproof"},
		"heightm": 2.2,
		"weightkg": 135.5,
		"color": "White",
		"prevo": "Snover",
		"evoLevel": 40,
		"eggGroups": ["Monster", "Grass"],
		"otherFormes": ["Abomasnow-Mega"],
		"formeOrder": ["Abomasnow", "Abomasnow-Mega"],
	},
	"Abomasnowmega": {
		"num": 460,
		"name": "Abomasnow-Mega",
		"baseSpecies": "Abomasnow",
		"forme": "Mega",
		"types": ["Grass", "Ice"],
		"baseStats": {"hp": 90, "atk": 132, "def": 105, "spa": 132, "spd": 105, "spe": 30},
		"abilities": {"0": "Snow Warning"},
		"heightm": 2.7,
		"weightkg": 185,
		"color": "White",
		"eggGroups": ["Monster", "Grass"],
		"requiredItem": "Abomasite",
	},
	"Weavile": {
		"num": 461,
		"name": "Weavile",
		"types": ["Dark", "Ice"],
		"baseStats": {"hp": 70, "atk": 120, "def": 65, "spa": 45, "spd": 85, "spe": 125},
		"abilities": {"0": "Pressure", "H": "Pickpocket"},
		"heightm": 1.1,
		"weightkg": 34,
		"color": "Black",
		"prevo": "Sneasel",
		"evoType": "levelHold",
		"evoItem": "Razor Claw",
		"evoCondition": "at night",
		"eggGroups": ["Field"],
	},
	"Magnezone": {
		"num": 462,
		"name": "Magnezone",
		"types": ["Electric", "Steel"],
		"gender": "N",
		"baseStats": {"hp": 70, "atk": 70, "def": 115, "spa": 130, "spd": 90, "spe": 60},
		"abilities": {"0": "Magnet Pull", "1": "Sturdy", "H": "Analytic"},
		"heightm": 1.2,
		"weightkg": 180,
		"color": "Gray",
		"prevo": "Magneton",
		"evoType": "useItem",
		"evoItem": "Thunder Stone",
		"eggGroups": ["Mineral"],
	},
	"Lickilicky": {
		"num": 463,
		"name": "Lickilicky",
		"types": ["Normal"],
		"baseStats": {"hp": 110, "atk": 85, "def": 95, "spa": 80, "spd": 95, "spe": 50},
		"abilities": {"0": "Own Tempo", "1": "Oblivious", "H": "Cloud Nine"},
		"heightm": 1.7,
		"weightkg": 140,
		"color": "Pink",
		"prevo": "Lickitung",
		"evoType": "levelMove",
		"evoMove": "Rollout",
		"eggGroups": ["Monster"],
	},
	"Rhyperior": {
		"num": 464,
		"name": "Rhyperior",
		"types": ["Ground", "Rock"],
		"baseStats": {"hp": 115, "atk": 140, "def": 130, "spa": 55, "spd": 55, "spe": 40},
		"abilities": {"0": "Lightning Rod", "1": "Solid Rock", "H": "Reckless"},
		"heightm": 2.4,
		"weightkg": 282.8,
		"color": "Gray",
		"prevo": "Rhydon",
		"evoType": "trade",
		"evoItem": "Protector",
		"eggGroups": ["Monster", "Field"],
	},
	"Tangrowth": {
		"num": 465,
		"name": "Tangrowth",
		"types": ["Grass"],
		"baseStats": {"hp": 100, "atk": 100, "def": 125, "spa": 110, "spd": 50, "spe": 50},
		"abilities": {"0": "Chlorophyll", "1": "Leaf Guard", "H": "Regenerator"},
		"heightm": 2,
		"weightkg": 128.6,
		"color": "Blue",
		"prevo": "Tangela",
		"evoType": "levelMove",
		"evoMove": "Ancient Power",
		"eggGroups": ["Grass"],
	},
	"Electivire": {
		"num": 466,
		"name": "Electivire",
		"types": ["Electric"],
		"genderRatio": {"M": 0.75, "F": 0.25},
		"baseStats": {"hp": 75, "atk": 123, "def": 67, "spa": 95, "spd": 85, "spe": 95},
		"abilities": {"0": "Motor Drive", "H": "Vital Spirit"},
		"heightm": 1.8,
		"weightkg": 138.6,
		"color": "Yellow",
		"prevo": "Electabuzz",
		"evoType": "trade",
		"evoItem": "Electirizer",
		"eggGroups": ["Human-Like"],
	},
	"Magmortar": {
		"num": 467,
		"name": "Magmortar",
		"types": ["Fire"],
		"genderRatio": {"M": 0.75, "F": 0.25},
		"baseStats": {"hp": 75, "atk": 95, "def": 67, "spa": 125, "spd": 95, "spe": 83},
		"abilities": {"0": "Flame Body", "H": "Vital Spirit"},
		"heightm": 1.6,
		"weightkg": 68,
		"color": "Red",
		"prevo": "Magmar",
		"evoType": "trade",
		"evoItem": "Magmarizer",
		"eggGroups": ["Human-Like"],
	},
	"Togekiss": {
		"num": 468,
		"name": "Togekiss",
		"types": ["Fairy", "Flying"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 85, "atk": 50, "def": 95, "spa": 120, "spd": 115, "spe": 80},
		"abilities": {"0": "Hustle", "1": "Serene Grace", "H": "Super Luck"},
		"heightm": 1.5,
		"weightkg": 38,
		"color": "White",
		"prevo": "Togetic",
		"evoType": "useItem",
		"evoItem": "Shiny Stone",
		"eggGroups": ["Flying", "Fairy"],
	},
	"Yanmega": {
		"num": 469,
		"name": "Yanmega",
		"types": ["Bug", "Flying"],
		"baseStats": {"hp": 86, "atk": 76, "def": 86, "spa": 116, "spd": 56, "spe": 95},
		"abilities": {"0": "Speed Boost", "1": "Tinted Lens", "H": "Frisk"},
		"heightm": 1.9,
		"weightkg": 51.5,
		"color": "Green",
		"prevo": "Yanma",
		"evoType": "levelMove",
		"evoMove": "Ancient Power",
		"eggGroups": ["Bug"],
	},
	"Leafeon": {
		"num": 470,
		"name": "Leafeon",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 65, "atk": 110, "def": 130, "spa": 60, "spd": 65, "spe": 95},
		"abilities": {"0": "Leaf Guard", "H": "Chlorophyll"},
		"heightm": 1,
		"weightkg": 25.5,
		"color": "Green",
		"prevo": "Eevee",
		"evoType": "useItem",
		"evoItem": "Leaf Stone",
		"eggGroups": ["Field"],
	},
	"Glaceon": {
		"num": 471,
		"name": "Glaceon",
		"types": ["Ice"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 65, "atk": 60, "def": 110, "spa": 130, "spd": 95, "spe": 65},
		"abilities": {"0": "Snow Cloak", "H": "Ice Body"},
		"heightm": 0.8,
		"weightkg": 25.9,
		"color": "Blue",
		"prevo": "Eevee",
		"evoType": "useItem",
		"evoItem": "Ice Stone",
		"eggGroups": ["Field"],
	},
	"Gliscor": {
		"num": 472,
		"name": "Gliscor",
		"types": ["Ground", "Flying"],
		"baseStats": {"hp": 75, "atk": 95, "def": 125, "spa": 45, "spd": 75, "spe": 95},
		"abilities": {"0": "Hyper Cutter", "1": "Sand Veil", "H": "Poison Heal"},
		"heightm": 2,
		"weightkg": 42.5,
		"color": "Purple",
		"prevo": "Gligar",
		"evoType": "levelHold",
		"evoItem": "Razor Fang",
		"evoCondition": "at night",
		"eggGroups": ["Bug"],
	},
	"Mamoswine": {
		"num": 473,
		"name": "Mamoswine",
		"types": ["Ice", "Ground"],
		"baseStats": {"hp": 110, "atk": 130, "def": 80, "spa": 70, "spd": 60, "spe": 80},
		"abilities": {"0": "Oblivious", "1": "Snow Cloak", "H": "Thick Fat"},
		"heightm": 2.5,
		"weightkg": 291,
		"color": "Brown",
		"prevo": "Piloswine",
		"evoType": "levelMove",
		"evoMove": "Ancient Power",
		"eggGroups": ["Field"],
	},
	"Porygonz": {
		"num": 474,
		"name": "Porygon-Z",
		"types": ["Normal"],
		"gender": "N",
		"baseStats": {"hp": 85, "atk": 80, "def": 70, "spa": 135, "spd": 75, "spe": 90},
		"abilities": {"0": "Adaptability", "1": "Download", "H": "Analytic"},
		"heightm": 0.9,
		"weightkg": 34,
		"color": "Red",
		"prevo": "Porygon2",
		"evoType": "trade",
		"evoItem": "Dubious Disc",
		"eggGroups": ["Mineral"],
	},
	"Gallade": {
		"num": 475,
		"name": "Gallade",
		"types": ["Psychic", "Fighting"],
		"gender": "M",
		"baseStats": {"hp": 68, "atk": 125, "def": 65, "spa": 65, "spd": 115, "spe": 80},
		"abilities": {"0": "Steadfast", "1": "Sharpness", "H": "Justified"},
		"heightm": 1.6,
		"weightkg": 52,
		"color": "White",
		"prevo": "Kirlia",
		"evoType": "useItem",
		"evoItem": "Dawn Stone",
		"eggGroups": ["Human-Like", "Amorphous"],
		"otherFormes": ["Gallade-Mega"],
		"formeOrder": ["Gallade", "Gallade-Mega"],
	},
	"Gallademega": {
		"num": 475,
		"name": "Gallade-Mega",
		"baseSpecies": "Gallade",
		"forme": "Mega",
		"types": ["Psychic", "Fighting"],
		"gender": "M",
		"baseStats": {"hp": 68, "atk": 165, "def": 95, "spa": 65, "spd": 115, "spe": 110},
		"abilities": {"0": "Inner Focus"},
		"heightm": 1.6,
		"weightkg": 56.4,
		"color": "White",
		"eggGroups": ["Amorphous"],
		"requiredItem": "Galladite",
	},
	"Probopass": {
		"num": 476,
		"name": "Probopass",
		"types": ["Rock", "Steel"],
		"baseStats": {"hp": 60, "atk": 55, "def": 145, "spa": 75, "spd": 150, "spe": 40},
		"abilities": {"0": "Sturdy", "1": "Magnet Pull", "H": "Sand Force"},
		"heightm": 1.4,
		"weightkg": 340,
		"color": "Gray",
		"prevo": "Nosepass",
		"evoType": "levelExtra",
		"evoCondition": "near a special magnetic field",
		"eggGroups": ["Mineral"],
	},
	"Dusknoir": {
		"num": 477,
		"name": "Dusknoir",
		"types": ["Ghost"],
		"baseStats": {"hp": 45, "atk": 100, "def": 135, "spa": 65, "spd": 135, "spe": 45},
		"abilities": {"0": "Pressure", "H": "Frisk"},
		"heightm": 2.2,
		"weightkg": 106.6,
		"color": "Black",
		"prevo": "Dusclops",
		"evoType": "trade",
		"evoItem": "Reaper Cloth",
		"eggGroups": ["Amorphous"],
	},
	"Froslass": {
		"num": 478,
		"name": "Froslass",
		"types": ["Ice", "Ghost"],
		"gender": "F",
		"baseStats": {"hp": 70, "atk": 80, "def": 70, "spa": 80, "spd": 70, "spe": 110},
		"abilities": {"0": "Snow Cloak", "H": "Cursed Body"},
		"heightm": 1.3,
		"weightkg": 26.6,
		"color": "White",
		"prevo": "Snorunt",
		"evoType": "useItem",
		"evoItem": "Dawn Stone",
		"eggGroups": ["Fairy", "Mineral"],
	},
	"Rotom": {
		"num": 479,
		"name": "Rotom",
		"types": ["Electric", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 50, "def": 77, "spa": 95, "spd": 77, "spe": 91},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Red",
		"eggGroups": ["Amorphous"],
		"otherFormes": ["Rotom-Heat", "Rotom-Wash", "Rotom-Frost", "Rotom-Fan", "Rotom-Mow"],
		"formeOrder": ["Rotom", "Rotom-Heat", "Rotom-Wash", "Rotom-Frost", "Rotom-Fan", "Rotom-Mow"],
	},
	"Rotomheat": {
		"num": 479,
		"name": "Rotom-Heat",
		"baseSpecies": "Rotom",
		"forme": "Heat",
		"types": ["Electric", "Fire"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 65, "def": 107, "spa": 105, "spd": 107, "spe": 86},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Red",
		"eggGroups": ["Amorphous"],
		"changesFrom": "Rotom",
	},
	"Rotomwash": {
		"num": 479,
		"name": "Rotom-Wash",
		"baseSpecies": "Rotom",
		"forme": "Wash",
		"types": ["Electric", "Water"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 65, "def": 107, "spa": 105, "spd": 107, "spe": 86},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Red",
		"eggGroups": ["Amorphous"],
		"changesFrom": "Rotom",
	},
	"Rotomfrost": {
		"num": 479,
		"name": "Rotom-Frost",
		"baseSpecies": "Rotom",
		"forme": "Frost",
		"types": ["Electric", "Ice"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 65, "def": 107, "spa": 105, "spd": 107, "spe": 86},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Red",
		"eggGroups": ["Amorphous"],
		"changesFrom": "Rotom",
	},
	"Rotomfan": {
		"num": 479,
		"name": "Rotom-Fan",
		"baseSpecies": "Rotom",
		"forme": "Fan",
		"types": ["Electric", "Flying"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 65, "def": 107, "spa": 105, "spd": 107, "spe": 86},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Red",
		"eggGroups": ["Amorphous"],
		"changesFrom": "Rotom",
	},
	"Rotommow": {
		"num": 479,
		"name": "Rotom-Mow",
		"baseSpecies": "Rotom",
		"forme": "Mow",
		"types": ["Electric", "Grass"],
		"gender": "N",
		"baseStats": {"hp": 50, "atk": 65, "def": 107, "spa": 105, "spd": 107, "spe": 86},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Red",
		"eggGroups": ["Amorphous"],
		"changesFrom": "Rotom",
	},
	"Uxie": {
		"num": 480,
		"name": "Uxie",
		"types": ["Psychic"],
		"gender": "N",
		"baseStats": {"hp": 75, "atk": 75, "def": 130, "spa": 75, "spd": 130, "spe": 95},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Yellow",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Mesprit": {
		"num": 481,
		"name": "Mesprit",
		"types": ["Psychic"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 105, "def": 105, "spa": 105, "spd": 105, "spe": 80},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Pink",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Azelf": {
		"num": 482,
		"name": "Azelf",
		"types": ["Psychic"],
		"gender": "N",
		"baseStats": {"hp": 75, "atk": 125, "def": 70, "spa": 125, "spd": 70, "spe": 115},
		"abilities": {"0": "Levitate"},
		"heightm": 0.3,
		"weightkg": 0.3,
		"color": "Blue",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Dialga": {
		"num": 483,
		"name": "Dialga",
		"types": ["Steel", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 120, "def": 120, "spa": 150, "spd": 100, "spe": 90},
		"abilities": {"0": "Pressure", "H": "Telepathy"},
		"heightm": 5.4,
		"weightkg": 683,
		"tags": ["Restricted Legendary"],
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Dialga-Origin"],
		"formeOrder": ["Dialga", "Dialga-Origin"],
	},
	"Dialgaorigin": {
		"num": 483,
		"name": "Dialga-Origin",
		"baseSpecies": "Dialga",
		"forme": "Origin",
		"types": ["Steel", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 100, "def": 120, "spa": 150, "spd": 120, "spe": 90},
		"abilities": {"0": "Pressure", "H": "Telepathy"},
		"heightm": 7,
		"weightkg": 850,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Adamant Crystal",
		"changesFrom": "Dialga",
		"gen": 8,
	},
	"Palkia": {
		"num": 484,
		"name": "Palkia",
		"types": ["Water", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 90, "atk": 120, "def": 100, "spa": 150, "spd": 120, "spe": 100},
		"abilities": {"0": "Pressure", "H": "Telepathy"},
		"heightm": 4.2,
		"weightkg": 336,
		"color": "Purple",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Palkia-Origin"],
		"formeOrder": ["Palkia", "Palkia-Origin"],
	},
	"Palkiaorigin": {
		"num": 484,
		"name": "Palkia-Origin",
		"baseSpecies": "Palkia",
		"forme": "Origin",
		"types": ["Water", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 90, "atk": 100, "def": 100, "spa": 150, "spd": 120, "spe": 120},
		"abilities": {"0": "Pressure", "H": "Telepathy"},
		"heightm": 6.3,
		"weightkg": 660,
		"color": "Purple",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Lustrous Globe",
		"changesFrom": "Palkia",
		"gen": 8,
	},
	"Heatran": {
		"num": 485,
		"name": "Heatran",
		"types": ["Fire", "Steel"],
		"baseStats": {"hp": 91, "atk": 90, "def": 106, "spa": 130, "spd": 106, "spe": 77},
		"abilities": {"0": "Flash Fire", "H": "Flame Body"},
		"heightm": 1.7,
		"weightkg": 430,
		"color": "Brown",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Regigigas": {
		"num": 486,
		"name": "Regigigas",
		"types": ["Normal"],
		"gender": "N",
		"baseStats": {"hp": 110, "atk": 160, "def": 110, "spa": 80, "spd": 110, "spe": 100},
		"abilities": {"0": "Slow Start"},
		"heightm": 3.7,
		"weightkg": 420,
		"color": "White",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Giratina": {
		"num": 487,
		"name": "Giratina",
		"baseForme": "Altered",
		"types": ["Ghost", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 150, "atk": 100, "def": 120, "spa": 100, "spd": 120, "spe": 90},
		"abilities": {"0": "Pressure", "H": "Telepathy"},
		"heightm": 4.5,
		"weightkg": 750,
		"color": "Black",
		"eggGroups": ["Undiscovered"],
		"tags": ["Restricted Legendary"],
		"otherFormes": ["Giratina-Origin"],
		"formeOrder": ["Giratina", "Giratina-Origin"],
	},
	"Giratinaorigin": {
		"num": 487,
		"name": "Giratina-Origin",
		"baseSpecies": "Giratina",
		"forme": "Origin",
		"types": ["Ghost", "Dragon"],
		"gender": "N",
		"baseStats": {"hp": 150, "atk": 120, "def": 100, "spa": 120, "spd": 100, "spe": 90},
		"abilities": {"0": "Levitate"},
		"heightm": 6.9,
		"weightkg": 650,
		"color": "Black",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Griseous Core",
		"changesFrom": "Giratina",
	},
	"Cresselia": {
		"num": 488,
		"name": "Cresselia",
		"types": ["Psychic"],
		"gender": "F",
		"baseStats": {"hp": 120, "atk": 70, "def": 110, "spa": 75, "spd": 120, "spe": 85},
		"abilities": {"0": "Levitate"},
		"heightm": 1.5,
		"weightkg": 85.6,
		"color": "Yellow",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Phione": {
		"num": 489,
		"name": "Phione",
		"types": ["Water"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 80, "def": 80, "spa": 80, "spd": 80, "spe": 80},
		"abilities": {"0": "Hydration"},
		"heightm": 0.4,
		"weightkg": 3.1,
		"color": "Blue",
		"tags": ["Mythical"],
		"eggGroups": ["Water 1", "Fairy"],
	},
	"Manaphy": {
		"num": 490,
		"name": "Manaphy",
		"types": ["Water"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 100, "def": 100, "spa": 100, "spd": 100, "spe": 100},
		"abilities": {"0": "Hydration"},
		"heightm": 0.3,
		"weightkg": 1.4,
		"color": "Blue",
		"tags": ["Mythical"],
		"eggGroups": ["Water 1", "Fairy"],
	},
	"Darkrai": {
		"num": 491,
		"name": "Darkrai",
		"types": ["Dark"],
		"gender": "N",
		"baseStats": {"hp": 70, "atk": 90, "def": 90, "spa": 135, "spd": 90, "spe": 125},
		"abilities": {"0": "Bad Dreams"},
		"heightm": 1.5,
		"weightkg": 50.5,
		"color": "Black",
		"tags": ["Mythical"],
		"eggGroups": ["Undiscovered"],
	},
	"Shaymin": {
		"num": 492,
		"name": "Shaymin",
		"baseForme": "Land",
		"types": ["Grass"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 100, "def": 100, "spa": 100, "spd": 100, "spe": 100},
		"abilities": {"0": "Natural Cure"},
		"heightm": 0.2,
		"weightkg": 2.1,
		"color": "Green",
		"eggGroups": ["Undiscovered"],
		"tags": ["Mythical"],
		"otherFormes": ["Shaymin-Sky"],
		"formeOrder": ["Shaymin", "Shaymin-Sky"],
	},
	"Shayminsky": {
		"num": 492,
		"name": "Shaymin-Sky",
		"baseSpecies": "Shaymin",
		"forme": "Sky",
		"types": ["Grass", "Flying"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 103, "def": 75, "spa": 120, "spd": 75, "spe": 127},
		"abilities": {"0": "Serene Grace"},
		"heightm": 0.4,
		"weightkg": 5.2,
		"color": "Green",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Shaymin",
	},
	"Arceus": {
		"num": 493,
		"name": "Arceus",
		"baseForme": "Normal",
		"types": ["Normal"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"tags": ["Mythical"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": [
			"Arceus-Bug",
			"Arceus-Dark",
			"Arceus-Dragon",
			"Arceus-Electric",
			"Arceus-Fairy",
			"Arceus-Fighting",
			"Arceus-Fire",
			"Arceus-Flying",
			"Arceus-Ghost",
			"Arceus-Grass",
			"Arceus-Ground",
			"Arceus-Ice",
			"Arceus-Poison",
			"Arceus-Psychic",
			"Arceus-Rock",
			"Arceus-Steel",
			"Arceus-Water",
		],
		"formeOrder": [
			"Arceus",
			"Arceus-Fighting",
			"Arceus-Flying",
			"Arceus-Poison",
			"Arceus-Ground",
			"Arceus-Rock",
			"Arceus-Bug",
			"Arceus-Ghost",
			"Arceus-Steel",
			"Arceus-Fire",
			"Arceus-Water",
			"Arceus-Grass",
			"Arceus-Electric",
			"Arceus-Psychic",
			"Arceus-Ice",
			"Arceus-Dragon",
			"Arceus-Dark",
			"Arceus-Fairy",
		],
	},
	"Arceusbug": {
		"num": 493,
		"name": "Arceus-Bug",
		"baseSpecies": "Arceus",
		"forme": "Bug",
		"types": ["Bug"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Insect Plate", "Buginium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusdark": {
		"num": 493,
		"name": "Arceus-Dark",
		"baseSpecies": "Arceus",
		"forme": "Dark",
		"types": ["Dark"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Dread Plate", "Darkinium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusdragon": {
		"num": 493,
		"name": "Arceus-Dragon",
		"baseSpecies": "Arceus",
		"forme": "Dragon",
		"types": ["Dragon"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Draco Plate", "Dragonium Z"],
		"changesFrom": "Arceus",
	},
	"Arceuselectric": {
		"num": 493,
		"name": "Arceus-Electric",
		"baseSpecies": "Arceus",
		"forme": "Electric",
		"types": ["Electric"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Zap Plate", "Electrium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusfairy": {
		"num": 493,
		"name": "Arceus-Fairy",
		"baseSpecies": "Arceus",
		"forme": "Fairy",
		"types": ["Fairy"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Pixie Plate", "Fairium Z"],
		"changesFrom": "Arceus",
		"gen": 6,
	},
	"Arceusfighting": {
		"num": 493,
		"name": "Arceus-Fighting",
		"baseSpecies": "Arceus",
		"forme": "Fighting",
		"types": ["Fighting"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Fist Plate", "Fightinium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusfire": {
		"num": 493,
		"name": "Arceus-Fire",
		"baseSpecies": "Arceus",
		"forme": "Fire",
		"types": ["Fire"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Flame Plate", "Firium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusflying": {
		"num": 493,
		"name": "Arceus-Flying",
		"baseSpecies": "Arceus",
		"forme": "Flying",
		"types": ["Flying"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Sky Plate", "Flyinium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusghost": {
		"num": 493,
		"name": "Arceus-Ghost",
		"baseSpecies": "Arceus",
		"forme": "Ghost",
		"types": ["Ghost"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Spooky Plate", "Ghostium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusgrass": {
		"num": 493,
		"name": "Arceus-Grass",
		"baseSpecies": "Arceus",
		"forme": "Grass",
		"types": ["Grass"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Meadow Plate", "Grassium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusground": {
		"num": 493,
		"name": "Arceus-Ground",
		"baseSpecies": "Arceus",
		"forme": "Ground",
		"types": ["Ground"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Earth Plate", "Groundium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusice": {
		"num": 493,
		"name": "Arceus-Ice",
		"baseSpecies": "Arceus",
		"forme": "Ice",
		"types": ["Ice"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Icicle Plate", "Icium Z"],
		"changesFrom": "Arceus",
	},
	"Arceuspoison": {
		"num": 493,
		"name": "Arceus-Poison",
		"baseSpecies": "Arceus",
		"forme": "Poison",
		"types": ["Poison"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Toxic Plate", "Poisonium Z"],
		"changesFrom": "Arceus",
	},
	"Arceuspsychic": {
		"num": 493,
		"name": "Arceus-Psychic",
		"baseSpecies": "Arceus",
		"forme": "Psychic",
		"types": ["Psychic"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Mind Plate", "Psychium Z"],
		"changesFrom": "Arceus",
	},
	"Arceusrock": {
		"num": 493,
		"name": "Arceus-Rock",
		"baseSpecies": "Arceus",
		"forme": "Rock",
		"types": ["Rock"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Stone Plate", "Rockium Z"],
		"changesFrom": "Arceus",
	},
	"Arceussteel": {
		"num": 493,
		"name": "Arceus-Steel",
		"baseSpecies": "Arceus",
		"forme": "Steel",
		"types": ["Steel"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Iron Plate", "Steelium Z"],
		"changesFrom": "Arceus",
	},
	"Arceuswater": {
		"num": 493,
		"name": "Arceus-Water",
		"baseSpecies": "Arceus",
		"forme": "Water",
		"types": ["Water"],
		"gender": "N",
		"baseStats": {"hp": 120, "atk": 120, "def": 120, "spa": 120, "spd": 120, "spe": 120},
		"abilities": {"0": "Multitype"},
		"heightm": 3.2,
		"weightkg": 320,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredItems": ["Splash Plate", "Waterium Z"],
		"changesFrom": "Arceus",
	},
}
