"""Pokédex entries for Unova region."""

from ..functions.pokedex_funcs import *

pokedex = {
	"Victini": {
		"num": 494,
		"name": "Victini",
		"types": ["Psychic", "Fire"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 100, "def": 100, "spa": 100, "spd": 100, "spe": 100},
		"abilities": {"0": "Victory Star"},
		"heightm": 0.4,
		"weightkg": 4,
		"color": "Yellow",
		"tags": ["Mythical"],
		"eggGroups": ["Undiscovered"],
	},
	"Snivy": {
		"num": 495,
		"name": "Snivy",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 45, "atk": 45, "def": 55, "spa": 45, "spd": 55, "spe": 63},
		"abilities": {"0": "Overgrow", "H": "Contrary"},
		"heightm": 0.6,
		"weightkg": 8.1,
		"color": "Green",
		"evos": ["Servine"],
		"eggGroups": ["Field", "Grass"],
	},
	"Servine": {
		"num": 496,
		"name": "Servine",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 60, "atk": 60, "def": 75, "spa": 60, "spd": 75, "spe": 83},
		"abilities": {"0": "Overgrow", "H": "Contrary"},
		"heightm": 0.8,
		"weightkg": 16,
		"color": "Green",
		"prevo": "Snivy",
		"evoLevel": 17,
		"evos": ["Serperior"],
		"eggGroups": ["Field", "Grass"],
	},
	"Serperior": {
		"num": 497,
		"name": "Serperior",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 75, "atk": 75, "def": 95, "spa": 75, "spd": 95, "spe": 113},
		"abilities": {"0": "Overgrow", "H": "Contrary"},
		"heightm": 3.3,
		"weightkg": 63,
		"color": "Green",
		"prevo": "Servine",
		"evoLevel": 36,
		"eggGroups": ["Field", "Grass"],
	},
	"Tepig": {
		"num": 498,
		"name": "Tepig",
		"types": ["Fire"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 65, "atk": 63, "def": 45, "spa": 45, "spd": 45, "spe": 45},
		"abilities": {"0": "Blaze", "H": "Thick Fat"},
		"heightm": 0.5,
		"weightkg": 9.9,
		"color": "Red",
		"evos": ["Pignite"],
		"eggGroups": ["Field"],
	},
	"Pignite": {
		"num": 499,
		"name": "Pignite",
		"types": ["Fire", "Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 90, "atk": 93, "def": 55, "spa": 70, "spd": 55, "spe": 55},
		"abilities": {"0": "Blaze", "H": "Thick Fat"},
		"heightm": 1,
		"weightkg": 55.5,
		"color": "Red",
		"prevo": "Tepig",
		"evoLevel": 17,
		"evos": ["Emboar"],
		"eggGroups": ["Field"],
	},
	"Emboar": {
		"num": 500,
		"name": "Emboar",
		"types": ["Fire", "Fighting"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 110, "atk": 123, "def": 65, "spa": 100, "spd": 65, "spe": 65},
		"abilities": {"0": "Blaze", "H": "Reckless"},
		"heightm": 1.6,
		"weightkg": 150,
		"color": "Red",
		"prevo": "Pignite",
		"evoLevel": 36,
		"eggGroups": ["Field"],
	},
	"Oshawott": {
		"num": 501,
		"name": "Oshawott",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 55, "atk": 55, "def": 45, "spa": 63, "spd": 45, "spe": 45},
		"abilities": {"0": "Torrent", "H": "Shell Armor"},
		"heightm": 0.5,
		"weightkg": 5.9,
		"color": "Blue",
		"evos": ["Dewott"],
		"eggGroups": ["Field"],
	},
	"Dewott": {
		"num": 502,
		"name": "Dewott",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 75, "atk": 75, "def": 60, "spa": 83, "spd": 60, "spe": 60},
		"abilities": {"0": "Torrent", "H": "Shell Armor"},
		"heightm": 0.8,
		"weightkg": 24.5,
		"color": "Blue",
		"prevo": "Oshawott",
		"evoLevel": 17,
		"evos": ["Samurott", "Samurott-Hisui"],
		"eggGroups": ["Field"],
	},
	"Samurott": {
		"num": 503,
		"name": "Samurott",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 95, "atk": 100, "def": 85, "spa": 108, "spd": 70, "spe": 70},
		"abilities": {"0": "Torrent", "H": "Shell Armor"},
		"heightm": 1.5,
		"weightkg": 94.6,
		"color": "Blue",
		"prevo": "Dewott",
		"evoLevel": 36,
		"eggGroups": ["Field"],
		"otherFormes": ["Samurott-Hisui"],
		"formeOrder": ["Samurott", "Samurott-Hisui"],
	},
	"Samurotthisui": {
		"num": 503,
		"name": "Samurott-Hisui",
		"baseSpecies": "Samurott",
		"forme": "Hisui",
		"types": ["Water", "Dark"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 90, "atk": 108, "def": 80, "spa": 100, "spd": 65, "spe": 85},
		"abilities": {"0": "Torrent", "H": "Sharpness"},
		"heightm": 1.5,
		"weightkg": 58.2,
		"color": "Blue",
		"prevo": "Dewott",
		"evoLevel": 36,
		"eggGroups": ["Field"],
	},
	"Patrat": {
		"num": 504,
		"name": "Patrat",
		"types": ["Normal"],
		"baseStats": {"hp": 45, "atk": 55, "def": 39, "spa": 35, "spd": 39, "spe": 42},
		"abilities": {"0": "Run Away", "1": "Keen Eye", "H": "Analytic"},
		"heightm": 0.5,
		"weightkg": 11.6,
		"color": "Brown",
		"evos": ["Watchog"],
		"eggGroups": ["Field"],
	},
	"Watchog": {
		"num": 505,
		"name": "Watchog",
		"types": ["Normal"],
		"baseStats": {"hp": 60, "atk": 85, "def": 69, "spa": 60, "spd": 69, "spe": 77},
		"abilities": {"0": "Illuminate", "1": "Keen Eye", "H": "Analytic"},
		"heightm": 1.1,
		"weightkg": 27,
		"color": "Brown",
		"prevo": "Patrat",
		"evoLevel": 20,
		"eggGroups": ["Field"],
	},
	"Lillipup": {
		"num": 506,
		"name": "Lillipup",
		"types": ["Normal"],
		"baseStats": {"hp": 45, "atk": 60, "def": 45, "spa": 25, "spd": 45, "spe": 55},
		"abilities": {"0": "Vital Spirit", "1": "Pickup", "H": "Run Away"},
		"heightm": 0.4,
		"weightkg": 4.1,
		"color": "Brown",
		"evos": ["Herdier"],
		"eggGroups": ["Field"],
	},
	"Herdier": {
		"num": 507,
		"name": "Herdier",
		"types": ["Normal"],
		"baseStats": {"hp": 65, "atk": 80, "def": 65, "spa": 35, "spd": 65, "spe": 60},
		"abilities": {"0": "Intimidate", "1": "Sand Rush", "H": "Scrappy"},
		"heightm": 0.9,
		"weightkg": 14.7,
		"color": "Gray",
		"prevo": "Lillipup",
		"evoLevel": 16,
		"evos": ["Stoutland"],
		"eggGroups": ["Field"],
	},
	"Stoutland": {
		"num": 508,
		"name": "Stoutland",
		"types": ["Normal"],
		"baseStats": {"hp": 85, "atk": 110, "def": 90, "spa": 45, "spd": 90, "spe": 80},
		"abilities": {"0": "Intimidate", "1": "Sand Rush", "H": "Scrappy"},
		"heightm": 1.2,
		"weightkg": 61,
		"color": "Gray",
		"prevo": "Herdier",
		"evoLevel": 32,
		"eggGroups": ["Field"],
	},
	"Purrloin": {
		"num": 509,
		"name": "Purrloin",
		"types": ["Dark"],
		"baseStats": {"hp": 41, "atk": 50, "def": 37, "spa": 50, "spd": 37, "spe": 66},
		"abilities": {"0": "Limber", "1": "Unburden", "H": "Prankster"},
		"heightm": 0.4,
		"weightkg": 10.1,
		"color": "Purple",
		"evos": ["Liepard"],
		"eggGroups": ["Field"],
	},
	"Liepard": {
		"num": 510,
		"name": "Liepard",
		"types": ["Dark"],
		"baseStats": {"hp": 64, "atk": 88, "def": 50, "spa": 88, "spd": 50, "spe": 106},
		"abilities": {"0": "Limber", "1": "Unburden", "H": "Prankster"},
		"heightm": 1.1,
		"weightkg": 37.5,
		"color": "Purple",
		"prevo": "Purrloin",
		"evoLevel": 20,
		"eggGroups": ["Field"],
	},
	"Pansage": {
		"num": 511,
		"name": "Pansage",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 50, "atk": 53, "def": 48, "spa": 53, "spd": 48, "spe": 64},
		"abilities": {"0": "Gluttony", "H": "Overgrow"},
		"heightm": 0.6,
		"weightkg": 10.5,
		"color": "Green",
		"evos": ["Simisage"],
		"eggGroups": ["Field"],
	},
	"Simisage": {
		"num": 512,
		"name": "Simisage",
		"types": ["Grass"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 75, "atk": 98, "def": 63, "spa": 98, "spd": 63, "spe": 101},
		"abilities": {"0": "Gluttony", "H": "Overgrow"},
		"heightm": 1.1,
		"weightkg": 30.5,
		"color": "Green",
		"prevo": "Pansage",
		"evoType": "useItem",
		"evoItem": "Leaf Stone",
		"eggGroups": ["Field"],
	},
	"Pansear": {
		"num": 513,
		"name": "Pansear",
		"types": ["Fire"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 50, "atk": 53, "def": 48, "spa": 53, "spd": 48, "spe": 64},
		"abilities": {"0": "Gluttony", "H": "Blaze"},
		"heightm": 0.6,
		"weightkg": 11,
		"color": "Red",
		"evos": ["Simisear"],
		"eggGroups": ["Field"],
	},
	"Simisear": {
		"num": 514,
		"name": "Simisear",
		"types": ["Fire"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 75, "atk": 98, "def": 63, "spa": 98, "spd": 63, "spe": 101},
		"abilities": {"0": "Gluttony", "H": "Blaze"},
		"heightm": 1,
		"weightkg": 28,
		"color": "Red",
		"prevo": "Pansear",
		"evoType": "useItem",
		"evoItem": "Fire Stone",
		"eggGroups": ["Field"],
	},
	"Panpour": {
		"num": 515,
		"name": "Panpour",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 50, "atk": 53, "def": 48, "spa": 53, "spd": 48, "spe": 64},
		"abilities": {"0": "Gluttony", "H": "Torrent"},
		"heightm": 0.6,
		"weightkg": 13.5,
		"color": "Blue",
		"evos": ["Simipour"],
		"eggGroups": ["Field"],
	},
	"Simipour": {
		"num": 516,
		"name": "Simipour",
		"types": ["Water"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 75, "atk": 98, "def": 63, "spa": 98, "spd": 63, "spe": 101},
		"abilities": {"0": "Gluttony", "H": "Torrent"},
		"heightm": 1,
		"weightkg": 29,
		"color": "Blue",
		"prevo": "Panpour",
		"evoType": "useItem",
		"evoItem": "Water Stone",
		"eggGroups": ["Field"],
	},
	"Munna": {
		"num": 517,
		"name": "Munna",
		"types": ["Psychic"],
		"baseStats": {"hp": 76, "atk": 25, "def": 45, "spa": 67, "spd": 55, "spe": 24},
		"abilities": {"0": "Forewarn", "1": "Synchronize", "H": "Telepathy"},
		"heightm": 0.6,
		"weightkg": 23.3,
		"color": "Pink",
		"evos": ["Musharna"],
		"eggGroups": ["Field"],
	},
	"Musharna": {
		"num": 518,
		"name": "Musharna",
		"types": ["Psychic"],
		"baseStats": {"hp": 116, "atk": 55, "def": 85, "spa": 107, "spd": 95, "spe": 29},
		"abilities": {"0": "Forewarn", "1": "Synchronize", "H": "Telepathy"},
		"heightm": 1.1,
		"weightkg": 60.5,
		"color": "Pink",
		"prevo": "Munna",
		"evoType": "useItem",
		"evoItem": "Moon Stone",
		"eggGroups": ["Field"],
	},
	"Pidove": {
		"num": 519,
		"name": "Pidove",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 50, "atk": 55, "def": 50, "spa": 36, "spd": 30, "spe": 43},
		"abilities": {"0": "Big Pecks", "1": "Super Luck", "H": "Rivalry"},
		"heightm": 0.3,
		"weightkg": 2.1,
		"color": "Gray",
		"evos": ["Tranquill"],
		"eggGroups": ["Flying"],
	},
	"Tranquill": {
		"num": 520,
		"name": "Tranquill",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 62, "atk": 77, "def": 62, "spa": 50, "spd": 42, "spe": 65},
		"abilities": {"0": "Big Pecks", "1": "Super Luck", "H": "Rivalry"},
		"heightm": 0.6,
		"weightkg": 15,
		"color": "Gray",
		"prevo": "Pidove",
		"evoLevel": 21,
		"evos": ["Unfezant"],
		"eggGroups": ["Flying"],
	},
	"Unfezant": {
		"num": 521,
		"name": "Unfezant",
		"types": ["Normal", "Flying"],
		"baseStats": {"hp": 80, "atk": 115, "def": 80, "spa": 65, "spd": 55, "spe": 93},
		"abilities": {"0": "Big Pecks", "1": "Super Luck", "H": "Rivalry"},
		"heightm": 1.2,
		"weightkg": 29,
		"color": "Gray",
		"prevo": "Tranquill",
		"evoLevel": 32,
		"eggGroups": ["Flying"],
	},
	"Blitzle": {
		"num": 522,
		"name": "Blitzle",
		"types": ["Electric"],
		"baseStats": {"hp": 45, "atk": 60, "def": 32, "spa": 50, "spd": 32, "spe": 76},
		"abilities": {"0": "Lightning Rod", "1": "Motor Drive", "H": "Sap Sipper"},
		"heightm": 0.8,
		"weightkg": 29.8,
		"color": "Black",
		"evos": ["Zebstrika"],
		"eggGroups": ["Field"],
	},
	"Zebstrika": {
		"num": 523,
		"name": "Zebstrika",
		"types": ["Electric"],
		"baseStats": {"hp": 75, "atk": 100, "def": 63, "spa": 80, "spd": 63, "spe": 116},
		"abilities": {"0": "Lightning Rod", "1": "Motor Drive", "H": "Sap Sipper"},
		"heightm": 1.6,
		"weightkg": 79.5,
		"color": "Black",
		"prevo": "Blitzle",
		"evoLevel": 27,
		"eggGroups": ["Field"],
	},
	"Roggenrola": {
		"num": 524,
		"name": "Roggenrola",
		"types": ["Rock"],
		"baseStats": {"hp": 55, "atk": 75, "def": 85, "spa": 25, "spd": 25, "spe": 15},
		"abilities": {"0": "Sturdy", "1": "Weak Armor", "H": "Sand Force"},
		"heightm": 0.4,
		"weightkg": 18,
		"color": "Blue",
		"evos": ["Boldore"],
		"eggGroups": ["Mineral"],
	},
	"Boldore": {
		"num": 525,
		"name": "Boldore",
		"types": ["Rock"],
		"baseStats": {"hp": 70, "atk": 105, "def": 105, "spa": 50, "spd": 40, "spe": 20},
		"abilities": {"0": "Sturdy", "1": "Weak Armor", "H": "Sand Force"},
		"heightm": 0.9,
		"weightkg": 102,
		"color": "Blue",
		"prevo": "Roggenrola",
		"evoLevel": 25,
		"evos": ["Gigalith"],
		"eggGroups": ["Mineral"],
	},
	"Gigalith": {
		"num": 526,
		"name": "Gigalith",
		"types": ["Rock"],
		"baseStats": {"hp": 85, "atk": 135, "def": 130, "spa": 60, "spd": 80, "spe": 25},
		"abilities": {"0": "Sturdy", "1": "Sand Stream", "H": "Sand Force"},
		"heightm": 1.7,
		"weightkg": 260,
		"color": "Blue",
		"prevo": "Boldore",
		"evoType": "trade",
		"eggGroups": ["Mineral"],
	},
	"Woobat": {
		"num": 527,
		"name": "Woobat",
		"types": ["Psychic", "Flying"],
		"baseStats": {"hp": 65, "atk": 45, "def": 43, "spa": 55, "spd": 43, "spe": 72},
		"abilities": {"0": "Unaware", "1": "Klutz", "H": "Simple"},
		"heightm": 0.4,
		"weightkg": 2.1,
		"color": "Blue",
		"evos": ["Swoobat"],
		"eggGroups": ["Flying", "Field"],
	},
	"Swoobat": {
		"num": 528,
		"name": "Swoobat",
		"types": ["Psychic", "Flying"],
		"baseStats": {"hp": 67, "atk": 57, "def": 55, "spa": 77, "spd": 55, "spe": 114},
		"abilities": {"0": "Unaware", "1": "Klutz", "H": "Simple"},
		"heightm": 0.9,
		"weightkg": 10.5,
		"color": "Blue",
		"prevo": "Woobat",
		"evoType": "levelFriendship",
		"eggGroups": ["Flying", "Field"],
	},
	"Drilbur": {
		"num": 529,
		"name": "Drilbur",
		"types": ["Ground"],
		"baseStats": {"hp": 60, "atk": 85, "def": 40, "spa": 30, "spd": 45, "spe": 68},
		"abilities": {"0": "Sand Rush", "1": "Sand Force", "H": "Mold Breaker"},
		"heightm": 0.3,
		"weightkg": 8.5,
		"color": "Gray",
		"evos": ["Excadrill"],
		"eggGroups": ["Field"],
	},
	"Excadrill": {
		"num": 530,
		"name": "Excadrill",
		"types": ["Ground", "Steel"],
		"baseStats": {"hp": 110, "atk": 135, "def": 60, "spa": 50, "spd": 65, "spe": 88},
		"abilities": {"0": "Sand Rush", "1": "Sand Force", "H": "Mold Breaker"},
		"heightm": 0.7,
		"weightkg": 40.4,
		"color": "Gray",
		"prevo": "Drilbur",
		"evoLevel": 31,
		"eggGroups": ["Field"],
	},
	"Audino": {
		"num": 531,
		"name": "Audino",
		"types": ["Normal"],
		"baseStats": {"hp": 103, "atk": 60, "def": 86, "spa": 60, "spd": 86, "spe": 50},
		"abilities": {"0": "Healer", "1": "Regenerator", "H": "Klutz"},
		"heightm": 1.1,
		"weightkg": 31,
		"color": "Pink",
		"eggGroups": ["Fairy"],
		"otherFormes": ["Audino-Mega"],
		"formeOrder": ["Audino", "Audino-Mega"],
	},
	"Audinomega": {
		"num": 531,
		"name": "Audino-Mega",
		"baseSpecies": "Audino",
		"forme": "Mega",
		"types": ["Normal", "Fairy"],
		"baseStats": {"hp": 103, "atk": 60, "def": 126, "spa": 80, "spd": 126, "spe": 50},
		"abilities": {"0": "Healer"},
		"heightm": 1.5,
		"weightkg": 32,
		"color": "White",
		"eggGroups": ["Fairy"],
		"requiredItem": "Audinite",
	},
	"Timburr": {
		"num": 532,
		"name": "Timburr",
		"types": ["Fighting"],
		"genderRatio": {"M": 0.75, "F": 0.25},
		"baseStats": {"hp": 75, "atk": 80, "def": 55, "spa": 25, "spd": 35, "spe": 35},
		"abilities": {"0": "Guts", "1": "Sheer Force", "H": "Iron Fist"},
		"heightm": 0.6,
		"weightkg": 12.5,
		"color": "Gray",
		"evos": ["Gurdurr"],
		"eggGroups": ["Human-Like"],
	},
	"Gurdurr": {
		"num": 533,
		"name": "Gurdurr",
		"types": ["Fighting"],
		"genderRatio": {"M": 0.75, "F": 0.25},
		"baseStats": {"hp": 85, "atk": 105, "def": 85, "spa": 40, "spd": 50, "spe": 40},
		"abilities": {"0": "Guts", "1": "Sheer Force", "H": "Iron Fist"},
		"heightm": 1.2,
		"weightkg": 40,
		"color": "Gray",
		"prevo": "Timburr",
		"evoLevel": 25,
		"evos": ["Conkeldurr"],
		"eggGroups": ["Human-Like"],
	},
	"Conkeldurr": {
		"num": 534,
		"name": "Conkeldurr",
		"types": ["Fighting"],
		"genderRatio": {"M": 0.75, "F": 0.25},
		"baseStats": {"hp": 105, "atk": 140, "def": 95, "spa": 55, "spd": 65, "spe": 45},
		"abilities": {"0": "Guts", "1": "Sheer Force", "H": "Iron Fist"},
		"heightm": 1.4,
		"weightkg": 87,
		"color": "Brown",
		"prevo": "Gurdurr",
		"evoType": "trade",
		"eggGroups": ["Human-Like"],
	},
	"Tympole": {
		"num": 535,
		"name": "Tympole",
		"types": ["Water"],
		"baseStats": {"hp": 50, "atk": 50, "def": 40, "spa": 50, "spd": 40, "spe": 64},
		"abilities": {"0": "Swift Swim", "1": "Hydration", "H": "Water Absorb"},
		"heightm": 0.5,
		"weightkg": 4.5,
		"color": "Blue",
		"evos": ["Palpitoad"],
		"eggGroups": ["Water 1"],
	},
	"Palpitoad": {
		"num": 536,
		"name": "Palpitoad",
		"types": ["Water", "Ground"],
		"baseStats": {"hp": 75, "atk": 65, "def": 55, "spa": 65, "spd": 55, "spe": 69},
		"abilities": {"0": "Swift Swim", "1": "Hydration", "H": "Water Absorb"},
		"heightm": 0.8,
		"weightkg": 17,
		"color": "Blue",
		"prevo": "Tympole",
		"evoLevel": 25,
		"evos": ["Seismitoad"],
		"eggGroups": ["Water 1"],
	},
	"Seismitoad": {
		"num": 537,
		"name": "Seismitoad",
		"types": ["Water", "Ground"],
		"baseStats": {"hp": 105, "atk": 95, "def": 75, "spa": 85, "spd": 75, "spe": 74},
		"abilities": {"0": "Swift Swim", "1": "Poison Touch", "H": "Water Absorb"},
		"heightm": 1.5,
		"weightkg": 62,
		"color": "Blue",
		"prevo": "Palpitoad",
		"evoLevel": 36,
		"eggGroups": ["Water 1"],
	},
	"Throh": {
		"num": 538,
		"name": "Throh",
		"types": ["Fighting"],
		"gender": "M",
		"baseStats": {"hp": 120, "atk": 100, "def": 85, "spa": 30, "spd": 85, "spe": 45},
		"abilities": {"0": "Guts", "1": "Inner Focus", "H": "Mold Breaker"},
		"heightm": 1.3,
		"weightkg": 55.5,
		"color": "Red",
		"eggGroups": ["Human-Like"],
	},
	"Sawk": {
		"num": 539,
		"name": "Sawk",
		"types": ["Fighting"],
		"gender": "M",
		"baseStats": {"hp": 75, "atk": 125, "def": 75, "spa": 30, "spd": 75, "spe": 85},
		"abilities": {"0": "Sturdy", "1": "Inner Focus", "H": "Mold Breaker"},
		"heightm": 1.4,
		"weightkg": 51,
		"color": "Blue",
		"eggGroups": ["Human-Like"],
	},
	"Sewaddle": {
		"num": 540,
		"name": "Sewaddle",
		"types": ["Bug", "Grass"],
		"baseStats": {"hp": 45, "atk": 53, "def": 70, "spa": 40, "spd": 60, "spe": 42},
		"abilities": {"0": "Swarm", "1": "Chlorophyll", "H": "Overcoat"},
		"heightm": 0.3,
		"weightkg": 2.5,
		"color": "Yellow",
		"evos": ["Swadloon"],
		"eggGroups": ["Bug"],
	},
	"Swadloon": {
		"num": 541,
		"name": "Swadloon",
		"types": ["Bug", "Grass"],
		"baseStats": {"hp": 55, "atk": 63, "def": 90, "spa": 50, "spd": 80, "spe": 42},
		"abilities": {"0": "Leaf Guard", "1": "Chlorophyll", "H": "Overcoat"},
		"heightm": 0.5,
		"weightkg": 7.3,
		"color": "Green",
		"prevo": "Sewaddle",
		"evoLevel": 20,
		"evos": ["Leavanny"],
		"eggGroups": ["Bug"],
	},
	"Leavanny": {
		"num": 542,
		"name": "Leavanny",
		"types": ["Bug", "Grass"],
		"baseStats": {"hp": 75, "atk": 103, "def": 80, "spa": 70, "spd": 80, "spe": 92},
		"abilities": {"0": "Swarm", "1": "Chlorophyll", "H": "Overcoat"},
		"heightm": 1.2,
		"weightkg": 20.5,
		"color": "Yellow",
		"prevo": "Swadloon",
		"evoType": "levelFriendship",
		"eggGroups": ["Bug"],
	},
	"Venipede": {
		"num": 543,
		"name": "Venipede",
		"types": ["Bug", "Poison"],
		"baseStats": {"hp": 30, "atk": 45, "def": 59, "spa": 30, "spd": 39, "spe": 57},
		"abilities": {"0": "Poison Point", "1": "Swarm", "H": "Speed Boost"},
		"heightm": 0.4,
		"weightkg": 5.3,
		"color": "Red",
		"evos": ["Whirlipede"],
		"eggGroups": ["Bug"],
	},
	"Whirlipede": {
		"num": 544,
		"name": "Whirlipede",
		"types": ["Bug", "Poison"],
		"baseStats": {"hp": 40, "atk": 55, "def": 99, "spa": 40, "spd": 79, "spe": 47},
		"abilities": {"0": "Poison Point", "1": "Swarm", "H": "Speed Boost"},
		"heightm": 1.2,
		"weightkg": 58.5,
		"color": "Gray",
		"prevo": "Venipede",
		"evoLevel": 22,
		"evos": ["Scolipede"],
		"eggGroups": ["Bug"],
	},
	"Scolipede": {
		"num": 545,
		"name": "Scolipede",
		"types": ["Bug", "Poison"],
		"baseStats": {"hp": 60, "atk": 100, "def": 89, "spa": 55, "spd": 69, "spe": 112},
		"abilities": {"0": "Poison Point", "1": "Swarm", "H": "Speed Boost"},
		"heightm": 2.5,
		"weightkg": 200.5,
		"color": "Red",
		"prevo": "Whirlipede",
		"evoLevel": 30,
		"eggGroups": ["Bug"],
	},
	"Cottonee": {
		"num": 546,
		"name": "Cottonee",
		"types": ["Grass", "Fairy"],
		"baseStats": {"hp": 40, "atk": 27, "def": 60, "spa": 37, "spd": 50, "spe": 66},
		"abilities": {"0": "Prankster", "1": "Infiltrator", "H": "Chlorophyll"},
		"heightm": 0.3,
		"weightkg": 0.6,
		"color": "Green",
		"evos": ["Whimsicott"],
		"eggGroups": ["Fairy", "Grass"],
	},
	"Whimsicott": {
		"num": 547,
		"name": "Whimsicott",
		"types": ["Grass", "Fairy"],
		"baseStats": {"hp": 60, "atk": 67, "def": 85, "spa": 77, "spd": 75, "spe": 116},
		"abilities": {"0": "Prankster", "1": "Infiltrator", "H": "Chlorophyll"},
		"heightm": 0.7,
		"weightkg": 6.6,
		"color": "Green",
		"prevo": "Cottonee",
		"evoType": "useItem",
		"evoItem": "Sun Stone",
		"eggGroups": ["Fairy", "Grass"],
	},
	"Petilil": {
		"num": 548,
		"name": "Petilil",
		"types": ["Grass"],
		"gender": "F",
		"baseStats": {"hp": 45, "atk": 35, "def": 50, "spa": 70, "spd": 50, "spe": 30},
		"abilities": {"0": "Chlorophyll", "1": "Own Tempo", "H": "Leaf Guard"},
		"heightm": 0.5,
		"weightkg": 6.6,
		"color": "Green",
		"evos": ["Lilligant", "Lilligant-Hisui"],
		"eggGroups": ["Grass"],
	},
	"Lilligant": {
		"num": 549,
		"name": "Lilligant",
		"types": ["Grass"],
		"gender": "F",
		"baseStats": {"hp": 70, "atk": 60, "def": 75, "spa": 110, "spd": 75, "spe": 90},
		"abilities": {"0": "Chlorophyll", "1": "Own Tempo", "H": "Leaf Guard"},
		"heightm": 1.1,
		"weightkg": 16.3,
		"color": "Green",
		"prevo": "Petilil",
		"evoType": "useItem",
		"evoItem": "Sun Stone",
		"eggGroups": ["Grass"],
		"otherFormes": ["Lilligant-Hisui"],
		"formeOrder": ["Lilligant", "Lilligant-Hisui"],
	},
	"Lilliganthisui": {
		"num": 549,
		"name": "Lilligant-Hisui",
		"baseSpecies": "Lilligant",
		"forme": "Hisui",
		"types": ["Grass", "Fighting"],
		"gender": "F",
		"baseStats": {"hp": 70, "atk": 105, "def": 75, "spa": 50, "spd": 75, "spe": 105},
		"abilities": {"0": "Chlorophyll", "1": "Hustle", "H": "Leaf Guard"},
		"heightm": 1.2,
		"weightkg": 19.2,
		"color": "Green",
		"prevo": "Petilil",
		"evoType": "useItem",
		"evoItem": "Sun Stone",
		"eggGroups": ["Grass"],
	},
	"Basculin": {
		"num": 550,
		"name": "Basculin",
		"baseForme": "Red-Striped",
		"types": ["Water"],
		"baseStats": {"hp": 70, "atk": 92, "def": 65, "spa": 80, "spd": 55, "spe": 98},
		"abilities": {"0": "Reckless", "1": "Adaptability", "H": "Mold Breaker"},
		"heightm": 1,
		"weightkg": 18,
		"color": "Green",
		"eggGroups": ["Water 2"],
		"otherFormes": ["Basculin-Blue-Striped", "Basculin-White-Striped"],
		"formeOrder": ["Basculin", "Basculin-Blue-Striped", "Basculin-White-Striped"],
	},
	"Basculinbluestriped": {
		"num": 550,
		"name": "Basculin-Blue-Striped",
		"baseSpecies": "Basculin",
		"forme": "Blue-Striped",
		"types": ["Water"],
		"baseStats": {"hp": 70, "atk": 92, "def": 65, "spa": 80, "spd": 55, "spe": 98},
		"abilities": {"0": "Rock Head", "1": "Adaptability", "H": "Mold Breaker"},
		"heightm": 1,
		"weightkg": 18,
		"color": "Green",
		"eggGroups": ["Water 2"],
	},
	"Basculinwhitestriped": {
		"num": 550,
		"name": "Basculin-White-Striped",
		"baseSpecies": "Basculin",
		"forme": "White-Striped",
		"types": ["Water"],
		"baseStats": {"hp": 70, "atk": 92, "def": 65, "spa": 80, "spd": 55, "spe": 98},
		"abilities": {"0": "Rattled", "1": "Adaptability", "H": "Mold Breaker"},
		"heightm": 1,
		"weightkg": 18,
		"color": "Green",
		"evos": ["Basculegion", "Basculegion-F"],
		"eggGroups": ["Water 2"],
		"gen": 8,
	},
	"Sandile": {
		"num": 551,
		"name": "Sandile",
		"types": ["Ground", "Dark"],
		"baseStats": {"hp": 50, "atk": 72, "def": 35, "spa": 35, "spd": 35, "spe": 65},
		"abilities": {"0": "Intimidate", "1": "Moxie", "H": "Anger Point"},
		"heightm": 0.7,
		"weightkg": 15.2,
		"color": "Brown",
		"evos": ["Krokorok"],
		"eggGroups": ["Field"],
	},
	"Krokorok": {
		"num": 552,
		"name": "Krokorok",
		"types": ["Ground", "Dark"],
		"baseStats": {"hp": 60, "atk": 82, "def": 45, "spa": 45, "spd": 45, "spe": 74},
		"abilities": {"0": "Intimidate", "1": "Moxie", "H": "Anger Point"},
		"heightm": 1,
		"weightkg": 33.4,
		"color": "Brown",
		"prevo": "Sandile",
		"evoLevel": 29,
		"evos": ["Krookodile"],
		"eggGroups": ["Field"],
	},
	"Krookodile": {
		"num": 553,
		"name": "Krookodile",
		"types": ["Ground", "Dark"],
		"baseStats": {"hp": 95, "atk": 117, "def": 80, "spa": 65, "spd": 70, "spe": 92},
		"abilities": {"0": "Intimidate", "1": "Moxie", "H": "Anger Point"},
		"heightm": 1.5,
		"weightkg": 96.3,
		"color": "Red",
		"prevo": "Krokorok",
		"evoLevel": 40,
		"eggGroups": ["Field"],
	},
	"Darumaka": {
		"num": 554,
		"name": "Darumaka",
		"types": ["Fire"],
		"baseStats": {"hp": 70, "atk": 90, "def": 45, "spa": 15, "spd": 45, "spe": 50},
		"abilities": {"0": "Hustle", "H": "Inner Focus"},
		"heightm": 0.6,
		"weightkg": 37.5,
		"color": "Red",
		"evos": ["Darmanitan"],
		"eggGroups": ["Field"],
		"otherFormes": ["Darumaka-Galar"],
		"formeOrder": ["Darumaka", "Darumaka-Galar"],
	},
	"Darumakagalar": {
		"num": 554,
		"name": "Darumaka-Galar",
		"baseSpecies": "Darumaka",
		"forme": "Galar",
		"types": ["Ice"],
		"baseStats": {"hp": 70, "atk": 90, "def": 45, "spa": 15, "spd": 45, "spe": 50},
		"abilities": {"0": "Hustle", "H": "Inner Focus"},
		"heightm": 0.7,
		"weightkg": 40,
		"color": "White",
		"evos": ["Darmanitan-Galar"],
		"eggGroups": ["Field"],
	},
	"Darmanitan": {
		"num": 555,
		"name": "Darmanitan",
		"baseForme": "Standard",
		"types": ["Fire"],
		"baseStats": {"hp": 105, "atk": 140, "def": 55, "spa": 30, "spd": 55, "spe": 95},
		"abilities": {"0": "Sheer Force", "H": "Zen Mode"},
		"heightm": 1.3,
		"weightkg": 92.9,
		"color": "Red",
		"prevo": "Darumaka",
		"evoLevel": 35,
		"eggGroups": ["Field"],
		"otherFormes": ["Darmanitan-Zen", "Darmanitan-Galar", "Darmanitan-Galar-Zen"],
		"formeOrder": ["Darmanitan", "Darmanitan-Zen", "Darmanitan-Galar", "Darmanitan-Galar-Zen"],
	},
	"Darmanitanzen": {
		"num": 555,
		"name": "Darmanitan-Zen",
		"baseSpecies": "Darmanitan",
		"forme": "Zen",
		"types": ["Fire", "Psychic"],
		"baseStats": {"hp": 105, "atk": 30, "def": 105, "spa": 140, "spd": 105, "spe": 55},
		"abilities": {"0": "Zen Mode"},
		"heightm": 1.3,
		"weightkg": 92.9,
		"color": "Blue",
		"eggGroups": ["Field"],
		"requiredAbility": "Zen Mode",
		"battleOnly": "Darmanitan",
	},
	"Darmanitangalar": {
		"num": 555,
		"name": "Darmanitan-Galar",
		"baseSpecies": "Darmanitan",
		"forme": "Galar",
		"types": ["Ice"],
		"baseStats": {"hp": 105, "atk": 140, "def": 55, "spa": 30, "spd": 55, "spe": 95},
		"abilities": {"0": "Gorilla Tactics", "H": "Zen Mode"},
		"heightm": 1.7,
		"weightkg": 120,
		"color": "White",
		"prevo": "Darumaka-Galar",
		"evoType": "useItem",
		"evoItem": "Ice Stone",
		"eggGroups": ["Field"],
	},
	"Darmanitangalarzen": {
		"num": 555,
		"name": "Darmanitan-Galar-Zen",
		"baseSpecies": "Darmanitan",
		"forme": "Galar-Zen",
		"types": ["Ice", "Fire"],
		"baseStats": {"hp": 105, "atk": 160, "def": 55, "spa": 30, "spd": 55, "spe": 135},
		"abilities": {"0": "Zen Mode"},
		"heightm": 1.7,
		"weightkg": 120,
		"color": "White",
		"eggGroups": ["Field"],
		"requiredAbility": "Zen Mode",
		"battleOnly": "Darmanitan-Galar",
	},
	"Maractus": {
		"num": 556,
		"name": "Maractus",
		"types": ["Grass"],
		"baseStats": {"hp": 75, "atk": 86, "def": 67, "spa": 106, "spd": 67, "spe": 60},
		"abilities": {"0": "Water Absorb", "1": "Chlorophyll", "H": "Storm Drain"},
		"heightm": 1,
		"weightkg": 28,
		"color": "Green",
		"eggGroups": ["Grass"],
	},
	"Dwebble": {
		"num": 557,
		"name": "Dwebble",
		"types": ["Bug", "Rock"],
		"baseStats": {"hp": 50, "atk": 65, "def": 85, "spa": 35, "spd": 35, "spe": 55},
		"abilities": {"0": "Sturdy", "1": "Shell Armor", "H": "Weak Armor"},
		"heightm": 0.3,
		"weightkg": 14.5,
		"color": "Red",
		"evos": ["Crustle"],
		"eggGroups": ["Bug", "Mineral"],
	},
	"Crustle": {
		"num": 558,
		"name": "Crustle",
		"types": ["Bug", "Rock"],
		"baseStats": {"hp": 70, "atk": 105, "def": 125, "spa": 65, "spd": 75, "spe": 45},
		"abilities": {"0": "Sturdy", "1": "Shell Armor", "H": "Weak Armor"},
		"heightm": 1.4,
		"weightkg": 200,
		"color": "Red",
		"prevo": "Dwebble",
		"evoLevel": 34,
		"eggGroups": ["Bug", "Mineral"],
	},
	"Scraggy": {
		"num": 559,
		"name": "Scraggy",
		"types": ["Dark", "Fighting"],
		"baseStats": {"hp": 50, "atk": 75, "def": 70, "spa": 35, "spd": 70, "spe": 48},
		"abilities": {"0": "Shed Skin", "1": "Moxie", "H": "Intimidate"},
		"heightm": 0.6,
		"weightkg": 11.8,
		"color": "Yellow",
		"evos": ["Scrafty"],
		"eggGroups": ["Field", "Dragon"],
	},
	"Scrafty": {
		"num": 560,
		"name": "Scrafty",
		"types": ["Dark", "Fighting"],
		"baseStats": {"hp": 65, "atk": 90, "def": 115, "spa": 45, "spd": 115, "spe": 58},
		"abilities": {"0": "Shed Skin", "1": "Moxie", "H": "Intimidate"},
		"heightm": 1.1,
		"weightkg": 30,
		"color": "Red",
		"prevo": "Scraggy",
		"evoLevel": 39,
		"eggGroups": ["Field", "Dragon"],
	},
	"Sigilyph": {
		"num": 561,
		"name": "Sigilyph",
		"types": ["Psychic", "Flying"],
		"baseStats": {"hp": 72, "atk": 58, "def": 80, "spa": 103, "spd": 80, "spe": 97},
		"abilities": {"0": "Wonder Skin", "1": "Magic Guard", "H": "Tinted Lens"},
		"heightm": 1.4,
		"weightkg": 14,
		"color": "Black",
		"eggGroups": ["Flying"],
	},
	"Yamask": {
		"num": 562,
		"name": "Yamask",
		"types": ["Ghost"],
		"baseStats": {"hp": 38, "atk": 30, "def": 85, "spa": 55, "spd": 65, "spe": 30},
		"abilities": {"0": "Mummy"},
		"heightm": 0.5,
		"weightkg": 1.5,
		"color": "Black",
		"evos": ["Cofagrigus"],
		"eggGroups": ["Mineral", "Amorphous"],
		"otherFormes": ["Yamask-Galar"],
		"formeOrder": ["Yamask", "Yamask-Galar"],
	},
	"Yamaskgalar": {
		"num": 562,
		"name": "Yamask-Galar",
		"baseSpecies": "Yamask",
		"forme": "Galar",
		"types": ["Ground", "Ghost"],
		"baseStats": {"hp": 38, "atk": 55, "def": 85, "spa": 30, "spd": 65, "spe": 30},
		"abilities": {"0": "Wandering Spirit"},
		"heightm": 0.5,
		"weightkg": 1.5,
		"color": "Black",
		"evos": ["Runerigus"],
		"eggGroups": ["Mineral", "Amorphous"],
	},
	"Cofagrigus": {
		"num": 563,
		"name": "Cofagrigus",
		"types": ["Ghost"],
		"baseStats": {"hp": 58, "atk": 50, "def": 145, "spa": 95, "spd": 105, "spe": 30},
		"abilities": {"0": "Mummy"},
		"heightm": 1.7,
		"weightkg": 76.5,
		"color": "Yellow",
		"prevo": "Yamask",
		"evoLevel": 34,
		"eggGroups": ["Mineral", "Amorphous"],
	},
	"Tirtouga": {
		"num": 564,
		"name": "Tirtouga",
		"types": ["Water", "Rock"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 54, "atk": 78, "def": 103, "spa": 53, "spd": 45, "spe": 22},
		"abilities": {"0": "Solid Rock", "1": "Sturdy", "H": "Swift Swim"},
		"heightm": 0.7,
		"weightkg": 16.5,
		"color": "Blue",
		"evos": ["Carracosta"],
		"eggGroups": ["Water 1", "Water 3"],
	},
	"Carracosta": {
		"num": 565,
		"name": "Carracosta",
		"types": ["Water", "Rock"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 74, "atk": 108, "def": 133, "spa": 83, "spd": 65, "spe": 32},
		"abilities": {"0": "Solid Rock", "1": "Sturdy", "H": "Swift Swim"},
		"heightm": 1.2,
		"weightkg": 81,
		"color": "Blue",
		"prevo": "Tirtouga",
		"evoLevel": 37,
		"eggGroups": ["Water 1", "Water 3"],
	},
	"Archen": {
		"num": 566,
		"name": "Archen",
		"types": ["Rock", "Flying"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 55, "atk": 112, "def": 45, "spa": 74, "spd": 45, "spe": 70},
		"abilities": {"0": "Defeatist"},
		"heightm": 0.5,
		"weightkg": 9.5,
		"color": "Yellow",
		"evos": ["Archeops"],
		"eggGroups": ["Flying", "Water 3"],
	},
	"Archeops": {
		"num": 567,
		"name": "Archeops",
		"types": ["Rock", "Flying"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 75, "atk": 140, "def": 65, "spa": 112, "spd": 65, "spe": 110},
		"abilities": {"0": "Defeatist"},
		"heightm": 1.4,
		"weightkg": 32,
		"color": "Yellow",
		"prevo": "Archen",
		"evoLevel": 37,
		"eggGroups": ["Flying", "Water 3"],
	},
	"Trubbish": {
		"num": 568,
		"name": "Trubbish",
		"types": ["Poison"],
		"baseStats": {"hp": 50, "atk": 50, "def": 62, "spa": 40, "spd": 62, "spe": 65},
		"abilities": {"0": "Stench", "1": "Sticky Hold", "H": "Aftermath"},
		"heightm": 0.6,
		"weightkg": 31,
		"color": "Green",
		"evos": ["Garbodor"],
		"eggGroups": ["Mineral"],
	},
	"Garbodor": {
		"num": 569,
		"name": "Garbodor",
		"types": ["Poison"],
		"baseStats": {"hp": 80, "atk": 95, "def": 82, "spa": 60, "spd": 82, "spe": 75},
		"abilities": {"0": "Stench", "1": "Weak Armor", "H": "Aftermath"},
		"heightm": 1.9,
		"weightkg": 107.3,
		"color": "Green",
		"prevo": "Trubbish",
		"evoLevel": 36,
		"eggGroups": ["Mineral"],
		"canGigantamax": "G-Max Malodor",
	},
	"Garbodorgmax": {
		"num": 569,
		"name": "Garbodor-Gmax",
		"baseSpecies": "Garbodor",
		"forme": "Gmax",
		"types": ["Poison"],
		"baseStats": {"hp": 80, "atk": 95, "def": 82, "spa": 60, "spd": 82, "spe": 75},
		"abilities": {"0": "Stench", "1": "Weak Armor", "H": "Aftermath"},
		"heightm": 21,
		"weightkg": 0,
		"color": "Green",
		"eggGroups": ["Mineral"],
		"changesFrom": "Garbodor",
	},
	"Zorua": {
		"num": 570,
		"name": "Zorua",
		"types": ["Dark"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 40, "atk": 65, "def": 40, "spa": 80, "spd": 40, "spe": 65},
		"abilities": {"0": "Illusion"},
		"heightm": 0.7,
		"weightkg": 12.5,
		"color": "Gray",
		"evos": ["Zoroark"],
		"eggGroups": ["Field"],
		"otherFormes": ["Zorua-Hisui"],
		"formeOrder": ["Zorua", "Zorua-Hisui"],
	},
	"Zoruahisui": {
		"num": 570,
		"name": "Zorua-Hisui",
		"baseSpecies": "Zorua",
		"forme": "Hisui",
		"types": ["Normal", "Ghost"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 35, "atk": 60, "def": 40, "spa": 85, "spd": 40, "spe": 70},
		"abilities": {"0": "Illusion"},
		"heightm": 0.7,
		"weightkg": 12.5,
		"color": "Gray",
		"evos": ["Zoroark-Hisui"],
		"eggGroups": ["Field"],
	},
	"Zoroark": {
		"num": 571,
		"name": "Zoroark",
		"types": ["Dark"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 60, "atk": 105, "def": 60, "spa": 120, "spd": 60, "spe": 105},
		"abilities": {"0": "Illusion"},
		"heightm": 1.6,
		"weightkg": 81.1,
		"color": "Gray",
		"prevo": "Zorua",
		"evoLevel": 30,
		"eggGroups": ["Field"],
		"otherFormes": ["Zoroark-Hisui"],
		"formeOrder": ["Zoroark", "Zoroark-Hisui"],
	},
	"Zoroarkhisui": {
		"num": 571,
		"name": "Zoroark-Hisui",
		"baseSpecies": "Zoroark",
		"forme": "Hisui",
		"types": ["Normal", "Ghost"],
		"genderRatio": {"M": 0.875, "F": 0.125},
		"baseStats": {"hp": 55, "atk": 100, "def": 60, "spa": 125, "spd": 60, "spe": 110},
		"abilities": {"0": "Illusion"},
		"heightm": 1.6,
		"weightkg": 73,
		"color": "Gray",
		"prevo": "Zorua-Hisui",
		"evoLevel": 30,
		"eggGroups": ["Field"],
	},
	"Minccino": {
		"num": 572,
		"name": "Minccino",
		"types": ["Normal"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 55, "atk": 50, "def": 40, "spa": 40, "spd": 40, "spe": 75},
		"abilities": {"0": "Cute Charm", "1": "Technician", "H": "Skill Link"},
		"heightm": 0.4,
		"weightkg": 5.8,
		"color": "Gray",
		"evos": ["Cinccino"],
		"eggGroups": ["Field"],
	},
	"Cinccino": {
		"num": 573,
		"name": "Cinccino",
		"types": ["Normal"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 75, "atk": 95, "def": 60, "spa": 65, "spd": 60, "spe": 115},
		"abilities": {"0": "Cute Charm", "1": "Technician", "H": "Skill Link"},
		"heightm": 0.5,
		"weightkg": 7.5,
		"color": "Gray",
		"prevo": "Minccino",
		"evoType": "useItem",
		"evoItem": "Shiny Stone",
		"eggGroups": ["Field"],
	},
	"Gothita": {
		"num": 574,
		"name": "Gothita",
		"types": ["Psychic"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 45, "atk": 30, "def": 50, "spa": 55, "spd": 65, "spe": 45},
		"abilities": {"0": "Frisk", "1": "Competitive", "H": "Shadow Tag"},
		"heightm": 0.4,
		"weightkg": 5.8,
		"color": "Purple",
		"evos": ["Gothorita"],
		"eggGroups": ["Human-Like"],
	},
	"Gothorita": {
		"num": 575,
		"name": "Gothorita",
		"types": ["Psychic"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 60, "atk": 45, "def": 70, "spa": 75, "spd": 85, "spe": 55},
		"abilities": {"0": "Frisk", "1": "Competitive", "H": "Shadow Tag"},
		"heightm": 0.7,
		"weightkg": 18,
		"color": "Purple",
		"prevo": "Gothita",
		"evoLevel": 32,
		"evos": ["Gothitelle"],
		"eggGroups": ["Human-Like"],
	},
	"Gothitelle": {
		"num": 576,
		"name": "Gothitelle",
		"types": ["Psychic"],
		"genderRatio": {"M": 0.25, "F": 0.75},
		"baseStats": {"hp": 70, "atk": 55, "def": 95, "spa": 95, "spd": 110, "spe": 65},
		"abilities": {"0": "Frisk", "1": "Competitive", "H": "Shadow Tag"},
		"heightm": 1.5,
		"weightkg": 44,
		"color": "Purple",
		"prevo": "Gothorita",
		"evoLevel": 41,
		"eggGroups": ["Human-Like"],
	},
	"Solosis": {
		"num": 577,
		"name": "Solosis",
		"types": ["Psychic"],
		"baseStats": {"hp": 45, "atk": 30, "def": 40, "spa": 105, "spd": 50, "spe": 20},
		"abilities": {"0": "Overcoat", "1": "Magic Guard", "H": "Regenerator"},
		"heightm": 0.3,
		"weightkg": 1,
		"color": "Green",
		"evos": ["Duosion"],
		"eggGroups": ["Amorphous"],
	},
	"Duosion": {
		"num": 578,
		"name": "Duosion",
		"types": ["Psychic"],
		"baseStats": {"hp": 65, "atk": 40, "def": 50, "spa": 125, "spd": 60, "spe": 30},
		"abilities": {"0": "Overcoat", "1": "Magic Guard", "H": "Regenerator"},
		"heightm": 0.6,
		"weightkg": 8,
		"color": "Green",
		"prevo": "Solosis",
		"evoLevel": 32,
		"evos": ["Reuniclus"],
		"eggGroups": ["Amorphous"],
	},
	"Reuniclus": {
		"num": 579,
		"name": "Reuniclus",
		"types": ["Psychic"],
		"baseStats": {"hp": 110, "atk": 65, "def": 75, "spa": 125, "spd": 85, "spe": 30},
		"abilities": {"0": "Overcoat", "1": "Magic Guard", "H": "Regenerator"},
		"heightm": 1,
		"weightkg": 20.1,
		"color": "Green",
		"prevo": "Duosion",
		"evoLevel": 41,
		"eggGroups": ["Amorphous"],
	},
	"Ducklett": {
		"num": 580,
		"name": "Ducklett",
		"types": ["Water", "Flying"],
		"baseStats": {"hp": 62, "atk": 44, "def": 50, "spa": 44, "spd": 50, "spe": 55},
		"abilities": {"0": "Keen Eye", "1": "Big Pecks", "H": "Hydration"},
		"heightm": 0.5,
		"weightkg": 5.5,
		"color": "Blue",
		"evos": ["Swanna"],
		"eggGroups": ["Water 1", "Flying"],
	},
	"Swanna": {
		"num": 581,
		"name": "Swanna",
		"types": ["Water", "Flying"],
		"baseStats": {"hp": 75, "atk": 87, "def": 63, "spa": 87, "spd": 63, "spe": 98},
		"abilities": {"0": "Keen Eye", "1": "Big Pecks", "H": "Hydration"},
		"heightm": 1.3,
		"weightkg": 24.2,
		"color": "White",
		"prevo": "Ducklett",
		"evoLevel": 35,
		"eggGroups": ["Water 1", "Flying"],
	},
	"Vanillite": {
		"num": 582,
		"name": "Vanillite",
		"types": ["Ice"],
		"baseStats": {"hp": 36, "atk": 50, "def": 50, "spa": 65, "spd": 60, "spe": 44},
		"abilities": {"0": "Ice Body", "1": "Snow Cloak", "H": "Weak Armor"},
		"heightm": 0.4,
		"weightkg": 5.7,
		"color": "White",
		"evos": ["Vanillish"],
		"eggGroups": ["Mineral"],
	},
	"Vanillish": {
		"num": 583,
		"name": "Vanillish",
		"types": ["Ice"],
		"baseStats": {"hp": 51, "atk": 65, "def": 65, "spa": 80, "spd": 75, "spe": 59},
		"abilities": {"0": "Ice Body", "1": "Snow Cloak", "H": "Weak Armor"},
		"heightm": 1.1,
		"weightkg": 41,
		"color": "White",
		"prevo": "Vanillite",
		"evoLevel": 35,
		"evos": ["Vanilluxe"],
		"eggGroups": ["Mineral"],
	},
	"Vanilluxe": {
		"num": 584,
		"name": "Vanilluxe",
		"types": ["Ice"],
		"baseStats": {"hp": 71, "atk": 95, "def": 85, "spa": 110, "spd": 95, "spe": 79},
		"abilities": {"0": "Ice Body", "1": "Snow Warning", "H": "Weak Armor"},
		"heightm": 1.3,
		"weightkg": 57.5,
		"color": "White",
		"prevo": "Vanillish",
		"evoLevel": 47,
		"eggGroups": ["Mineral"],
	},
	"Deerling": {
		"num": 585,
		"name": "Deerling",
		"baseForme": "Spring",
		"types": ["Normal", "Grass"],
		"baseStats": {"hp": 60, "atk": 60, "def": 50, "spa": 40, "spd": 50, "spe": 75},
		"abilities": {"0": "Chlorophyll", "1": "Sap Sipper", "H": "Serene Grace"},
		"heightm": 0.6,
		"weightkg": 19.5,
		"color": "Pink",
		"evos": ["Sawsbuck"],
		"eggGroups": ["Field"],
		"cosmeticFormes": ["Deerling-Summer", "Deerling-Autumn", "Deerling-Winter"],
		"formeOrder": ["Deerling", "Deerling-Summer", "Deerling-Autumn", "Deerling-Winter"],
	},
	"Sawsbuck": {
		"num": 586,
		"name": "Sawsbuck",
		"baseForme": "Spring",
		"types": ["Normal", "Grass"],
		"baseStats": {"hp": 80, "atk": 100, "def": 70, "spa": 60, "spd": 70, "spe": 95},
		"abilities": {"0": "Chlorophyll", "1": "Sap Sipper", "H": "Serene Grace"},
		"heightm": 1.9,
		"weightkg": 92.5,
		"color": "Brown",
		"prevo": "Deerling",
		"evoLevel": 34,
		"eggGroups": ["Field"],
		"cosmeticFormes": ["Sawsbuck-Summer", "Sawsbuck-Autumn", "Sawsbuck-Winter"],
		"formeOrder": ["Sawsbuck", "Sawsbuck-Summer", "Sawsbuck-Autumn", "Sawsbuck-Winter"],
	},
	"Emolga": {
		"num": 587,
		"name": "Emolga",
		"types": ["Electric", "Flying"],
		"baseStats": {"hp": 55, "atk": 75, "def": 60, "spa": 75, "spd": 60, "spe": 103},
		"abilities": {"0": "Static", "H": "Motor Drive"},
		"heightm": 0.4,
		"weightkg": 5,
		"color": "White",
		"eggGroups": ["Field"],
	},
	"Karrablast": {
		"num": 588,
		"name": "Karrablast",
		"types": ["Bug"],
		"baseStats": {"hp": 50, "atk": 75, "def": 45, "spa": 40, "spd": 45, "spe": 60},
		"abilities": {"0": "Swarm", "1": "Shed Skin", "H": "No Guard"},
		"heightm": 0.5,
		"weightkg": 5.9,
		"color": "Blue",
		"evos": ["Escavalier"],
		"eggGroups": ["Bug"],
	},
	"Escavalier": {
		"num": 589,
		"name": "Escavalier",
		"types": ["Bug", "Steel"],
		"baseStats": {"hp": 70, "atk": 135, "def": 105, "spa": 60, "spd": 105, "spe": 20},
		"abilities": {"0": "Swarm", "1": "Shell Armor", "H": "Overcoat"},
		"heightm": 1,
		"weightkg": 33,
		"color": "Gray",
		"prevo": "Karrablast",
		"evoType": "trade",
		"evoCondition": "with a Shelmet",
		"eggGroups": ["Bug"],
	},
	"Foongus": {
		"num": 590,
		"name": "Foongus",
		"types": ["Grass", "Poison"],
		"baseStats": {"hp": 69, "atk": 55, "def": 45, "spa": 55, "spd": 55, "spe": 15},
		"abilities": {"0": "Effect Spore", "H": "Regenerator"},
		"heightm": 0.2,
		"weightkg": 1,
		"color": "White",
		"evos": ["Amoonguss"],
		"eggGroups": ["Grass"],
	},
	"Amoonguss": {
		"num": 591,
		"name": "Amoonguss",
		"types": ["Grass", "Poison"],
		"baseStats": {"hp": 114, "atk": 85, "def": 70, "spa": 85, "spd": 80, "spe": 30},
		"abilities": {"0": "Effect Spore", "H": "Regenerator"},
		"heightm": 0.6,
		"weightkg": 10.5,
		"color": "White",
		"prevo": "Foongus",
		"evoLevel": 39,
		"eggGroups": ["Grass"],
	},
	"Frillish": {
		"num": 592,
		"name": "Frillish",
		"types": ["Water", "Ghost"],
		"baseStats": {"hp": 55, "atk": 40, "def": 50, "spa": 65, "spd": 85, "spe": 40},
		"abilities": {"0": "Water Absorb", "1": "Cursed Body", "H": "Damp"},
		"heightm": 1.2,
		"weightkg": 33,
		"color": "White",
		"evos": ["Jellicent"],
		"eggGroups": ["Amorphous"],
	},
	"Jellicent": {
		"num": 593,
		"name": "Jellicent",
		"types": ["Water", "Ghost"],
		"baseStats": {"hp": 100, "atk": 60, "def": 70, "spa": 85, "spd": 105, "spe": 60},
		"abilities": {"0": "Water Absorb", "1": "Cursed Body", "H": "Damp"},
		"heightm": 2.2,
		"weightkg": 135,
		"color": "White",
		"prevo": "Frillish",
		"evoLevel": 40,
		"eggGroups": ["Amorphous"],
	},
	"Alomomola": {
		"num": 594,
		"name": "Alomomola",
		"types": ["Water"],
		"baseStats": {"hp": 165, "atk": 75, "def": 80, "spa": 40, "spd": 45, "spe": 65},
		"abilities": {"0": "Healer", "1": "Hydration", "H": "Regenerator"},
		"heightm": 1.2,
		"weightkg": 31.6,
		"color": "Pink",
		"eggGroups": ["Water 1", "Water 2"],
	},
	"Joltik": {
		"num": 595,
		"name": "Joltik",
		"types": ["Bug", "Electric"],
		"baseStats": {"hp": 50, "atk": 47, "def": 50, "spa": 57, "spd": 50, "spe": 65},
		"abilities": {"0": "Compound Eyes", "1": "Unnerve", "H": "Swarm"},
		"heightm": 0.1,
		"weightkg": 0.6,
		"color": "Yellow",
		"evos": ["Galvantula"],
		"eggGroups": ["Bug"],
	},
	"Galvantula": {
		"num": 596,
		"name": "Galvantula",
		"types": ["Bug", "Electric"],
		"baseStats": {"hp": 70, "atk": 77, "def": 60, "spa": 97, "spd": 60, "spe": 108},
		"abilities": {"0": "Compound Eyes", "1": "Unnerve", "H": "Swarm"},
		"heightm": 0.8,
		"weightkg": 14.3,
		"color": "Yellow",
		"prevo": "Joltik",
		"evoLevel": 36,
		"eggGroups": ["Bug"],
	},
	"Ferroseed": {
		"num": 597,
		"name": "Ferroseed",
		"types": ["Grass", "Steel"],
		"baseStats": {"hp": 44, "atk": 50, "def": 91, "spa": 24, "spd": 86, "spe": 10},
		"abilities": {"0": "Iron Barbs"},
		"heightm": 0.6,
		"weightkg": 18.8,
		"color": "Gray",
		"evos": ["Ferrothorn"],
		"eggGroups": ["Grass", "Mineral"],
	},
	"Ferrothorn": {
		"num": 598,
		"name": "Ferrothorn",
		"types": ["Grass", "Steel"],
		"baseStats": {"hp": 74, "atk": 94, "def": 131, "spa": 54, "spd": 116, "spe": 20},
		"abilities": {"0": "Iron Barbs", "H": "Anticipation"},
		"heightm": 1,
		"weightkg": 110,
		"color": "Gray",
		"prevo": "Ferroseed",
		"evoLevel": 40,
		"eggGroups": ["Grass", "Mineral"],
	},
	"Klink": {
		"num": 599,
		"name": "Klink",
		"types": ["Steel"],
		"gender": "N",
		"baseStats": {"hp": 40, "atk": 55, "def": 70, "spa": 45, "spd": 60, "spe": 30},
		"abilities": {"0": "Plus", "1": "Minus", "H": "Clear Body"},
		"heightm": 0.3,
		"weightkg": 21,
		"color": "Gray",
		"evos": ["Klang"],
		"eggGroups": ["Mineral"],
	},
	"Klang": {
		"num": 600,
		"name": "Klang",
		"types": ["Steel"],
		"gender": "N",
		"baseStats": {"hp": 60, "atk": 80, "def": 95, "spa": 70, "spd": 85, "spe": 50},
		"abilities": {"0": "Plus", "1": "Minus", "H": "Clear Body"},
		"heightm": 0.6,
		"weightkg": 51,
		"color": "Gray",
		"prevo": "Klink",
		"evoLevel": 38,
		"evos": ["Klinklang"],
		"eggGroups": ["Mineral"],
	},
	"Klinklang": {
		"num": 601,
		"name": "Klinklang",
		"types": ["Steel"],
		"gender": "N",
		"baseStats": {"hp": 60, "atk": 100, "def": 115, "spa": 70, "spd": 85, "spe": 90},
		"abilities": {"0": "Plus", "1": "Minus", "H": "Clear Body"},
		"heightm": 0.6,
		"weightkg": 81,
		"color": "Gray",
		"prevo": "Klang",
		"evoLevel": 49,
		"eggGroups": ["Mineral"],
	},
	"Tynamo": {
		"num": 602,
		"name": "Tynamo",
		"types": ["Electric"],
		"baseStats": {"hp": 35, "atk": 55, "def": 40, "spa": 45, "spd": 40, "spe": 60},
		"abilities": {"0": "Levitate"},
		"heightm": 0.2,
		"weightkg": 0.3,
		"color": "White",
		"evos": ["Eelektrik"],
		"eggGroups": ["Amorphous"],
	},
	"Eelektrik": {
		"num": 603,
		"name": "Eelektrik",
		"types": ["Electric"],
		"baseStats": {"hp": 65, "atk": 85, "def": 70, "spa": 75, "spd": 70, "spe": 40},
		"abilities": {"0": "Levitate"},
		"heightm": 1.2,
		"weightkg": 22,
		"color": "Blue",
		"prevo": "Tynamo",
		"evoLevel": 39,
		"evos": ["Eelektross"],
		"eggGroups": ["Amorphous"],
	},
	"Eelektross": {
		"num": 604,
		"name": "Eelektross",
		"types": ["Electric"],
		"baseStats": {"hp": 85, "atk": 115, "def": 80, "spa": 105, "spd": 80, "spe": 50},
		"abilities": {"0": "Levitate"},
		"heightm": 2.1,
		"weightkg": 80.5,
		"color": "Blue",
		"prevo": "Eelektrik",
		"evoType": "useItem",
		"evoItem": "Thunder Stone",
		"eggGroups": ["Amorphous"],
	},
	"Elgyem": {
		"num": 605,
		"name": "Elgyem",
		"types": ["Psychic"],
		"baseStats": {"hp": 55, "atk": 55, "def": 55, "spa": 85, "spd": 55, "spe": 30},
		"abilities": {"0": "Telepathy", "1": "Synchronize", "H": "Analytic"},
		"heightm": 0.5,
		"weightkg": 9,
		"color": "Blue",
		"evos": ["Beheeyem"],
		"eggGroups": ["Human-Like"],
	},
	"Beheeyem": {
		"num": 606,
		"name": "Beheeyem",
		"types": ["Psychic"],
		"baseStats": {"hp": 75, "atk": 75, "def": 75, "spa": 125, "spd": 95, "spe": 40},
		"abilities": {"0": "Telepathy", "1": "Synchronize", "H": "Analytic"},
		"heightm": 1,
		"weightkg": 34.5,
		"color": "Brown",
		"prevo": "Elgyem",
		"evoLevel": 42,
		"eggGroups": ["Human-Like"],
	},
	"Litwick": {
		"num": 607,
		"name": "Litwick",
		"types": ["Ghost", "Fire"],
		"baseStats": {"hp": 50, "atk": 30, "def": 55, "spa": 65, "spd": 55, "spe": 20},
		"abilities": {"0": "Flash Fire", "1": "Flame Body", "H": "Infiltrator"},
		"heightm": 0.3,
		"weightkg": 3.1,
		"color": "White",
		"evos": ["Lampent"],
		"eggGroups": ["Amorphous"],
	},
	"Lampent": {
		"num": 608,
		"name": "Lampent",
		"types": ["Ghost", "Fire"],
		"baseStats": {"hp": 60, "atk": 40, "def": 60, "spa": 95, "spd": 60, "spe": 55},
		"abilities": {"0": "Flash Fire", "1": "Flame Body", "H": "Infiltrator"},
		"heightm": 0.6,
		"weightkg": 13,
		"color": "Black",
		"prevo": "Litwick",
		"evoLevel": 41,
		"evos": ["Chandelure"],
		"eggGroups": ["Amorphous"],
	},
	"Chandelure": {
		"num": 609,
		"name": "Chandelure",
		"types": ["Ghost", "Fire"],
		"baseStats": {"hp": 60, "atk": 55, "def": 90, "spa": 145, "spd": 90, "spe": 80},
		"abilities": {"0": "Flash Fire", "1": "Flame Body", "H": "Infiltrator"},
		"heightm": 1,
		"weightkg": 34.3,
		"color": "Black",
		"prevo": "Lampent",
		"evoType": "useItem",
		"evoItem": "Dusk Stone",
		"eggGroups": ["Amorphous"],
	},
	"Axew": {
		"num": 610,
		"name": "Axew",
		"types": ["Dragon"],
		"baseStats": {"hp": 46, "atk": 87, "def": 60, "spa": 30, "spd": 40, "spe": 57},
		"abilities": {"0": "Rivalry", "1": "Mold Breaker", "H": "Unnerve"},
		"heightm": 0.6,
		"weightkg": 18,
		"color": "Green",
		"evos": ["Fraxure"],
		"eggGroups": ["Monster", "Dragon"],
	},
	"Fraxure": {
		"num": 611,
		"name": "Fraxure",
		"types": ["Dragon"],
		"baseStats": {"hp": 66, "atk": 117, "def": 70, "spa": 40, "spd": 50, "spe": 67},
		"abilities": {"0": "Rivalry", "1": "Mold Breaker", "H": "Unnerve"},
		"heightm": 1,
		"weightkg": 36,
		"color": "Green",
		"prevo": "Axew",
		"evoLevel": 38,
		"evos": ["Haxorus"],
		"eggGroups": ["Monster", "Dragon"],
	},
	"Haxorus": {
		"num": 612,
		"name": "Haxorus",
		"types": ["Dragon"],
		"baseStats": {"hp": 76, "atk": 147, "def": 90, "spa": 60, "spd": 70, "spe": 97},
		"abilities": {"0": "Rivalry", "1": "Mold Breaker", "H": "Unnerve"},
		"heightm": 1.8,
		"weightkg": 105.5,
		"color": "Yellow",
		"prevo": "Fraxure",
		"evoLevel": 48,
		"eggGroups": ["Monster", "Dragon"],
	},
	"Cubchoo": {
		"num": 613,
		"name": "Cubchoo",
		"types": ["Ice"],
		"baseStats": {"hp": 55, "atk": 70, "def": 40, "spa": 60, "spd": 40, "spe": 40},
		"abilities": {"0": "Snow Cloak", "1": "Slush Rush", "H": "Rattled"},
		"heightm": 0.5,
		"weightkg": 8.5,
		"color": "White",
		"evos": ["Beartic"],
		"eggGroups": ["Field"],
	},
	"Beartic": {
		"num": 614,
		"name": "Beartic",
		"types": ["Ice"],
		"baseStats": {"hp": 95, "atk": 130, "def": 80, "spa": 70, "spd": 80, "spe": 50},
		"abilities": {"0": "Snow Cloak", "1": "Slush Rush", "H": "Swift Swim"},
		"heightm": 2.6,
		"weightkg": 260,
		"color": "White",
		"prevo": "Cubchoo",
		"evoLevel": 37,
		"eggGroups": ["Field"],
	},
	"Cryogonal": {
		"num": 615,
		"name": "Cryogonal",
		"types": ["Ice"],
		"gender": "N",
		"baseStats": {"hp": 80, "atk": 50, "def": 50, "spa": 95, "spd": 135, "spe": 105},
		"abilities": {"0": "Levitate"},
		"heightm": 1.1,
		"weightkg": 148,
		"color": "Blue",
		"eggGroups": ["Mineral"],
	},
	"Shelmet": {
		"num": 616,
		"name": "Shelmet",
		"types": ["Bug"],
		"baseStats": {"hp": 50, "atk": 40, "def": 85, "spa": 40, "spd": 65, "spe": 25},
		"abilities": {"0": "Hydration", "1": "Shell Armor", "H": "Overcoat"},
		"heightm": 0.4,
		"weightkg": 7.7,
		"color": "Red",
		"evos": ["Accelgor"],
		"eggGroups": ["Bug"],
	},
	"Accelgor": {
		"num": 617,
		"name": "Accelgor",
		"types": ["Bug"],
		"baseStats": {"hp": 80, "atk": 70, "def": 40, "spa": 100, "spd": 60, "spe": 145},
		"abilities": {"0": "Hydration", "1": "Sticky Hold", "H": "Unburden"},
		"heightm": 0.8,
		"weightkg": 25.3,
		"color": "Red",
		"prevo": "Shelmet",
		"evoType": "trade",
		"evoCondition": "with a Karrablast",
		"eggGroups": ["Bug"],
	},
	"Stunfisk": {
		"num": 618,
		"name": "Stunfisk",
		"types": ["Ground", "Electric"],
		"baseStats": {"hp": 109, "atk": 66, "def": 84, "spa": 81, "spd": 99, "spe": 32},
		"abilities": {"0": "Static", "1": "Limber", "H": "Sand Veil"},
		"heightm": 0.7,
		"weightkg": 11,
		"color": "Brown",
		"eggGroups": ["Water 1", "Amorphous"],
		"otherFormes": ["Stunfisk-Galar"],
		"formeOrder": ["Stunfisk", "Stunfisk-Galar"],
	},
	"Stunfiskgalar": {
		"num": 618,
		"name": "Stunfisk-Galar",
		"baseSpecies": "Stunfisk",
		"forme": "Galar",
		"types": ["Ground", "Steel"],
		"baseStats": {"hp": 109, "atk": 81, "def": 99, "spa": 66, "spd": 84, "spe": 32},
		"abilities": {"0": "Mimicry"},
		"heightm": 0.7,
		"weightkg": 20.5,
		"color": "Green",
		"eggGroups": ["Water 1", "Amorphous"],
	},
	"Mienfoo": {
		"num": 619,
		"name": "Mienfoo",
		"types": ["Fighting"],
		"baseStats": {"hp": 45, "atk": 85, "def": 50, "spa": 55, "spd": 50, "spe": 65},
		"abilities": {"0": "Inner Focus", "1": "Regenerator", "H": "Reckless"},
		"heightm": 0.9,
		"weightkg": 20,
		"color": "Yellow",
		"evos": ["Mienshao"],
		"eggGroups": ["Field", "Human-Like"],
	},
	"Mienshao": {
		"num": 620,
		"name": "Mienshao",
		"types": ["Fighting"],
		"baseStats": {"hp": 65, "atk": 125, "def": 60, "spa": 95, "spd": 60, "spe": 105},
		"abilities": {"0": "Inner Focus", "1": "Regenerator", "H": "Reckless"},
		"heightm": 1.4,
		"weightkg": 35.5,
		"color": "Purple",
		"prevo": "Mienfoo",
		"evoLevel": 50,
		"eggGroups": ["Field", "Human-Like"],
	},
	"Druddigon": {
		"num": 621,
		"name": "Druddigon",
		"types": ["Dragon"],
		"baseStats": {"hp": 77, "atk": 120, "def": 90, "spa": 60, "spd": 90, "spe": 48},
		"abilities": {"0": "Rough Skin", "1": "Sheer Force", "H": "Mold Breaker"},
		"heightm": 1.6,
		"weightkg": 139,
		"color": "Red",
		"eggGroups": ["Monster", "Dragon"],
	},
	"Golett": {
		"num": 622,
		"name": "Golett",
		"types": ["Ground", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 59, "atk": 74, "def": 50, "spa": 35, "spd": 50, "spe": 35},
		"abilities": {"0": "Iron Fist", "1": "Klutz", "H": "No Guard"},
		"heightm": 1,
		"weightkg": 92,
		"color": "Green",
		"evos": ["Golurk"],
		"eggGroups": ["Mineral"],
	},
	"Golurk": {
		"num": 623,
		"name": "Golurk",
		"types": ["Ground", "Ghost"],
		"gender": "N",
		"baseStats": {"hp": 89, "atk": 124, "def": 80, "spa": 55, "spd": 80, "spe": 55},
		"abilities": {"0": "Iron Fist", "1": "Klutz", "H": "No Guard"},
		"heightm": 2.8,
		"weightkg": 330,
		"color": "Green",
		"prevo": "Golett",
		"evoLevel": 43,
		"eggGroups": ["Mineral"],
	},
	"Pawniard": {
		"num": 624,
		"name": "Pawniard",
		"types": ["Dark", "Steel"],
		"baseStats": {"hp": 45, "atk": 85, "def": 70, "spa": 40, "spd": 40, "spe": 60},
		"abilities": {"0": "Defiant", "1": "Inner Focus", "H": "Pressure"},
		"heightm": 0.5,
		"weightkg": 10.2,
		"color": "Red",
		"evos": ["Bisharp"],
		"eggGroups": ["Human-Like"],
	},
	"Bisharp": {
		"num": 625,
		"name": "Bisharp",
		"types": ["Dark", "Steel"],
		"baseStats": {"hp": 65, "atk": 125, "def": 100, "spa": 60, "spd": 70, "spe": 70},
		"abilities": {"0": "Defiant", "1": "Inner Focus", "H": "Pressure"},
		"heightm": 1.6,
		"weightkg": 70,
		"color": "Red",
		"prevo": "Pawniard",
		"evoLevel": 52,
		"evos": ["Kingambit"],
		"eggGroups": ["Human-Like"],
	},
	"Bouffalant": {
		"num": 626,
		"name": "Bouffalant",
		"types": ["Normal"],
		"baseStats": {"hp": 95, "atk": 110, "def": 95, "spa": 40, "spd": 95, "spe": 55},
		"abilities": {"0": "Reckless", "1": "Sap Sipper", "H": "Soundproof"},
		"heightm": 1.6,
		"weightkg": 94.6,
		"color": "Brown",
		"eggGroups": ["Field"],
	},
	"Rufflet": {
		"num": 627,
		"name": "Rufflet",
		"types": ["Normal", "Flying"],
		"gender": "M",
		"baseStats": {"hp": 70, "atk": 83, "def": 50, "spa": 37, "spd": 50, "spe": 60},
		"abilities": {"0": "Keen Eye", "1": "Sheer Force", "H": "Hustle"},
		"heightm": 0.5,
		"weightkg": 10.5,
		"color": "White",
		"evos": ["Braviary", "Braviary-Hisui"],
		"eggGroups": ["Flying"],
	},
	"Braviary": {
		"num": 628,
		"name": "Braviary",
		"types": ["Normal", "Flying"],
		"gender": "M",
		"baseStats": {"hp": 100, "atk": 123, "def": 75, "spa": 57, "spd": 75, "spe": 80},
		"abilities": {"0": "Keen Eye", "1": "Sheer Force", "H": "Defiant"},
		"heightm": 1.5,
		"weightkg": 41,
		"color": "Red",
		"prevo": "Rufflet",
		"evoLevel": 54,
		"eggGroups": ["Flying"],
		"otherFormes": ["Braviary-Hisui"],
		"formeOrder": ["Braviary", "Braviary-Hisui"],
	},
	"Braviaryhisui": {
		"num": 628,
		"name": "Braviary-Hisui",
		"baseSpecies": "Braviary",
		"forme": "Hisui",
		"types": ["Psychic", "Flying"],
		"gender": "M",
		"baseStats": {"hp": 110, "atk": 83, "def": 70, "spa": 112, "spd": 70, "spe": 65},
		"abilities": {"0": "Keen Eye", "1": "Sheer Force", "H": "Tinted Lens"},
		"heightm": 1.7,
		"weightkg": 43.4,
		"color": "White",
		"prevo": "Rufflet",
		"evoLevel": 54,
		"eggGroups": ["Flying"],
	},
	"Vullaby": {
		"num": 629,
		"name": "Vullaby",
		"types": ["Dark", "Flying"],
		"gender": "F",
		"baseStats": {"hp": 70, "atk": 55, "def": 75, "spa": 45, "spd": 65, "spe": 60},
		"abilities": {"0": "Big Pecks", "1": "Overcoat", "H": "Weak Armor"},
		"heightm": 0.5,
		"weightkg": 9,
		"color": "Brown",
		"evos": ["Mandibuzz"],
		"eggGroups": ["Flying"],
	},
	"Mandibuzz": {
		"num": 630,
		"name": "Mandibuzz",
		"types": ["Dark", "Flying"],
		"gender": "F",
		"baseStats": {"hp": 110, "atk": 65, "def": 105, "spa": 55, "spd": 95, "spe": 80},
		"abilities": {"0": "Big Pecks", "1": "Overcoat", "H": "Weak Armor"},
		"heightm": 1.2,
		"weightkg": 39.5,
		"color": "Brown",
		"prevo": "Vullaby",
		"evoLevel": 54,
		"eggGroups": ["Flying"],
	},
	"Heatmor": {
		"num": 631,
		"name": "Heatmor",
		"types": ["Fire"],
		"baseStats": {"hp": 85, "atk": 97, "def": 66, "spa": 105, "spd": 66, "spe": 65},
		"abilities": {"0": "Gluttony", "1": "Flash Fire", "H": "White Smoke"},
		"heightm": 1.4,
		"weightkg": 58,
		"color": "Red",
		"eggGroups": ["Field"],
	},
	"Durant": {
		"num": 632,
		"name": "Durant",
		"types": ["Bug", "Steel"],
		"baseStats": {"hp": 58, "atk": 109, "def": 112, "spa": 48, "spd": 48, "spe": 109},
		"abilities": {"0": "Swarm", "1": "Hustle", "H": "Truant"},
		"heightm": 0.3,
		"weightkg": 33,
		"color": "Gray",
		"eggGroups": ["Bug"],
	},
	"Deino": {
		"num": 633,
		"name": "Deino",
		"types": ["Dark", "Dragon"],
		"baseStats": {"hp": 52, "atk": 65, "def": 50, "spa": 45, "spd": 50, "spe": 38},
		"abilities": {"0": "Hustle"},
		"heightm": 0.8,
		"weightkg": 17.3,
		"color": "Blue",
		"evos": ["Zweilous"],
		"eggGroups": ["Dragon"],
	},
	"Zweilous": {
		"num": 634,
		"name": "Zweilous",
		"types": ["Dark", "Dragon"],
		"baseStats": {"hp": 72, "atk": 85, "def": 70, "spa": 65, "spd": 70, "spe": 58},
		"abilities": {"0": "Hustle"},
		"heightm": 1.4,
		"weightkg": 50,
		"color": "Blue",
		"prevo": "Deino",
		"evoLevel": 50,
		"evos": ["Hydreigon"],
		"eggGroups": ["Dragon"],
	},
	"Hydreigon": {
		"num": 635,
		"name": "Hydreigon",
		"types": ["Dark", "Dragon"],
		"baseStats": {"hp": 92, "atk": 105, "def": 90, "spa": 125, "spd": 90, "spe": 98},
		"abilities": {"0": "Levitate"},
		"heightm": 1.8,
		"weightkg": 160,
		"color": "Blue",
		"prevo": "Zweilous",
		"evoLevel": 64,
		"eggGroups": ["Dragon"],
	},
	"Larvesta": {
		"num": 636,
		"name": "Larvesta",
		"types": ["Bug", "Fire"],
		"baseStats": {"hp": 55, "atk": 85, "def": 55, "spa": 50, "spd": 55, "spe": 60},
		"abilities": {"0": "Flame Body", "H": "Swarm"},
		"heightm": 1.1,
		"weightkg": 28.8,
		"color": "White",
		"evos": ["Volcarona"],
		"eggGroups": ["Bug"],
	},
	"Volcarona": {
		"num": 637,
		"name": "Volcarona",
		"types": ["Bug", "Fire"],
		"baseStats": {"hp": 85, "atk": 60, "def": 65, "spa": 135, "spd": 105, "spe": 100},
		"abilities": {"0": "Flame Body", "H": "Swarm"},
		"heightm": 1.6,
		"weightkg": 46,
		"color": "White",
		"prevo": "Larvesta",
		"evoLevel": 59,
		"eggGroups": ["Bug"],
	},
	"Cobalion": {
		"num": 638,
		"name": "Cobalion",
		"types": ["Steel", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 91, "atk": 90, "def": 129, "spa": 90, "spd": 72, "spe": 108},
		"abilities": {"0": "Justified"},
		"heightm": 2.1,
		"weightkg": 250,
		"color": "Blue",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Terrakion": {
		"num": 639,
		"name": "Terrakion",
		"types": ["Rock", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 91, "atk": 129, "def": 90, "spa": 72, "spd": 90, "spe": 108},
		"abilities": {"0": "Justified"},
		"heightm": 1.9,
		"weightkg": 260,
		"color": "Gray",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Virizion": {
		"num": 640,
		"name": "Virizion",
		"types": ["Grass", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 91, "atk": 90, "def": 72, "spa": 90, "spd": 129, "spe": 108},
		"abilities": {"0": "Justified"},
		"heightm": 2,
		"weightkg": 200,
		"color": "Green",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Tornadus": {
		"num": 641,
		"name": "Tornadus",
		"baseForme": "Incarnate",
		"types": ["Flying"],
		"gender": "M",
		"baseStats": {"hp": 79, "atk": 115, "def": 70, "spa": 125, "spd": 80, "spe": 111},
		"abilities": {"0": "Prankster", "H": "Defiant"},
		"heightm": 1.5,
		"weightkg": 63,
		"color": "Green",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Tornadus-Therian"],
		"formeOrder": ["Tornadus", "Tornadus-Therian"],
	},
	"Tornadustherian": {
		"num": 641,
		"name": "Tornadus-Therian",
		"baseSpecies": "Tornadus",
		"forme": "Therian",
		"types": ["Flying"],
		"gender": "M",
		"baseStats": {"hp": 79, "atk": 100, "def": 80, "spa": 110, "spd": 90, "spe": 121},
		"abilities": {"0": "Regenerator"},
		"heightm": 1.4,
		"weightkg": 63,
		"color": "Green",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Tornadus",
	},
	"Thundurus": {
		"num": 642,
		"name": "Thundurus",
		"baseForme": "Incarnate",
		"types": ["Electric", "Flying"],
		"gender": "M",
		"baseStats": {"hp": 79, "atk": 115, "def": 70, "spa": 125, "spd": 80, "spe": 111},
		"abilities": {"0": "Prankster", "H": "Defiant"},
		"heightm": 1.5,
		"weightkg": 61,
		"color": "Blue",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Thundurus-Therian"],
		"formeOrder": ["Thundurus", "Thundurus-Therian"],
	},
	"Thundurustherian": {
		"num": 642,
		"name": "Thundurus-Therian",
		"baseSpecies": "Thundurus",
		"forme": "Therian",
		"types": ["Electric", "Flying"],
		"gender": "M",
		"baseStats": {"hp": 79, "atk": 105, "def": 70, "spa": 145, "spd": 80, "spe": 101},
		"abilities": {"0": "Volt Absorb"},
		"heightm": 3,
		"weightkg": 61,
		"color": "Blue",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Thundurus",
	},
	"Reshiram": {
		"num": 643,
		"name": "Reshiram",
		"types": ["Dragon", "Fire"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 120, "def": 100, "spa": 150, "spd": 120, "spe": 90},
		"abilities": {"0": "Turboblaze"},
		"heightm": 3.2,
		"weightkg": 330,
		"color": "White",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Zekrom": {
		"num": 644,
		"name": "Zekrom",
		"types": ["Dragon", "Electric"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 150, "def": 120, "spa": 120, "spd": 100, "spe": 90},
		"abilities": {"0": "Teravolt"},
		"heightm": 2.9,
		"weightkg": 345,
		"color": "Black",
		"tags": ["Restricted Legendary"],
		"eggGroups": ["Undiscovered"],
	},
	"Landorus": {
		"num": 645,
		"name": "Landorus",
		"baseForme": "Incarnate",
		"types": ["Ground", "Flying"],
		"gender": "M",
		"baseStats": {"hp": 89, "atk": 125, "def": 90, "spa": 115, "spd": 80, "spe": 101},
		"abilities": {"0": "Sand Force", "H": "Sheer Force"},
		"heightm": 1.5,
		"weightkg": 68,
		"color": "Brown",
		"tags": ["Sub-Legendary"],
		"eggGroups": ["Undiscovered"],
		"otherFormes": ["Landorus-Therian"],
		"formeOrder": ["Landorus", "Landorus-Therian"],
	},
	"Landorustherian": {
		"num": 645,
		"name": "Landorus-Therian",
		"baseSpecies": "Landorus",
		"forme": "Therian",
		"types": ["Ground", "Flying"],
		"gender": "M",
		"baseStats": {"hp": 89, "atk": 145, "def": 90, "spa": 105, "spd": 80, "spe": 91},
		"abilities": {"0": "Intimidate"},
		"heightm": 1.3,
		"weightkg": 68,
		"color": "Brown",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Landorus",
	},
	"Kyurem": {
		"num": 646,
		"name": "Kyurem",
		"types": ["Dragon", "Ice"],
		"gender": "N",
		"baseStats": {"hp": 125, "atk": 130, "def": 90, "spa": 130, "spd": 90, "spe": 95},
		"abilities": {"0": "Pressure"},
		"heightm": 3,
		"weightkg": 325,
		"color": "Gray",
		"eggGroups": ["Undiscovered"],
		"tags": ["Restricted Legendary"],
		"otherFormes": ["Kyurem-Black", "Kyurem-White"],
		"formeOrder": ["Kyurem", "Kyurem-White", "Kyurem-Black"],
	},
	"Kyuremblack": {
		"num": 646,
		"name": "Kyurem-Black",
		"baseSpecies": "Kyurem",
		"forme": "Black",
		"types": ["Dragon", "Ice"],
		"gender": "N",
		"baseStats": {"hp": 125, "atk": 170, "def": 100, "spa": 120, "spd": 90, "spe": 95},
		"abilities": {"0": "Teravolt"},
		"heightm": 3.3,
		"weightkg": 325,
		"color": "Gray",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Kyurem",
	},
	"Kyuremwhite": {
		"num": 646,
		"name": "Kyurem-White",
		"baseSpecies": "Kyurem",
		"forme": "White",
		"types": ["Dragon", "Ice"],
		"gender": "N",
		"baseStats": {"hp": 125, "atk": 120, "def": 90, "spa": 170, "spd": 100, "spe": 95},
		"abilities": {"0": "Turboblaze"},
		"heightm": 3.6,
		"weightkg": 325,
		"color": "Gray",
		"eggGroups": ["Undiscovered"],
		"changesFrom": "Kyurem",
	},
	"Keldeo": {
		"num": 647,
		"name": "Keldeo",
		"baseForme": "Ordinary",
		"types": ["Water", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 91, "atk": 72, "def": 90, "spa": 129, "spd": 90, "spe": 108},
		"abilities": {"0": "Justified"},
		"heightm": 1.4,
		"weightkg": 48.5,
		"color": "Yellow",
		"eggGroups": ["Undiscovered"],
		"tags": ["Mythical"],
		"otherFormes": ["Keldeo-Resolute"],
		"formeOrder": ["Keldeo", "Keldeo-Resolute"],
	},
	"Keldeoresolute": {
		"num": 647,
		"name": "Keldeo-Resolute",
		"baseSpecies": "Keldeo",
		"forme": "Resolute",
		"types": ["Water", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 91, "atk": 72, "def": 90, "spa": 129, "spd": 90, "spe": 108},
		"abilities": {"0": "Justified"},
		"heightm": 1.4,
		"weightkg": 48.5,
		"color": "Yellow",
		"eggGroups": ["Undiscovered"],
		"requiredMove": "Secret Sword",
		"changesFrom": "Keldeo",
	},
	"Meloetta": {
		"num": 648,
		"name": "Meloetta",
		"baseForme": "Aria",
		"types": ["Normal", "Psychic"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 77, "def": 77, "spa": 128, "spd": 128, "spe": 90},
		"abilities": {"0": "Serene Grace"},
		"heightm": 0.6,
		"weightkg": 6.5,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"tags": ["Mythical"],
		"otherFormes": ["Meloetta-Pirouette"],
		"formeOrder": ["Meloetta", "Meloetta-Pirouette"],
	},
	"Meloettapirouette": {
		"num": 648,
		"name": "Meloetta-Pirouette",
		"baseSpecies": "Meloetta",
		"forme": "Pirouette",
		"types": ["Normal", "Fighting"],
		"gender": "N",
		"baseStats": {"hp": 100, "atk": 128, "def": 90, "spa": 77, "spd": 77, "spe": 128},
		"abilities": {"0": "Serene Grace"},
		"heightm": 0.6,
		"weightkg": 6.5,
		"color": "White",
		"eggGroups": ["Undiscovered"],
		"requiredMove": "Relic Song",
		"battleOnly": "Meloetta",
	},
	"Genesect": {
		"num": 649,
		"name": "Genesect",
		"types": ["Bug", "Steel"],
		"gender": "N",
		"baseStats": {"hp": 71, "atk": 120, "def": 95, "spa": 120, "spd": 95, "spe": 99},
		"abilities": {"0": "Download"},
		"heightm": 1.5,
		"weightkg": 82.5,
		"color": "Purple",
		"eggGroups": ["Undiscovered"],
		"tags": ["Mythical"],
		"otherFormes": ["Genesect-Douse", "Genesect-Shock", "Genesect-Burn", "Genesect-Chill"],
		"formeOrder": ["Genesect", "Genesect-Douse", "Genesect-Shock", "Genesect-Burn", "Genesect-Chill"],
	},
	"Genesectdouse": {
		"num": 649,
		"name": "Genesect-Douse",
		"baseSpecies": "Genesect",
		"forme": "Douse",
		"types": ["Bug", "Steel"],
		"gender": "N",
		"baseStats": {"hp": 71, "atk": 120, "def": 95, "spa": 120, "spd": 95, "spe": 99},
		"abilities": {"0": "Download"},
		"heightm": 1.5,
		"weightkg": 82.5,
		"color": "Purple",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Douse Drive",
		"changesFrom": "Genesect",
	},
	"Genesectshock": {
		"num": 649,
		"name": "Genesect-Shock",
		"baseSpecies": "Genesect",
		"forme": "Shock",
		"types": ["Bug", "Steel"],
		"gender": "N",
		"baseStats": {"hp": 71, "atk": 120, "def": 95, "spa": 120, "spd": 95, "spe": 99},
		"abilities": {"0": "Download"},
		"heightm": 1.5,
		"weightkg": 82.5,
		"color": "Purple",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Shock Drive",
		"changesFrom": "Genesect",
	},
	"Genesectburn": {
		"num": 649,
		"name": "Genesect-Burn",
		"baseSpecies": "Genesect",
		"forme": "Burn",
		"types": ["Bug", "Steel"],
		"gender": "N",
		"baseStats": {"hp": 71, "atk": 120, "def": 95, "spa": 120, "spd": 95, "spe": 99},
		"abilities": {"0": "Download"},
		"heightm": 1.5,
		"weightkg": 82.5,
		"color": "Purple",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Burn Drive",
		"changesFrom": "Genesect",
	},
	"Genesectchill": {
		"num": 649,
		"name": "Genesect-Chill",
		"baseSpecies": "Genesect",
		"forme": "Chill",
		"types": ["Bug", "Steel"],
		"gender": "N",
		"baseStats": {"hp": 71, "atk": 120, "def": 95, "spa": 120, "spd": 95, "spe": 99},
		"abilities": {"0": "Download"},
		"heightm": 1.5,
		"weightkg": 82.5,
		"color": "Purple",
		"eggGroups": ["Undiscovered"],
		"requiredItem": "Chill Drive",
		"changesFrom": "Genesect",
	},
}
