# ruff: noqa: E501

POKE_BALLS = {
    "poké_ball": {
        "name": "Poké Ball",
        "introduced_in": "Gen I",
        "catch_rate_modifier": "1×",
        "description": "1×",
        "notes": "Must be in the player's [[Bag]] with an empty space in the [[party]] to obtain a {{p|Shedinja}} when {{p|Nincada}} [[Evolution|evolves]] from [[Generation IV]] onwards.",
    },
    "great_ball": {
        "name": "Great Ball",
        "introduced_in": "Gen I",
        "catch_rate_modifier": "1.5×",
        "description": "1.5×",
        "notes": "",
    },
    "ultra_ball": {
        "name": "Ultra Ball",
        "introduced_in": "Gen I",
        "catch_rate_modifier": "2×",
        "description": "2×",
        "notes": "",
    },
    "master_ball": {
        "name": "Master Ball",
        "introduced_in": "Gen I",
        "catch_rate_modifier": "255× (guaranteed capture)",
        "description": "255× (guaranteed capture)",
        "notes": "The only Poké Ball other than the Beast Ball that does not have a 0.1× catch modifier when used on an Ultra Beast.",
    },
    "safari_ball": {
        "name": "Safari Ball",
        "introduced_in": "Gen I",
        "catch_rate_modifier": "{{tt|1×|2× in Gen I; 1.5× from Gen II to SwSh; 1.5× in BDSP}}",
        "description": "{{tt|1×|2× in Gen I; 1.5× from Gen II to SwSh; 1.5× in BDSP}}",
        "notes": "Prior to [[Generation VIII]], it was only usable within [[Safari Zone]]s.",
    },
    "fast_ball": {
        "name": "Fast Ball",
        "introduced_in": "Gen II",
        "catch_rate_modifier": "4× if used on a Pokémon with a base {{stat|Speed}} {{cat|Pokémon whose base Speed stat is greater than 100|of at least 100}} 1× otherwise",
        "description": "4× if used on a Pokémon with a base {{stat|Speed}} {{cat|Pokémon whose base Speed stat is greater than 100|of at least 100}} 1× otherwise",
        "notes": "In [[Generation II]], it was intended to have a 4× catch modifier for Pokémon that can [[Escape#Wild Pokémon|flee]], but it only does for three of them: {{p|Magnemite}}, {{p|Grimer}} and {{p|Tangela}}.",
    },
    "level_ball": {
        "name": "Level Ball",
        "introduced_in": "Gen II",
        "catch_rate_modifier": "1× if the player's Pokémon is the same level as or a lower level than the wild Pokémon 2× if the player's Pokémon is at a higher level than the wild Pokémon but less than double it 4× if the player's Pokémon is more than double but less than four times the level of the wild Pokémon 8× if the player's Pokémon is of a level four times or more than that of the wild Pokémon",
        "description": "1× if the player's Pokémon is the same level as or a lower level than the wild Pokémon 2× if the player's Pokémon is at a higher level than the wild Pokémon but less than double it 4× if the player's Pokémon is more than double but less than four times the level of the wild Pokémon 8× if the player's Pokémon is of a level four times or more than that of the wild Pokémon",
        "notes": "",
    },
    "lure_ball": {
        "name": "Lure Ball",
        "introduced_in": "Gen II",
        "catch_rate_modifier": "4× if used on a Pokémon encountered while [[fishing]] 1× otherwise",
        "description": "4× if used on a Pokémon encountered while [[fishing]] 1× otherwise",
        "notes": "In [[Johto]], the bonus was 3x while in [[Alola]], the bonus was 5x",
    },
    "heavy_ball": {
        "name": "Heavy Ball",
        "introduced_in": "Gen II",
        "catch_rate_modifier": "-20 if used on a Pokémon weighing [[List of Pokémon by weight#218.3 lbs. to 220.2 lbs. (99.0 kg to 99.9 kg)|220.2 lbs. (99.9 kg)]] or less ±0 if used on a Pokémon weighing [[List of Pokémon by weight#220.5 lbs. to 225.5 lbs. (100.0 kg to 102.3 kg)|220.5 lbs. (100.0 kg)]] – [[List of Pokémon by weight#330.7 lbs. to 440.7 lbs. (150.0 kg to 199.9 kg)|440.7 lbs. (199.9 kg)]] +20 if used on a Pokémon weighing [[List of Pokémon by weight#440.9 lbs. to 451.3 lbs. (200.0 kg to 204.7 kg)|440.9 lbs. (200.0 kg)]] – [[List of Pokémon by weight#617.3 lbs. to 661.2 lbs. (280.0 kg to 299.9 kg)|661.2 lbs. (299.9 kg)]] +30 if used on a Pokémon weighing [[List of Pokémon by weight#661.4 lbs. to 677.0 lbs. (300.0 kg to 307.1 kg)|661.4 lbs. (300.0 kg)]] or more",
        "description": "-20 if used on a Pokémon weighing [[List of Pokémon by weight#218.3 lbs. to 220.2 lbs. (99.0 kg to 99.9 kg)|220.2 lbs. (99.9 kg)]] or less ±0 if used on a Pokémon weighing [[List of Pokémon by weight#220.5 lbs. to 225.5 lbs. (100.0 kg to 102.3 kg)|220.5 lbs. (100.0 kg)]] – [[List of Pokémon by weight#330.7 lbs. to 440.7 lbs. (150.0 kg to 199.9 kg)|440.7 lbs. (199.9 kg)]] +20 if used on a Pokémon weighing [[List of Pokémon by weight#440.9 lbs. to 451.3 lbs. (200.0 kg to 204.7 kg)|440.9 lbs. (200.0 kg)]] – [[List of Pokémon by weight#617.3 lbs. to 661.2 lbs. (280.0 kg to 299.9 kg)|661.2 lbs. (299.9 kg)]] +30 if used on a Pokémon weighing [[List of Pokémon by weight#661.4 lbs. to 677.0 lbs. (300.0 kg to 307.1 kg)|661.4 lbs. (300.0 kg)]] or more",
        "notes": "In [[Pokémon Crystal Version|Pokémon Crystal]] only, there is a glitch that causes the retrieved weights of Pokémon whose index numbers are divisible by 64 ({{p|Kadabra}}, {{p|Tauros}}, and {{p|Sunflora}}) to become junk data that are, in turn, interpreted as massive weights, causing these particular Pokémon to receive the +40 capture modifier. In {{g|Sun and Moon}} only, a Heavy Ball will always fail to catch a Pokémon whose weight is less than 220.46 lbs (100.0 kg) and whose catch rate is less than or equal to 20. This is because the game will set the catch rate to 0 when the catch rate becomes negative due to the -20 modifier that is applied.",
    },
    "love_ball": {
        "name": "Love Ball",
        "introduced_in": "Gen II",
        "catch_rate_modifier": "8× if used on a Pokémon of the same species but opposite gender of the player's Pokémon 1× otherwise",
        "description": "8× if used on a Pokémon of the same species but opposite gender of the player's Pokémon 1× otherwise",
        "notes": "In [[Generation II]], it has an 8× catch modifier if both Pokémon are the same species ''and'' gender.",
    },
    "friend_ball": {
        "name": "Friend Ball",
        "introduced_in": "Gen II",
        "catch_rate_modifier": "1×",
        "description": "1×",
        "notes": "Sets caught Pokémon's [[friendship]] to 200 [[Generation II|Gen II]]-[[Generation VII|VII]] , or 150 [[Generation VIII|Gen VIII]]+",
    },
    "moon_ball": {
        "name": "Moon Ball",
        "introduced_in": "Gen II",
        "catch_rate_modifier": "4× if used on a Pokémon that evolves by using a [[Moon Stone]] 1× otherwise",
        "description": "4× if used on a Pokémon that evolves by using a [[Moon Stone]] 1× otherwise",
        "notes": "In [[Generation II]], it always has a 1× catch modifier due to a [[List of glitches in Generation II#Catch rate|programming error]].",
    },
    "sport_ball": {
        "name": "Sport Ball",
        "introduced_in": "Gen II",
        "catch_rate_modifier": "{{tt|1×|1.5× prior to Generation VIII}}",
        "description": "{{tt|1×|1.5× prior to Generation VIII}}",
        "notes": "Prior to [[Generation VIII]], it was only usable during the [[Bug-Catching Contest]].",
    },
    "net_ball": {
        "name": "Net Ball",
        "introduced_in": "Gen III",
        "catch_rate_modifier": "3.5× if used on a {{t|Water}} or {{type|Bug}} Pokémon 1× otherwise",
        "description": "3.5× if used on a {{t|Water}} or {{type|Bug}} Pokémon 1× otherwise",
        "notes": "",
    },
    "dive_ball": {
        "name": "Dive Ball",
        "introduced_in": "Gen III",
        "catch_rate_modifier": "3.5× if used while {{m|surf}}ing, [[fishing]], or [[underwater]] 1× otherwise",
        "description": "3.5× if used while {{m|surf}}ing, [[fishing]], or [[underwater]] 1× otherwise",
        "notes": "In [[Generation III]], it only had an increased catch rate [[underwater]].",
    },
    "nest_ball": {
        "name": "Nest Ball",
        "introduced_in": "Gen III",
        "catch_rate_modifier": "((41 - Pokémon's level) ÷ 10)× if Pokémon's level is between 1 and 29 1× otherwise",
        "description": "((41 - Pokémon's level) ÷ 10)× if Pokémon's level is between 1 and 29 1× otherwise",
        "notes": "",
    },
    "repeat_ball": {
        "name": "Repeat Ball",
        "introduced_in": "Gen III",
        "catch_rate_modifier": "3.5× if used on a Pokémon that is registered in the player's [[Pokédex]] as caught 1× otherwise",
        "description": "3.5× if used on a Pokémon that is registered in the player's [[Pokédex]] as caught 1× otherwise",
        "notes": "",
    },
    "timer_ball": {
        "name": "Timer Ball",
        "introduced_in": "Gen III",
        "catch_rate_modifier": "(1 + number of turns passed in battle * {{tt|1229/4096|approx. 0.3}})×, maximum 4× at 10 turns",
        "description": "(1 + number of turns passed in battle * {{tt|1229/4096|approx. 0.3}})×, maximum 4× at 10 turns",
        "notes": "",
    },
    "luxury_ball": {
        "name": "Luxury Ball",
        "introduced_in": "Gen III",
        "catch_rate_modifier": "1×",
        "description": "1×",
        "notes": "Doubles the rate at which the contained Pokémon's [[friendship]] increases.",
    },
    "premier_ball": {
        "name": "Premier Ball",
        "introduced_in": "Gen III",
        "catch_rate_modifier": "1×",
        "description": "1×",
        "notes": "",
    },
    "dusk_ball": {
        "name": "Dusk Ball",
        "introduced_in": "Gen IV",
        "catch_rate_modifier": "3× if used in a cave or at night 1× otherwise",
        "description": "3× if used in a cave or at night 1× otherwise",
        "notes": "",
    },
    "heal_ball": {
        "name": "Heal Ball",
        "introduced_in": "Gen IV",
        "catch_rate_modifier": "1×",
        "description": "1×",
        "notes": "Fully restores a caught Pokémon's {{stat|HP}} and [[PP]] and removes their [[status condition]]s.",
    },
    "quick_ball": {
        "name": "Quick Ball",
        "introduced_in": "Gen IV",
        "catch_rate_modifier": "5× if used on the first turn of a battle 1× otherwise",
        "description": "5× if used on the first turn of a battle 1× otherwise",
        "notes": "",
    },
    "cherish_ball": {
        "name": "Cherish Ball",
        "introduced_in": "Gen IV",
        "catch_rate_modifier": "1×",
        "description": "1×",
        "notes": "Unobtainable by the player, but used for various [[event Pokémon]].",
    },
    "park_ball": {
        "name": "Park Ball",
        "introduced_in": "Gen IV",
        "catch_rate_modifier": "255× (guaranteed capture if used in [[Pal Park]]) {{tt|1× otherwise|If used outside of Pal Park, the game will behave as if the player had thrown a standard Poké Ball instead.}}",
        "description": "255× (guaranteed capture if used in [[Pal Park]]) {{tt|1× otherwise|If used outside of Pal Park, the game will behave as if the player had thrown a standard Poké Ball instead.}}",
        "notes": "Unobtainable by the player, but used in [[Pal Park]].",
    },
    "dream_ball": {
        "name": "Dream Ball",
        "introduced_in": "Gen V",
        "catch_rate_modifier": "4× if used on a {{status|sleep}}ing Pokémon 1× otherwise",
        "description": "4× if used on a {{status|sleep}}ing Pokémon 1× otherwise",
        "notes": "Used only in [[Entralink|Entree Forest]] prior to [[Generation VIII]]. Catch rate modifier 255× (guaranteed capture) in [[Generation V]].",
    },
    "beast_ball": {
        "name": "Beast Ball",
        "introduced_in": "Gen VII",
        "catch_rate_modifier": "5× if used on an [[Ultra Beast]] 0.1× otherwise",
        "description": "5× if used on an [[Ultra Beast]] 0.1× otherwise",
        "notes": "If any other Poké Ball (except the Master Ball) is used on an Ultra Beast, it has a 0.1× catch modifier.",
    },
    "strange_ball": {
        "name": "Strange Ball",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "{{tt|0.75×|Defaults to Poké Ball (Hisui) catchrate in Legends: Arceus if obtained via cheating; has no catchrate in BDSP due to a lack of item data.}}",
        "description": "{{tt|0.75×|Defaults to Poké Ball (Hisui) catchrate in Legends: Arceus if obtained via cheating; has no catchrate in BDSP due to a lack of item data.}}",
        "notes": "Unobtainable by the player. Pokémon in [[Pokémon Legends: Arceus]] that were transferred from other games via [[Pokémon HOME]], as well as Pokémon from Legends: Arceus in [[Pokémon Brilliant Diamond and Shining Pearl]] or [[Pokémon Scarlet and Violet]] will be displayed in this ball.",
    },
    "poké_ball_(hisui)": {
        "name": "Poké Ball (Hisui)",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "0.75×",
        "description": "0.75×",
        "notes": "",
    },
    "great_ball_(hisui)": {
        "name": "Great Ball (Hisui)",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "1.5×",
        "description": "1.5×",
        "notes": "",
    },
    "ultra_ball_(hisui)": {
        "name": "Ultra Ball (Hisui)",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "2.25×",
        "description": "2.25×",
        "notes": "",
    },
    "feather_ball": {
        "name": "Feather Ball",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "1× 1.25× when boosted",
        "description": "1× 1.25× when boosted",
        "notes": "Can be thrown further than a regular Poké Ball. Is more effective for catching Pokémon {{tt|that fly high in the air|This only applies to specific flying encounters that fly well above the terrain.}}.",
    },
    "wing_ball": {
        "name": "Wing Ball",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "1.5× 1.75× when boosted",
        "description": "1.5× 1.75× when boosted",
        "notes": "Can be thrown further than a Feather Ball. Is more effective for catching Pokémon {{tt|that fly high in the air|This only applies to specific flying encounters that fly well above the terrain.}}.",
    },
    "jet_ball": {
        "name": "Jet Ball",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "2× 2.75× when boosted",
        "description": "2× 2.75× when boosted",
        "notes": "Can be thrown further than a Wing Ball. Is more effective for catching Pokémon {{tt|that fly high in the air|This only applies to specific flying encounters that fly well above the terrain.}}.",
    },
    "heavy_ball_(hisui)": {
        "name": "Heavy Ball (Hisui)",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "1× 1.25× when boosted",
        "description": "1× 1.25× when boosted",
        "notes": "Doesn't fly far, but is more effective if the Pokémon {{tt|hasn't noticed the player|This bonus is always active during battle, regardless of whether the player was noticed prior to starting the battle. Therefore, the boosted catch rate will always apply in battle.}}.",
    },
    "leaden_ball": {
        "name": "Leaden Ball",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "1.75× 2× when boosted",
        "description": "1.75× 2× when boosted",
        "notes": "Upgraded version of the Heavy Ball. Doesn't fly far, but is more effective if the Pokémon {{tt|hasn't noticed the player|This bonus is always active during battle, regardless of whether the player was noticed prior to starting the battle. Therefore, the boosted catch rate will always apply in battle.}}.",
    },
    "gigaton_ball": {
        "name": "Gigaton Ball",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "2.5× 2.75× when boosted",
        "description": "2.5× 2.75× when boosted",
        "notes": "Upgraded version of the Leaden Ball. Doesn't fly far, but is more effective if the Pokémon {{tt|hasn't noticed the player|This bonus is always active during battle, regardless of whether the player was noticed prior to starting the battle. Therefore, the boosted catch rate will always apply in battle.}}.",
    },
    "origin_ball": {
        "name": "Origin Ball",
        "introduced_in": "Gen VIII",
        "catch_rate_modifier": "{{tt|Unknown|Has no programmed catch rate, as it cannot be thrown outside of battle nor selected during battle, even if moved from Key Items to the player's normal inventory via cheating.}}",
        "description": "{{tt|Unknown|Has no programmed catch rate, as it cannot be thrown outside of battle nor selected during battle, even if moved from Key Items to the player's normal inventory via cheating.}}",
        "notes": "Automatically catches {{form|Dialga and Palkia|Origin Forme}} {{p|Dialga}} or {{p|Palkia}} at the end of the main story in [[Pokémon Legends: Arceus]].",
    },
}
