from .pokefunc import Return, Acrobatics, CrushGrip

py_dict = {
    "Return": {
        "num": 216,
        "accuracy": 100,
        "basePower": 0,
        "basePowerCallback": Return().basePowerCallback,
        "category": "Physical",
        "isNonstandard": "Past",
        "name": "Return",
        "pp": 20,
        "priority": 0,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "metronome": 1},
        "secondary": None,
        "target": "normal",
        "type": "Normal",
        "zMove": {"basePower": 160},
        "maxMove": {"basePower": 130},
        "contestType": "Cute",
    },
    "Acrobatics": {
        "num": 512,
        "accuracy": 100,
        "basePower": 55,
        "basePowerCallback": Acrobatics().basePowerCallback,
        "category": "Physical",
        "name": "Acrobatics",
        "pp": 15,
        "priority": 0,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "distance": 1, "metronome": 1},
        "secondary": None,
        "target": "any",
        "type": "Flying",
        "contestType": "Cool",
    },
    "CrushGrip": {
        "num": 462,
        "accuracy": 100,
        "basePower": 0,
        "basePowerCallback": CrushGrip().basePowerCallback,
        "category": "Physical",
        "name": "CrushGrip",
        "pp": 5,
        "priority": 0,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "metronome": 1},
        "secondary": None,
        "target": "normal",
        "type": "Normal",
        "zMove": {"basePower": 190},
        "maxMove": {"basePower": 140},
        "contestType": "Tough",
    },
}
