# Generated by Django 4.2.23 on 2025-06-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                ("type_", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_pokemon",
                    models.ManyToManyField(
                        related_name="active_users", to="pokemon.pokemon"
                    ),
                ),
                (
                    "stored_pokemon",
                    models.ManyToManyField(
                        related_name="stored_users", to="pokemon.pokemon"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trainer_number", models.PositiveIntegerField(unique=True)),
                ("money", models.PositiveIntegerField(default=0)),
                ("badge_count", models.PositiveIntegerField(default=0)),
                (
                    "seen_pokemon",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seen_by_trainers",
                        to="pokemon.pokemon",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
    ]
