# Generated by Django 4.2.13 on 2025-06-25 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0005_ownedpokemon_and_moveset"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="ability",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userstorage",
            name="stored_pokemon",
            field=models.ManyToManyField(
                blank=True, related_name="stored_users", to="pokemon.pokemon"
            ),
        ),
        migrations.CreateModel(
            name="StorageBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "pokemon",
                    models.ManyToManyField(
                        blank=True, related_name="boxes", to="pokemon.pokemon"
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="pokemon.userstorage",
                    ),
                ),
            ],
        ),
    ]
