# Generated by Django 5.2.4 on 2025-07-09 09:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0014_gender_nature_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="name",
        ),
        migrations.AddField(
            model_name="pokemon",
            name="evs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=6
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("N", "None")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="ivs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=6
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="nature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hardy", "Hardy"),
                    ("Lonely", "Lonely"),
                    ("Brave", "Brave"),
                    ("Adamant", "Adamant"),
                    ("Naughty", "Naughty"),
                    ("Bold", "Bold"),
                    ("Docile", "Docile"),
                    ("Relaxed", "Relaxed"),
                    ("Impish", "Impish"),
                    ("Lax", "Lax"),
                    ("Timid", "Timid"),
                    ("Hasty", "Hasty"),
                    ("Serious", "Serious"),
                    ("Jolly", "Jolly"),
                    ("Naive", "Naive"),
                    ("Modest", "Modest"),
                    ("Mild", "Mild"),
                    ("Quiet", "Quiet"),
                    ("Bashful", "Bashful"),
                    ("Rash", "Rash"),
                    ("Calm", "Calm"),
                    ("Gentle", "Gentle"),
                    ("Sassy", "Sassy"),
                    ("Careful", "Careful"),
                    ("Quirky", "Quirky"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="species",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="npctrainerpokemon",
            name="evs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=6
            ),
        ),
        migrations.AlterField(
            model_name="npctrainerpokemon",
            name="ivs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=6
            ),
        ),
        migrations.AlterField(
            model_name="npctrainerpokemon",
            name="species",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="ownedpokemon",
            name="evs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=6
            ),
        ),
        migrations.AlterField(
            model_name="ownedpokemon",
            name="ivs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=6
            ),
        ),
        migrations.AlterField(
            model_name="ownedpokemon",
            name="species",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="level",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
