# Generated by Django 5.2.4 on 2025-07-26 05:11

import django.contrib.postgres.fields
import django.db.models.deletion
import pokemon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0029_moveset_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moveset",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="movesetslot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ownedpokemon",
            name="evs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=list,
                size=6,
                validators=[pokemon.models.validate_evs],
            ),
        ),
        migrations.AlterField(
            model_name="ownedpokemon",
            name="ivs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=list,
                size=6,
                validators=[pokemon.models.validate_ivs],
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="evs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=list,
                size=6,
                validators=[pokemon.models.validate_evs],
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="ivs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=list,
                size=6,
                validators=[pokemon.models.validate_ivs],
            ),
        ),
        migrations.AlterField(
            model_name="pokemonfusion",
            name="pokemon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer_fusions",
                to="pokemon.ownedpokemon",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonfusion",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pokemon_fusions",
                to="pokemon.trainer",
            ),
        ),
    ]
