# Generated by Django 5.2.4 on 2025-08-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0033_verifiedmove_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PokemonFusion",
        ),
    ]
