# Generated by Django 6.0.8 on 2026-09-20 17:56

import django.db.models.deletion
from django.db import migrations, models


def require_valid_placements(apps, schema_editor):
    """Stop before installing constraints; never repair ambiguous player data."""
    from pokemon.services.placement_audit import audit_placements_v1

    # Prevent writers from invalidating the preflight between audit and DDL.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "LOCK TABLE pokemon_ownedpokemon, pokemon_pokemonplacement, "
            "pokemon_userstorage, pokemon_storagebox, pokemon_activepokemonslot, "
            "pokemon_userstorage_stored_pokemon, pokemon_storagebox_pokemon, "
            "pokemon_trainer IN SHARE ROW EXCLUSIVE MODE"
        )
    problems = list(audit_placements_v1(apps, schema_editor.connection.alias))
    if problems:
        raise RuntimeError(
            "Canonical placement migration blocked. No repairs were made. "
            "Run audit_pokemon_placements and resolve these records before retrying:\n"
            + "\n".join(str(problem) for problem in problems)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0039_adventure_session'),
    ]

    operations = [
        migrations.RunPython(require_valid_placements, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CaptureReceipt',
            fields=[
                ('encounter_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('owned_id', models.UUIDField(editable=False)),
                ('location', models.CharField(max_length=10)),
                ('party_slot', models.PositiveSmallIntegerField(null=True)),
                ('box_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ownedpokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemonplacement',
            name='location_type',
            field=models.CharField(choices=[('party', 'Party'), ('box', 'Box'), ('fusion', 'Fusion reservation')], db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='pokemonplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('location_type', 'box')), fields=('box', 'box_position'), name='pokemon_box_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='pokemonplacement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('box__isnull', True), ('box_position__isnull', True), ('location_type', 'party'), ('slot__gte', 1), ('slot__isnull', False), ('slot__lte', 6)), models.Q(('box__isnull', False), ('box_position__gte', 1), ('box_position__isnull', False), ('location_type', 'box'), ('slot__isnull', True)), models.Q(('box__isnull', True), ('box_position__isnull', True), ('location_type', 'fusion'), ('slot__isnull', True)), _connector='OR'), name='pokemon_placement_shape'),
        ),
        migrations.AddField(
            model_name='capturereceipt',
            name='pokemon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.ownedpokemon'),
        ),
        migrations.AddField(
            model_name='capturereceipt',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.userstorage'),
        ),
    ]
