# Generated by hand for LockDefaults model
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LockDefaults",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("room_default", models.TextField(blank=True, default="")),
                ("exit_default", models.TextField(blank=True, default="")),
            ],
        ),
    ]
