name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
          pip install ruff
          pip install -e .
      - name: Lint
        run: ruff check .
      - name: Test (no Evennia)
        env:
          PF2_NO_EVENNIA: "1"
        run: pytest -q
