name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install ruff
          pip install -e .
      - name: Lint (Ruff)
        run: ruff check .
      - name: Tests with coverage
        env:
          PF2_NO_EVENNIA: "1"
        run: |
          pip install coverage
          coverage run -m pytest -q
          coverage xml
      - name: Coverage summary
        if: always()
        run: |
          pip install coverage
          coverage report -m || true
